### ISSUE TITLE
Add shepherd reports to telechat document zip file

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1087]
`keyword_sprint` `type_defect`   |    by barryleiba@computer.org

___

Now that the Secretariat is making sure that the shepherd writeups are
put into the writeup field in the datatracker, could we have the
writeups added to the zip file of documents on the telechat?  That
would help a lot when I suck the zip file down to my tablet and take
it on the road.

___
_Issue migrated from trac:1087 at 2022-03-04 02:54:11 +0000_

**Comment by rjsparks** [comment]
closing as stale

**Comment by rjsparks** [comment]
see #4081
