### ISSUE TITLE
Check for next state when expiring IETF LC could be smarter

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1120]
`keyword_sprint` `type_defect`   |    by rjsparks@nostrum.com

___

See
<http://wiki.tools.ietf.org/tools/ietfdb/browser/trunk/ietf/idrfc/lastcall.py#L75>

Currently, the code looks into the contents of the ballot writeup to see if it's been edited by looking for a string that appears in the template for that writeup.

It should look for the DocEvent that gets written when the template is edited instead.

___
_Issue migrated from trac:1120 at 2022-03-04 02:56:52 +0000_

**Comment by rjsparks** [comment]
Closing as stale
