### ISSUE TITLE
Almost empty emails sent by milestone tracking

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1166]
`keyword_sprint` `type_defect`   |    by magnus.westerlund@ericsson.com

___

When proposing a new milestone for the AVTCORE WG, the WG mailing list received an almost empty email. I assume this is due to that when adding new milestones going to AD for review the text is kept secret. Should there really be email sent when this happens, as the WG anyway are by design not allowed to see the proposed milestones. 

Subject: [AVTCORE] Milestones changed for avtcore WG

The email to avt@ietf.org said the following:

URL: http://datatracker.ietf.org/wg/avtcore/charter/
_______________________________________________
Audio/Video Transport Core Maintenance
avt@ietf.org
https://www.ietf.org/mailman/listinfo/avt

___
_Issue migrated from trac:1166 at 2022-03-04 03:00:47 +0000_

**Comment by larseggert** [comment]
There now is information about the milestones in the email. Close?
