### ISSUE TITLE
LC docevent text generated incorrectly for second last calls

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1168]
`keyword_sprint` `type_defect`   |    by rjsparks@nostrum.com

___

See http://datatracker.ietf.org/doc/draft-ietf-mmusic-rfc2326bis/history/ 

This entry:
2013-10-11 	38 	Cindy Morgan 	State changed to In Last Call (ends 2013-06-04) from Last Call Requested 

has the end date from the _previous_ last call, not this one.

___
_Issue migrated from trac:1168 at 2022-03-04 03:00:55 +0000_

**Comment by rjsparks** [comment]
Closing as OBE
