### ISSUE TITLE
Stragne sorting of status when displaying search results

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1199]
`type_defect`   |    by magnus.westerlund@ericsson.com

___

I did the following search:
https://datatracker.ietf.org/doc/search/?sort=status&name=&by=ad&activedrafts=on&ad=108049

Then I selected sort on status. The result I get is very confusing, as I can't determine any sorting pattern. My expectance in this case was to sort the status subfield in the following order:

1. IETF main state
2. IESG main state
3. IESG sub-state

And I expect to have each ordered according to how far in the process they repreent. So publication requests before AD evalutation etc. 

___
_Issue migrated from trac:1199 at 2022-03-04 03:29:27 +0000_

**Comment by rjsparks** [comment]
Closing this as stale. Future work on the search page will gather a more full set of requirements.
