### ISSUE TITLE
Multiple Ways to Defer a Document from IESG Telechat?

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1206]
`keyword_sprint` `type_defect`   |    by cmorgan@amsl.com

___

On last week's IESG telechat, we had two documents deferred through the datatracker.  However, only one of those deferrals worked properly.

Benoit Claise deferred draft-ietf-karp-ops-model, I believe by hitting the "Defer" link from the IESG Evaluation record page.  This is the one that worked properly, and the doc moved to the next telechat (2013-12-05).

Joel Jaeggli deferred draft-ietf-mmusic-rfc2326bis, apparently by changing the state to "IESG Evaluation - Defer."  This changed the state, but did not actually move the document to the next telechat.  Is that a bug, or is simply changing the doc state not a valid way to actually defer a doc (i.e. the "Defer" link from the Evaluation record must be used to defer a document)?

Best regards,
Cindy

___
_Issue migrated from trac:1206 at 2022-03-04 03:29:51 +0000_

**Comment by rjsparks** [comment]
Can improve this as part of #5644. Otherwise closing this issue as stale.
