### ISSUE TITLE
Periodically rerun author extraction over old drafts

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1239]
`type_defect`   |    by magnus.westerlund@ericsson.com

___

Original Summary: Wrong Author information for this expired document

https://datatracker.ietf.org/doc/draft-ietf-avt-rtp-no-op/

The page lists only Flemming Andreasen as author, however there are two more authors of this document. This error also appears to be propagated into the xml2rfc reference files.

___
_Issue migrated from trac:1239 at 2022-03-04 03:32:16 +0000_

**Comment by rjsparks** [comment]
This will be replaced with work to allow author information to be recalculated on demand by the appropriate parties.
