### ISSUE TITLE
"Search Internet-Drafts and RFCs" should search filenames too

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1274]
`type_enhancement`   |    by jeff.hodges@kingsmountain.com

___

the top level editable item for the..

  "Search Internet-Drafts and RFCs"
  https://datatracker.ietf.org/doc/search/

..is labeled "Name/number/title:" and it appears that that label is accurate in that only names, 
RFC #s, and document titles are searched by default.

I am suggesting that in the case of (at least) Internet-drafts it should also search filenames.

And also, that in the "Advanced" mode of that same page, that "filename" be added to the 
detailed search criteria under the "Additional search criteria:" heading.

thanks, 

=JeffH

___
_Issue migrated from trac:1274 at 2022-03-04 03:34:22 +0000_

**Comment by larseggert** [comment]
I think this works now. Close?
