### ISSUE TITLE
Display tags (in addition to states) on WG page

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1297]
`keyword_sprint` `keyword_tags` `type_enhancement`   |    by martin.vigoureux@alcatel-lucent.com

___

Hello,

on the page of a WG (https://datatracker.ietf.org/wg/<wg>/) the status column of the tables shows the state the drafts are in.

It would be helpful if the cells of that column could also contain an indication on the tags which are set for each draft.
This is a valuable information which however is currently only accessible today by accessing the page of each draft (https://datatracker.ietf.org/doc/<draft>)

thank you

___
_Issue migrated from trac:1297 at 2022-03-04 03:35:50 +0000_

**Comment by rjsparks** [comment]
Closing this as stale.
