### ISSUE TITLE
Refactor role_required to improve expressivity

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1365]
`type_enhancement`   |    by rjsparks@nostrum.com

___

(Recalled imperfectly from a conversation at IETF89 - please edit if you remember more or different details)

It is currently more difficult than it should be to use the role_required
decorator to restrict access to a view to people with a certain role in a certain group.

This has led to several special names being created inside the decorator itself.
See <http://wiki.tools.ietf.org/tools/ietfdb/browser/trunk/ietf/ietfauth/utils.py#L44>.

If we refactor the decorator to explicitly take a group and a role name inside that group, many of those will become unnecessary, and it will allow us to more easily express new access policies such as "those people allowed to use the announcement tools".

It may not be possible to remove all the special names. Nomcom chair is a particularly thorny thing to express since there may be more than one active at a time (and the group is named something like nomcomyyyy, not just nomcom)

___
_Issue migrated from trac:1365 at 2022-03-04 03:41:00 +0000_

**Comment by rjsparks** [comment]
Closing as stale. If the need becomes more pressing in the future it can be considered at that time.
