### ISSUE TITLE
When reporting state age, please show both the total time in state, and the time since the last sub-state change

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1371]
`keyword_sprint` `type_enhancement`   |    by adrian@olddog.co.uk

___

Currently, a document's main page, and the summary rows on AD status pages and document search results show how long a document has been in a state using a badge that says [for 117 days] or similar. The age reported there is ostensibly how long it's been since the document first entered the state. It would be useful to also show how long it's been in the substate(s).

For instance, for a document in
AD Evaluation::Revised I-D Needed
please show [for 120::2 days] or something similar.

___
_Issue migrated from trac:1371 at 2022-03-04 03:41:28 +0000_

**Comment by rjsparks** [comment]
merging this into #2711
