### ISSUE TITLE
state age calculation is inconsistant

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1372]
`keyword_sprint` `type_defect`   |    by adrian@olddog.co.uk

___

Please see the rows for 
draft-ietf-ccamp-rsvp-te-mpls-tp-oam-ext-12
and 
draft-ietf-mpls-lsp-ping-ttl-tlv-07
at <https://datatracker.ietf.org/doc/ad/adrian.farrel/>

At the time of this report, the state age badge says [for 13 days] for the first document and [for 115 days] for the second.

In one case, it appears to be counting from the last sub-state (that is, tag) change. In the other it appears to be counting from the last state change.

Why are these different?
(See also ticket #1371)

___
_Issue migrated from trac:1372 at 2022-03-04 03:41:32 +0000_

**Comment by rjsparks** [comment]
Merging this into #2711
