### ISSUE TITLE
Session Request form initializes resource choices too early

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1388]
`type_defect`   |    by rjsparks@nostrum.com

___

Currently the session request form initializes the resource choices statically at load instead of during __init__. This will make it hard to add the notion of whether a resource type is currently used.

___
_Issue migrated from trac:1388 at 2022-03-04 03:42:59 +0000_

**Comment by rjsparks** [comment]
See #3372 - closing this as duplicate
