### ISSUE TITLE
There are bad addresses parsed during submission, and bad addresses used when notifying folks of the submission

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1391]
`keyword_sprint` `type_defect`   |    by rjsparks@nostrum.com

___

The recent post of draft-iab-strint-report set up this relationship:
```
In: Document.objects.get(name='draft-iab-strint-report').documentauthor_set.get(author__person__name="Bert Bos").author.address
Out: u'unknown-email-Bert-Bos'
```

But Bert's address does appear in the document, and the database already knows about that address:

```
In: Person.objects.get(name="Bert Bos").email_set.all()
Out: [<Email: bert@w3.org>, <Email: unknown-email-Bert-Bos>]
```

Why didn't bert@w3.org get used for the documentauthor association?

The code that sends mail to the authors notifying them of the new version tried to send mail to unknown-email-Bert-Bos. It should pay attention at least to whether the email address is marked as active:

```
In: Email.objects.get(address="unknown-email-Bert-Bos").active
Out: False
```

___
_Issue migrated from trac:1391 at 2022-03-04 03:43:13 +0000_

**Comment by rjsparks** [comment]
Long OBE
