### ISSUE TITLE
Errors in submission handling happen when the parsed display name has a comma in it.

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1392]
`keyword_sprint` `type_defect`   |    by rjsparks@nostrum.com

___

A recent submission of draft-ietf-kitten-rfc4402bis resulted in data records saying:
```
In: Submission.objects.filter(name='draft-ietf-kitten-rfc4402bis').first().authors_parsed()
Out:
[{'email': u'shawn.emery@oracle.com', 'name': u'Shawn Emery'},
 {'email': u'nico@cryptonector.com', 'name': u'Cryptonector, LLC'}]
```

The output of that function is converted to simple strings by submission_confirmation_email_list, and that is fed straight to "To".

As a result, mail tries to go
```
   To: Shawn Emery <shawn.emery@oracle.com>, Cryptonector, LLC <nico@cryptonector.com>
```

which SMTP treats as three addresses, the middle of which is bad...

The code that parses drafts for authors should probably not have found Cryptonector, LLC in this case.

The code that uses these addresses should protect itself from commas. Perhaps putting the display names in double-quotes would be safest?

___
_Issue migrated from trac:1392 at 2022-03-04 03:43:18 +0000_

**Comment by rjsparks** [comment]
Closing this as stale.
