### ISSUE TITLE
NAK button, when asked for approving a new wg document

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1405]
`type_enhancement`   |    by loa@pi.nu

___

In some rare cases a wg chair might want to deny posting of a new working group document, this can happen e.g. when an author tries to post a document with a file name that indicates that it is a working group, but the draft has not been adopted by the working group. Today the only choice that is given a wg chair when asked to approve a new document is "approve" or sending a mail to the IETF secretariat and ask them to stop the posting. A deny button in parallel to the approve button would fix this.

___
_Issue migrated from trac:1405 at 2022-03-04 03:44:22 +0000_

**Comment by rjsparks** [comment]
closing this as stale - the cases are rare enough that the secretariat escape valve is sufficient
