### ISSUE TITLE
Add a graph of normative dependencies for a document

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1407]
`keyword_sprint` `type_defect`   |    by rjsparks@nostrum.com

___

(This has been around a few times, but has come up again in several conversations, the most recent with Cullen Jennings who was doing analysis as an RTCWeb co-chair)

It would be useful to see a graph of the closure of normative dependencies from a given document (what this document relies on, what those documents rely on, etc.). It might also be useful to include the closure of what relies on this document.

Most drafts, however, have a large set of attractors of very stable process or far back-in-history RFCs (such as TCP, or requirements for internet hosts). That should be considered noise, and should be elided or shown as a single collector node.

Much of the code rendering the dependency graphs for working groups should be reusable for this.

___
_Issue migrated from trac:1407 at 2022-03-04 03:44:34 +0000_

**Comment by rjsparks** [comment]
Closing as stale - if this rises to the level that someone really wants it again, a new issue can be opened.
