### ISSUE TITLE
Include idnit messages in mail sent to chairs for approving -00 documents

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1462]
`type_defect`   |    by rjsparks@nostrum.com

___

If idnits raises potential issues, particularly potential issues with the chosen boilerplate, the mail that requests their approval should have a prominent statement prompting them to check the draft carefully before approving the posting.

___
_Issue migrated from trac:1462 at 2022-03-04 03:49:12 +0000_

**Comment by rjsparks** [comment]
closing as stale
