### ISSUE TITLE
Submissions should expire

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1514]
`keyword_sprint` `type_defect`   |    by rjsparks@nostrum.com

___

There are many Submissions that are pending some form of approval indefinitely. From a recent database snapshot:

```

In: set(Submission.objects.values_list('state__name',flat=True))
Out:
{u"Awaiting Approval from Previous Version Authors'",
 u'Awaiting Initial Version Approval',
 u'Awaiting Manual Post',
 u'Awaiting Submitter Authentication',
 u'Cancelled',
 u'Posted',
 u'Uploaded'}

In: Submission.objects.filter(state__name__startswith='Awaiting').count()
Out: 1697

In: Submission.objects.filter(state__name='Awaiting Manual Post',submission_date__year=2008).count()
Out: 468

```

It would be better if Submissions timed out at some point, and be moved to some not-awaiting state (see the use scenario at #987).

I suggest 90 days (grooming this similarly to how we groom expiring drafts) and moving the Submissions either to Cancelled, or a new state of TimedOut.

___
_Issue migrated from trac:1514 at 2022-03-04 03:53:56 +0000_

**Comment by rjsparks** [comment]
There is an expire-submissions command in ietf/bin that is not being used. It needs to be vetted and tested, and if appropriate, plugged into bin/daily.

**Comment by rjsparks** [comment]
Fixed by https://github.com/ietf-tools/datatracker/pull/7461
