### ISSUE TITLE
Investigate alternate ways to represent 'republished' RFCs in the datatracker

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1548]
`type_defect`   |    by rjsparks@nostrum.com

___

In the rare cases where the RFC editor publishes an RFC replacing another recently published RFC to address a publishing issue (see 7158/7159 and 7386/7396), the current system creates a new Document object for the second RFC.

It has been suggested that it might make the history easier to follow if these were, instead, another version of the original Document object that represents the drafts and the first version of the RFC published.

Some initial thoughts on issues:

There is code that assumes there are either 0 or 1 versions of a document that is an RFC. Adjustment will have to happen to allow 2.

Any change would still need to preserve the Obsoletes document relationship.
This change would require code to deal with a Document obsoleting a previous version of itself.

While exploring, consider the alternative of making the history view show the related document history.

___
_Issue migrated from trac:1548 at 2022-03-04 03:56:41 +0000_

**Comment by rjsparks** [comment]
cc: @jennifer-richards 

I think with modern thinking the answer here is just "no".

Closing this as will-not-fix.

**Comment by rjsparks** [comment]
OBE (and should have been closed in 2023)
