### ISSUE TITLE
Investigate whether Submission objects should keep nameaddrs or only addrs for authors

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1582]
`type_defect`   |    by rjsparks@nostrum.com

___

Currently, a Submission object's authors and submitter CharFields are supposed to be populated  with name-addr strings such as
```
John Doe <john@example.org>
```

In practice, we collect many variants of malformed strings, including things like:
```
Doe, John <john@example.org>
John
```
and of course, just bare addresses.

These are used, at least, to send email to confirm and acknowledge submission.

We should investigate whether collecting the name part of the address here is actually useful. 

These are CharFields and not sets of Email records because we don't want to create Person and Email objects for unconfirmed (possibly spam) submissions. If we only capture the addresses and not the names, we stand to lose information about the submitter that could be useful in helping a new contributor post a draft. However, that information is probably available in the draft itself (but note there is no easy way to view of a draft while it is sequestered pending confirmation).

It may be that the right thing to do is keep the name-addr form in these fields, but parse out the addrs for sending mail.

___
_Issue migrated from trac:1582 at 2022-03-04 03:59:18 +0000_

**Comment by rjsparks** [comment]
closing as stale (and the modeling will be reconsidered when addressing submission staging)
