### ISSUE TITLE
Need better verification email address list entry fields

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1583]
`keyword_sprint` `type_defect`   |    by rjsparks@nostrum.com

___

When submitting a recent ballot position, an AD manually added an address to the CC line (to copy a genart reviewer) by cut-paste from an address book. The pasted address string looked like u'Last, First <name@example.com>'. 

When this was submitted to the mail subsystem, it resulted in an error for the address u'Last'.

The form validation should catch this instead.

The same should be done for the Document.notify field and any other place we ask for a list of comma separated addresses.

___
_Issue migrated from trac:1583 at 2022-03-04 03:59:24 +0000_

**Comment by rjsparks** [comment]
Long OBE with better validation
