### ISSUE TITLE
Show when an RFC in the metadata of a document has other alias names (such as BCP)

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1675]
`keyword_sprint` `type_enhancement`   |    by rjsparks@nostrum.com

___

In the Obsoletes or Replaces fields, when an RFC is listed, it would also be useful to show if that RFC is part (or all of) a BCP. There may be other aliases that would be useful to show.

___
_Issue migrated from trac:1675 at 2022-03-04 04:35:08 +0000_

**Comment by rjsparks** [comment]
This is being overtaken by the work on feat/rfc
