### ISSUE TITLE
Provide an IESG progress report

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1706]
`keyword_sprint` `type_enhancement`   |    by rjsparks@nostrum.com

___

The IESG liaisons often have to report things that can be easily extracted from the tracker, including:

* Groups chartered and closed since a given date
* WG personnel changes since a given date
* Chartering work currently in progress

This should be available on one or more pages (preferably one) to anyone at any time.

___
_Issue migrated from trac:1706 at 2022-03-04 04:37:45 +0000_

**Comment by rjsparks** [comment]
closing as OBE (noting that a general dashboard is being discussed that would likely include this data).
