### ISSUE TITLE
Email alias <barry-leiba-chairs@ietf.org> (and so on) are not generated

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1726]
`keyword_sprint` `type_defect`   |    by barryleiba@computer.org

___

Can we get the <adfirstname-adlastname-chairs> aliases back?  Thanks.

___
_Issue migrated from trac:1726 at 2022-03-04 04:39:18 +0000_

**Comment by rjsparks** [comment]
closing as stale.
