### ISSUE TITLE
Refactor markup in DocEvent desc fields (was format_history_text bug)

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1749]
`type_defect`   |    by lars@eggert.org

___

In ietf/templates/doc/document_history.html, the line
```
<td>[ e.desc|format_history_text|safe ]</td>
```
turns a text history line like this (from /doc/draft-ietf-lisp-ddt/history/)
```
<td>Notification list changed to &amp;quot;Luigi Iannone&amp;quot; &amp;lt;ggx@gigix.net&amp;gt;</td>
```
into
```
<td>Notification list changed to "Luigi Iannone" &lt;<a href="mailto:ggx@gigix.net>">ggx@gigix.net&gt;</a>;</td>
```
which is invalid HTML (and won't work to send email), because the &gt; is part of the href.

I can't quite warp my head around format_history_text and fix this, which is why I am filing the bug.

___
_Issue migrated from trac:1749 at 2022-03-04 04:41:23 +0000_

**Comment by larseggert** [comment]
Closing this, since the situation is much better now.

**Comment by rjsparks** [comment]
We still need to change DocEvent.desc to contain something like markdown and migrate all existing content to remove the embedded html. See #5030
