### ISSUE TITLE
/submit/status/ "File size" reports 0 bytes

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1766]
`keyword_sprint` `type_defect`   |    by fenner@fenron.net

___

I just happened to notice this on my recent submission:

https://datatracker.ietf.org/submit/status/71357/ reports "File size 0 bytes".  It reports the number of pages properly, and the files are still at https://www.ietf.org/staging/draft-ietf-v6ops-ipv6-mibs-obsolete-00.txt and https://www.ietf.org/staging/draft-ietf-v6ops-ipv6-mibs-obsolete-00.xml, so it's not like it's dynamically trying and failing to determine the file size of something that's been garbage-collected because of my delay in revisiting the submission.

(By the way, since you can upload 4 files, which file is this field talking about?  I guess it's implicitly the canonical text version?)

___
_Issue migrated from trac:1766 at 2022-03-04 04:42:40 +0000_

**Comment by rjsparks** [comment]
Closing in favor of #4334
