### ISSUE TITLE
Need explicit messages on unapproved liaison statements

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1808]
`type_enhancement`   |    by rcross@amsl.com

___

If a liaison statement is submitted and requires approval, the submitter should get an explicit message indicating who can approve the statement, including cases when only the Secretariat can approve the statement.

___
_Issue migrated from trac:1808 at 2022-03-04 04:46:04 +0000_

**Comment by rjsparks** [comment]
closing as stale.
