### ISSUE TITLE
Anchor-based links inside ballot popups do not solve the problem they were intended to solve

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1812]
`keyword_sprint` `type_defect`   |    by rjsparks@nostrum.com

___

At <datatracker.ietf.org/iesg/agenda/documents/> on any given week there are a bunch of documents with ballots. The ballots are represented with a grid of colored squares. If you click on a square you get a modal popup with the text of the ballot.

That popup has the ADs listed in the left column. If the AD has entered text as part of their position (a discuss perhaps), their name is a link. That link should cause the view in the popup to move to the text that AD entered.

As implemented the links look like
<http://datatracker.ietf.org/iesg/agenda/documents/#kathleen-moriarty>

At least with modern firefox, this is only partially working.

It works for the first ballot on the agenda page.

It doesn't work for most (any?) of the others - until you scroll the agenda page some. Then it will work for something else in the resulting view (sometimes), but nothing else.

___
_Issue migrated from trac:1812 at 2022-03-04 04:46:28 +0000_

**Comment by larseggert** [comment]
This is working now.
