### ISSUE TITLE
Datatracker and tools shortcut icons should have a retina form

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1816]
`type_enhancement`   |    by jonathan@vidyo.com

___

The shortcut icons look ugly on a retina (high-DPI) display, since they're only 16x16 pixels.  There should be a 32x32 version of them.

This is easy for tools which uses a .ico file (which can have multiple resolutions embedded); harder for datatracker, which uses a .png.

___
_Issue migrated from trac:1816 at 2022-03-04 04:46:49 +0000_

**Comment by larseggert** [comment]
Done.
