### ISSUE TITLE
The message to ADs to review a milestone is ambiguous

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1828]
`type_defect`   |    by rjsparks@nostrum.com

___

Example:

```
Added milestone "A second bogus milestone" for review, due December
2015.
```

The due date given is the proposed date for the milestone, not a deadline for the AD to approve the milestone.

The whole message should be replaced with something clearer, with simple instructions and even a link for the AD to use to complete the review of the milestone.

___
_Issue migrated from trac:1828 at 2022-03-04 04:47:51 +0000_

**Comment by rjsparks** [comment]
closing as stale
