### ISSUE TITLE
Problems with draft submission email parsing

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1835]
`type_defect`   |    by rcross@amsl.com

___

A comma in the email address string causes parsing problems:

In 6d4a31ba35b707e1679740f4da71dd1cec12e4f9: Submission.objects.get(name='draft-birrane-dtn-sbsp',rev='01').authors
Out6d4a31ba35b707e1679740f4da71dd1cec12e4f9: u'Edward J. Birrane, III <Edward.Birrane@jhuapl.edu>\nJeremy Pierce-Mayer <jeremy.mayer@insyen.com>\nDennis C. Iannicca <dennis.c.iannicca@nasa.gov>'

Edward: (550, '5.1.1 <Edward>: Recipient address rejected: User unknown in local recipient table')

The original message follows:

Subject:	New Version Notification for draft-birrane-dtn-sbsp-01.txt
Date:	Fri, 16 Oct 2015 14:11:01 -0700
To:	<Edward>, "III" <Edward.Birrane@jhuapl.edu>, "Dennis C. Iannicca" <dennis.c.iannicca@nasa.gov>, "Edward J. Birrane" <edward.birrane@jhuapl.edu>, "Dennis C. Iannicca" <dennis.c.iannicca@nasa.gov>, "Jeremy Pierce-Mayer" <jeremy.mayer@insyen.com>, "Jeremy Pierce-Mayer" <jeremy.mayer@insyen.com>

------------------------------------------

Here is an example of a submission which results in a <None> address 

In dc22fb842160a0c0387457a61838e807e01c8c4a: Submission.objects.get(name='draft-sreekantiah-idr-segment-routing-te').authors
Outdc22fb842160a0c0387457a61838e807e01c8c4a: u'Arjun Sreekantiah <asreekan@cisco.com>\nClarence FilsFils <cfilsfil@cisco.com>\nStefano Previdi <sprevidi@cisco.com>\nSiva Sivabalan <msiva@cisco.com>\nPaul Mattes <pamattes@microsoft.com>\nSteven Lin <None>'

___
_Issue migrated from trac:1835 at 2022-03-04 04:48:28 +0000_

**Comment by rjsparks** [comment]
closing as stale.
