### ISSUE TITLE
Add button from agenda to slides

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1838]
`keyword_easy` `keyword_sprint` `type_enhancement`   |    by lars@eggert.org

___

The buttons on the agenda page currently only allow to download the IDs for a session. It would be useful to also allow downloading the slides, or at least provide a link over to the respective section on the meeting materials page.

___
_Issue migrated from trac:1838 at 2022-03-04 04:48:42 +0000_

**Comment by larseggert** [comment]
OBE
