### ISSUE TITLE
Unicode object replacement character U+FFFC in slide titles

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1840]
`type_defect`   |    by jonathan@vidyo.com

___

Looking at the meeting materials page https://datatracker.ietf.org/meeting/94/materials.html, I see several drafts whose names start with the character U+FFFC -- notably ￼Metadata discovery for third party authorized TURN session and ￼Ufrag Permissions for TURN, under TRAM, and (appearing twice) ￼￼Token Binding over HTTPS, for TOKBIND.

Not sure why those are there. It seems unlikely the chair would have typed them?

___
_Issue migrated from trac:1840 at 2022-03-04 04:48:51 +0000_

**Comment by rjsparks** [comment]
closing as stale.
