### ISSUE TITLE
filter out invalid email addresses from the generated document and group alias lists

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1865]
`type_defect`   |    by henrik@levkowetz.com

___

We already filter out invalid email addresses when sending email from within
the datatracker, but we're not applying the same validation to the addresses
put in the alias lists.

___
_Issue migrated from trac:1865 at 2022-03-04 04:50:53 +0000_

**Comment by rjsparks** [comment]
closing as stale.
