### ISSUE TITLE
"Undefer ballot" button should disappear once the IESG telechat is passed

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1872]
`type_defect`   |    by bclaise@cisco.com

___

Hi,

"Undefer ballot" button should disappear once the IESG telechat (for which the defer button was pushed) is passed

Example: https://datatracker.ietf.org/doc/draft-ietf-clue-framework/history/
2015-12-01 	24 	Benoit Claise 	IESG state changed to IESG Evaluation - Defer from IESG Evaluation

This document is on the Dec 17th telechat (today), and I still see the "undefer ballot" today. This is confusing.

Regards, Benoit

___
_Issue migrated from trac:1872 at 2022-03-04 04:51:28 +0000_

**Comment by rjsparks** [comment]
closing this as stale (and probably unimplementable the way "on telechat" is currently modeled).
