### ISSUE TITLE
Manual post SubmissionEvent description is set incorrectly

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1923]
`type_defect`   |    by rjsparks@nostrum.com

___

at <http://wiki.tools.ietf.org/tools/ietfdb/browser/trunk/ietf/submit/views.py#L313>

The state being tested has _always_ just been set to 'posted'.
No SubmissionEvent containing the manual post description has been created since 2013.

___
_Issue migrated from trac:1923 at 2022-03-04 04:55:18 +0000_

**Comment by rjsparks** [comment]
OBE
