### ISSUE TITLE
Changing the documents associated with a session should invalidate the cache on the materials page

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1931]
`type_defect`   |    by rjsparks@nostrum.com

___

Currently, the materials view (in the template) only uses timestamps on Document objects to determine when to invalidate it's cache. It should also (or maybe only) pay attention to when SessionPresentation rows change.

___
_Issue migrated from trac:1931 at 2022-03-04 04:55:54 +0000_

**Comment by rjsparks** [comment]
Whatever caching was involved at the time has changed. Closing this as OBE.
