### ISSUE TITLE
Make it easy to see what area (and group) an RFC came out of

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1937]
`keyword_sprint` `type_defect`   |    by rjsparks@nostrum.com

___

The main document page should make it clearer what _area_ a document was published from, when it was published from an area. It currently indicates the group, but only points to the current notion of the group as far as the datatracker is concerned.

This is problematic with groups that have closed and reopened, possibly in different areas (see XMPP), groups that get renamed, and groups that move between areas (especially because of area restructuring like the recent creation of ART).

The main page should be sensitive to the doc being published as an RFC, and look at the history at the time of publication to speak about the group and area.

___
_Issue migrated from trac:1937 at 2022-03-04 04:56:23 +0000_

**Comment by rjsparks** [comment]
Closing as wontfix - the confusion is rare, and the document history is better about helping people find the right group to contact if needed,

**Comment by ajeanmahoney** [comment]
Although the comment above says that it was supposed to be closed as wontfix, it's still open. Following the WG link will show the area that the WG was in when the document was published. The History tab for the WG can show when the WG moved to a different area and/or closed (see https://datatracker.ietf.org/wg/xmpp/history/).
