### ISSUE TITLE
Link to Meetecho Videos from Meeting Materials Page

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1954]
`type_enhancement`   |    by amorris@amsl.com

___

It would be great to have the links to Meetecho session recordings available at ietf.org in the draft meeting materials view, before the Proceedings are finalized. We have inserted the links to the YouTube videos (https://datatracker.ietf.org/secr/proceedings/95/recording/) but they don't appear in IETF 95 meeting materials. Since the recordings are most likely to be accessed in the weeks directly following a meeting, this would be a great enhancement. Now people need to access them off of https://ietf95.conf.meetecho.com/.

___
_Issue migrated from trac:1954 at 2022-03-04 04:57:38 +0000_

**Comment by larseggert** [comment]
I think this is done?
