### ISSUE TITLE
Custom colors for agenda

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1990]
`type_enhancement`   |    by kivinen@iki.fi

___

Earlier there used to be a way to add custom colors on the agenda, i.e., I could mark all the interesting groups with yellow, and one that is bit more important than others with orange, and those where I really need to go with red, so I can immediately see where to go, and still see the full agenda for the timeslot. 

This feature was lost at one point.

___
_Issue migrated from trac:1990 at 2022-03-04 05:00:37 +0000_

**Comment by rjsparks** [comment]
Closing as this is a feature in the new agenda. @kivinen - reopen or open other issues if there are still things you would like to see differntly.
