### ISSUE TITLE
NomCom Feedback page crowded in IE

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2006]
`type_defect`   |    by adrian@olddog.co.uk

___

The "no feedback" token is dropped on top of the name of the nominee making t hard to work out which is which.

This seems to be an IE feature since in Chrome it is somewhat easier to see,

FWIW, the hover-over only shows the email address of the nominee and not the name, making it hard to guess the name through that approach.

___
_Issue migrated from trac:2006 at 2022-03-04 05:01:51 +0000_

**Comment by larseggert** [comment]
Suggest to close?
