### ISSUE TITLE
Allow WG Chair to provide replaces information when approving a -00 draft submission

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2063]
`type_enhancement`   |    by housley@vigilsec.com

___

Most often, the the author provides the replaces information when the draft is submitted, but it is a good idea to show the WG chair the information that the author provided, and if none, allow the WG Chair to provide it.

___
_Issue migrated from trac:2063 at 2022-03-04 05:33:35 +0000_

**Comment by rjsparks** [comment]
Will close as "has easy alternate path".
