### ISSUE TITLE
review importer left hyphens at the end of draft names in the title of the review documents

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2077]
`type_defect`   |    by rjsparks@nostrum.com

___

Last Call Review of draft-ietf-appsawg-rfc3462bis- doesn't need the trailing hyphen

___
_Issue migrated from trac:2077 at 2022-03-04 05:34:38 +0000_

**Comment by rjsparks** [comment]
This involves a _lot_ (1170) of the imported reviews, but may not actually be worth fixing (we've had zero complaints for years now). I'm going to close this as "won't fix".

**Comment by rjsparks** [comment]
to clarify what the terse description was originally pointing to:
```
>>> Document.objects.filter(type="review",title__endswith="-").count()
1170
>>> Document.objects.filter(type="review",title__endswith="-").last().title
'Last Call Review of draft-hardie-rfc6455-iana-clarification-'
```
