### ISSUE TITLE
Somewhat unruly button layout on review request page

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2098]
`type_defect`   |    by henrik@levkowetz.com

___

When a reviewer looks at a requested review, i.e., /doc/draft-ietf-foo-bar/reviewrequest/NNNN/, the layout of the available buttons (reject, accept, complete, reassign, close request) position them all over the place -- it would be nicer if they showed up in some kind of pattern; maybe in an aligned column.

(Laying them out in a row would be more in line with most other forms, but would not show the buttons close to the status line with which they are associated, so might be a bit of a loss.)

___
_Issue migrated from trac:2098 at 2022-03-04 05:36:17 +0000_

**Comment by larseggert** [comment]
OBE?

**Comment by rjsparks** [comment]
What's requested here will be addressed through of the natural pressure of improvement as the front-end changes.
