### ISSUE TITLE
"Abandon chartering" email is confusing

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2100]
`keyword_sprint` `type_defect`   |    by lars@eggert.org

___

When abandoning the chartering of a group, the email that is sent out is:
```
To: <nmlrg-chairs@ietf.org>, <irtf-chair@irtf.org>
Subject: ID Tracker State Update Notice: <charter-irtf-nmlrg-00-00.txt>

State changed to Not currently under review.
ID Tracker URL: https://datatracker.ietf.org/doc/charter-irtf-nmlrg/
```
That's not really capturing what has happened. It should say something along the lines of "charting has been abandoned".

Also, the subject containing "ID Tracker" is confusing, since this is not about an ID. Maybe we should change the term to "Datatracker" everywhere?

___
_Issue migrated from trac:2100 at 2022-03-04 05:36:28 +0000_

**Comment by larseggert** [comment]
Subject was changed, and I can live with the email content.
