### ISSUE TITLE
Make it easier to navigate from a review document to the document being reviewed

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2121]
`type_defect`   |    by rjsparks@nostrum.com

___

Right now, at 
/doc/review-ietf-curdle-dnskey-eddsa-02-genart-lc-romascanu-2016-12-11/
there is no link back to draft-ietf-curdle-dnskey-eddsa

___
_Issue migrated from trac:2121 at 2022-03-04 05:38:05 +0000_

**Comment by larseggert** [comment]
There is now.
