### ISSUE TITLE
excessive space forces horizontal scrolling

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2245]
`type_defect`   |    by mt@lowentropy.net

___

See for example: https://datatracker.ietf.org/doc/html/draft-ietf-rtcweb-return

When the page is at the minimum width that allows the sidebar, a considerable amount of padding/margin is added to the sides of the draft text.  This leads to the space available to the text being too narrow.

The way that this is handled (overflow:auto) leads to horizontal scrolling, which might be reasonable for extremely narrow screens, but - even there - avoiding horizontal scrolling is *highly* desirable.

___
_Issue migrated from trac:2245 at 2022-03-04 05:48:07 +0000_

**Comment by larseggert** [comment]
OBE
