### ISSUE TITLE
width on .rfcmarkup pre.meta-info causes unnecessary horizontal scrolling

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2425]
`type_defect`   |    by mt@lowentropy.net

___

There is already a width directive that is better tuned.  Removing the directive works well enough (absent issues already raised).

For example: https://datatracker.ietf.org/doc/html/draft-thomson-quic-invariants

___
_Issue migrated from trac:2425 at 2022-03-04 06:36:40 +0000_

**Comment by larseggert** [comment]
OBE
