### ISSUE TITLE
Notify nomcom members when new feedback is available

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2432]
`type_defect`   |    by rjsparks@nostrum.com

___

It would be useful for nomcom members to be able to subscribe for a notification that, for instance, a new questionnaire response has been received.

One possible solution is an email once a week (on a day configurable by the chair to help align with when the nomcom meets) summarizing how many new feedback objects of each type are available.

___
_Issue migrated from trac:2432 at 2022-03-04 06:37:26 +0000_

**Comment by richsalz** [comment]
I am not so sure if this is still worthwhile.  The nomcom `private/view_feedback` does add a "NEW" tag when there is new data. Since individual feedback items (as opposed, say, the questionnaires) can't be easily viewed, perhaps this should be closed wontfix.
