### ISSUE TITLE
datatracker profile page issues

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2462]
`keyword_person` `type_enhancement`   |    by tte@cs.fau.de

___

a) The profile page does not explain which profile elements will show up on the datatracker/person page. It would be great if every element of the profile would explain whether or not it is displayed publically. I had to experiment and figure out that the affiliation/address are not made public, but the others are.

b) It would be great if one could select for each profile element whether it should be made public or not (binary choice)

c) It would be great if the profile page would have a link to the public page - most people with datatracker account would probably not even know that they have a datatracker/person/name page.

d) It would be great if the profile page would allow uploading of a photo

___
_Issue migrated from trac:2462 at 2022-03-04 06:40:09 +0000_

**Comment by rjsparks** [comment]
The fix for #4521 is merged. It does address all but d) in the original report (we'll deal with that seperately), but without much finesse. The end result is that anything that's displayed can be expected to be public _somewhere_.
