### ISSUE TITLE
Make it possible to download numbers from the statistics reports

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2631]
`keyword_sprint` `type_defect`   |    by rjsparks@nostrum.com

___

Particularly when there's a graph, having an easy download for the data that made the graph would be useful.

___
_Issue migrated from trac:2631 at 2022-03-04 07:03:21 +0000_

**Comment by rjsparks** [comment]
closing per https://github.com/ietf-tools/datatracker/issues/3712
