### ISSUE TITLE
(OBE?) Submission tool will need additional work with v3 files

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2679]
`type_defect`   |    by henrik@levkowetz.com

___

RFC 4228 says in Section 7:
```  
                      ... XML source is acceptable without accompanying
   plain text only if the Toolset successfully generates a draft in
   plain text format from the XML source, as a part of the processing
   step documented below (R69/b).
```

which generally means that the submitted xml file has to be standalone.

However, with the v3 formatters, <artwork> may refer to external URI resources, and without explicitly running the preptool and saving the resulting xml, these external resources will not be captured, and could change or go away.

It is also possible to construct a v2 xml file that uses for instance xml entity constructs to pull in external content from the web.  (This is routine
for references, but could also be used for body content.)  We've taken no action to prevent this, and it could lead to a similar situation.  Possibly this can be handled by running xml2rfc with the --expand switch in order to generate an xml file that will be truly standalone.

In any case, this needs some attention if we want to capture the complete xml for a given submission.

___
_Issue migrated from trac:2679 at 2022-03-04 07:07:19 +0000_

**Comment by rjsparks** [comment]
Closing this as (mostly) OBE, noting that we still need to address #3577.
