### ISSUE TITLE
photos need previews

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2688]
`type_enhancement`   |    by lars@eggert.org

___

The photo pulled in for me on https://datatracker.ietf.org/wg/quic/photos/ has 7.4MB. That seems suboptimal, given that it's rendered 100 pixels wide...

___
_Issue migrated from trac:2688 at 2022-03-04 07:08:00 +0000_

**Comment by larseggert** [comment]
I think this can be closed?

**Comment by larseggert** [comment]
We have #2209, so we could close this one.
