### ISSUE TITLE
Markdown support for charters

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2695]
`keyword_sprint` `owner:pusateri@bangj.com` `type_enhancement`   |    by lars@eggert.org

___

Could we allow charters to be edited in Markdown? That would greatly improve their web rendering, and ASCII representations can be easily obtained, too.

___
_Issue migrated from trac:2695 at 2022-03-04 07:08:35 +0000_

**Comment by rjsparks** [comment]
Time to wake this back up. The rendertest has been in place for almost a year, and the feedback of the results has stopped. The IESG has worked out the ability to make cosmetic changes - we need to finish deploying this.

**Comment by rjsparks** [comment]
cc @larseggert

**Comment by larseggert** [comment]
Let's do it and deal with any fallout after.

**Comment by rjsparks** [comment]
Closing this as done (see #6628)
