### ISSUE TITLE
Updated-by list is sorted unintuitively

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2723]
`keyword_sprint` `type_defect`   |    by rjsparks@nostrum.com

___

It might be more useful to sort the updates and updated-by lists on a documents main page by RFC number.

Right now, for instance, the main page for RFC1123 says:
'''
Updated by RFC 5966, RFC 2181, RFC 5321, RFC 7766, RFC 1349
'''

___
_Issue migrated from trac:2723 at 2022-03-04 07:11:00 +0000_

**Comment by larseggert** [comment]
It's ordered numerically now - close?
