### ISSUE TITLE
IPR disclosure notification e-mails have misplaced URL-encoding of things like ampersands

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2734]
`type_defect`   |    by jabley@hopcount.ca

___

Per subject, example below; apostrophe in Cisco's, quotation marks around the title and embedded within Warren's name are encoded as HTML character entities rather than in ASCII, despite the fact that the message is in plain text.

Begin forwarded message:

From: IETF Secretariat <ietf-ipr@ietf.org>
Subject: [DNSOP] IPR Disclosure Cisco&#39; s Statement about IPR related to draft-ietf-dnsop-serve-stale
Date: 21 June 2019 at 13:00:58 EDT
To: <draft-ietf-dnsop-serve-stale@ietf.org>
Cc: dnsop@ietf.org, ipr-announce@ietf.org

Dear David C Lawrence, Warren &quot;Ace&quot; Kumari, Puneet Sood:

An IPR disclosure that pertains to your Internet-Draft entitled &quot;Serving
Stale Data to Improve DNS Resiliency&quot; (draft-ietf-dnsop-serve-stale) was
submitted to the IETF Secretariat on  and has been posted on the "IETF Page
of Intellectual Property Rights Disclosures"
(https://datatracker.ietf.org/ipr/3590/). The title of the IPR disclosure is
"Cisco&#39;s Statement about IPR related to draft-ietf-dnsop-serve-stale"

Thank you

IETF Secretariat

_______________________________________________
DNSOP mailing list
DNSOP@ietf.org
https://www.ietf.org/mailman/listinfo/dnsop

___
_Issue migrated from trac:2734 at 2022-03-04 07:11:50 +0000_

**Comment by larseggert** [comment]
This seems to be fixed now

**Comment by larseggert** [comment]
https://mailarchive.ietf.org/arch/msg/ipr-announce/VlsbxF1Jw3T6EQ84O2yyOEklUWY/

**Comment by rjsparks** [comment]
The shifting sands of the encoding wastelands favor us today.
