### ISSUE TITLE
Extract any remaining relevant issues from the old bootstrap todo page into individual tickets

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2778]
`type_defect`   |    by rjsparks@nostrum.com

___

See <https://trac.ietf.org/trac/ietfdb/browser/trunk/ietf/templates/release/todo.html?rev=9551>

___
_Issue migrated from trac:2778 at 2022-03-04 07:15:27 +0000_

**Comment by larseggert** [comment]
OBE
