### ISSUE TITLE
Something wrong with the message archive links

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2789]
`type_defect`   |    by kivinen@iki.fi

___

I was trying to complete the review for draft-ietf-ecrit-data-only-ea:

https://datatracker.ietf.org/doc/draft-ietf-ecrit-data-only-ea/reviewrequest/10812/complete/

It properly found out 3 emails in the secdir list but returned url to mailarchive.ietf.org for the final review as follows:

https://mailarchive.ietf.org/arch/msg/secdir/fkBCkz0BdqT686DQ9SM_pNWmSrQ

and when I tried to save review, I got error saying 

  Trying to retrieve the URL resulted in status code 404: Not Found. Please provide an URL that can be retrieved.

If I try to manually cut & paste that url, I do get same error. If I find the correct url for the email:

https://mailarchive.ietf.org/arch/msg/secdir/ifkPx-TombE6PuKsLs71m04PyFg

and put that in the url field, then everything works. 

___
_Issue migrated from trac:2789 at 2022-03-04 07:16:26 +0000_

**Comment by larseggert** [comment]
@rpcross close or transfer to mailarchive?

**Comment by rjsparks** [comment]
This is essentially repaired, and the last bits are already tracked in the mailarchive project - I'll close this one.
