### ISSUE TITLE
When previous review request was rejected the output in reassignment page is not understandable

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2798]
`type_defect`   |    by kivinen@iki.fi

___

Previous reviewer of the document did not have time to review the document and the assignment got rejected. The output on the 

https://datatracker.ietf.org/review/secdir/reviews/manage/unassigned/

page for this document is less than optimal:

Previous review of this document: result unavail. by Russ Mundy 

Better output would be to say 

Previous review of this document was rejected by Russ Mundy.

most likely the output is bad also if the previous review assignment was withdrawn or timed out with no response error.

___
_Issue migrated from trac:2798 at 2022-03-04 07:17:10 +0000_

**Comment by kivinen** [comment]
This has been fixed already. Now it will not show rejected, withdrawn etc reviews in the reassignment page. This issue can be closed.

**Comment by rjsparks** [comment]
obe
