### ISSUE TITLE
If previous review got no response there is no point trying to reassign document to same person

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2836]
`type_defect`   |    by kivinen@iki.fi

___

When I mark some review as no response, and try to assign it again, the tool will automatically pick the previous reviewer who did not respond even if he is unavailable... It should not try to reassign document back to same person if last review requested was no response (or rejected, but that was taken care of by other ticket already).

___
_Issue migrated from trac:2836 at 2022-03-04 07:36:26 +0000_

**Comment by kivinen** [comment]
I tested this with current version of the datatracker, and even if the previous reviewer was at the top of the queue, the system did not assign the document to him because he had previously ended up having no response review result status. So think this can be closed.
