### ISSUE TITLE
Open slides in a new browser's tab

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2842]
`type_enhancement`   |    by valery@smyslov.net

___

On meeting agenda page (e.g. https://datatracker.ietf.org/meeting/106/agenda) 
when you click "Show Meeting Materials" button a pop-up window appears 
showing agenda for the WG and a list of links to the slides (and minutes for past meeting).
When you want to see some slides you click on the link and the slides open in the same window (tab).
When you finished working with these slides and push browser's "Back" button, 
you get back to an agenda page, so that the pop-up window with the WG materials 
is closed. If you want to see other slides, you have to click "Show Meeting Materials" 
again, scroll down to the list of links to the slides and click another link.
This is inconvenient. I think it's better to open slides in a new browser's tab,
so that the pop-up window remains open and you can easily get back to it to 
open other slides.

___
_Issue migrated from trac:2842 at 2022-03-04 07:37:05 +0000_

**Comment by larseggert** [comment]
They seem to open in a new tab on the new agenda page. Close?

**Comment by rjsparks** [comment]
@smyslov - Is there still a change here you are looking for?

**Comment by smyslov** [comment]
If they now open in a new tab, it's fine. In this case the ticket can be closed.
