### ISSUE TITLE
Assignment queue got stuck

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2879]
`type_defect`   |    by kivinen@iki.fi

___

I did assignments 2020-01-19 and the list of next reviewers was:

  Joseph Salowey
  Rich Salz
  Stefan Santesson
  Yaron Sheffer
  Rifaat Shekh-Yusef
  Melinda Shore
  Valery Smyslov
  Robert Sparks
  Takeshi Takahashi
  Tina Tsou

I did next assignments last week 2020-01-23 and the list of next reviwers stayed exactly same, i.e., it did not get updated last week, and when I did assignements again now I assigned same documents again to people who did assignments last week, and the queue did not go forward even then.

The head of the queue is Joseph Salowey which is unavailable, so that might cause the issue. 

___
_Issue migrated from trac:2879 at 2022-03-04 07:40:46 +0000_

**Comment by kivinen** [comment]
I haven't seen this happen for long time anymore, and I think we already fixed few issues that could have caused this, so I think this issue could be closed. We can always reopen or create a new issue if this thing happens again.
