### ISSUE TITLE
Clean form input to validate against what the database can store

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2895]
`type_defect`   |    by henrik@levkowetz.com

___

A recent crash was a case where a submitted review used a character (U+1F642,
Slightly Smiling Face) that lies outside the unicode Basic Multilingual
Plane.  Such characters cannot be saved in the MySQL utf-8 encoding the
database currently uses.

We should find a way to generally clean form input text that contain
such characters, to avoid crashing.

___
_Issue migrated from trac:2895 at 2022-03-04 07:42:18 +0000_

**Comment by kesara** [comment]
This can be closed because we are moving PostgreSQL.
