### ISSUE TITLE
Editing reviewer availability does not send email to reviewer

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2898]
`keyword_sprint` `type_enhancement`   |    by mahoney@nostrum.com

___

In the review tool, I selected Skip Next Assignment 1 for a reviewer that was behind on other assignments. When I hit save, an email was sent to the other Gen-ART secretary but not to the reviewer. 

___
_Issue migrated from trac:2898 at 2022-03-04 07:42:37 +0000_

**Comment by kivinen** [comment]
I think the review tool now sends much more frequent emails to reviewers for status changes etc. Is this issue still open or has it already been fixed in the datatracker?

**Comment by kivinen** [comment]
Tested this in sandbox and it seems the datatracker does not send email updates when review team secretary changes his/her review settings, by for example incrementing / decrementing skip count.

**Comment by kivinen** [comment]
I think this is duplicate of #3403
