### ISSUE TITLE
Incorrect validation error for XML

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2900]
`owner:mark@painless-security.com` `type_defect`   |    by julian.reschke@gmx.de

___

The validation fails for <iref> elements that contain a comment; like that
```
  <iref item="foo"><!--bar--></iref>
```
Marking this as major because it might cause people not to submit XML although they have it.

___
_Issue migrated from trac:2900 at 2022-03-04 07:42:48 +0000_

**Comment by rjsparks** [comment]
@reschke : Have you encountered this since the original report. If not, I plan to close this as OBE.
