### ISSUE TITLE
Make RFCs first-class document objects

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2917]
`type_enhancement`   |    by rjsparks@nostrum.com

___

Investigate making RFCs first-class document objects to faciliate being able to model BCPs that represent groups of RFCs properly. Then fix the rfc sync script to update BCP aliases when changes occur changes (a BCP points to new RFC numbers)

___
_Issue migrated from trac:2917 at 2022-03-04 07:44:28 +0000_

**Comment by rjsparks** [comment]
This will happen as one of the first steps in the RPC toolchain modernization effort.

**Comment by rjsparks** [comment]
deployed with 12.0.0
