### ISSUE TITLE
URLs surrounded in angle brackets in uploaded txt agendas are not rendered correctly

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2920]
`type_defect`   |    by resnick@episteme.net

___

See the "discussion" items in  https://datatracker.ietf.org/doc/agenda-107-gendispatch/ to see that the URLs have disappeared.

___
_Issue migrated from trac:2920 at 2022-03-04 07:44:45 +0000_

**Comment by larseggert** [comment]
I think this is done.
