### ISSUE TITLE
Replace buttons which are links with something which is recognisable as links, preferably in submenu form.

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2948]
`type_defect`   |    by henrik@levkowetz.com

___

Replace buttons which are links with something which is recognisable as links, preferably in submenu form.

___
_Issue migrated from trac:2948 at 2022-03-04 07:47:31 +0000_

**Comment by larseggert** [comment]
OBE?

**Comment by rjsparks** [comment]
We can close it. I think there are still places we should normalize UI but that will happen with the coming wave of front-end work.
