### ISSUE TITLE
Failure to load CSS and metadata.min.js for v3 HTML resource on datatracker.

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#2990]
`type_defect`   |    by magnus.westerlund@ericsson.com

___

When loading https://www.ietf.org/id/draft-ietf-tsvwg-datagram-plpmtud-21.html in Chrome 81.0.4044.138 on Windows 10 (1809)

It fails to load two resources according to the console:

rfc-local.css which for which the full URL is: https://www.ietf.org/id/rfc-local.css which has been cancelled. (However the full URL results in a 404). 

metadata.min.js which has the full URL: https://www.ietf.org/id/metadata.min.js
which resulted in a 404. 

___
_Issue migrated from trac:2990 at 2022-03-04 07:51:33 +0000_

**Comment by larseggert** [comment]
OBE?

**Comment by rjsparks** [comment]
The issue still festers (and will likely be an RSWG conversation), but this ticket is not needed to drive work on it.
