### ISSUE TITLE
Admin forms for group should validate acronyms more carefully

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#3026]
`type_defect`   |    by rjsparks@nostrum.com

___

Currently, the admin allows creating groups with acronyms that violate the expectations of the patterns in various urls.py. At the very least, it is allowing uppercase letters, and it shouldn't

___
_Issue migrated from trac:3026 at 2022-03-04 07:55:03 +0000_

**Comment by rjsparks** [comment]
Closing this as obe - other work should be driven by specific issues (such as #6825)
