### ISSUE TITLE
Cut-and-paste from CodiMD

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#3046]
`type_defect`   |    by henrik@levkowetz.com

___

It would be useful to be able to cut-n-paste minutes from CodiMD, but currently the HTML sanitization makes the results unsatisfactory.  From <francesca.palombini@ericsson.com>:

I was trying to upload my minutes in the HTML version that codimd creates. The problem is when I upload them I get the following message from the datatracker:

"Uploaded html content is sanitized to prevent unsafe content. Your upload minutes-108-cbor-00.html was changed by the sanitization; please check the resulting content."

And when I open the minutes the table of content seems to appear on top of the minutes and make them unreadable. (see: https://www.ietf.org/proceedings/108/minutes/minutes-108-cbor-00.html )

I could use the Raw HTML minutes from the codimd, but if possible I'd like to keep the nice look of the HTML. I tried to see if I could remove the table of content from codimd but could not find a way.

___
_Issue migrated from trac:3046 at 2022-03-04 07:57:05 +0000_

**Comment by chrysn** [comment]
This appears to be resolved in the latest data tracker release; there is an "import from notes.ietf.org" / "import preview" step now.

It has [some remaining problems](https://github.com/ietf-tools/datatracker/issues/3851), but they're probably better handled in a separate issue.

**Comment by rjsparks** [comment]
Closing as OBE
