### ISSUE TITLE
Agenda rows don’t show icons on my iPhone

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#3049]
`type_defect`   |    by lars@eggert.org

___

When viewing the agenda on my phone, I do t get any of the session icons shown in either horizontal or vertical mode. This makes meeting participation impossible.

___
_Issue migrated from trac:3049 at 2022-03-04 07:57:21 +0000_

**Comment by larseggert** [comment]
OBE
