### ISSUE TITLE
expired WG drafts should still be automatically displayed somewhere at /group/<acronym/documents

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#3078]
`type_defect`   |    by bob.hinden@gmail.com

___

At the moment, when a WG draft expires, it disappears from the group's /document page.

It should instead continue to be shown _somewhere_ on the page, perhaps in an expired drafts section.

___
_Issue migrated from trac:3078 at 2022-03-04 08:00:32 +0000_

**Comment by smyslov** [comment]
I think the issue may be closed...

**Comment by rjsparks** [comment]
Yes, thanks - by #4252
