### ISSUE TITLE
Timeslot creation and management needs improvement

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#3127]
`owner:jennifer@painless-security.com` `type_defect`   |    by rjsparks@nostrum.com

___

Right now, timeslot objects are created mostly by side-effect - places in the meeting and or secr/meetings code will bring them into existence when _other_ things are created.

The current strategy creates many timeslots that are never used - see, for example, the large number of timeslot objects created with the name "Hot RFC Lightning Talks" for IETF 109 spread across many rooms.

We (Henrik, Robert, Ryan) have consistently had to make manual changes to the timeslots to account for edges for the last many meetings. Instead, we need to rethink how they are created and managed - the workflow with them needs to be more natural, and in the hands of the people with the task of setting a meeting's schedule.

___
_Issue migrated from trac:3127 at 2022-03-04 08:05:22 +0000_

**Comment by jennifer-richards** [comment]
Closing this - too open-ended to be of further value. Individual bugs / feature requests should replace it.
