### ISSUE TITLE
Reconsider how sessions like AD office hours are modeled.

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#3128]
`owner:jennifer@painless-security.com` `type_defect`   |    by rjsparks@nostrum.com

___

Currently, AD office hours are entered as session of the group "IESG".
This leads to sharp corners in the agenda page, pointing to the iesg codimd page and the iesg jabber room (which is not publically accessible).

They might better be listed as sessions of the area (such as TSV, but not the area group, such as tsvarea - not all areas _have_ area groups). There may be other options.

Alternatively, we may need these to use a new TimeSlotTypeName - something like "office hours" to help make the agenda show the right things.

___
_Issue migrated from trac:3128 at 2022-03-04 08:05:31 +0000_

**Comment by rjsparks** [comment]
OBE.
