### ISSUE TITLE
Duplicate moment.js library

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#3132]
`type_defect`   |    by kivinen@iki.fi

___

The agenda & Upcoming code will include the moments library with latest versions pulled to the externals/static/moment, but there is also one version in the static/ietf/js/agenda/moment.min.js. This static version is used by the ietf/templates/meeting/room_edit.html.

Most likely the room_edit.html can simply be changed to use the external version and static version can be removed, but this needs to be tested and checked it works before it can be done.

___
_Issue migrated from trac:3132 at 2022-03-04 08:05:54 +0000_

**Comment by larseggert** [comment]
OBE
