### ISSUE TITLE
Links off of datatracker.ietf.org/wg/ are generic

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#3138]
`type_defect`   |    by paul.hoffman@icann.org

___

On https://datatracker.ietf.org/wg/, the "Issue Tracker" and "Wiki" links for each area are just URLs back to this page itself. The page source shows empty hrefs.

___
_Issue migrated from trac:3138 at 2022-03-04 08:06:23 +0000_

**Comment by larseggert** [comment]
OBE
