### ISSUE TITLE
Improve the utility of the nonwg-list list

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#3139]
`type_defect`   |    by cabo@tzi.org

___

From the thread at

https://mailarchive.ietf.org/arch/msg/tools-discuss/t8HM4nZ-4PikUD7xxNbCuIfLQV8

```

I think the list at

https://datatracker.ietf.org/list/nonwg

might benefit from an indication of how much mold has grown over a list (and maybe filter for active ones).

Not sure it really needs to start with 101-newcomers…

```

___
_Issue migrated from trac:3139 at 2022-03-04 08:06:27 +0000_

**Comment by larseggert** [comment]
OBE?

**Comment by rjsparks** [comment]
I don't think it's OBE. The page has cruft. It really should be replaced with something more useful to the community.

See also #5271 (which, if taken wholly, would make this page go away), and remember Jay's wireframe of the interface he'd _like_ to see for managing mail list subscriptions.

I think, though, that the work needed for #5271 will include what this ticket asks for, so I'll close this one in favor of that.
