### ISSUE TITLE
Style bug on doc/html

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#3181]
`type_defect`   |    by mt@lowentropy.net

___

The HTML-ized rendering of documents, for example https://datatracker.ietf.org/doc/html/rfc8446 is good, but there is a style bug at certain window widths.

When window.innerWidth is above 993, the document is approximately centred.  Below this, different style rules apply and the document renders on the left of the viewport.  However, from a width of about 993 to about 1027, the rules on the 'rfcmarkup' div element do not allow enough space for the document content.  The result is that a horizontal scroll box is added for every page.  The horizontal scrollbar is often off the bottom of the viewport, so it looks more like the right-hand edge of the page is cut off.

The style rules here are complex enough that I couldn't quickly identify the cause.  It might be that a min-width rule in the right place could be enough to fix the problem.

___
_Issue migrated from trac:3181 at 2022-03-04 08:09:58 +0000_

**Comment by larseggert** [comment]
OBE
