### ISSUE TITLE
Unicode problems in PDF rendering of documents

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#3191]
`type_defect`   |    by lars@eggert.org

___

https://tools.ietf.org/pdf/draft-eggert-tcpm-rfc8312bis-02.pdf which is linked from the "pdf" button on https://datatracker.ietf.org/doc/draft-eggert-tcpm-rfc8312bis/ doesn't render α and β correctly in either the figures or the text. 

___
_Issue migrated from trac:3191 at 2022-03-04 08:10:49 +0000_

**Comment by larseggert** [comment]
OBE
