### ISSUE TITLE
extracting references from xml fails when the reference is an xi:include

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3576]
See #3570.

rebuild_reference_relations should use the new bibxml api to fetch bibxml safely. We should not blindly follow arbitrary xi:includes.

We _could_ build heuristics that would get the references from the right place if the original link is to xml2rfc.tools.ietf.org or similar known sites.

Consider, in the meantime, falling back to the txt if parsing the xml finds no references.

**Comment by larseggert** [comment]
I think this is OBE.

**Comment by rjsparks** [comment]
I'm willing to close this - the remainder of what I think _isn't_ done will be part of the work to force submissions to be wholly self contained.
