### ISSUE TITLE
Datatracker not showing diffs in new w.g. drafts

### ISSUE THREAD

**Issue by bobhinden** [ietf-tools/datatracker#3581]
In my w.g. chair role, I just approved:

https://datatracker.ietf.org/doc/draft-ietf-6man-enhanced-vpn-vtn-id/

It shows that is replaced the individual draft version, but when I look at the htmlized version, it doesn’t show any links to the diffs from the that version.  I am pretty sure it used to do this.

This is a very helpful feature to be able to see what changed.

**Comment by rjsparks** [comment]
Until this quick way to find the diffs is adjusted, remember you can use the history tab to get the diffs (and that _is_ currently following the replaces link).

**Comment by bobhinden** [comment]
Thanks, that is helpful.

**Comment by rjsparks** [comment]
@larseggert I think this is OBE?

**Comment by larseggert** [comment]
I agree.
