### ISSUE TITLE
"NONE area" shown for AD for AD-sponsored docs

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#3582]
On the IESG agenda, for AD-sponsored docs, `(NONE area)` is shown. I'd expected `(GEN area)` here in the example below.

<img width="492" alt="Screen Shot 2022-03-07 at 9 52 18" src="https://user-images.githubusercontent.com/200328/156990226-6ff04fce-b53c-470e-a0be-edb54ab753df.png">

**Comment by rjsparks** [comment]
The document is an individual submission - it doesn't belong to any area. The label shouldn't show at all, or perhaps it could reinforce that this is an individual submission being sponsored by that particular AD.

**Comment by larseggert** [comment]
Ah - I thought the area label was shown based on the AD in question, not based on the area the document was coming out of. We could change it to be based on that, or hide it in this case.

**Comment by russhousley** [comment]
If this is about the document, would it be more clear on the line with draft name.  The current placement makes it appear to be about the token holder.

**Comment by Spectre17** [comment]
I worked up a fix for this based on Russ' comment on the ride from Vienna, but I need a NONE area document in an IESG agenda to test that case. I'll see what I can do to generate one.

**Comment by russhousley** [comment]
Look at draft-rsalz-2028bis-07 on the IESG Telechat agenda for 2022-03-10.

**Comment by Spectre17** [comment]
With the rewrite of ietf/templates/iesg/agenda_doc.html, I would suggest that this issue is OBE and can be closed.

**Comment by rjsparks** [comment]
I confirmed the issue as reported no longer appears through manual manipulation of a draft into the requisite state.
