### ISSUE TITLE
Verify email addresses in drafts used to create aliases

### ISSUE THREAD

**Issue by bobhinden** [ietf-tools/datatracker#3583]
This is low priority.

I responded to a draft alias <draft-chen-pim-mrh6@ietf.org> and got a bounce for one of the email addresses:

<[wangaj3@chinatelecom.cn](mailto:wangaj3@chinatelecom.cn)> (expanded from
   <[expand-draft-chen-pim-mrh6@virtual.ietf.org](mailto:expand-draft-chen-pim-mrh6@virtual.ietf.org)>): host
   [oa-mta.21cn.net](http://oa-mta.21cn.net/)[42.123.76.201] said: 501 Invalid Client IP (in reply to
   DATA command)

I was wondering if there is some way to validate the email addresses in internet drafts where I assume these aliases are created.

Or perhaps, remove them after there is a bounce.

Again, low priority.

**Comment by rjsparks** [comment]
There's no way to pre-verify that an address will accept messages, other than sending a message to it. But that doesn't really cover what you mean by validate I suspect.

Disabling on bounce has been problematic in the past when people have temporary issues with their mail servers. It would also require us to keep a _lot_ more state (every address in an internet draft that has ever bounced).

**Comment by bobhinden** [comment]
That makes sense.   I guess I will notify the other authors and ask them to fix it in the next version.

**Comment by bobhinden** [comment]
One other comment, I note that author email addresses that don't work if a draft gets to AUTH48 does become a problem.

**Comment by rjsparks** [comment]
Yes. Many of the auth48 email mechanics use the code that chooses the "best" address for each author already rather than using the draft alias.
