### ISSUE TITLE
The AD Dashboard "Blocking positions held by..." section misses (some?) non-draft documents

### ISSUE THREAD

**Issue by kaduk** [ietf-tools/datatracker#3588]
This feature was requested in #2800 and implemented in https://github.com/ietf-tools/datatracker/commit/6688d37bb4b57f5f42e1ee38d4688b2788a1221e ; there are references in the code to document types of "charter" and "conflrev", but I do not believe the handling for those document types is currently functional.
In particular, I currently hold a BLOCK on charter-ietf-shmoo but it does not show up on my AD Dashboard page.

**Comment by russhousley** [comment]
The blocked charter code looks for blocked charters in the internal review and IESG review states; it needs to also include charters in the External review state.

**Comment by rjsparks** [comment]
Closing this given the sprint effort - if it doesn't have the desired effect when deployed, please reopen
