### ISSUE TITLE
temporary directories for tests created in project root

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#3592]
When running tests, a bunch of temporary directories are created in the project root:
```
$ ls -d tmp*
tmp-bibxml_base_path-submittests-dir/                 tmp-rfc_path-submittests-dir/
tmp-idsubmit_staging_path-submittests-dir/            tmp-storage-meetinghosttests-dir/
tmp-internet_all_drafts_archive_dir-submittests-dir/  tmp-submit_yang_catalog_dir-submittests-dir/
tmp-internet_draft_archive_dir-submittests-dir/       tmp-submit_yang_draft_model_dir-submittests-dir/
tmp-internet_draft_path-submittests-dir/              tmp-submit_yang_iana_model_dir-submittests-dir/
tmp-nomcom-public-keys-dir/                           tmp-submit_yang_rfc_model_dir-submittests-dir/
```
Some of these are not cleaned up (see #3520), but they also interact poorly with PyCharm's external file detection. When tests are running, a window pops up offering to add the files to version control, causing annoyance.

If these temporary directories could be placed in a common subdirectory (`tmp/` or `test/`, perhaps) that can be excluded from the project in the IDE, this would allow the sometimes useful external file alert to be enabled without the annoyance of repeated suggestions to add throwaway test files to the project.

**Comment by rjsparks** [comment]
Is this specific to the dev container, or to the bs5 branch?
For native install, most of these things do land in (project-root)/tmp, except for one which (bizarrely) ends up at `env/tmp-storage-meetinghosttests-dir`.

**Comment by jennifer-richards** [comment]
I'm not sure. Other than the two mentioned in #3520, I hadn't noticed it before but I probably had disabled the "add external files" alert. I don't think it's specific to the bs5 branch but perhaps the dev container because I've done most of my work there. I'll try it over here with a native install.

**Comment by jennifer-richards** [comment]
Oh- except that `tmp-nomcom-public-keys-dir` is created in the project root even after everything else is in `venv/`

**Comment by rjsparks** [comment]
I think this is OBE - reopen if it is not.
