### ISSUE TITLE
Provide a nicer UI for people who hold the same role in a group more than once

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3593]
For reasons, we have at least one chair that wants all mail sent to the chair alias to go to two addresses. The workaround is to have two Chair roles in the group with the different addresses.

When this happens, the UI that displays roles, such as at group/.../about, should notice and only list the chair once. The link builder could be modified to return a link that refers to multiple mailtos.

**Comment by larseggert** [comment]
Is bespike tooling forget a single individual really the way to go?

**Comment by rjsparks** [comment]
The fix here isn't _for_ that small group of people - it's for everyone else.
