### ISSUE TITLE
feedback_email test fails due to line wrapping in email

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#3598]
The `test_send_error_to_admins` test for nomcom feedback email fails if the path to the `feedback_email.py` file is long enough to cause line wrapping in the email handling. It searches for `"feedback_email.py"` in the email content, but this has `"=\n"` inserted in it when it is wrapped.

Should update the test to take this into account

**Comment by rjsparks** [comment]
I think this may have already been done? Please confirm, and if it has, close the issue?

**Comment by jennifer-richards** [comment]
Yes, was fixed by #3926 I think
