### ISSUE TITLE
ID list notification lacks links

### ISSUE THREAD

**Issue by cabo** [ietf-tools/datatracker#3600]
ID list for Concise Binary Object Representation Maintenance and Extensions notification: Changes to draft-ietf-cbor-file-magic

```
review has been solicited, provided by Bernard Aboba (see ), and addressed in 
```

Actual shepherd report:

```
File formats and file type recognition falls into the broad ART area expertise; review has been solicited, provided by Bernard Aboba (see <https://mailarchive.ietf.org/arch/msg/cbor/5ZgOxVcITa6ACe8hAeMEH3gH2KY>), and addressed in the later versions of the document (eg. the switch to Proposed Standard).

```

**Comment by rjsparks** [comment]
More context please - Is this a notification via feed, or by email? (The obvious feeds look right)...

**Comment by rjsparks** [comment]
Definitely email.

**Comment by cabo** [comment]
Email, indeed.

**Comment by jimfenton** [comment]
I'm wondering if this is happening in @cabo 's email user agent or if this is being removed prior to transmission. Does it look this way in a "show source" view? 

If some mail agents are not displaying links within angle brackets properly (perhaps treating as HTML tag?) then it would make sense to remove pairs of angle brackets on transmission. On the other hand, my mail agent (MailMate) displays stuff between angle brackets properly in plain text email.

**Comment by cabo** [comment]
This was sent as text/plain, charset="utf-8"

So view source of the paragraph in question gives:

```
File formats and file type recognition falls into the broad ART area expertise; review has been solicited, provided by Bernard Aboba (see ), and addressed in the later versions of the document (eg. the switch to Proposed Standard).
```

Message-ID: <164551919086.24980.5342281885017097687@ietfa.amsl.com>
X-IETF-IDTracker: 7.45.0
No DKIM.

**Comment by larseggert** [comment]
I wonder if this content is running through `bleach` somehow before being sent?

**Comment by rjsparks** [comment]
Bleach or some other tag killer is what I would be looking for.

**Comment by larseggert** [comment]
@cabo how can I trigger that kind of email from the DT?

**Comment by cabo** [comment]
Update a shepherd report while somebody is subscribed to wg notifications

**Comment by rjsparks** [comment]
Fwiw, I think we're in a bug-flap. There are DocEvents with other html in them that will annoy the recipients in a way that will eventually ask us to change this back.
One possible real fix (is big) is to migrate all the existing DocEvents to use markdown in their desc instead of containing embedded html.

**Comment by larseggert** [comment]
So then we need to move the bleaching from the template to the various python functions that prepare those DocEvents. I don't know which those are, however.

**Comment by rjsparks** [comment]
Most have been eradicated from the code, so we're not making new ones (that I know of). The issue is with older ones. (And yes, those won't end up in the mails this particular ticket is about).

**Comment by rjsparks** [comment]
But it's worth scanning the code for the creation of DocEvent.desc fields to see if anything's left that sticks in html in case I'm wrong about the eradication.

**Comment by rjsparks** [comment]
I'm seeing a few remaining on quick scan. 

https://github.com/ietf-tools/datatracker/blob/main/ietf/doc/utils.py#L813

https://github.com/ietf-tools/datatracker/blob/main/ietf/doc/views_draft.py#L716

So this set of changes will let those `<b>` bleed through to email (and is the motivation for the striptags function you removed I suspect).

Your proposal is probably better - annoying people with those <b> is better than losing the information Carsten was pointing to.

Unless you want to change direction with this information, I'll merge your PR as is, and we'll approach the issue with HTML in the DocEvent desc when it comes to top of queue.

**Comment by larseggert** [comment]
The `<b>`s were removed by `textify` - want me to restore that bit?

**Comment by rjsparks** [comment]
puts us on middle ground, and I'm fine with that.

**Comment by larseggert** [comment]
PR updated
