### ISSUE TITLE
docker/run fails

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#3604]
```
 lars  ~/D/C/datatracker   feat/bs5  docker  bash -x ./run
+ docker-compose -f docker-compose.yml -f docker-compose.extend.yml up -d
[+] Running 0/1
 ⠿ db Error                                                                                                              0.5s
Error response from daemon: Head "https://ghcr.io/v2/ietf-tools/datatracker-db/manifests/latest": denied: denied
+ docker-compose exec app /bin/sh /docker-init.sh
service "app" is not running container #1
+ docker-compose down
[+] Running 1/0
 ⠿ docker  Warning: No resource found to remove                                                                          0.0s
```

Any idea?

**Comment by larseggert** [comment]
Going to https://ghcr.io/v2/ietf-tools/datatracker-db/manifests/latest manually results in:
```json
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}
```

**Comment by NGPixel** [comment]
Are you able to pull the image manually?
```sh
docker pull ghcr.io/ietf-tools/datatracker-db:latest
```

I wasn't able to reproduce your issue. I also tried from a remote machine and the image pulled just fine...

I also get unauthorized when opening the link you posted, so I'm not sure why it's trying to fetch that in your case.

**Comment by larseggert** [comment]
> Are you able to pull the image manually?

No.
```
# docker pull ghcr.io/ietf-tools/datatracker-db:latest
Error response from daemon: Head "https://ghcr.io/v2/ietf-tools/datatracker-db/manifests/latest": denied: denied
```

**Comment by larseggert** [comment]
Ah, it works when I do `docker login -u larseggert -p $GITHUB_API_TOKEN ghcr.io`.

It's odd that I wasn't logged in already, since I use ghcr.io a lot. Anyway, this should probably go into a README and then I'll close?

**Comment by NGPixel** [comment]
That shouldn't be required though, the image is public and doesn't require authentication. I was able to pull it from a server that never logged in to ghcr.io before...

**Comment by larseggert** [comment]
I don't know. All I know is that it worked After `docker login`.

**Comment by NGPixel** [comment]
Just confirmed it works fine on a brand new ubuntu droplet:

<img width="606" alt="image" src="https://user-images.githubusercontent.com/15522395/157730490-317c5c38-9eaa-481e-a21e-a8b321a8aad6.png">

So it must be some weird configuration issue on your machine...?

**Comment by larseggert** [comment]
I don't know. Let's close it, and I will reopen if I can reliably reproduce.
