### ISSUE TITLE
page tabs are less clear in the mobile view with new BS5 theme

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/datatracker#3608]
In the new BS theme the tabs available on  pages (e.g. the meeting agenda page and document pages) are less clear than on the existing theme. Screenshots attached of a few examples taken at random.

It would be better if the new theme more closely did something that replicated the effect of the existing theme (e.g. possibly using outlines and shading to indicate non-visible tabs).

<img width="419" alt="image" src="https://user-images.githubusercontent.com/5347540/157698383-6927a5ea-f867-40e2-b7c2-923e86940950.png">
<img width="417" alt="image" src="https://user-images.githubusercontent.com/5347540/157698586-bf4c8bd6-42a5-4c5c-9fda-7198b1dbc906.png">
<img width="412" alt="image" src="https://user-images.githubusercontent.com/5347540/157699653-f16ef12a-352f-47ca-950f-0909726936c3.png">
<img width="415" alt="image" src="https://user-images.githubusercontent.com/5347540/157699812-800a3bfe-dd8b-4cd5-8e0c-6c6cc35b192e.png">

**Comment by rjsparks** [comment]
One of Lars' goals was to get us, to the extent possible, away from customization of the framework.

The _heavy_ customization of bs3 was part of why we were stuck there for so long - tools that were designed to help projects make the transition between breaking-change versions of bootstrap could not help us as they could not understand the customization.

It may well be that we should adjust the look certain elements further , but we need to keep the ongoing cost of doing so in mind.

**Comment by ghwood** [comment]
I agree with this as a general goal and understand that the value of "better" might not be worth the effort/ongoing cost in any particular case.

**Comment by larseggert** [comment]
It might be possible to tweak visibility by overriding some defaults: https://getbootstrap.com/docs/5.1/components/navs-tabs/#variables

I am not sure if the wrapping can be addressed easily.

**Comment by larseggert** [comment]
Turns out the wrapping on the agenda page was a page structure issue that the PR above fixes.

**Comment by rjsparks** [comment]
Making tab that don't work more visually distinctive is still an outstanding issue, yes? (Currently the only visual distinction is font color, an effect of a link being present or not).

**Comment by larseggert** [comment]
Yes. It's possible me to change the background color of tabs from white to something else (for both selected or unselected tabs), and the borders can also be played with, both  y only changing sass variables. I'll see if I can come up with something.

**Comment by larseggert** [comment]
@ghwood I looked into tweaking the color scheme but wasn't happy with the results. Are you OK with leaving this as is?

**Comment by ghwood** [comment]
Yes. Thanks for taking look. And the wrapping issue looks fixed. I'll close this issue.
