### ISSUE TITLE
Weird line breaking in (at least) WG doc lists

### ISSUE THREAD

**Issue by paulehoffman** [ietf-tools/datatracker#3609]
See wg/dnsop/documents/. The document title for draft-ietf-dnsop-rfc5933-bis has an extra break that should not be there. The same is true for RFC 3258. This does not appear on the current Datatracker page.

**Comment by rjsparks** [comment]
This is a consequence of the way the search result pages are built in this branch (tables with fixed widths) and the font size I think.

**Comment by larseggert** [comment]
No, I think I have some code that tries to wrap things more smartly when documents have long titles, and it's dumb in this case. I need to find it and we should disable it.

**Comment by larseggert** [comment]
I think it's here: https://github.com/ietf-tools/datatracker/blob/feat/bs5/ietf/templates/doc/search/search_result_row.html#L86

**Comment by larseggert** [comment]
This should be closed.

I am surprised this didn't automatically happen, since #3620 said it was fixing this issue in its description? That should have caused it to be linked to this issue

**Comment by paulehoffman** [comment]
On 14 Mar 2022, at 3:11, Lars Eggert wrote:

> This should be closed.
>
> I am surprised this didn't automatically happen, since #3620 said it 
> was fixing this issue in its description? That should have caused it 
> to be linked to this issue

#620 says it is merged, but I'm still seeing the issue on the DNSOP WG 
page right now.

**Comment by larseggert** [comment]
It probably wasn't pushed to `sandbox-ng` yet. I don't know what cadence that happens. We should probably indicate what git hash `sandbox-ng` runs.

**Comment by rjsparks** [comment]
As for automatically closing issues, I don't think that will happen until the code is merged to main?

**Comment by larseggert** [comment]
For other repos - but maybe I have some elevated privileges for those - a "fixes 123" in a PR comment links the PR to the issue and closes that when the PR is merged.

That linking doesn't seem to happen in this repo.

**Comment by rjsparks** [comment]
fwiw, I'm manually adding the (short) hash as a patch number.
