### ISSUE TITLE
Long session names lead to unwieldy agenda filter parameter keywords

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#3613]
The agenda filtering system assigns a keyword to enable/disable display of many types of sessions based on the session's assigned name. If that session has a long name as is sometimes done to add important information to the agenda, this translates into impractically long keywords. (E.g., `/meeting/agenda/?show=newcomers-dinner-open-to-newcomers-note-that-pre-registration-is-required-and-a-25usd-fee-will-be-charged`)

This is not a technical problem, but contradicts the goal of having human-manageable URL parameters for the agenda page.

**Comment by rjsparks** [comment]
At the 114 sprint, get Liz to explain _why_ the session has all this extra stuff in the _name_. We may be able to better model what she needs and avoid this problem altogether.

**Comment by jennifer-richards** [comment]
Talked to @flynnliz (who should correct me if I get this wrong). The need was for a way to show additional essential information directly on the agenda. A subtitle or description field that appears prominently along with the session name should avoid the temptation to use long names.

**Comment by jennifer-richards** [comment]
Related #4457

**Comment by jennifer-richards** [comment]
I think using the existing `agenda_note` may do the trick. Setting that causes a note to show up below the session title as is most visible for the "Joint with xyz" notes on recent meeting agendas.
![Screenshot from 2023-02-08 16-48-50](https://user-images.githubusercontent.com/19472766/217648699-c5e2ae84-aa56-43fd-8513-5513198ae609.png)
I'm planning to make it easier to edit that field.
