### ISSUE TITLE
Use max-width on the table in document summaries

### ISSUE THREAD

**Issue by martinthomson** [ietf-tools/datatracker#3615]
I have a WIIIIDE screen and I found it hard to trace across the gulf of whitespace between the columns in the table on https://sandbox-ng.ietf.org/doc/draft-ietf-quic-version-negotiation/  This resizes very nicely if I narrow the window, but a simple max-width rule might make it a shade more usable at larger scales.

**Comment by rjsparks** [comment]
I agree - I had noticed this as well, but more strongly on /group/foo/about pages.

**Comment by larseggert** [comment]
Not sure if `max-width` is the right answer here, because some tables can make use of extra horizontal space.

What would be ideal is a CSS way to say "make this column as wide as needed by the widest cell content, but no wider." Is that possible somehow?

**Comment by martinthomson** [comment]
That is the default mode, I think.  What you have now is `width: 100%` on the table itself, so it expands to fit.  Remove that and things might work out.

**Comment by larseggert** [comment]
Thanks, will try. `width: 100%` is the bootstrap default.

**Comment by larseggert** [comment]
This works but looks a bit odd, because the table header and dividers then don't extend all the way to the right viewport edge anymore.

I wish there was a way to use `width: 100%` but indicate which column(s) should grow, or alternatively, which ones shouldn't...

**Comment by martinthomson** [comment]
You can maybe use `<col>` or `<colgroup>` elements and style those (with `calc()` rules perhaps), you can use `:nth-child()` selectors on td/th, or maybe you can look into grid layout.  Grid layout is too new for me to be able to help you much though.

**Comment by rjsparks** [comment]
Was there a strong reason not do these kind of pages using the grid system? I think I can build them that way fairly quickly.
