### ISSUE TITLE
Improve experience for low vision readers

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3632]
From https://mailarchive.ietf.org/arch/msg/tools-discuss/0P6JR4SoKb-bbPM7-UEAD810zt0

>I often read web pages referenced in e-mails with w3m, a text browser.  This gives me a view of the page which is approximately that of a speech browser.  I saw
>
>  IETF Logo Datatracker Dev Mode
>
>  • Groups
>      □ By area/parent
>      □ Apps & Realtime
>      □ General
>      □ Internet
>      □ Ops & Management
>      □ Routing
>      □ Security
>      □ Transport
>      □ IAB
>      □ IRTF
>      □ IETF LLC
>      □ Other
>          ☆ Active AGs  etc, etc, etc,...
>
>and some 50 odd lines before I got to the subject.  On behalf of "low vision" readers, could you put a link at the very top of the page to the subject matter.
>It would save a lot of time, and doesn't get in the way of users of "high vision" browsers.
>
>The page https://www.w3.org/WAI/people-use-web/tools-techniques/
>gives an example of how to do this.
>
>Thanks, Roger

**Comment by larseggert** [comment]
Is this a regression with bs5? The old page structure was basically identical.

**Comment by rjsparks** [comment]
No, it's not a regression. I can remove the label, but I do think that any work here should happen in the bs5 framing and not the bs3.

**Comment by larseggert** [comment]
Assign it to me? I'll add a skipnav link during codesprint.

**Comment by larseggert** [comment]
See #3645.
