### ISSUE TITLE
No history entry when changing RFC Editor Note for doc

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#3633]
### What happened?

The datatracker does not seem to add a history entry capturing previous versions of an RFC Editor Note for a document when that is changed multiple times.

### What browser(s) are you seeing the problem on?

Not Applicable

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by rjsparks** [comment]
Fixing this going forward is easy. Trying to repair old data will be nearly impossible.

**Comment by mrw42** [comment]
I'm working on this and wondering what you would like to see.  I can add the previous value of the RFC Editor note to the message that appears on the "History" tab.  Is that what you are looking for?

**Comment by rjsparks** [comment]
We have an inconsistent mix of some things that show "new value", some that show "old value" and some that show "changed from old_value to new_value.

If we were building from scratch, I would have it say "set RFC Editor not set to <foo>" whenever it is set, and we could move to that, but again, backfilling history will be hard.

**Comment by rjsparks** [comment]
It looks like #6021 did what I describe (minus fixing the impossible part)
