### ISSUE TITLE
Conflict Review documents should allow "Send Notices To" to be edited by appropriate parties

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3639]
The ability to edit the "send notices to" field should be similar to the ability to change the conflict review text. 
cc. @akvezza, @cindymorgan

**Comment by russhousley** [comment]
Currently, the "Send notices to" cannot be changed if the conflict-review is in one of the approved states.  I'll remove that restriction.

**Comment by russhousley** [comment]
By the way, until the next release comes out, the Secretariat can modify the "send notices to" field by using this URL:

   https://datatracker.ietf.org/doc/conflict-review-DRAFT-NAME/conflict-review/notices/
