### ISSUE TITLE
Can't use sandbox-ng on mobile

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#3640]
### What happened?

I was trying to use the bs5 test instance at sandbox-ng.ietf.org  I get redirected to www.ietf.org when I use FFox or Chrome my Android phone.

### What browser(s) are you seeing the problem on?

Chrome / Edge, Firefox

### Code of Conduct

- [x] I agree to follow the IETF's Code of Conduct

**Comment by rjsparks** [comment]
https://sandbox-ng.ietf.org, correct?
I'm not able to reproduce from an iphone. Looking for an android...

**Comment by richsalz** [comment]
I'm current.  very strange.  as this is a temporary thing, i wouldn't treat this as something to fix, i was just curious what bs5 looked like on mobile :)

Feel free to close as wontfix.

**Comment by rjsparks** [comment]
Still would be nice to understand what the underlying cause is in case we run into it on a production service at some point.

**Comment by rjsparks** [comment]
not getting further reports. Did have one instance of someone seeing this on os/x safari, but it was cleared with a shift-reload. Will close.
