### ISSUE TITLE
Server error when meeting schedule editor URL does not have a meeting number

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#3670]
### What happened?

The meeting schedule editor can be opened for the official schedule by accessing, say, `/meeting/113/agenda/edit/`. If the meeting number is omitted, i.e. `/meeting/agenda/edit/`, a server error results.

This should be caught and handled gracefully. A 404 would be valid, but it would be consistent with other meeting-related URLs to default to the current meeting, if any.

### What browser(s) are you seeing the problem on?

Not Applicable

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by meadmaker** [comment]
If the edit URL ends in a slash, it works.  If the URL contains a meeting number but does not end in a slash, it works.  If the URL has no number and does not end in a slash, it returns the 404.

I've spoken with @jennifer-richards, who no longer thinks this is worth fixing.  Please close (I cannot)
