### ISSUE TITLE
Search box on /submit/status makes little sense

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3674]
Using the draft-chooser widget at /submit/status is not likely the right thing to do.

The widget is fed from the names of Document objects that already exist. Anything that's being submitted for the first time won't be there.

Anyone who has any business messing with submission status knows the full draft name. The convenience of a slow auto-complete isn't worth essentially the only thing the control might buy.

(It's also very confusing to click on something that looks like you should be able to type into and have the form change and want input somewhere else from where you clicked).

**Comment by kesara** [comment]
>(It's also very confusing to click on something that looks like you should be able to type into and have the form change and want input somewhere else from where you clicked).
This is a long-running issue in select2: https://github.com/select2/select2/issues/1345
