### ISSUE TITLE
Search at /list/nonwg is frustrating

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3675]
The search widget for this page will not let me find the lists ending with -ag.
That might be more important on other pages where the widget is used - it's just an annoyance here.

**Comment by larseggert** [comment]
The search issue seems to be due to https://github.com/javve/list.js/issues/699. I'm checking what can be done.

**Comment by rjsparks** [comment]
This is still in need of improvement. Example - use the search box to find the genart list...

**Comment by larseggert** [comment]
This is because https://github.com/javve/list.js/issues/699 is still not merged.

**Comment by rjsparks** [comment]
So, that project hasn't had a commit since Jan 2021. Do we start maintaining our own fork, or can we find a replacement for the library that is actively maintained?

**Comment by larseggert** [comment]
Yeah, sorry about picking this. When I started the bs5 work, Jan 2021 was not that far away, but now it is.

Don't we have the ability to monkey-patch things, or does that only work for python?

**Comment by rjsparks** [comment]
It's only python, and the fragility of monkey-patch approach has always bothered me.

**Comment by larseggert** [comment]
Then we should fork, or maybe @NGPixel has a vue thing that could replace it?

**Comment by NGPixel** [comment]
If we're going through the trouble of forking, patching and publishing our modified version of the library, it might indeed be worth rewriting the page in Vue (which can easily replicate this functionality, without the need for libraries).

**Comment by larseggert** [comment]
It's not just one page, it's all the search and sort stuff for all tables.
