### ISSUE TITLE
Manage unassigned open review requests  window is completely broken

### ISSUE THREAD

**Issue by kivinen** [ietf-tools/datatracker#3685]
### What happened?

The manage unassigned window is completely broken. This will make review assignment impossible. 

The first document properly has "Assign reviewer" and "Close" buttons (but on separate line, they should be on same line)., but the following documents show those hidden elements that are shown when you press those two buttons, i.e., they are not hidden from the beginning at all.

I.e., the "assign review" button should open up (on same line) 3 new elements, one saying "Assing Reviewer: <popup list>", next one having checkbox of "skip next time", and then button for "cancel", which will hide the assigned reviewer specific elements and go back to original two options 

When you click "Close" there that should open 3 new elements, one for popup for "Team will not review version / Team will not review document", one for optional comment text, and finally a "cancel" button to hide the elements and show back the original two selections. 

Also when you click assign reviewer or close all the elements should be on the same line where the original two buttons were. I.e. the displayed length of the item should not change.

Unfortunately I can't include any images as attaching images to github does not work on my browser.

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by ajeanmahoney** [comment]
I was able to get it to work, but the interface _is_ messy: it shows drop-down lists for both Assign: and Close: simultaneously. I was able to select a reviewer for each document in the Gen-ART queue, but it didn't start suggesting a reviewer until I had already assigned two reviews.  I didn't do a screen capture, but screen captures could be attached by creating a zip file (GitHub will accept those).

**Comment by jennifer-richards** [comment]
#3774 fixed much of this. Still need to address putting the form fields on a single line. At present, they use the same area of the page but are split over a couple lines and are somewhat taller.

Also need to fix sticky tooltip behavior when interacting with the buttons. The tooltips open and stay visible even after the elements they reference have been hidden.
