### ISSUE TITLE
No submenu for the statistcs

### ISSUE THREAD

**Issue by kivinen** [ietf-tools/datatracker#3690]
### What happened?

On the bs5 version The Other->Statistics does not have submenu like current version has. Current version has sub menu which allows going directly to "Drafts/RFCs", "Meetings", and "Reviews". 

Was this removal intentional or is this a bug.

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by rjsparks** [comment]
I think not having the submenus in this case is the right thing to do even if it wasn't an intentional change (@larseggert ?).

**Comment by rjsparks** [comment]
Closing this per #3712.
