### ISSUE TITLE
Statistics for word counts are meaningless

### ISSUE THREAD

**Issue by kivinen** [ietf-tools/datatracker#3693]
### What happened?

It says about 81% of our drafts and and 39% RFCs from last 5 years have less than 500 words. This does not seem likely, The beginning of draft has about 200 words of boilerplate and in the end the intellectual property statement is about 300 words (I was using old draft to calculate those, so they might not match what we currently use). 

Anyways my guess is that for some reason most of the drafts, and quite a lot of RFCs do not have word counts filled in, and are filled in as 0. Showing these kind of statistics can be very misleading and I think if they are so wrong we should remove them completely, or at least separate case where word count is 0, as "no data" and not combine it to 0-499 bucket.

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by larseggert** [comment]
I wouldn't mind ripping the statistics out completely. There is a lot of code copied between the various templates that should really be factored out. If the data is even wrong, there is no reason to keep this stuff.

**Comment by rjsparks** [comment]
The stats module was supposed to relieve Jari of maintaining his code. I think it has proven to be a failure. Bits may be salvagable, but on the whole, I think it should be removed, and the goal of filling the need that Jari's work fills should be revisited.
