### ISSUE TITLE
Floor plans return 404 error

### ISSUE THREAD

**Issue by kivinen** [ietf-tools/datatracker#3699]
### What happened?

http://localhost:8000/meeting/floor-plan/ and http://localhost:8000/meeting/107/floor-plan/ returns 404 error, but http://localhost:8000/meeting/110/floor-plan/ http://localhost:8000/meeting/111/floor-plan/ etc returns page from the datatracker, which does not have floor plan as those online meetings did not have floor plans. 

Normal datatracker does seem to return floor plan for current meeting.

Is this something that is only happening because we are running test version of datatracker or is this real bug?

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by rjsparks** [comment]
This is not a regression in the code - it is a result of the amount of file-system artifacts we load into the container. if we had copied the floor-plan files over they would show.
I'm going to close this, but there is an ongoing discussion about reworking what artifacts we port over in the base image (_everything_ would mean several GB of data) and making it easier to pull things that aren't there if a dev needs them to check that things are working as expected.
