### ISSUE TITLE
Agenda should have separate notes for text version and html version

### ISSUE THREAD

**Issue by kivinen** [ietf-tools/datatracker#3702]
### What happened?

I.e. the text version should still include text like:

 Times on the text agenda are shown in Vienna local time, UTC +1. 

On the other hand the html version should not include that line, as there the timezones are configurable. 

The reason secretariat puts that note there is to get that text to show on the text only agenda, where you can't configure the timezone. To fix this issue we should have separate configurable agenda_info_note for text and html versions.

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by rjsparks** [comment]
Instead of separate configurable notes, the text version should just provide the declaration of timezone itself. That way any note the secretariat provides still shows in both places (avoiding the potential for error if one place is missed).

**Comment by meadmaker** [comment]
Was this fixed already?  When I look at the plaintext agenda, I see the timezone text:
![image](https://user-images.githubusercontent.com/83085/180617453-cb041fdc-aa92-42d0-bd3c-8967e648c7ef.png)

When I look at the HTML agenda pages, I see the timezone text:
![image](https://user-images.githubusercontent.com/83085/180617477-111eeccd-6b35-4df6-9de5-e4f894ec7f99.png)
and
![image](https://user-images.githubusercontent.com/83085/180617495-afa3bb86-4f15-45d8-baa7-ebffbd9a668c.png)

**Comment by larseggert** [comment]
It's not fixed, but I think it needs to be fixed with a new agenda note rather that with a DT patch.

**Comment by rjsparks** [comment]
It's not fixed, and a new agenda note may be warranted, but what I think should happen is to make it such that the agenda note does not _have_ to speak of the meeting timezone. The datatracker already knows that and even _uses_ the information on the html agenda page. It can use the information to say what the meeting timezone is on the text agenda page as well, relieving the secretariat of the burden of having to work that into meeting agenda note  (and get it right).

**Comment by aph3rson** [comment]
@ IETF 115 code sprint, going to try and work on this.

**Comment by rjsparks** [comment]
I believe this is OBE (or will be at the next datatracker release) - see #5233
