### ISSUE TITLE
Editing Leadership for Bof Requests is a game of bring-me-a-rock

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3711]
The queryset for the personchooser on the edit leadership form for Bof Requests needs to be updated to only offer people who will match the form validation criteria (being IAB or IESG).

Right now it will let you select anyone, but then yell at you for selecting someone that's not IAB/IESG.

**Comment by jennifer-richards** [comment]
Keeping the current searchable field will require adding support for filtering on role in the `ajax_select2_search()` endpoint (or adding a new endpoint with filtering).

At the moment, there are only 26 `Person` records that can be selected - that's possibly reasonable for a pulldown select input.

**Comment by rjsparks** [comment]
Is it single vs multiselect at the moment?

**Comment by jennifer-richards** [comment]
It is multiselect, so the standard pulldown is not really workable unfortunately. I spent some time beating on select2 to try to make it use only pre-seeded data, which should solve this. Something that I haven't yet identified was causing it to make ajax requests even when configured without it.
