### ISSUE TITLE
chore: remove SECR_VIRTUAL_MEETINGS setting

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3717]
SECR_VIRTUAL_MEETINGS was added to settings (and used in a few code places) as a quick reaction to IETF 108. By the time we got to 109, the meeting code had adapted to being virtual, and since, to being hybrid.

The setting is no longer needed, and anything that was special about 108 should just be factored into the code.

**Comment by russhousley** [comment]
ietf/secr/sreq  seems to be the only place with SECR_VIRTUAL_MEETINGS ...
tests.py:    @override_settings(SECR_VIRTUAL_MEETINGS=tuple())  # ensure not unexpectedly testing a virtual meeting session
tests.py:    @override_settings(SECR_VIRTUAL_MEETINGS=tuple())  # ensure not unexpectedly testing a virtual meeting session
views.py:    if meeting.number in settings.SECR_VIRTUAL_MEETINGS:
views.py:        'is_virtual': meeting.number in settings.SECR_VIRTUAL_MEETINGS,
views.py:        'is_virtual': meeting.number in settings.SECR_VIRTUAL_MEETINGS,
views.py:    is_virtual = meeting.number in settings.SECR_VIRTUAL_MEETINGS
views.py:        'is_virtual': meeting.number in settings.SECR_VIRTUAL_MEETINGS,
