### ISSUE TITLE
The non-wg list view contains things that do not belong.

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3726]
The list contains things that do not belong.  For example, 'geopriv' is listed as a non-wg list, but it is a concluded wg.  Maybe this should be a separate issue.

_Originally posted by @russhousley in https://github.com/ietf-tools/datatracker/issues/3675#issuecomment-1075013354_

**Comment by russhousley** [comment]
The Concluded WGs have a separate page.  See https://datatracker.ietf.org/group/concluded/
