### ISSUE TITLE
Improve whitespace handling around action_holder_badge template tag

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#3744]
### What happened?

As discussed in #3662, the `action_holder_badge` template tag needs special handling of whitespace around it in at least some uses.

Need to check whether this is consistent enough to absorb into the tag itself or whether the whitespace treatment can be made clearer.

Original discussion: https://github.com/ietf-tools/datatracker/pull/3662#discussion_r830480568

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by larseggert** [comment]
@jennifer-richards still an issue?

**Comment by jennifer-richards** [comment]
It's still an issue as much as it ever was, but I think a "fix" will be far more complicated than appropriate. Closing as "don't care."
