### ISSUE TITLE
Cannot import first rev of minutes

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#3762]
### What happened?

Reported via email:

> Hi!  I really love the "import from notes.ietf.org" idea in the datatracker, but I'm finding that it's not present when I go to create new minutes, it only appears after I've already uploaded the minutes - so I'm finding that I copy them from notes into a file, upload that, then discover that the import button appears.
> 
> It would be great to have the import button BEFORE uploading the first time.

### What browser(s) are you seeing the problem on?

Not Applicable

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by toerless** [comment]
Is there a simple workaround, such as crafting the appropriate URL for                                               
the import button for a particular WG ? Or is the import button  one of those URL-free                                               
buttons from Javascript ?

**Comment by rjsparks** [comment]
```
/meeting/113/session/<session_id>/import/minutes
```
should work, but as noted on the tools-discuss list, we know that creating a simple text or markdown -00 that says something like 'preparing for import from notes' and then importing will work.
