### ISSUE TITLE
Pdfized rendering doesn't linkify adjacent reference callouts

### ISSUE THREAD

**Issue by jimfenton** [ietf-tools/datatracker#3764]
### What happened?

When two reference callouts are adjacent to each other (e.g., [RFC1111][RFC2222] ) with no space between them, the second one is not converted to a link in the PDF rendering. It is correctly linkified in the HTML rendering.

Example: draft-ietf-ipwave-vehicular-networking-27, Section 6, paragraph 3:
[RFC4301][RFC4302] [RFC4303][RFC4308] [RFC7206]

RFC4302 and RFC4308 are not linkified because they aren't separated by spaces; the others are.

### What browser(s) are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by larseggert** [comment]
This will be fixed as part of #4082.

**Comment by larseggert** [comment]
I checked the doc above, and this is fixed now.
