### ISSUE TITLE
Buttons related to "Personalize agenda" tab show on the "Agenda" tab instead

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#3786]
### What happened?

On the meeting agenda's "Personalize agenda" tab, there is meant to be a set of buttons to link to the agenda view and download the webcal/ics files for the personalized agenda. These were shown at the top and bottom of the "Select sessions" tab in the bs3 interface. In the bs5 rework, these are shown only on the "Agenda" tab, where the "View personalized agenda" link in particular is useless because it is a link to the currently displayed page.

The logic for showing/hiding these needs to be fixed.

### What browser(s) are you seeing the problem on?

Not Applicable

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by rjsparks** [comment]
Now I'm not sure I'm following what the ticket is suggesting.
In bs3, on the main agenda page, once you've selected something in the customize agenda window, this button (labeled `Customized schedule` appears:
![image](https://user-images.githubusercontent.com/10996692/162534065-c6c7ff14-f647-445d-b6bf-31ea15286cbf.png)
An analogous thing needs to be available on the main agenda page for bs5.

**Comment by rjsparks** [comment]
In #3803, on the personalized agenda tab there is
![image](https://user-images.githubusercontent.com/10996692/162534425-1ac45c41-29ef-424d-ac3e-28e364c3cf53.png)
That "Subscribe to personal agenda" button is the thing that needs to also be available to the main page, though it might make sense, given where we're taking it, for it to be labled "Subscribe to filtered agenda"
