### ISSUE TITLE
Confusing labels for "Personalize agenda" tab and agenda filter UI button

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#3787]
### What happened?

The agenda tab that was previously "Select sessions" has been renamed to "Personalize agenda". The button that formerly said "Customize the agenda view..." is now "Personalize the agenda view..." Separately, both are improvements in the terminology, but having both of these on the same page is confusing. It is unclear what the relationship exists between the two ways to "Personalize" the agenda.

A different label for one or the other (I lean toward the filter UI button being renamed) would make this clearer.

### What browser(s) are you seeing the problem on?

Not Applicable

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by larseggert** [comment]
Agreed.

I actually don't understand why we have two different ways to customize/personalize agendas, with functionalities that have a large overlap.

**Comment by rjsparks** [comment]
There are two different workflows that have customers.

One is where people want to say "I want to go to these groups meetings" without hunting for where the groups are in the schedule. People that do this manage their conflicts after building a calendar that has conflict in it.

The other is where people want to say "I want to look at all the groups in this session, and choose which I will attend". People who do this typically are deciding on conflict resolution at the time they are building their calendar.

**Comment by rjsparks** [comment]
Further - note that the behavior of the pages is _very_ different once a group is selected. The main page hides all non-selected groups, while the session-selection page always shows all groups. This _could_ be turned into a single page with a mode-toggle button perhaps, but a lot of the javascript running on the current main page would have to be touched to deal with it.

**Comment by rjsparks** [comment]
Could we just relabel the button "Filter this agenda view" and move on?
A more dramatic refactoring to support the two workflows is something we could research later.

**Comment by jennifer-richards** [comment]
That works for me
