### ISSUE TITLE
Confusing UI for agenda webcal subscribe/ics download buttons

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#3811]
The agenda page's UI for subscribing to webcal or downloading ics files looks something like:

![image](https://user-images.githubusercontent.com/10996692/162534425-1ac45c41-29ef-424d-ac3e-28e364c3cf53.png)

(see #3786). This is shared between the main "agenda" tab and the "personalize" tab that permits filtering as well as selecting individual sessions to appear on the agenda.

These are a bunch of similar buttons: an ics file can be downloaded for a specific area, for all the "non-area" events, or for the currently filtered set of sessions. The latter can also be "subscribed" to as a webcal link.

The filtered calendars are only offered when there are filter parameters selected. These can also represent "filtered" views selected by the UI above these links, or "personal" views selected by combining the filtered views with individually selected sessions on the Personalize tab.

The current set of buttons is a bit haphazard. Really need to rationalize this and offer a more coherent presentation of these options. Just visually, the button sets are different sizes/styles and split across lines in a way that's not of obvious significance to a user.

**Comment by NGPixel** [comment]
My agenda rework in vue.js use the following UX:

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/15522395/164311712-c672a027-4bc9-49b7-bc5a-a835d9dc8d7f.png">

The personalize tab is gone.

The user can instead filter by areas:

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/15522395/164311974-96fdcc27-46bb-4352-b472-046c63ac9c75.png">

The user can further filter the agenda by picking individual sessions:

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/15522395/164312204-b6bb91d1-69ec-4208-be90-7a3e5c0fd0a7.png">

The **Download as .ics** button use whatever you have selected / filtered from both the **Filter Agenda** and **Pick Sessions** features.

Does that make sense?

**Comment by NGPixel** [comment]
@rjsparks 

1. Considering you can only view a few entries before having to scroll up and down in the current view (see example below), would having the calendar as an overlay instead a better experience? For example, a "calendar view" button could be added to the right navigation (which follows as you scroll) and clicking it would display the calendar over the list, on demand, so you wouldn't loose your current position.

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/15522395/164375754-0987c441-5556-4256-868a-f835fb64c3fc.png">

2. The colors are temporary and can easily be changed to match the new IETF / datatracker theme colors.

3. Would highlighting the whole row in addition to the checkbox acceptable? Or do you have a better solution in mind?

**Comment by rjsparks** [comment]
at 1) interesting idea - lets pursue it, but I don't think you see the main workflow that I was trying to point to yet. Users will want to see the calendar change in realtime as groups are selected/deselected when filtering by groups in the "filter agenda" panel you show above,

at 3), I wasn't talking about the items in the list view, but rather the items in the "filter agenda" panel

**Comment by NGPixel** [comment]
Moved the "calendar view" to the sidebar menu, as a button:

<img width="1442" alt="image" src="https://user-images.githubusercontent.com/15522395/165438810-7722356e-e4b9-45be-a423-6b28c4d91f1e.png">

Clicking the button would open a drawer, on top of the current view, for example:

![image](https://user-images.githubusercontent.com/15522395/165439139-49e1b1d3-de57-47fa-bb13-6210a7f2b6b6.png)

**Comment by NGPixel** [comment]
@larseggert I was experimenting with some different fonts. I reverted to using the site defaults:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/15522395/165877037-7489f63a-35ea-4dac-99b0-201aea8d717c.png">

Here's an early preview of the FullCalendar implementation for the calendar view:

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/15522395/165877130-5d23d189-6897-4db7-9f2c-9e319a8d925c.png">

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/15522395/165877160-b68128f8-0e06-4299-87ac-fba19b6b5340.png">

and you can also filter areas / groups while the calendar view is opened:

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/15522395/165877340-ebc9c1d2-8898-4e4f-9352-057c20eced08.png">

**Comment by rjsparks** [comment]
Is this issue still useful, or are we better tracking these conversations in other places. I suggest closing it.

**Comment by vttale** [comment]
Still open, so I have a question. What is designed to happen when you click the "Add To Your Calendar" ->  "Subscribe...(Webcal) button"?    On Desktop Chrome, it opens Google Calendar for me but then as far as I can tell nothing else happens.  No subscription is evident among My Calendars / Other Calendars on the bottom left of the Google Calendar view.

The design of the button also makes it very difficult to fetch a calendar ID out of it that I could use by manually adding via  Google Calendar's Add Calendar interface.  I started to dig down through the Developer Console to find out what that might be, but then decided maybe I should just ask what I'm doing wrong.

Maybe this all belongs some place else and I should create a new issue, or maybe (as I am prepared to believe) it isn't even n issue and doesn't warrant one, just pilot error for which I need to be educated.   That's why I leveraged the most recent issue about subscriptions rather than starting a new one (yet).

Oh, also, this would be expected to dynamically subscribe only to the complete agenda, right?  Not to a personally filtered calendar?  Cuz that latter, now that would be killer -- a focus on only the groups I care about but that automatically gets any updates as needed.

**Comment by rjsparks** [comment]
The webcal buttons are just hrefs to webcal: URLs. Your OS and whatever app you've configured for dealing with those URLs are where you tell your system what should happen.

Right click on the URL and copy link.

And yes, you can subscribe to only the sessions you are interested in. Use the filter or pick buttons, save your selections, and then subscribe to the resulting calendar.

**Comment by rjsparks** [comment]
> Right click on the URL and copy link.
Ok - I see that doesn't work.
@NGPixel maybe we should add the ical/webcal links as options on the Share dialog?
