### ISSUE TITLE
new urlizer breaks on draft-xxxx-xxxx-00.txt

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3828]
At /doc/draft-calhoun-enh-radius-filter/history/
```
 <td>New version available: <b><a href="/doc/draft-calhoun-enh-radius-filter-00/">draft-calhoun-enh-radius-filter-00</a>.txt</b></td>
```

**Comment by larseggert** [comment]
Did you want the .txt included in the link text?

**Comment by rjsparks** [comment]
that would preserve the old implementation's behavior. The links that are being created now 404.

**Comment by rjsparks** [comment]
Fwiw, A rewrite of the URL handlers to make a url like what you construct _not_ 404 isn't the right way to go. An alternative would be to directly produce what /doc/draft-xxx-xxx-nn.txt redirects to, which is /doc/draft-xxx-xxx/nn/, but then we need to fix the danging .txt (or .whatever) in the source material. So for now, using the gearing we have is the right step.

**Comment by rjsparks** [comment]
I ended up producing /doc/draft-xxx-xxx/nn/ and a related pair of variants for charter versions.
