### ISSUE TITLE
menu subpane toggles get inverted

### ISSUE THREAD

**Issue by cabo** [ietf-tools/datatracker#3840]
### What happened?

When leafing through the subpanes of the WG menu, sometimes these stay open and are then toggled *off* when they should actually be opened.

<img width="748" alt="Screenshot 2022-04-19 at 23 15 35" src="https://user-images.githubusercontent.com/23118/164103439-06f67c3a-ed5a-4cc1-9325-c315ee2ab898.png">

### What browser(s) are you seeing the problem on?

Safari

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by larseggert** [comment]
@cabo could you check if this still happens on my dev instance, which has the new htmlization function? (A fix is not part of that PR but is already part of main and hence present there.)

**Comment by cabo** [comment]
The sticky tooltip is still there (Safari, see screenshot: click wdiff, move cursor go back).

The larger menu problem in this ticket seems to be gone.

Grüße, Carsten

**Comment by larseggert** [comment]
I don't see "wdiff" in the screenshot?

**Comment by cabo** [comment]
This screenshot <img width="436" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/23118/186686533-1e25e5de-83af-472a-ad49-35bee7d396af.png">

**Comment by larseggert** [comment]
Ah. This is for the #4082 PR.

**Comment by larseggert** [comment]
Fixed in 310e064a330e824333b9b31f1fc1be4654ee80e0.
