### ISSUE TITLE
Selecting last letter of WG chairs last name doesn't scroll on Chrome

### ISSUE THREAD

**Issue by paulehoffman** [ietf-tools/datatracker#3841]
### What happened?

On [chair photos](https://datatracker.ietf.org/wg/photos/), select a letter such as "H". The URL correctly changes to [this](https://datatracker.ietf.org/wg/photos/#H), but the page does not scroll.

### What browser(s) are you seeing the problem on?

Chrome / Edge

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by paulehoffman** [comment]
It did use to work on Chrome, my (faulty) memory tells me. It works on Firefox for me as well.

**Comment by paulehoffman** [comment]
It is failing for me in Chrome 100.0.4896.127 on Mac.

Also fails in Microsoft Edge version 100.0.1185.36 (Official build) (64-bit) on Windows 11.

**Comment by larseggert** [comment]
@paulehoffman could you check if the problem is still there?

**Comment by paulehoffman** [comment]
Thanks for the fix; now works for me!
