### ISSUE TITLE
disconnect between version ids and release tags

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3843]
As of the 8.0.0 release, the footer points to the wrong place for the release.
The base.html template points to 
```
https://github.com/ietf-tools/datatracker/releases/tag/{{version_num}}
```
Which 404s. To work with what's at github right now, it would need to point to
```
https://github.com/ietf-tools/datatracker/releases/tag/v{{version_num}}
```
(Note the extra `v` before `{{version_num}}`)

we need to reconcile v{numlist} vs just {numlist} for many things - release purposes, internal links, etc.

We have a pretty baked in idea of just {numlist} in the code and supporting configuration in production - do we need to change that? Or is it reasonable to change the tags to be {numlist} instead of v{numlist}?

**Comment by rjsparks** [comment]
_why_ (and where?) do they recommend it?

**Comment by NGPixel** [comment]
A few interesting answers here: https://stackoverflow.com/questions/2006265/is-there-a-standard-naming-convention-for-git-tags

It seems to be mostly for historical reasons where older vcs couldn't distinguish between tags and revisions, hence the v prefix.

Projects like git and Linux kernel use the v prefix.

Semantic versioning used to enforce the v prefix but that was dropped in version 2.

As for GitHub, there's only a small note suggesting to use v when you create a tag, but doesn't explain why...

**Comment by rjsparks** [comment]
Quite a mix in the wild. Interesting to see that neither python/cpython nor django/django use releases, but they do use tags, with the first using v and the second not.

This isn't a super big issue either way, but we have some internal plumbing that doesn't want to see the v, which argues for dropping it. Are there any heavy lifts should we try to do so?

**Comment by NGPixel** [comment]
Not really, it would actually result in a bit less logic in the workflow code to only have non-prefix versions.

**Comment by NGPixel** [comment]
All releases fixed to use non-prefixed versions.
