### ISSUE TITLE
update timestamp for meeting agendas seem incorrect

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/datatracker#3849]
### What happened?

The last updated timestamp seems to be too far in the past.

It also should use either the user's local timezone or UTC.

Attached is a screenshot of https://datatracker.ietf.org/meeting/114/agenda/ taken on 2022-04-20 at 9:45 in a EDT.

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/5347540/164244198-98608b0a-c574-4591-857e-9e906952dadf.png">

### What browser(s) are you seeing the problem on?

Safari

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by jennifer-richards** [comment]
Poking, there's an attempt to hide the "updated" indicator if `meeting.updated()` is not defined. Unfortunately, the `updated()` method returns 1970-01-01T00:00:00 rather than`None` in that situation, which defies the effort.

**Comment by jennifer-richards** [comment]
It localizes to `PRODUCTION_TIMEZONE`, so won't change due to the `USE_TZ` settings. It'd be nice to change it to be explicitly UTC instead of something that depends on `settings.py` if we want to use a magic number.

We could instead/also just say that anything before [date after Jan 2, 1970 and before plausible update time] is too long ago to be plausible. That'd avoid depending on a particular time zone for the view.

**Comment by Osoted56** [comment]
Hackearon

**Comment by microamp** [comment]
Looks like there are some guards in place now.

``` javascript
if (!updatedDatetime.isValid || updatedDatetime < DateTime.fromISO('1980-01-01')) {
  return false
}
```

(in `client/agenda/Agenda.vue`)

It's hard to know when the change was made. The Git history only goes back to Feb 2024 if I'm reading it correctly.

I'll spend some time testing the code at the code sprint tomorrow.

**Comment by microamp** [comment]
It appears to me that when `/api/meeting/114/agenda-data` returns the default `updated` time, i.e. `1970-01-01T00:00:00Z`, e.g.

``` javascript
{
    "meeting": {
        "number": "114",
        "city": "Philadelphia",
        "startDate": "2022-07-23",
        "endDate": "2022-07-29",
        "updated": "1970-01-01T00:00:00Z",
        "timezone": "America/New_York",
        "infoNote": "Please see the <a href=\"https://datatracker.ietf.org/meeting/114/proceedings\">IETF 114 Proceedings</a> for further records of this meeting.",
        "warningNote": ""
    },
    // ...
}
```

it correctly hides the `Updated` element in the UI. 

![image](https://github.com/user-attachments/assets/a754f05d-2fe6-4426-afcd-6b729f6a08ba)

So, I believe the bug has been fixed.

However, we may also want to apply the same filter to the plain text page for consistency.

``` example
^agenda(?P<utc>-utc)?(?P<ext>\.txt|\.csv)$
```

e.g. `/meeting/114/agenda.txt`

![image](https://github.com/user-attachments/assets/48259348-1cdf-42a5-acb7-6e5355ea2112)

P.S. `agenda.csv` does not use `updated`, only `agenda.txt` does.

**Comment by rjsparks** [comment]
> However, we may also want to apply the same filter to the plain text page for consistency.
Yes  - that sounds good.
