### ISSUE TITLE
The COMMENT section of a DISCUSS shows up as RED - it should probably just be GREEN 

### ISSUE THREAD

**Issue by paulwouters** [ietf-tools/datatracker#3856]
### What happened?

I noticed this today in the new layout (not sure if it was present in the old layout)

I had one minor discuss and a bunch of comments, but now the whole thing looks red as if i butchered it :)

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by rjsparks** [comment]
We need to be sure that the discuss part isn't visually lost when it's a small part.
Could you point to the discuss that made you notice this?

**Comment by paulwouters** [comment]
This one one where Roman has a Discuss with Comments, and the comments get the same red colour urgency as the discuss:   https://datatracker.ietf.org/doc/draft-ietf-bier-bar-ipa/ballot/

**Comment by rjsparks** [comment]
Thanks - @larseggert should the comments part of a blocking position get the same treatment as comments on no-objection positions?

**Comment by larseggert** [comment]
Can definitely change the color - what should the COMMENT box color be when there is also a DISCUSS?

**Comment by rjsparks** [comment]
it used to be red for both:

**Comment by larseggert** [comment]
Thanks, so at least it's not a regression with bs5.

**Comment by kesara** [comment]
OBE
