### ISSUE TITLE
Sheperd write ups are too difficult to read

### ISSUE THREAD

**Issue by paulwouters** [ietf-tools/datatracker#3861]
### What happened?

The problem is that the sheperd write up quoted text is not clearly separated from the answer, so it is not easy to spot the answer.

Examples (not sure if these survive the same layout on github comments):

(9) How solid is the WG consensus behind this document? Does it represent the
strong concurrence of a few individuals, with others being silent, or does the
WG as a whole understand and agree with it? It has received a wide diversity of
review from implementers, deployers of QUIC, network operators, and
researchers. There have been two WGLCs, where feedback from the first was
integrated, thus the consensus is good though the engagement has overall been
less than the original QUIC documents.

or:

(11) Identify any ID nits the Document Shepherd has found in this document.
(See <a href="http://www.ietf.org/tools/idnits/"
rel="nofollow">http://www.ietf.org/tools/idnits/</a> and the Internet-Drafts
Checklist). Boilerplate checks are not enough; this check needs to be thorough.
4 non-ascii characters, outdated references to documents now published as RFCs.

Probably the easiest would be to match the shepherd boilerplate text and add two BR tags or something to cause a line break?
Or the actual answer text could be bold'ed once the boilerplate text has been recognised and made non-bold ?

### What browser(s) are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by rjsparks** [comment]
likely overtaken by #4225

**Comment by larseggert** [comment]
Agree - close?
