### ISSUE TITLE
It's so... blue

### ISSUE THREAD

**Issue by mnot** [ietf-tools/datatracker#3873]
### What happened?

The bootstrap5 update is good, but the data tracker buttons are SO blue -- it makes it difficult to read the rest of the page, as they're so prominent, and much of the actual data values are grey.

There's also very little contrast in the top navber.

### What browser(s) are you seeing the problem on?

Firefox, Safari

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by rjsparks** [comment]
This will evolve, of course. But the basis of the color set is to outsource that set of decisions to bigger teams as best we can - we are, to the extent possible, using bootstrap defaults.

We have contracted a common bootstrap theme for the IETF (already part of the website, and will be integrated to the datatracker soon) that did involve real usability and accessibility testing. (It's at https://www.npmjs.com/package/@ietf-tools/common-bootstrap-theme).

Would it be alright with you to close this issue, knowing we've taken it as input into how the styling should evolve?

**Comment by mnot** [comment]
Sure thing. The main thing is that this isn't (just) an aesthetic issue -- it's affecting usability (at least for me).

Cheers,
