### ISSUE TITLE
Search for expired draft returns .txt although .html exists

### ISSUE THREAD

**Issue by becarpenter** [ietf-tools/datatracker#3881]
### What happened?

A search for (expired) draft-carpenter-anima-quads-grasp says:

A copy of the expired Internet-Draft can be found at:
https://www.ietf.org/archive/id/draft-carpenter-anima-quads-grasp-03.txt 

IMHO it should return the html version (when one exists).

### What browser(s) are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by rjsparks** [comment]
It should probably provide links to all available versions.

**Comment by becarpenter** [comment]
Yes, that would be fine. (I'd like to nudge people towards the HTML version when there is one, however.)
