### ISSUE TITLE
Menus don't behave in safari

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3884]
From Andy Malis: 

> The following works fine when using Firefox, but is buggy with Safari:
> 
> I'm looking at my profile page, https://datatracker.ietf.org/person/Andrew%20G.%20Malis . When I slide the cursor over the menu titles at the top of the page, the menus appear correctly when I'm using Firefox. However, when I'm using Safari, the text for the Groups and Documents menus are partially in front of and partially behind the existing page text. The Meetings, Other, and [agmalis@gmail.com](mailto:agmalis@gmail.com) menus work fine, it's just the first two menus that have the issue.
> 
> This is with MacOS Big Sur 11.6.5 (20G527), Safari 15.4 (16613.1.17.1.13), and Firefox 99.0.1 (64-bit).

**Comment by rjsparks** [comment]
Trying to reproduce - not seeing the issue with the same version of safari on Monterey.

**Comment by rjsparks** [comment]
Ah - possible, but Andy indicated he was using the top menubar, not the side menubar. I double-checked side menu and can't reproduce there either. Trying to build an environment with the same versions Andy reports now.

**Comment by agmalis** [comment]
Here are two screenshots showing the issue. I'm going to try again after disabling all extensions.
<img width="1020" alt="Screen Shot 2022-04-26 at 10 07 04" src="https://user-images.githubusercontent.com/9480233/165319598-db55358e-99af-43d1-8774-91fd6479ad28.png">
<img width="917" alt="Screen Shot 2022-04-26 at 10 07 19" src="https://user-images.githubusercontent.com/9480233/165319603-73f34874-0ecc-4eb3-b1db-f303562d14e5.png">

**Comment by agmalis** [comment]
Also, the bug depends on the order that I view the menus. If I just slide back and forth between the Meetings and Documents mess, then all is fine. Also, if I slide back and forth between the Datatracker logo and the Groups menu, then all is fine. I need to slide between the Groups and Documents menus (either direction) in order to reproduce the issue. And again, this only happens on the iMac, not the MacBook Pro.

**Comment by rjsparks** [comment]
Yes, you need js and you need the styling. I was hoping that something might be complaining into the js console, or one of the other developer tabs on the machine where you're seeing the misbehavior.

**Comment by rjsparks** [comment]
Andy - could you confirm this is still an issue for you?

**Comment by rjsparks** [comment]
Not hearing anything, I'm closing this. Reopen it if needed.
