### ISSUE TITLE
Session Request: After requesting info from IETF-113, Chairs were not recognized in Datatracker...

### ISSUE THREAD

**Issue by acmacm** [ietf-tools/datatracker#3889]
### What happened?

After requesting info from IETF-113, Error Message for "bethere" said Chairs were not recognized in Datatracker. I pressed submit anyway and the Session request submission failed.

### What browser(s) are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by acmacm** [comment]
This was for BMWG session at IETF-114.  New issue, AFAICT.

**Comment by jennifer-richards** [comment]
A server error corresponding to this also occurred. From that:

```
ValueError at /secr/sreq/bmwg/confirm/ invalid literal for int() with base 10: '<QuerySet [<Person: **REDACTED**>]>'
```

Guessing it's a bug to do with the select2 integration, which plays some tricks with integer keys in the form fields.

**Comment by rjsparks** [comment]
fwiw:
![image](https://user-images.githubusercontent.com/10996692/165365948-9f51055a-66a1-4011-9a9d-f59e258fb128.png)

**Comment by jennifer-richards** [comment]
There's something going wrong on the `new()` view - the `bethere` field is not being submitted with the correct value. E.g., I submitted a request with three people selected as "bethere", but:
```
(Pdb) pp request.POST
{'adjacent_with_wg': '',
 'attendees': '25',
 'bethere': '111656',
```
That number (111656) is the PK for one of the selected people, but a couple have been dropped.
