### ISSUE TITLE
Don't allow ADs to be added as bethere constraints for WGs

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3890]
Chairs have developed a practice of adding ADs to the bethere constraints in a session request. This is unnecessary, and even harmful, as it adds noise to the scheduling process which already knows that the AD for a group should be at its sessions.

Change the form to tell chairs not to add the group's AD, and block adding that AD (in rare cases, there may be more than one) from this field.

**Comment by rjsparks** [comment]
Right now, the form autopopulates ADs and Chairs. We also have the issue of the "fetch from previous meeting" propagating the behavior.

**Comment by Spectre17** [comment]
Per Robert Sparks, I am interpreting this issue to include Chairs along with ADs.

**Comment by rjsparks** [comment]
@spectre17 - unless you have something ready to commit, we'll pull this back into the tools team

**Comment by jennifer-richards** [comment]
Fixed by #5169
