### ISSUE TITLE
"find in page" misbehaves with Chrome/Mac

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3893]
From Amanda Baber:
> This is happening in Chrome with Mac versions 11 and 12. (Safari is fine.)
> 
> When I use command-F to find text at https://datatracker.ietf.org/iesg/agenda/ or https://datatracker.ietf.org/wg/, Chrome tells me how many occurrences there are, and if I scroll down the page, they’re highlighted. However, it won’t jump to them. The “previous” and “next” up/down arrows don’t work.

**Comment by larseggert** [comment]
Wonder if this is related to #3841.
