### ISSUE TITLE
Links to non-existing person profiles are being generated

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#3909]
### What happened?

For example, on http://127.0.0.1:8000/ipr/2670/history/, a link to http://127.0.0.1:8000/person/laura.hill@parc.com is being generated, which 404s.

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by kesara** [comment]
In this particular case, a `Person` record exists with that email address but there's no `Email` record.
Profile view checks `Email` records if the profile URL has an email address, that's the reason the profile page is 404.
I think the correct behaviour is to check both `Email` records and `Person` records in the profile view.
