### ISSUE TITLE
BoF deadline in important dates should rather have a link to the datatracker boF request page then the ietf.org page

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3911]
### Discussed in https://github.com/ietf-tools/datatracker/discussions/3910

<div type='discussions-op-text'>

<sup>Originally posted by **mirjak** April 29, 2022</sup>
The link to further instructions to the ietf.org should rather be at the point of the BoF request page, or at least also there!</div>

**Comment by ajeanmahoney** [comment]
The template for important date _adds_ text to what the important date's description field contains for several importanddatename ids. This seems really odd - the information should just be part of the importantdatename description itself. This needs review.

The fix for this particular ticket is to change the description of the field in the admin.

**Comment by evyncke** [comment]
I agree, it seems that `ietf/templates/meeting/important-dates.html` should be cleaned by removing most of of the specifics as they are not used.

**Comment by evyncke** [comment]
OTOH (discovering DT piecemeal by piecemeal...), the template can use nice hyperlink with a descriptive text while any URL in the DB is simply transformed into a hyperlink (a little less nice).

**Comment by rjsparks** [comment]
I think the right thing to do is to change the processing for the description of each important date to be markdown input, rendered through markdown at display.

All of the workarounds we're seeing in the template can then move into the description. @larseggert - do you have an opinion?

**Comment by evyncke** [comment]
Nicer and more elegant solution indeed. BTW, is there a MD rendering library somewhere ?

**Comment by rjsparks** [comment]
We are already using https://pypi.org/project/Markdown/.
Look at, for instance, https://github.com/ietf-tools/datatracker/blob/1ba87890ba9451bb696aef4c8d049bcefa85b71b/ietf/doc/views_doc.py#L560
