### ISSUE TITLE
Submit to IESG is not working

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3913]
When chairs try to "Submit to IESG for publication", nothing happens.

**Comment by rjsparks** [comment]
@larseggert This is an instance of a pattern of issues that I think we're starting to see. 

The HTML in this case sets things up so that the browser returns a form that says `confirm=`. That is, the button has no value. Is this a property of submit buttons that you are aiming for? (That they have no value?)

I'm going to fix this one by adding a value, and we can adjust later if there's a reason to go a different direction.

(Later, this particular form could be changed to only have on submit button, with 'back' being a link styled as a button as we have in other places.)

**Comment by larseggert** [comment]
This is a side effect of me having changed `input[type=button]` elements to `button`. That removed the `value` attribute on those new buttons. I checked a few and the value was not used, but I guess it is used in at least in some cases - sorry!

**Comment by rjsparks** [comment]
The tests don't use the HTML - the division is at the POST line - you'll see the tests provide the POST they expect to come back from the HTML.

We should look into other types of tests that verify that the html/javascript is resulting in the expected POSTs.
