### ISSUE TITLE
Form validation on /secr/sreq destroys be-there list

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3918]
On a form validation error, the be-there list is set to range(n) where n was the number of Person objects in the field before the validation failed. The result is lists of be-there with names that look like, for instance:

```
>>> Person.objects.order_by('pk')[:3]
<QuerySet [<Person: (System)>, <Person: David Ely>, <Person: Vinton Cerf>]>
```

**Comment by rjsparks** [comment]
See also #3372

**Comment by rpcross** [comment]
Unable to reproduce this issue. Tried submitting new session request and editing existing session request using a bogus group name in a conflict field to cause a form validation error, do not see any issues with bethere names.

**Comment by rjsparks** [comment]
closing as OBE
