### ISSUE TITLE
Posting a shepherd writeup from a text file

### ISSUE THREAD

**Issue by russhousley** [ietf-tools/datatracker#3935]
### What happened?

Uploaded the shepherd writeup as a .txt file.  Some back end processing added HTML hrefs for drafts and RFCs; however, when the shepherd writeup is displayed, the links are visible. They are not clickable...

### What browser(s) are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by rjsparks** [comment]
Deployed at 8.2.0
