### ISSUE TITLE
API for meeting registration returns only parts of the registration types

### ISSUE THREAD

**Issue by evyncke** [ietf-tools/datatracker#3936]
### What happened?

When requesting the meeting registration data via API
(e.g., https://datatracker.ietf.org/api/v1/stats/meetingregistration/?meeting__number=114&limit=200&offset=0&format=xml )
the registration_type part is wrong at least in my case as it shows only hackathon_onsite (while I am both registered for the meetings and for the hackathon). 

Same issue for Lars Eggert as far as I can tell

### What browser(s) are you seeing the problem on?

Chrome / Edge

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by rjsparks** [comment]
We are going to be refactoring the way that table works in the next few days (Ryan started long ago, but the work has been held to bring it in along with the fixes for nomcom eligibility). You can see where it's going by looking at https://github.com/ietf-tools/datatracker/pull/3641

**Comment by rjsparks** [comment]
Please review and see if this issue still exists - a lot has changed with MeetingRegistration in the interim

**Comment by evyncke** [comment]
Issue is still there... I.e., my registration only shows as hackathon_onsite

**Comment by rjsparks** [comment]
cc @rpcross

**Comment by evyncke** [comment]
Issue is fixed, it was working fine for IETF-115
