### ISSUE TITLE
Matomo script not always loaded in DT

### ISSUE THREAD

**Issue by evyncke** [ietf-tools/datatracker#3937]
### What happened?

Chrome console displays:
`​ Refused to load the script 'https://analytics.ietf.org/matomo.js' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' data: https://datatracker.ietf.org/ https://www.ietf.org/ http://ietf.org/". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.`

when loading https://datatracker.ietf.org/doc/ad/%C3%A9ric.vyncke (and possibly others)

### What browser(s) are you seeing the problem on?

Chrome / Edge

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by rjsparks** [comment]
See https://github.com/ietf-tools/datatracker/commit/47b89c1112313e9a40d464708d9e98ec0362c8af
