### ISSUE TITLE
Milestones with multiple associated drafts do not render those drafts

### ISSUE THREAD

**Issue by LPardue** [ietf-tools/datatracker#3940]
### What happened?

I created a new milestone, "Qlog documents to IESG" in the QUIC WG

The milestone has 3 associated drafts. But none of them render in the datatracker column.

![image](https://user-images.githubusercontent.com/6571445/167402519-1b2997c2-c523-4ab7-aa55-2f365f1e89e9.png)

### What browser(s) are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by larseggert** [comment]
The bug actually made it so that none of the entered documents were associated with the milestone in the database, if multiple were entered. So once the fix is deployed, you'll need to re-add those to the milestone. Sorry.

**Comment by LPardue** [comment]
No problem, just glad that it it will be fixed so promptly. Thanks.
