### ISSUE TITLE
Search result rows for drafts don't link to reviews specific to the draft

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3953]
Search result rows on pages like https://datatracker.ietf.org/wg/6man/documents/ show links to review team reviews, such as for opsdir.

Right now, the link shown for the row for draft-ietf-6man-ipv6-alt-mark points to https://datatracker.ietf.org/group/opsdir/

It should (and before the bootstrap5 upgrade, did) point to the actual opsdir review of the draft (or in this case, to the reviw assigment since the review isn't yet complete at https://datatracker.ietf.org/doc/draft-ietf-6man-ipv6-alt-mark/reviewrequest/14700/).

The logic should be the same as what builds the review links at https://datatracker.ietf.org/doc/draft-ietf-6man-ipv6-alt-mark/

**Comment by larseggert** [comment]
So pre-bs5, I think we just showed which team had reviewed something, but **did not** link to the actual review:
https://github.com/ietf-tools/datatracker/blob/e11583a87f492953e9406ca1f5a0b36ca5bafe3c/ietf/templates/doc/search/status_columns.html#L53-L56
But I will fix the link nevertheless.
