### ISSUE TITLE
Browser-dependent paging issue

### ISSUE THREAD

**Issue by agmalis** [ietf-tools/datatracker#3959]
### Describe the issue

When viewing a page that is more than one screenful in length, with some browsers (such as Safari, and possibly Internet Explorer) when you page up using the space key, you lose several lines of content that are under the menu bar, and you have to scroll back a few lines to be able to read them. With other browsers, such as Firefox, when you press the space key, you don't lose any content when the next page becomes visible.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by agmalis** [comment]
Robert,

I'm now on Safari 15.5 (17613.2.7.1.8) on Monterey 12.4 and everything is
working great. So either the code changed or my upgrade to Monterey fixed
it. Either way, you can close the ticket.

Cheers,
Andy

**Comment by agmalis** [comment]
Robert,

Actually, I take that back. I noticed after testing that I wasn't signed in
to the Datatracker. After signing in, the problem is back.Then I signed out
and all is OK. When I sign back in, the problem is back. When I sign out
again, all is fine. I can keep signing in and out and the same behavior
happens.

Out of curiosity, I went to the Sandbox and tried it there as well. Same
thing - if I'm signed out, all is fine. If I sign in, the problem is there.
Since I can sign in as anybody on the Sandbox, I also tried signing in as
***@***.*** and I still had the issue. Again, when I sign out, all
is fine.

So what's different in the menu code between when you're signed in and
signed out?

Cheers,
Andy

**Comment by rjsparks** [comment]
Thanks for that observation. Will pursue.
If you have time, try a shift-reload after signing in to see if that changes the behavior at all.

**Comment by agmalis** [comment]
Robert,

I just tried it - shift-reload has no effect.

Cheers,
Andy

**Comment by rjsparks** [comment]
Closing this - see Andy's comments at 3884.
