### ISSUE TITLE
OpenID authorization page has title "404 Not Found"

### ISSUE THREAD

**Issue by jimfenton** [ietf-tools/datatracker#3987]
### Describe the issue

When authorizing for Zulip, the page displayed when Zulip went back to Datatracker had the title "404 Not Found"

But the page was displayed correctly, and worked successfully.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
Do you know what the URL was that had the 404?
