### ISSUE TITLE
Add an ability for WG chairs to indicate the replacement document at the time of I-D approval

### ISSUE THREAD

**Issue by smyslov** [ietf-tools/datatracker#3992]
### Description

Quite often individual I-Ds when adopted to a WG first appear in "Active Internet-Drafts" keeping their names (which are not draft-ietf-*). Later authors re-submit these I-Ds as new -00 drafts with draft-ietf-WG-* names and these submission requests require an approval from WG chairs. It happens sometimes that when making such a submission requests authors forget to mark a new I-D as a replacement for their individual I-D, which is already adopted. Currently it is not possible for WG chairs to fix this at the approval page, so in this case chairs should either ask authors to cancel current submission request and make a new one with proper indication of a replacement draft or ask the Secretariat to do this manually. It would be nice if the ability to indicate the replacement draft was added to the approval page (probably restricted to only drafts with individual names that are adopted by a WG).

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Chairs can edit replaces for a documents without invoking the secretariat now.

You are able to approve the post and then edit the replaces immediately (without asking the secretariat to do anything).

We could add this to the approval form (the truly new enhancement would be to add this indication of replaces when _pre_-approving a document), but it adds significant complexity.

**Comment by smyslov** [comment]
Thank you for this information - I didn't know that. If this is possible now, then the ticket can be closed.
