### ISSUE TITLE
Document needs attention indicators have become too subtle.

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#4009]
The IESG would like to have the datatracker be more assertive in pointing out that a document has been in a state for a long time. The egg-timer takes less screen space, but doesn't capture enough attention to drive action.

Conversation about this began with the AD dashboard, but it was noted that any search result page should have stronger indication when documents are in such states.

**Comment by larseggert** [comment]
Some questions:
1. Should this change be made only for people where the role is "AD"?
2. Should this change be made only for those documents that are _severely_ over there time budget for a state?

(The reason I made this change is that the document metadata table is _way_ too busy.)

**Comment by larseggert** [comment]
Anyone got an idea that is more visible than the new way but uses less screen real estate than the old way?

**Comment by rjsparks** [comment]
(not intending to pick on Roman)
Instead of
![image](https://user-images.githubusercontent.com/10996692/171749248-bde9aa98-e034-4777-9471-ab46795efee5.png)
Perhaps the entire iesg state could be badged with the color that the hourglass is now, and the label for action holders could also be badged with those colors. Maybe only one hourglass would be needed on action holders (which would remove some visual noise) since right now, they're always all on the same deadline.
