### ISSUE TITLE
Make test suite generate files outside of the source tree

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#4020]
### Description

The tests seem to generate directories in the source tree names `tmp-*` and they also seem to generate files under `test/media` and possibly `test` in general.

It would be nice if that as reworked so all that happened under `/tmp`.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
or at least outside /workspace. /tmp brings its own dragons, as we saw with the html validation code.
