### ISSUE TITLE
Add minimal codecov threshold

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#4033]
### Describe the issue

Many PRs have a failign codecov check, but with messages like "will decrease coverage by 0.00%", which seems bogus. Can codecov be configured to not fail with 0% changes?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
It would be nice if this didn't fail even with small downward drift.

**Comment by NGPixel** [comment]
Added a threshold of 1%:
https://github.com/ietf-tools/datatracker/blob/main/dev/codecov.yml

Let me know if this is too low.

**Comment by rjsparks** [comment]
1% may end up being too high 😄 but we'll start here and see how well it helps.
I think having the codecov post even if it doesn't think coverage has change will be better than suppressing it.
I'll close this, we can re-open it, or start anew, if adjustment is needed.
