### ISSUE TITLE
New pronouns field

### ISSUE THREAD

**Issue by JayDaley** [ietf-tools/datatracker#4043]
### Description

As per the [consultation](https://mailarchive.ietf.org/arch/msg/ietf-announce/aweKuk52RkhA8DPPLMhC7BedRNU/), a new field should be added "Pronouns" that is shown on the public profile.  

The Pronouns field either allows the user to select any number of the following:
- he/him
- she/her
- they/them
Or they can select "Other" which is a free text field of up to 20 characters.

The informational text next to the field should be "Optionally provide your personal pronouns.  These will be displayed on your public profile page and alongside your name in Meetecho and, in future, other systems."

The Pronouns field should be available as a new OIDC claim that returns either those selected from the list with commas in between, or the contents of the free text field, depending on what was selected.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
>The Pronouns field should be available as a new OIDC claim that returns either those selected from the list with commas in between, or the contents of the free text field, depending on what was selected.

I can't parse this, what is an example of what you expected to see that would have commas in it?

If the selection is one of the three listed, that selection will be returned.

Rather than a new claim, I'm adding this as a field to the existing userinfo claim  (where we provide name, etc.)

**Comment by JayDaley** [comment]
If they have chosen "Other" and then that text is supplied (it may be blank).  If they have selected any of the pre-written options (e.g. he/him) then all those selections are concatenated into one string with comma delimiter.  To be clear, someone cannot select a pre-written options and Other at the same time - when they select Other then the pre-written options should no longer be available and not recorded.

**Comment by rjsparks** [comment]
I'm still unclear on what you're asking for. See Jennifer's possible interpretation at https://github.com/ietf-tools/datatracker/pull/4059.

Are you saying that someone should be able to select _multiple_ options from the provided list (that is, that someone could select all of (he/him, she/her, they/them) and the result would be the string "he/him,she/her,they/them"?

I've interpreted this in the code in the PR so far as a user could select _one_ of those choices or select other. Is that not what was intended?

**Comment by JayDaley** [comment]
> Are you saying that someone should be able to select _multiple_ options from the provided list (that is, that someone could select all of (he/him, she/her, they/them) and the result would be the string "he/him,she/her,they/them"?

Yes.

> I've interpreted this in the code in the PR so far as a user could select _one_ of those choices or select other. Is that not what was intended?

No.  They can either select any number of the fixed options -OR- select the other field and enter the text.

(Re-reading my original note above, there is a MD spacing issue that is the cause of this confusion.)

**Comment by rjsparks** [comment]
Can we change the limit from 20 to 25 or 30?

`he/him,she/her,they/them` is 24 characters, and `he/him, she/her, they/them` is 26

Places where the results will be displayed will have to deal with at least 24 or 26 depending on whether you want spaces after the commas or not, so other should be allowed to go to the same length.

I'd suggest 30.

**Comment by JayDaley** [comment]
Sure.  We may run into a limit of what can be displayed in some places but that can be dealt with by the app that does the displaying.
