### ISSUE TITLE
Not receiving email confirmations when trying to post IETF I-Ds via the web interface

### ISSUE THREAD

**Issue by fgont** [ietf-tools/datatracker#4044]
### Describe the issue

Hello, folks,

For a while now, I have not been receiving confirmation emails when I submit my internet drafts (with fgont@si6networks.com as the submitter).

The last instance of this has been May 31st, at around 8:30 PM UTC-0300, when I tried to submit a revisionof of draft-gont-v6ops-ipv6-addressing-considerations (version -02) via the online tool at: https://datatracker.ietf.org/submit/.

My email seems to be working okay, and no, the confirmation email did NOT get trapped in my Spam folder.

Could you please check what's going on that is preventing me from receiving the aforementioned confirmation emails?

Thanks!

Regards,
Fernando Gont

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Fernando -

I'll ask the mail to be traced, but in the meantime : if you are logged in when you submit, the email verification step will be skipped.

**Comment by rjsparks** [comment]
@fgont - I emailed the logs of the message being delivered to your servers, with a transaction ID to look for in your logs to trace what happened further. Please let me know if you didn't receive that either.

**Comment by rjsparks** [comment]
Closing this. Reopen if you find data that needs further investigation.
