### ISSUE TITLE
Meeting materials modal injects unsafe content

### ISSUE THREAD

**Issue by NGPixel** [ietf-tools/datatracker#4049]
### Describe the issue

Since the bs5 refactor, the modal that appears when clicking on a meeting injects the content directly into the HTML, instead of using an iframe. This is potentially dangerous as unsafe content can be included and run in the same context as the rest of the datatracker page. Using iframes is safer as the meeting agenda is running in a separate context.

@larseggert Is there a reason why iframes were removed in favor of injecting the content directly via jquery?

Another solution is to sanitize the content beforehand on the server to remove any potentially dangerous content.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
> @larseggert Is there a reason why iframes were removed in favor of injecting the content directly via jquery?

I don't recall whether removing iframes was a conscious decision. I think I remember having issues with getting them styled so they wouldn't cause jumpy layouts and/or have scrollbars.

We can certainly put them back if we can make them look nice.

**Comment by rjsparks** [comment]
Even if we abandon the current agenda page we should pursue sanitization.

I am also becoming increasingly reticent to allow anyone to enter raw html as an artifact (such as minutes or agendas).

**Comment by rjsparks** [comment]
@NGPixel, @larseggert  - whats the current state here? Should we change anything about this before 116?

**Comment by NGPixel** [comment]
It only applied to the old agenda, which no longer exists. The new agenda is using iframes again.
