### ISSUE TITLE
IPR question(s) in shepherd questionnaire should be reviewed by legal

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#4063]
### Describe the issue

The IPR questions in the shepherd writeup should be reviewed by IETF counsel.
I made this point in the wgchairs mailing list, and it seems to have gotten list.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
Sorry for not following up - I didn't forget about it; I just wanted to have the text settle before forwarding it to Brad.

**Comment by larseggert** [comment]
Brad got back to me with a rewording, which I applied in 5742e1d5dcd995ff884217d193ca26259e035164.
