### ISSUE TITLE
Meeting requests column headings formatted poorly

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#4071]
### Describe the issue

On the [meeting requests page](https://datatracker.ietf.org/meeting/requests), the first few column headings are formatted poorly. The columns are too narrow, taking up two lines with the sort button meant to be to beside the heading text on the next line. This occurs even with a 2500px wide browser until I reduce the font size to something unreadable.

Seeing this on Firefox 101.0 on Linux. Screenshot shows the first few - the AD column is correct, but all those to its left show the problem.

![Screenshot from 2022-06-08 13-31-35](https://user-images.githubusercontent.com/19472766/172669786-f0995055-2bd7-4854-8fe2-8c9a6d9cadab.png)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
Yeah, this came in with bs5. I need to figure out a way to keep the arrows with the last word of the column title.
