### ISSUE TITLE
Internal Server Error when requesting joint WG session for IETF-114

### ISSUE THREAD

**Issue by ronald-intvelt** [ietf-tools/datatracker#4080]
### Describe the issue

Requested a WG session for manet at IETF 114; I thought I had asked for this to be a joint session with babel and roll, but it was pointed out to me that this information was not showing up. I tried to edit the request by once more specifying that this was to be a joint session of three WGs as mentioned, but then when I hit the save button, I got an Internal Server Error message.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Closing this as OBE. See also #6146
