### ISSUE TITLE
Show Time in Datatracker State 

### ISSUE THREAD

**Issue by bobhinden** [ietf-tools/datatracker#4087]
### Description

The old version of the datatracker showed how long a document was in a specific state, for example "Submitted to IESG for Publication" or "RFC Ed Queue".  This was apparently removed in the new version of the datatracker.  For example:

https://datatracker.ietf.org/wg/6man/documents/

Please add it back.  It is very useful in my role as a w.g. chair to see how long a document is in a specific state as to take some action to help move it along.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
It is still there, but you need to hover over the hourglass. This was raised in #4009 and I fixed it in #4069, but that has not been deployed yet.

**Comment by bobhinden** [comment]
I disagree that this fixed.   I would prefer to see the actual times displayed, not the hourglass method.   

As a w.g. chair, I want to this information for all of the w.g. document without having to hover over each one.

**Comment by larseggert** [comment]
You will, with #4069. But I will reopen until you confirm that the fix works for you.

**Comment by rjsparks** [comment]
@bobhinden The changes in #4069 have been deployed. I'm closing this. Please reopen if you think it needs further adjustment
