### ISSUE TITLE
provide a discrete URL with all information related to a session at an IETF meeting

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/datatracker#4121]
### Description

Currently, it is not possible to point directly to a location with all the information about any individual session which makes. 

Having this view would help provide all the information in one easily reachable place.

A view similar to that available for past and upcoming interim sessions, which provides links to conferencing information, agenda, slides, and notes would address the issue. Some examples:

https://datatracker.ietf.org/meeting/interim-2022-roll-01/session/roll

https://datatracker.ietf.org/meeting/interim-2022-avtcore-01/session/avtcore

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
What is missing from places like
https://datatracker.ietf.org/meeting/114/session/stir?

**Comment by ghwood** [comment]
I do not see a link for Meetecho.

How does one reach this from:
https://datatracker.ietf.org/meeting/agenda
?

**Comment by rjsparks** [comment]
See work in progress https://github.com/ietf-tools/datatracker/pull/3869 for, e.g., the meetecho links. That is something the interim links you point to above also do not have.

**Comment by ghwood** [comment]
OK! The suggestion https://datatracker.ietf.org/meeting/NNN/session/ACRONYM is most of what I was thinking about, so thanks for that. Meetecho links in that view would make everything right, IMO ;-) so I'll close this issue since it's being worked on elsewhere. Thanks.
