### ISSUE TITLE
Incorect page title when IPR content is restricted

### ISSUE THREAD

**Issue by kesara** [ietf-tools/datatracker#4130]
### Describe the issue

Datatracker page title incorrectly states `404 Not Found` when the actual HTTP Status is `403` for restricted IPR content. This issue might not be limited to IPR content.
Example: https://datatracker.ietf.org/ipr/5682/

```
curl -I https://datatracker.ietf.org/ipr/5682/
HTTP/2 403
```

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This is probably because of this template:
https://github.com/ietf-tools/datatracker/blob/337d2ad38751b9c6ff5b6184b6343a13896214ce/ietf/templates/403.html#L4

**Comment by rjsparks** [comment]
Addressed in 8.10.0
