### ISSUE TITLE
IPR update confirmation email is confusing

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#4133]
When IPR disclosure new_id replaces disclosure old_id, mail is sent to the discloser of old_id asking that the discloser of new_id has the authority make such an update, even if the disclosers of each id appear to be the same person/email address.

(This is because the disclosure form simply collects the email address, it doesn't require login, nor does it perform a round-trip validation of the address provided in the disclosure).

When the discloser of new_id and old_id are, in fact, the same person (or at least email address), the message that is sent out is confusing. It should be reworded to read well in both the case that it really was the person, and the case that someone was attempting to make an update when they shouldn't have.

Further, the subject needs to clearly signal that action is requested. If multiple disclosures are submitted near the same time, and the secretariat processes them near the same time, it is likely that the datatracker sent _other_ email of very similar form, where action was not required, burying the message that needed attention.

An abstraction of a recently sent message demonstrating the confusion follows:

```
To: YOUR NAME <you@example.com>: 
Subject: IPR update notification
 

Dear YOUR NAME:

We have just received a request to update the IPR disclosure(s) submitted by you:


YOUR NAME's Statement about IPR related to [draft-whatever](https://datatracker.ietf.org/doc/draft-whatever/) https://datatracker.ietf.org/ipr/old_id/


The name and email address of the person who submitted the update to your IPR disclosure are:
YOUR NAME, [you@example.com](mailto:you@example.com).

We will not post this update unless we receive positive confirmation from you that
YOUR NAME is authorized to update your disclosure.
Please respond to this message to confirm.

If we do not hear from you within 30 days, we will inform YOUR NAME
that we were not able to secure approval for posting and that we are therefore rejecting
the update until we can be assured it is authorized.

Thank you

IETF Secretariat
```

**Comment by rjsparks** [comment]
cc @jennybui1

**Comment by rjsparks** [comment]
The requirements will change here if we ever shift to requiring datatracker login to submit an IPR disclosure.

**Comment by rjsparks** [comment]
How about this:
```
To: YOUR NAME <you@example.com>:
Subject: Response required: IPR update notification


Dear YOUR NAME:

We have just received a request to update one or more IPR disclosures previously submitted by you:


YOUR NAME's Statement about IPR related to [draft-whatever](https://datatracker.ietf.org/doc/draft-whatever/) https://datatracker.ietf.org/ipr/old_id/


The name and email address of the person who submitted the update to your IPR disclosure are:
YOUR NAME, [you@example.com](mailto:you@example.com). If this is you or someone known by you to be authorized
to update the above disclosures, please respond to this message to confirm.

We will not post this update unless we receive positive confirmation from you that the update
is indeed from you or someone authorized to update the above listed disclosures.

If we do not hear from you within 30 days, we will inform YOUR NAME
that we were not able to secure approval for posting and that we are therefore rejecting
the update until we can be assured it is authorized.

Thank you

IETF Secretariat
```

**Comment by rjsparks** [comment]
If the new disclosure is from someone else, this will read as follows:
```
To: YOUR NAME <you@example.com>:
Subject: Response required: IPR update notification


Dear YOUR NAME:

We have just received a request to update one or more IPR disclosures previously submitted by you:


YOUR NAME's Statement about IPR related to [draft-whatever](https://datatracker.ietf.org/doc/draft-whatever/) https://datatracker.ietf.org/ipr/old_id/


The name and email address of the person who submitted the update to your IPR disclosure are:
THEIR NAME, [them@example.com](mailto:them@example.com). If this is you or someone known by you to be authorized
to update the above disclosures, please respond to this message to confirm.

We will not post this update unless we receive positive confirmation from you that the update
is indeed from you or someone authorized to update the above listed disclosures.

If we do not hear from you within 30 days, we will inform THEIR NAME
that we were not able to secure approval for posting and that we are therefore rejecting
the update until we can be assured it is authorized.

Thank you

IETF Secretariat
```

**Comment by evyncke** [comment]
Would it be possible to:

1. Indicate in the Subject header the draft name ?
2. Have two different templates ? (one when old_id and new_id based on email addresses are the same and one when the email addresses are different)

**Comment by rjsparks** [comment]
In general there are _multiple_ (sometimes dozens) of drafts.
And 2) is what I proposed above isn't it?

**Comment by evyncke** [comment]
> In general there are _multiple_ (sometimes dozens) of drafts.

OK, I failed to understand this.

> And for 2), that's more or less what I was proposing (though I would realize it with a single template). Could you draft words that you would use if the templates were more radically different?

Beside the instantiation of them@, the text is very similar
