### ISSUE TITLE
bad default parameter in doc.utils.has_same_ballot 

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#4141]
### Describe the issue

In `ietf/doc/utils.py`, this method has the signature `has_same_ballot(doc, date1, date2=datetime.date.today())`. The `date2` default value will be evaluated when this module is imported, not at call-time, which is probably not what's intended.

Should init to `None` and grab `today()` at runtime instead of import time.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
Also affects the `is_nomcom_eligible()` filter in `person_filters.py` and perhaps other functions. Should probably search for function calls in default parameters to try to scrub these out.

**Comment by rjsparks** [comment]
ietf/nomcom/utils.py:def previous_five_meetings(date = datetime.date.today()):

**Comment by rjsparks** [comment]
I did a pretty strong scrub (grep, including dealing with multi-line signatures and that's all I found.

**Comment by rjsparks** [comment]
or not. We actually may have a fairly pervasive problem with mutable empty lists and dicts being used as defaults.

**Comment by jennifer-richards** [comment]
I think that's the case - many of these are currently mostly harmless as far as I remember, but are certainly opportunities for bugs to creep in.
