### ISSUE TITLE
`rswg` not filterable on agenda view

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#4158]
### Describe the issue

https://datatracker.ietf.org/meeting/agenda has the `rswg` session in the list, but it doesn't show up under "filter this agenda view"

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
This is because it is of group type "RFC Editor", which has `features.agenda_filter_type="none"`. If that's changed to `"normal"`, then rswg will show up as a button under "Other."

**Comment by larseggert** [comment]
Could that be changed?

**Comment by jennifer-richards** [comment]
Yes, it just needs to be set in the DB. I've done this on the sandbox so you can see the effect until it resets tomorrow.

I think @rjsparks will be in tomorrow and can make the change for production.

**Comment by rjsparks** [comment]
changed. (Anyone on the secretariat can do this (more specifically, anyone with admin access) if I'm not available in the future.
