### ISSUE TITLE
Problem with password reset

### ISSUE THREAD

**Issue by cfjanz** [ietf-tools/datatracker#4199]
### Describe the issue

For the past two days, I have been trying to reset my IETF password. I would like to register for the upcoming meeting.

However, when I open the links returned to me after requesting a reset and entering my email address, every time I get the following:

"Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there was an error in a script used to generate the requested page. In case this was an overload problem or other temporary error, you may want to try again in a little while.

A failure report with details about what happened has been sent to the server administrators. It would be helpful if you would create an issue providing additional information at [GitHub](https://github.com/ietf-tools/datatracker/issues/new/choose), too."

Help!

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
@cfjanz  - I've sent direct email - please reply as soon as you can.

**Comment by rjsparks** [comment]
Resolved via direct email.
