### ISSUE TITLE
Implement GraphQL Endpoint

### ISSUE THREAD

**Issue by NGPixel** [ietf-tools/datatracker#4245]
### Description

⚠️ **Depends on Django 3.2 or later, so on hold until the project is upgraded to a newer version.**

Implement [Strawberry](https://strawberry.rocks/) + [Strawberry Django Plus](https://blb-ventures.github.io/strawberry-django-plus/) to provide a GraphQL endpoint to query the models.

Early agenda tests shows a 10x performance improvement compared to the current implementation.

Would replace temporary REST endpoint implementation:
https://github.com/ietf-tools/datatracker/blob/main/ietf/meeting/views.py#L1596

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Closing this as OBE. We might use strawberry or another graphql endpoint for specialized APIs, but will track that with another issue.
