### ISSUE TITLE
Javascript errors from datatracker

### ISSUE THREAD

**Issue by kivinen** [ietf-tools/datatracker#4247]
### Describe the issue

Some of the pages prints following javascript error when loaded:

TypeError: e.composedPath is not a function
ietf.js:62:101303

This can come from for example https://datatracker.ietf.org/meeting/agenda or https://datatracker.ietf.org/meeting/materials pages. I have not noticed that anything is not working because of this error, but on the other hand it is hard to notice when something is not happening... 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by NGPixel** [comment]
Seems to be a SeaMonkey specific issue. I couldn't replicate on Chrome, Edge, Firefox and Safari browsers.

[Event.composedPath](https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath) is supported on over [95% of global browsers usage](https://caniuse.com/mdn-api_event_composedpath), and should be supported since Firefox 52.

**Comment by kivinen** [comment]
Nicolas Giard writes:
> Seems to be a SeaMonkey specific issue. I couldn't replicate on Chrome, Edge,
> Firefox and Safari browsers.

Yes. It is seamonkey specific, but I assume we are writing web pages,
not pages for some specific browsers. You can download seamonkey from
https://www.seamonkey-project.org/ 

> Event.composedPath is supported on over 95% of global browsers usage, and
> should be supported since Firefox 52.

So we are not trying to be inclusive, but saying it is ok to ignore
minority, because they are only 5% of the people... I had assumed IETF
had bit different values.
-- 
***@***.***

**Comment by NGPixel** [comment]
The latest SeaMonkey (2.53.13) is said to be based on the Firefox 60 gecko rendering engine. Event.composedPath was added back in Firefox 52, so this seems to be a bug in SeaMonkey's implementation?

**Comment by kivinen** [comment]
Nicolas Giard writes:
> The latest SeaMonkey (2.53.13) is said to be based on the Firefox 60 gecko
> rendering engine. Event.composedPath was added back in Firefox 52, so this
> seems to be a bug in SeaMonkey's implementation?

Might be, I did submit a bug report to them also, but I think there
are also other browsers which do not support this, so checking whether
it is really needed by ietf javascript would be useful.
-- 
***@***.***

**Comment by larseggert** [comment]
IIRC it comes from sizzle via jquery. So it will be difficult to avoid that dependency, at least in the short term.

**Comment by rjsparks** [comment]
Tero - we've looked at what it would take to make things work well in SeaMonkey, and have made changes where it was possible to do so, but that browser is not supporting things needed by the libraries we are going to be depending on.
In particular, we're going to be removing the older agenda pages before IETF 115.

Fwiw, as far as logs can tell us, the number of seamonkey users touching the ietf web services approximates one, so while your 5% point is taken in the spirit it was meant, it's not really 5% in this case.

While we'll continue to do what we can reasonably do to help, I think your pressure for this particular issue would be better applied to the SeaMonkey project.
