### ISSUE TITLE
Timezone is reset when meeting agenda page is re-visited (in some browsers)

### ISSUE THREAD

**Issue by smyslov** [ietf-tools/datatracker#4271]
### Describe the issue

If you select timezone value other than "Meeting", then leave the page (for example, follow the link to look on a particular WG agenda) and then get back to agenda page (press Back button), the timezone is reset to default "Meeting" state. It is inconvenient - you have to select it each time you re-visit the agenda page. I observed this behaviour in Edge (to my surprise, not in Chrome, where all works as expected).

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
Are you seeing this on the regular ("old") agenda page or the new one?

The old one involved some wrestling with JS events to make it work with Chrome - it helpfully preserves the state of the forms when you navigate back to the page, but it was tricky to sort out how to detect this and update the times on the page to match. The normal change events did not fire.

Not sure if this would apply to the "neue" one.

**Comment by smyslov** [comment]
Both "old" and "new" agenda behave the same way with regard to this issue in my experience. So, with Edge the timezone is reset in both cases, with Chrome it is preserved in both cases.

**Comment by NGPixel** [comment]
The behavior in agenda-neue is to set the timezone to the meeting local timezone. We could add an option to preserve the user selection though.

**Comment by smyslov** [comment]
I believe it should be preserved. It's annoying to set it again and again when getting back to the agenda page...

**Comment by jennifer-richards** [comment]
I just did a couple quick tests with Chrome and Firefox - in both cases, the timezone reset. This was both for old and neue agendas. Have you tried it recently other than with Edge? My recollection was that it preserved it under Chrome, but that was some time ago (before the bootstrap5 reskinning).

I agree that preserving it would be a nice feature.

**Comment by smyslov** [comment]
I checked Chrome and Edge today at the same time. Probably the behaviour depends on some other conditions (e.g. caching settings etc.)
