### ISSUE TITLE
In the new agenda, links in the material box don't open in a new window

### ISSUE THREAD

**Issue by mirjak** [ietf-tools/datatracker#4273]
### Describe the issue
<img width="1410" alt="Screenshot 2022-07-25 at 16 40 37" src="https://user-images.githubusercontent.com/8420764/180804830-1b5d0af8-0c81-4544-96f5-5218ff97c658.png">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by mirjak** [comment]
I clicked on a link in the dispatch agenda to the slides.

**Comment by mirjak** [comment]
Actually the box only show the agenda and not the rest of the material.

**Comment by mirjak** [comment]
And one more issue about the new agenda (might be a separate issue, please decide to split up yourself): I have a setting to always show the left-side menu but it does not show up with the new agenda.

**Comment by rjsparks** [comment]
left menu for that page is a known issue

**Comment by NGPixel** [comment]
This might be a bit problematic to solve as the contents are rendered inside an iframe, but we could add `<base target="_blank" />` to the page loaded inside the iframe to force all links to open in a new window (or `_parent` to re-use the same window).

**Comment by rjsparks** [comment]
@ngpixel if there's not a separate issue tracking left menu, please add one?

**Comment by NGPixel** [comment]
See #4285 for left menu.
