### ISSUE TITLE
"video stream" is not a sufficiently descriptive tooltip

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#4279]
The link for the remote MeetEcho client is currently labelled "video stream". That's confusing - it's easy to think that might mean "go look at the live youtube feed" or something else. The label should be changed to indicate it is the right place to go to join the full remote experience, even if we do attempt to avoid naming MeetEcho directly.

cc @NGPixel

**Comment by rjsparks** [comment]
cc @JoelHalpern

**Comment by NGPixel** [comment]
Any suggestion for the term to use?

- Join Video Call
- Remote Client
- ... ?

**Comment by JoelHalpern** [comment]
The tooltip I was looking for was "Full Client".  Given that apparently 
the message other folks things is important is that it gives you video 
(which i actually didn't need or want), then how about "Full Tool with 
Video feeds"  ?

Yours,

Joel
