### ISSUE TITLE
AD field lists also non-ADs

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#4302]
### Describe the issue

On https://datatracker.ietf.org/group/chartering/create/wg/

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This needs similar treatment as #4276

**Comment by nathaliepoulin** [comment]
> ### Describe the issue
> On https://datatracker.ietf.org/group/chartering/create/wg/
> 
> ### Code of Conduct
> * [x]  I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)
