### ISSUE TITLE
Datatracker fetches the shepherd write-up for individual documents

### ISSUE THREAD

**Issue by ju7ien** [ietf-tools/datatracker#4312]
### Describe the issue

I would have expected one of the following behaviors:
- fetch the full template, with both "Option 1" (WG I-D) and "Option 2" (individual I-D) that one can easily prune;
- fetch the WG I-D template by default and let the shepherds of individual I-Ds browse to chairs.ietf.org (so far, I've never had to shepherd an individual document);
- identify the type of document so as to fetch the proper 1st template section (in case this is already expected, I guess I've faced a bug).

BTW, the WG doc template layout suggest that the "common part" to options 1 and 2 stars in the "Additional Reviews" section; looking deeper to the questions, it seems that it should start before question 3, which puts the section title in a very misleading place.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
I verified that the Individual writeup template is returned in the prepopulated writeup for wg documents, which is not what is intended.

Note that what's at chairs.ietf.org has now changed to point back into the datatracker so we single-source these templates.

The BTW comment is not clear to me - please elaborate. Perhaps it is now OBE?

**Comment by thaiwab11** [comment]
> ### Describe the issue
> I would have expected one of the following behaviors:
> 
> * fetch the full template, with both "Option 1" (WG I-D) and "Option 2" (individual I-D) that one can easily prune;
> * fetch the WG I-D template by default and let the shepherds of individual I-Ds browse to chairs.ietf.org (so far, I've never had to shepherd an individual document);
> * identify the type of document so as to fetch the proper 1st template section (in case this is already expected, I guess I've faced a bug).
> 
> BTW, the WG doc template layout suggest that the "common part" to options 1 and 2 stars in the "Additional Reviews" section; looking deeper to the questions, it seems that it should start before question 3, which puts the section title in a very misleading place.
> 
> ### Code of Conduct
> * [x]  I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ju7ien** [comment]
> Note that what's at chairs.ietf.org has now changed to point back into the datatracker so we single-source these templates.

I indeed see the links to the datatracker on the page [https://chairs.ietf.org/en/documents](url)
Note however that [https://chairs.ietf.org/documents/document-shepherding ](url) is still pointing to [https://chairs.ietf.org/documents/qa-style-writeup-template](url), which is now broken.


> BTW, the WG doc template layout suggest that the "common part" to options 1 and 2 stars in the "Additional Reviews" section; looking deeper to the questions, it seems that it should start before question 3, which puts the section title in a very misleading place.

The former page, which was behind the broken link above, looked like the following:  

### Option 1: WG I-D
1. ...
2. ...
### Option 2: individual I-D
1. ...
2. ...
3. ...
4. ...
### Additional Reviews
5. ...

The visual break was at the "Additional Reviews" section and there was no section break between questions 3 and 4. That was (mis)leading to consider the template's "common part" to start at question 5 (though I believe it actually starts at Q3).

**Comment by rjsparks** [comment]
cc @ghwood

**Comment by ghwood** [comment]
> > Note that what's at chairs.ietf.org has now changed to point back into the datatracker so we single-source these templates.
> 
> I indeed see the links to the datatracker on the page [https://chairs.ietf.org/en/documents](url) Note however that [https://chairs.ietf.org/documents/document-shepherding ](url) is still pointing to [https://chairs.ietf.org/documents/qa-style-writeup-template](url), which is now broken.

Thanks for catching this and it is now fixed. [Suggestions and improvements](https://chairs.ietf.org/en/improvements) are always welcome.
