### ISSUE TITLE
Ability to manage wg document page more manually

### ISSUE THREAD

**Issue by mirjak** [ietf-tools/datatracker#4324]
### Description

It would be nice if chairs could add drafts to "Related Internet-Drafts" category manually even if the wg name is not in the draft name; or vice versa remove a document that is not related but for other reason seem to match with wg name.

I just saw that documents have an "manage adoption" button but that only covers wg doc and not related drafts. Also this button is hard to find and didn't feel self-explanatory for me...

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
`manage adoption` is not how to add documents to `Related Internet-Drafts`.

That's done through the working group's community list, which is done with the [Manage document list] button on the group's documents page.

Any related draft can be added to the Related Internet-Drafts category here:
![image](https://user-images.githubusercontent.com/10996692/184717532-8b9156f2-c499-49a1-bd4c-69a6d181d6f4.png)

**Comment by rjsparks** [comment]
If you are looking to do this from document pages or from search results we could try to build UI similar to the current [track] and [untrack] elements that add/remove the document from your personal community list, but for each group that the logged in user was chair of, but that would likely get very busy.

**Comment by rjsparks** [comment]
And there's not currently any way to exclude a specific document, particularly one that matches the working group name ruleset. The rules are all additive (by the original design in rfc6293). It would be a substantive change to add subtractive rules.

**Comment by rjsparks** [comment]
@mirjak Given the above feedback, is there anything still to do here?

**Comment by mirjak** [comment]
No, it's fine I think. Thanks!
