### ISSUE TITLE
Show associated BCP/STD document numbers in document search results

### ISSUE THREAD

**Issue by jimfenton** [ietf-tools/datatracker#4329]
### Description

One way to search for a BCP is to type the number only in the search box (e.g., "195"). The search results show a bunch of documents whose RFC number contain the string "195", but also shows RFC 7525 with no explanation why (i.e., that this is BCP 195). This would be a lot more intuitive if any associated BCP/STD numbers were shown somewhere in the search results.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Similar to #4328, and copying what I said there:

The datatracker doesn't really understand BCPs right now - it tries to use DocAlias to point to a Document of type 'draft' that happens to be an RFC, and it can only point to one, so trying to do anything with any BCP with more than one RFC in it simply won't work.

What you ask will need to wait until after we change the models to make RFCs their own document type, rework DocAlias completely, and then (I currently plan) to add BCP and STD document types that consist of nothing but DocumentRelations to the constituent RFCs.

See also #2664, #1675, #2917, #3490

**Comment by toerless** [comment]
Feel free to ping me to check if/when any of this gets resolved, as i did stumble across these problems today.

**Comment by rjsparks** [comment]
fixed on the feat/rfc branch. Closing this, but note that it will be some time before this makes it to production. In the meantime, you can exercise the fix at dt-rfc.dev.ietf.org
