### ISSUE TITLE
`hotrfc` not accessible from "Groups" menu

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#4339]
### Describe the issue

https://datatracker.ietf.org/group/hotrfc/about/ exists, but I can't figure out how to get to it from within the menu structure.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Because HotRFC (and a few others) were created quickly as "doesn't fit anywhere" groups.

```
>>> from ietf.group.models import Group
>>> g = Group.objects.get(acronym='hotrfc')
>>> g.type
<GroupTypeName: Ad Hoc>
>>> Group.objects.filter(type='adhoc')
<QuerySet [<Group: IEPG - Internet Engineering and Planning Group>, <Group: Hot RFC Lightning Talks>, <Group: Technology Deep Dive>]>
```

Do you want an "Active Ad Hoc" item added to Other under Groups, or would you prefer to rethink how these groups are modeled in the first place?

**Comment by larseggert** [comment]
I think some quick fix would be good now - we can rethink this later.

**Comment by rjsparks** [comment]
Closing - handled with data model changes as discussed in 4380.
