### ISSUE TITLE
`group.type.name` for RSWG/RSAB is "RFC Editor"

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#4360]
### Describe the issue

That leads to an odd display on https://datatracker.ietf.org/group/rsab/about/.

Maybe it should be "RFC Editor Group" or something similar?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This is a consequence of moving the RFC Editor groups we had into the new RFC editor model and adding RSWG and RSAB as groups of the same type.

If we change the group type name for the group type, all of these groups will be affected:
```
<QuerySet [<Group: RFC Series Editor>, <Group: RFC Editor>, <Group: RFC Production Center>, <Group: RFC Series Working Group>, <Group: RFC Series Approval Board>]>
aka:
<QuerySet ['rse', 'rfceditor', 'rpc', 'rswg', 'rsab']>
```
If you don't want all of those to change the same way, we will have to change the models (and there will be code implications).

"RFC Editor Group" doesn't really follow the pattern for the names so far.
```
>>> list(GroupTypeName.objects.values_list('name',flat=True))
['Ad Hoc', 'AG', 'Area', 'Directorate', 'Directorate (with reviews)', 'Editorial', 'IAB', 'IAB ASG', 'IANA', 'IESG', 'IETF', 'Individual', 'IRTF', 'ISE', 'ISOC', 'Nomcom', 'Program', 'RAG', 'RG', 'SDO', 'Team', 'WG', 'Admin', 'RFC Editor']
```

Is there a container word from the new RFC editor model we can use?

On the other hand, what is actually _wrong_ with "RFC Editor"?

**Comment by rjsparks** [comment]
"RFC Editor function" is getting pretty long, but that's what it looks like 9280 is calling the set of groups.

**Comment by rjsparks** [comment]
@larseggert - what are your thoughts now? Can we leave this as is?
