### ISSUE TITLE
The ipr-announce list no longer includes live links to the announced disclosure 

### ISSUE THREAD

**Issue by bradbiddle** [ietf-tools/datatracker#4366]
### Describe the issue

A few months ago announcement emails shifted from including links in standard URL format (e.g.  <https://datatracker.ietf.org/ipr/5669/>) to including text that looks like this -- "(/ipr/5780/history/)" -- and that does not link to the disclosure page. Could you please include links to the disclosure page for the announced disclosure in the announcement email? Thanks!

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
This is fixed by #4357

**Comment by rjsparks** [comment]
merged - will be part of next release.
