### ISSUE TITLE
Filtering group types is not quite completely working 

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#4375]
From @flynnliz

On Wednesday during lunch at 12:15 there’s a WG Chairs lunch that’s held in one of the regular session meeting rooms. This timeslot is marked as “Other” but I cannot get it to disappear from the grid. Even when I have selected that the Timeslot Types visible should only be Regular, this lunch session still appears. I have also tried marking that time slot as Registration or other random things just to get it to go away, but it still appears in the middle of the grid. It pushes out the rest of the day on Wednesday so the session time slots don’t line up — see screenshot. The regular sessions not aligning vertically makes it really difficult to re-schedule any sessions needed so we can accurately see conflicts. For example, if I want to check which sessions can go in that one empty spot, I also have to look at LPWAN to its right which is the session that conflicts with everything else in that column.

Also, that WG Chairs lunch session is actually from 12:15-13:15 but the header on its rectangle lists 13:30-14:30 as it’s trying to fit itself into the rest of that column, which just adds to the confusion of what times those lpwan and idr sessions are.

![image](https://user-images.githubusercontent.com/10996692/186987115-78e25b79-ea1d-4fa2-a310-47ad528b8bc5.png)

**Comment by rjsparks** [comment]
Will split this out to its own issue:
>Also, that WG Chairs lunch session is actually from 12:15-13:15 but the header on its rectangle lists 13:30-14:30 as it’s trying to fit itself into the rest of that column, which just adds to the confusion of what times those lpwan and idr sessions are.

**Comment by jennifer-richards** [comment]
I traced this a bit and it looks like there's a mashup of methods for hiding elements used in the JS (`edit-meeting-schedule.js`). The timeslots and sessions of type "Other" are marked with the `hidden` class, but are still visible. The JS does this by explicitly adding the `hidden` class. Elsewhere, elements are shown / hidden using jQuery's `show()` and `hide()` methods. I suspect this came up with the bootstrap 5 transition and slipped through the refactoring.
