### ISSUE TITLE
datatracker draft diff failure

### ISSUE THREAD

**Issue by rgwilton** [ietf-tools/datatracker#4420]
### Describe the issue

I'm trying to diff between the last two versions of this draft:

https://datatracker.ietf.org/doc/draft-ietf-ippm-rfc8321bis/history/

This returns a page with the following error message:

./rfcdiff: Error: Failed to create temporary directory '/tmp/rfcdiff-8431'.

Perhaps out of space, or the directory already exists?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This was a transient error at IETFA that has been corrected.
