### ISSUE TITLE
AD dashboard should also display trend when current == 0

### ISSUE THREAD

**Issue by evyncke** [ietf-tools/datatracker#4450]
### Description

https://datatracker.ietf.org/doc/ad/ with the trending arrows would benefit by displaying the trend *even* if the current value is 0.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
I think it does show it, but only if the count thirty days ago was not also zero. Is there a field where you think something should be displayed?

**Comment by evyncke** [comment]
This may indeed be the case. Then, this issue is not relevant (to be checked of course).

The 30-day period appears a little short to me BTW, should rather be more than 2 telechats

**Comment by rjsparks** [comment]
This is lingering - should we turn this into a request to look back more than 30 days instead?

**Comment by rjsparks** [comment]
nudge

**Comment by evyncke** [comment]
> This is lingering - should we turn this into a request to look back more than 30 days instead?

IMHO: yes

**Comment by larseggert** [comment]
How many days?

**Comment by evyncke** [comment]
Like briefly discussed with @rjsparks , 120 days (= IETF cycle) would be a better match ;-)
