### ISSUE TITLE
shepherd upload rejects .txt file

### ISSUE THREAD

**Issue by cindymorgan** [ietf-tools/datatracker#4453]
### Describe the issue

From Michael Richardson <mcr@sandelman.ca>: 

Hi, I tried to upload the shepherd review.
It was rejected as not being text/plain. I don't know what MIME type my
browser put in, not sure how I can get that debug out of chrome.
it says: text/x-Algol68; charset=us-ascii

which seems ridiculous to me!

The files are at: https://www.sandelman.ca/tmp/shep01/
which includes two screen shots of me uploading.

I have pasted my review into the box.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Can reproduce.

**Comment by rjsparks** [comment]
issue is server-side:
```
rjsparks@ietfa:~> file sain-shepherd-review.txt
sain-shepherd-review.txt: Algol 68 source, ASCII text
```

**Comment by rjsparks** [comment]
I think @mcr already worked around this, but until we straighten out what `magic` is doing above, and anyone else needs to avoid the issue, `ref ` is read as ascii, not algol 38.

**Comment by mcr** [comment]
Robert Sparks ***@***.***> wrote:
    > I think @mcr already worked around this, but until we straighten out
    > what `magic` is doing above, and anyone else needs to avoid the issue,
    > `ref ` is read as ascii, not algol 38.

I did run file on my .txt file, and it did not say anything about algol-38.
did my browser label it text/plain?  and if it did, why would the output of
file/magic matter?

**Comment by rjsparks** [comment]
First off: Glen modified magic on the server to not identify things containing "REF " as algol 68, so I'm closing this issue.

To answer your question:
What matters is what libmagic says (which is what file uses) on the server, not on your client. What the browser labels it is not used at all. The relevant code is here: https://github.com/ietf-tools/datatracker/blob/main/ietf/utils/textupload.py#L27-L41

The relevant code in magic is here:
https://github.com/file/file/blob/fb7fa4de919c030c2f4d9fcba02b198512d29c7c/magic/Magdir/algol68
Note that this is not HEAD at that repository, but matches what the OS the server runs on has packaged.
HEAD there has a slightly different (but still not great) set of regex that would cause a file to be declared algol68. See https://github.com/file/file/blob/master/magic/Magdir/algol68
