### ISSUE TITLE
post_submission() creates bibxml that likely has incorrect timezone handling

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#4459]
### Describe the issue

The `doc/bibxml.xml` template rendered by `post_submission()` includes
```
      <date month="{{doc.date|date:"F"}}" day="{{doc.date.day}}" year="{{doc.date.year}}" />
```
which will give inconsistent day/year for a few hours at start of the day.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
The code I quoted there is ok - `doc.date` is a `datetime.date` so it's ok to refer to its day and year fields directly in a template. The code that calls it is now going to be handing it dates computed from the UTC time when the `NewRevisionDocEvent` was created instead of the PST8PDT time. @rjsparks, do we need to worry about that level of precision for this date?

**Comment by rjsparks** [comment]
It should match whatever shows for a date for the NewRevisionDocEvent in the document's history.

**Comment by rjsparks** [comment]
closing even though this isn't yet deployed - it will come in with tzaware
