### ISSUE TITLE
upcoming meeting view should use Meeting.end_date() method

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#4462]
### Describe the issue

The `upcoming()` view in `ietf.meeting.views` assigns an `end` attribute to each meeting. The `Meeting.end_date()` method performs the same calculation.

Replace the ad hoc `end` attribute with calls to `end_date` to get rid of the redundant code.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Closing as Complete - re-open if there's still something not done.
