### ISSUE TITLE
Cannot "add another" room to secr app room creation tool

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#4466]
### Describe the issue

On the "Rooms" tab of the secr app's meeting management tool, clicking the "Add another" button at the bottom does nothing. On page load, the javascript debug console shows the message
```
Uncaught ReferenceError: add_inline_form is not defined
```
but no further errors appear when clicking the button.

The effect is that all rooms must be created in one go and no more than ten rooms can be created.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
Check the pre-bs5 code if I accidentally dropped a function?

**Comment by jennifer-richards** [comment]
It's caused by some old code that injects html with an onclick attribute. That breaks due to minification. I'm trying to update it but running into problems with the source mal in the debuggers...
