### ISSUE TITLE
Conflicts to Avoid field is empty in Session Request Tool email notifications

### ISSUE THREAD

**Issue by plonkamai** [ietf-tools/datatracker#4477]
### Describe the issue

When we receive email notifications of session requests or updates to session requests, it seems the "Conflicts to Avoid" field in the email message is always empty, even when we have submitted conflicts when requesting the session or updating the session request.

For example, my cochair added conflicts to avoid and this is the resulting email notification:

On Mon, Sep 19, 2022 at 10:53 AM IETF Meeting Session Request Tool
<session-request@ietf.org> wrote:
>
>
>
> An update to a meeting session request has just been submitted by Mirja Kuehlewind, a Chair of the maprg working group.
>
>
> ---------------------------------------------------------
> Working Group Name: Measurement and Analysis for Protocols
> Area Name: IRTF
> Session Requester: Mirja Kühlewind
>
>
> Number of Sessions: 1
> Length of Session(s): 2 Hours
> Number of Attendees: 100
> Conflicts to Avoid:
>
>
>
>
> People who must be present:
>   Mirja Kuehlewind
>   Dave Plonka
>
> Resources Requested:
>
> Special Requests:
>
> ---------------------------------------------------------
>
>

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
Also see https://mailarchive.ietf.org/arch/msg/tools-discuss/Q8r_D087CwCd_qHA94XWXSkNsYM

**Comment by jennifer-richards** [comment]
I see this happening when updating an existing session request, but I'm not able to reproduce the problem for new requests. These correctly list the conflicts, at least on my dev system.
