### ISSUE TITLE
"Duplicate timeslots" option for new rooms does not respect timezones

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#4484]
### Describe the issue

Reported by @flynnliz,

> On the page [...]/secr/meetings/115/liz-flynn-1/rooms/ , I entered a bunch of rooms. At the bottom of the page, checking the box "Duplicate timeslots from previous meeting for new rooms?" results in creating the previous time slots but in the new time zone — for example, 114’s 10:00 timeslot in Philadelphia becomes 14:00 in 115’s London. (This essentially makes the feature useless, as now every single time slot is at the wrong time. I usually do everything from scratch every meeting anyway so this being broken isn’t a big deal.)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Closing even though this isn't deployed - it will come in with tzaware.
