### ISSUE TITLE
sandbox/htmlize: remove preferences tab

### ISSUE THREAD

**Issue by elear** [ietf-tools/datatracker#4497]
### Describe the issue

There are two problems with the preference tab in the right frame:

1. Preferences shouldn't be in a tab.  Nearly the entire world has settled on an icon in the upper right hand corner for preferences.
2. They're showing preferences that probably shouldn't be preferences.  Which tab is the default indicates perhaps that we haven't concluded what the right tab is.  We should do that.  Also, htmlize text versus plaintextify html raises the same question.  I suspect that ties to whether we have a good HTML diff mechanism.

### Code of Conduct

- [x] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
On (1), would you then show the prefs with a modal?

On (2), I'd **love to** pick one choice for everything, but past feedback was such that everyone wanted something different.

**Comment by elear** [comment]
On (1) you have to render these things slightly differently on different media.  There are plenty of real life examples, not least of which is the one I'm typing into now and you are reading this on.
On (2) stop asking.  If you have a parkable frame with tabs, which one is the default matters a lot less.

**Comment by elear** [comment]
As an aside, I find it entertaining that I can check the "agree to the code of conduct" box, submit, and then unclick the box.

**Comment by elear** [comment]
Do you have any positive feedback about this aspect?

**Comment by larseggert** [comment]
I have no other feedback. Going to close.
