### ISSUE TITLE
Liaison detail form buttons do not work

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#4517]
At least the `Approve` button at `https://datatracker.ietf.org/liaison/<pk>` does nothing.
The other buttons need to be checked.

**Comment by larseggert** [comment]
What's a workflow that would expose the bug? When I just go to any existing LS the buttons do work.

**Comment by rjsparks** [comment]
you need to find a LS that is not yet approved to work with - it's the approve button that caused the bug to be filed.
(I had to mimic the code and do the approval of https://datatracker.ietf.org/liaison/1796/history/ manually as the button didn't work for either Éric or Jenny).

**Comment by larseggert** [comment]
I can't even enter an outgoing liaison anymore - the "From contact" seems to clear on submit.

**Comment by rjsparks** [comment]
yes - another bug in the way. Captured at #4610.

I'll work with you online to set one of these up using the shell or the admin.
