### ISSUE TITLE
"Share nominator name with candidate" on NomCom form doesn't do anything

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#4523]
### Describe the issue

I just nominated a bunch of people for NomCom roles, and got several reports that my name as nominator was **not** in the nomination email that people received.

So the "Share nominator name with candidate" checkbox doesn't seem to do anything.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
That's not what the button is for.

It gives the nomcom members a visual indication when they are viewing the feedback that the nomcom member can feel free to share that you provided the feedback (in this case, the nomination).

It looks like this while viewing feedback:
![image](https://user-images.githubusercontent.com/10996692/193154608-918a56b8-fead-42d5-a04d-178de96713c8.png)

I'm marking this as invalid - feel free to argue with me. But if that clears things up, please close the issue.

**Comment by larseggert** [comment]
Well, then the label is **really** misleading.

**Comment by larseggert** [comment]
Or maybe rather the logic should be inverted, and the label should say "keep nominator confidential".

**Comment by rjsparks** [comment]
"Tell nomcom it's ok to share this nominator's name with candidate"?
