### ISSUE TITLE
Vertical bars in the nomcom private pages

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#4529]
### Describe the issue

I know it's gonna look clunky if taken to extremes, but in some of the nomcom private pages (I'll share a screenshot when you want) it's hard to see the column alignments.  Perhaps vertical lines or colorization (checkerboard?  hmm.)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
lots of tables post bs5 have the column heading and the column content positioned in the columns differently, making it hard to tell where the column boundaries really are.

**Comment by larseggert** [comment]
The meta issue here is that we overuse tables for presenting data.

**Comment by rjsparks** [comment]
Ironic to point to that here, as the nomcom private pages are a place where tables actually make sense.

**Comment by larseggert** [comment]
If you tell me which tables/URLs, I can add them.

**Comment by richsalz** [comment]
The table at the start of https://datatracker.ietf.org/nomcom/2022/private/ where the columns start as Position, Open, Accepting Nominations, etc.  Let me know if that's not clear.

The detailed "Nominations by position" doesn't need it.
