### ISSUE TITLE
"report a bug" should open in new window

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#4530]
### Describe the issue

Often need to look back at the page while creating the bug report.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
https://github.com/ietf-tools/datatracker/pull/4525 (just merged) does this already.
