### ISSUE TITLE
test_docs_for_ad randomly spuriously fails

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#4572]
We occasionally see this failure:
 ======================================================================
FAIL: test_docs_for_ad (ietf.doc.tests.SearchTests.test_docs_for_ad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/datatracker/datatracker/ietf/doc/tests.py", line 301, in test_docs_for_ad
    self.assertEqual(r.status_code, 200)
AssertionError: 404 != 200

It's clearly a test-harness randomly generated data data mismatch with the view being tested. Investigation is needed to see if this is a real (but obscure corner) bug, or just insufficient constraints on the generated data issue.

**Comment by larseggert** [comment]
I was very sure it would fail with `person__name="O'Gowan Mullin"` but no luck.

**Comment by larseggert** [comment]
I think this was fixed by #4695.

**Comment by jennifer-richards** [comment]
Yes, it looks that way (another one that did not auto-close because it went to the feat/tzaware branch)
