### ISSUE TITLE
Add Total Number of I-Ds to the I-D State Count table in the AD Dashboard

### ISSUE THREAD

**Issue by rdanyliw** [ietf-tools/datatracker#4577]
### Description

The I-D State Count table of the AD Dashboard (https://datatracker.ietf.org/doc/ad) currently lists the documents an AD is shepherding from PubReq to Approval.  To provide a sense of the load prior to PubReq, recommend adding a column as follows:

OLD I-D State Count
* Column 1 = AD Name
* Column = Pub Req

NEW I-D State Count
* Column 1 = AD Name
* Column 2 = Total I-Ds = a count of adopted I-Ds in the WGs overseen by the AD + any independent documents the AD is assigned to (in cases of AD sponsored documents) 
* Column 3 = Pub Req

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Col 2 excludes anything at or past "approved" correct?

**Comment by rdanyliw** [comment]
Yes, the new Col 2 would be anything that is in "WG state = * AND IESG state = I-D Exists" -- informally, "anything still with the WG" (but only adopted documents).

**Comment by evyncke** [comment]
May I assume that expired WG I-Ds are not counted ?

I am ambivalent as it happens that I-Ds expire for a couple of weeks even if still worked on. OTOH, not counting expired I-D is cleaner.

**Comment by rdanyliw** [comment]
IMO, expired WG I-Ds should not be counted.

**Comment by hollowaysmith** [comment]
@rdanyliw Hi Roman,

Is this the kind of thing you had in mind?

![Screenshot from 2024-05-27 15-49-12](https://github.com/ietf-tools/datatracker/assets/44757643/e835e325-0abe-4a32-b6ff-dcef06b3ad2a)

**Comment by rdanyliw** [comment]
@hollowaysmith Hi!  Thanks for this mock-up.  Yes, that's exactly what I was thinking.

**Comment by rjsparks** [comment]
Merged into feat/ad-dash
