### ISSUE TITLE
Filtered calendar view of plenary doesn't work

### ISSUE THREAD

**Issue by mnot** [ietf-tools/datatracker#4580]
### Describe the issue

Go to the [115 HTML agenda](https://datatracker.ietf.org/meeting/115/agenda/) and filter for the plenary. It doesn't show up in the view, and the query string is `?show=None`.

(using Safari latest)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
https://datatracker.ietf.org/meeting/115/agenda?show=ietf-plenary is what you wanted (there's a button for it under the Plenary grouping in the filters), but it's clear why this changed from just "plenary" and why there is a separate "planary" thing that causes show=None to happen. Will investigate.

**Comment by mnot** [comment]
Aha - thanks!

**Comment by rjsparks** [comment]
So - this was an issue with the filter choser for the older agenda (which was just removed). The root was that it was gathering slugified session names and session purpose names for sessions that weren't regular wg/rg sessions.
```
>>> Session.objects.filter(meeting__number='115',name__icontains='plenary').values_list('name','purpose__name')
<SessionQuerySet [('IETF Plenary', 'Plenary')]>
```
The chooser for the new agenda handles this better. I'm going to close this issue with no code changes. Please reopen if you find the same problem in the new agenda in a place I haven't managed to see.
