### ISSUE TITLE
Agenda does not work for "agenda.html" URLs

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#4588]
### Describe the issue

Raised by @flynnliz, the new agenda is only functional at URLs like https://datatracker.ietf.org/meeting/agenda. 

With '.html' appended, the page appears to be loading but never displays the agenda. E.g., https://datatracker.ietf.org/meeting/agenda.html

The same is true with an explicit meeting number (https://datatracker.ietf.org/meeting/115/agenda.html)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by NGPixel** [comment]
The vue router is missing ".html" as an optional suffix, so it just ignores the route and doesn't load anything. I'll make a PR...
