### ISSUE TITLE
Hi all.

### ISSUE THREAD

**Issue by alaoy0225** [ietf-tools/datatracker#4591]
Hi all. 

I'm thinking of creating an RFC about URLON(URL Object Notation) which is a concept of url in JSON object... and originally designed by [vjeux](https://blog.vjeux.com/2011/javascript/urlon-url-object-notation.html). There is no RFC available today about URLON, although there are several implementations about urlon as: [cerebral/url](https://github.com/cerebral/urlon) or [Double-oxygeN/urlon-nim](https://github.com/Double-oxygeN/urlon-nim). In this sense, I would like to know where I can find the rfc file template so that I can create this rfc over urlon and send it to the IETF. 

My questions are these:
1. where can I find the RFC file template for IETF?
2. where I send the RFC file to the IETF?
3. have you all heard about the urlon(url object notation) implementation?

_Originally posted by @codehangen in https://github.com/ietf-tools/datatracker/discussions/4473_

**Comment by JayDaley** [comment]
Please read https://www.ietf.org/about/participate/get-started/ and please do not add issues against this repository for unrelated subjects like this.
