### ISSUE TITLE
Add help / tutorial on how to use the agenda

### ISSUE THREAD

**Issue by NGPixel** [ietf-tools/datatracker#4597]
### Description

It would be worth adding a button to show a quick help dialog with basic instructions on how to use the agenda. Because of all the available options, it can be overwhelming to new users.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
It would be better to push for self-documentation, and start down the path of _simplifying_ the agenda page again. Separate pages providing instruction/tutorials rot almost instantly and can quickly do more harm than good. If we have such a page while we work towards self-documentation, please keep the probability of rot in mind while building it (considering things like screenshots, for example).
