### ISSUE TITLE
"send email" to nominess

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#4626]
### Description

It would be nice to be able to filter the nominees, for example, picking all accepted IAB nominations via https://datatracker.ietf.org/nomcom/2022/private/?state=accepted&position=109&submit=, and be able to send them a short email.  It could be a text box, or perhaps like #4618 to allow an upload. The textbox is probably good enough.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Is it important that the datatracker send the message? Would it be sufficient (or better?) if the datatracker gave you an easy way to gather the set of addresses to use to send from your own email client of choice?

Points to consider (these could be both pluses and minuses)
* the datatracker keeps a record of what message is sent to who and when
* sending from the ietf servers has well-explored (but not always well-working) properties wrt successful smtp delivery to community members

**Comment by rjsparks** [comment]
Maybe the answer to the above question should be "why not both?"

**Comment by richsalz** [comment]
I didn't think of just "give me these addresses" as a way of doing it.  And yes, that would be fine.

**Comment by richsalz** [comment]
I think this and #4893 are closely related, perhaps even duplicates :)

**Comment by richsalz** [comment]
Closing as a duplicate of #4893 which is fixed.
