### ISSUE TITLE
Unexpected meeting chosen for meeting/agenda.ics and meeting/agenda.json endpoints

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#4629]
### Describe the issue

The `meeting/agenda.ics` and `meeting/agenda.json` endpoints returns an iCalendar file for the next meeting of any type - at the moment, this is for an interim meeting. This is surprising because `meeting/agenda.html` and `meeting/agenda.txt` both return the next full IETF meeting. It would be preferable if all the `meeting/agenda.*` URLs agreed on what meeting they represented.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This should be the next full ietf meeting.
