### ISSUE TITLE
Can not classify messages from the email queue

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#4634]
### Describe the issue

This is a couple of issues, let me know if you want me to split it into separate bugs.

I did a cut/paste of the email from a nominee. The simple newlines (`\n` I think) were not turned into full newlines (`\r\n`?) Therefore there questionnaire was all "smooshed" into like six newlines and is hard to read.

I then went to the classify email and tried to take that email and mark it as a questionnaire response. It kept bringing me back to the "pick which candidate" page, with no indication why. I assume it was because the candidate already had their responses uploaded. It should say why.

When I looked at the email BTW, it was double-spaced.  Inconsistency in newlines?

It would be nice to be able to replace a candidate's response. Is this possible? Maybe two steps, by first deleting then uploading the new one?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
The newline presentation issue is addressed by #4658.

The remaining issue is with classifying feedback (and assigning it to a nominee) received by the email ingester.

**Comment by rjsparks** [comment]
Replacing a candidate's response is tricky, and we probably want to keep everything in the record. What we should look at (not now - it is a big project) is something like adding a new classification of 'replaced', and making it possible for the chair to reclassify already classified objects.

For this nomcom (as past nomcoms have done), just make sure people know to scan from the bottom - feedback is in  time order.

**Comment by richsalz** [comment]
I am fine with your reasoning.  Let me know if you want me to open a new issue based on your comment or if you want to keep this one.

**Comment by rjsparks** [comment]
I'll make a new issue.
