### ISSUE TITLE
wording a bit off in "you've been nominated"

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#4641]
### Describe the issue

The nomination questionnaires are sent as part of the "you've been nominated" email. The text in that email implies they'll get them if/when they accept.  We should fix that.  And also fix the wording to allow for times when NomCom hasn't finished the questionnaires, maybe "if you do not see the questionnaire below, it will be available at shortly on the nomcom page, https://....."

See also #4637 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by richsalz** [comment]
Quoting email I have from Robert:
"We could tweak the text in the nomination notification message to help avoid confusion, but the current implementation sends the questionaire at the same time as  the nomination notice when the nomcom is configured to send questionnaires automatically. The theory is that people should get a chance to start in on the questionaire while they're still working out with their sponsor whether or not they can accept the nomination.

The relevant code is here:

https://github.com/ietf-tools/datatracker/blob/8.18.0/ietf/nomcom/utils.py#L363
"

**Comment by LPardue** [comment]
Sending the questionnaire at the same time is fine by me, so the suggestion of changing the text in the nomination announcement is reasonable. Just make it clearer like: "we've sent you the questionnaire at the same time. There's no obligation to complete or return it until you accept the nomination"

**Comment by rjsparks** [comment]
We could look at the configuration of the nomcom at the time the message is sent, and say either "You will receive another message with the questionnaire immediately. There's no obligation to complete or return it until you accept the nomination." or use the current text if the questionnaire won't be sent until some other point in the future.

**Comment by richsalz** [comment]
The proposed fix (#5357) changes the prompt to tell the nomcom chair to NOT click the "generate questionnaire email" button if the questionnaires are not ready.  That seems good enough.

**Comment by richsalz** [comment]
I think this can be closed as fixed by #5357
