### ISSUE TITLE
rfcdiff is broken

### ISSUE THREAD

**Issue by choppsv1** [ietf-tools/datatracker#4644]
### Describe the issue

The following is the output of trying to obtain a diff:

```
./rfcdiff: Error: Failed to create temporary directory '/tmp/rfcdiff-49297'.
```

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Not a datatracker issue - better reported at support@, but this has already been addressed.

**Comment by choppsv1** [comment]
Robert Sparks ***@***.***> writes:

> Not a datatracker issue - better reported at support@, but this has
> already been addressed.

***@***.***? :)

In any case, I'm not sure how I would know the difference. Should all issues be reported to support@<whatever> first and then issues opened later?

Thanks,
Chris.

**Comment by rjsparks** [comment]
If the URL says https://datatracker.ietf.org, then it's a datatracker bug.

rfcdiff is currently hosted at www.ietf.org, not on the datatracker - it's a separate application. (And it will be replaced with iddiff at author-tools.ietf.org soon)..

But generally speaking - look at the first part of the URL. If that doesn't make it obvious, use support@
