### ISSUE TITLE
html diff not working

### ISSUE THREAD

**Issue by louberger** [ietf-tools/datatracker#4645]
### Describe the issue

when clicking on any html diff1 or diff 2 see the following:
`./rfcdiff: Error: Failed to create temporary directory '/tmp/rfcdiff-10958'.`

for example visit: https://www.ietf.org/rfcdiff?difftype=--hwdiff&url2=draft-joung-detnet-asynch-detnet-framework-01.txt

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This isn't a datatracker issue - it would be better reported to support@, but it's already been addressed.
