### ISSUE TITLE
Add link to txt agenda to top menu

### ISSUE THREAD

**Issue by kivinen** [ietf-tools/datatracker#4655]
### Describe the issue

As the current agenda does not work anymore for all browsers, it would be nice to have link to the txt version of the agenda so I could use that to see what is going on in the IETF.

I.e. add link to https://datatracker.ietf.org/meeting/agenda.txt so it can be found from the top menu.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
Can you share what the error is? We might be able to conditionally add the link in those cases; I don't think adding the link for everyone makes sense.

**Comment by NGPixel** [comment]
Adding a link to the loading screen (which shows even if JS is disabled):

<img width="959" alt="image" src="https://user-images.githubusercontent.com/15522395/198388094-f251b952-f619-4e6b-a2a8-73174ff20a44.png">

**Comment by NGPixel** [comment]
And another link if the agenda fails to load for any reason:
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/15522395/198393222-7c1c5da3-8173-4274-b4c8-4c2c2f69d4a5.png">

**Comment by kivinen** [comment]
Lars Eggert writes:
> Can you share what the error is? We might be able to conditionally add the
> link in those cases; I don't think adding the link for everyone makes sense.

Here is trace:

TypeError: e.composedPath is not a function
	   ietf.js:110:96874
JQMIGRATE: Migrate is installed with logging active, version 3.4.0
	   jquery-migrate-npm-3.4.0-88c209e61f-7431:103:1
SyntaxError: expected expression, got keyword 'import'
	     main.5889cc86.js:9:22533
SyntaxError: expected expression, got keyword 'import'
	     embedded.84b2d0d3.js:1:297
GETXHR https://datatracker.ietf.org/group/groupmenu.json [HTTP/2.0 200 OK 0ms]

And the page is mostly blank with all elements disabled and spinning
icon in the middle with text saying "Loading meeting 115..."

Don't even get the tabs which would allow me to select "Plaintext"
version, but luckily I did remember the url...
-- 
***@***.***

**Comment by NGPixel** [comment]
That's the same error as #4247.

You'll be able to click the plain text version link from the loading screen in the new release being deployed today.
