### ISSUE TITLE
Setting a state for all positions at once

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#4681]
### Description

It would be nice to set (some?) states for all positions at the same time. I understand for "special elections" you need to tweak individual setting, but I think for the common case of "nominations are closed, feedback is open" the current scheme is a bit error-prone

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Currently the state of each position is shown on one page, and the ability to affect it is on another. The UI should be reworked to make it so that you can edit it where you see it, and to work on blocks of positions similar to how you can work on blocks of selected nominees.
