### ISSUE TITLE
link directly to page of proceedings

### ISSUE THREAD

**Issue by mcr** [ietf-tools/datatracker#4689]
### Description

"This page shows meetings within the last four years. For earlier meetings, please see the proceedings."

It would be great if this could actually link to the spot on ietf.org, where the proceedings *are*
I can't find them on the new site in the menus.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by russhousley** [comment]
I think you are asking for a link to https://www.ietf.org/how/meetings/past/ to be added to the light blue box at the bottom of the page.

**Comment by mcr** [comment]
Russ Housley ***@***.***> wrote:
    > I think you are asking for a link to
    > https://www.ietf.org/how/meetings/past/ to be added to the light blue
    > box at the bottom of the page.

If that's the canonical place to look for proceedings, then I guess so.
I wandered through ietf.org, looking for page that would give me links to all
the proceedings, and didn't find one.  I didn't think to look at the past
meetings page for some reason, thinking that there was a place for proceedings.

--
Michael Richardson ***@***.***>, Sandelman Software Works
 -= IPv6 IoT consulting =-
