### ISSUE TITLE
Save/restore meeting agenda filters

### ISSUE THREAD

**Issue by piersoh** [ietf-tools/datatracker#4692]
### Description

The new meeting agenda filters are handy but it's unclear how to keep a copy/export selected/filtered meetings if I want to view them in another window in another session? The Settings export only seems to export style type settings. For previous agendas one could add the items of interest to the `show` search arg which still works but now it seems to redirect and removes the args so there's now way to save them e.g. `https://datatracker.ietf.org/meeting/115/agenda?show=rmcat,maprg,quic,webtrans` 

It would be good to have a way to save/export the current filters - a simple approach could just be a url (containing set filters in the`show`/another args) copy/export?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Doesn't this "Share" button provide this?
<img width="403" alt="image" src="https://user-images.githubusercontent.com/10996692/200170432-7b5a4e47-adfe-43a5-bc5b-8d11b9e74109.png">

**Comment by piersoh** [comment]
Yes Thanks! (I just wasn't thinking 'share' for this but it hits the spot)
