### ISSUE TITLE
ietf links filter overmatches

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#4705]
From EKR:
![image](https://user-images.githubusercontent.com/10996692/200128592-07f10f62-6dd3-4130-ae33-0302afd6af4d.png)

The agenda parser seems to think that anything matching "RFC<ws>####" is an RFC, even if there is a line break, as in the thing above.

**Comment by larseggert** [comment]
We need to handle one line break, because we wordwrap some content and that can create one, but we shouldn't allow more than one. I'll make that change.
