### ISSUE TITLE
Where to find meetecho and other links when agenda is not working

### ISSUE THREAD

**Issue by kivinen** [ietf-tools/datatracker#4720]
### Describe the issue

As the agenda does not work on my browser, I am forced to use the text agenda, and I was trying to search the meetecho and notes links from somewhere else than from the agenda, but could not find them.

I do think there used to be links to them from the meeting materials page, but I think there were the recordings links, but cannot find even them now. We should have all links available somewhere from the working group page (or they might be there, but might be using feature of the javascript that does not work on my browser).

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kivinen** [comment]
It seems the ical entry does not have the links either. It would be useful to have those links in the calendar entry too...

**Comment by rjsparks** [comment]
See also #4722

**Comment by kivinen** [comment]
Robert Sparks writes:
> See also #4722

These two issues are not exactly related. The #4720 is about how to
find the meetecho links WHILE the IETF session is ongoing, i.e., when
you would normally use the agenda to find that link, but which does
not work on all browsers.

The #4722 is about finding links to old recordings, i.e., you want to
find the meetecho / youtube / audio recording of the LAMPS meeting at
IETF 106...

The links are not same, as current meetecho telechat link is different
than the link to the meetecho recording.

Other looks like https://www.meetecho.com/ietf114/recordings#IPSECME
the ongoing meetecho link is
https://meetings.conf.meetecho.com/ietf115/?group=ipsecme&short=&item=1
-- 
***@***.***

**Comment by rjsparks** [comment]
They are produced on the main agenda page (and had been before bs5 on the pages we're talking about) by a single view that produced one thing before the meeting passed, and another after it had. The fix for both tickets will be at the if not exactly _the_ same bit of code.

**Comment by rjsparks** [comment]
I'm going to split this into a separate ticket:
`It seems the ical entry does not have the links either. It would be useful to have those links in the calendar entry too...`

**Comment by kivinen** [comment]
It seems this was already fixed by the #4722 so this can be closed
