### ISSUE TITLE
Links to old meeting recordings are missing

### ISSUE THREAD

**Issue by kivinen** [ietf-tools/datatracker#4722]
### Describe the issue

I am pretty sure the meeting materials for the wg used to have links to the youtube and meetecho recordings. I.e. the page

https://datatracker.ietf.org/meeting/114/session/ipsecme

used to have links to them on the top right corner of the page. It also had links to the notes etc. I used them when making the presentations for the IEEE about what happened in the IETF, and those presentations always had links to the video recordings just in case someone wanted to go and check them later.

Now I do not seem to find them anywhere. Next IEEE session is on next week, and my presentation about the IETF-115 will be Thursday 17-Nov-2022 so it would be good to have links back before that (or I can probably guess the links based on the old links).

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Those links haven't been on that particular view. I had a PR (no longer viable, but i've left it open as documenting one way we might add them) at https://github.com/ietf-tools/datatracker/pull/3869.
The links are still on the main agenda page - while you are in the state that the page doesn't work for you, you could always ask the secretariat for them. For ipsecme at 114 they were
https://www.youtube.com/watch?v=vWrNIr0yyqI
https://www.meetecho.com/ietf114/recordings#IPSECME

**Comment by kivinen** [comment]
Robert Sparks writes:
> Those links haven't been on that particular view. I had a PR (no longer
> viable, but i've left it open as documenting one way we might add them) at #
> 3869.

They used to be there as you can see from the archive.org:

http://web.archive.org/web/20220515082442/https://datatracker.ietf.org/meeting/106/session/lamps

There is 4 buttons at the top right corner having tooltips for "Chat
logs", "Audio recording", "Video recording" and "Session recording".

If you go to the current view

https://datatracker.ietf.org/meeting/106/session/lamps

they are not there.

> The links are still on the main agenda page - while you are in the state that
> the page doesn't work for you, you could always ask the secretariat for them.
> For ipsecme at 114 they were
> https://www.youtube.com/watch?v=vWrNIr0yyqI
> https://www.meetecho.com/ietf114/recordings#IPSECME

As I said I cannot access the agenda page anymore as it does not work
for my browser, and I think the recordings should be in the same place
where the other meeting materials are, not in the agenda. If I am
interested in the recording of the lamps or some other working group,
I do not want to go to search agenda to see when it was, I want to go
to lamps datatraker page, and find them from there. 
-- 
***@***.***
