### ISSUE TITLE
Wrong generator for 3072-bit MODP Group in RFC 3526 

### ISSUE THREAD

**Issue by igorkrisyuk** [ietf-tools/datatracker#4726]
### Describe the issue

In RFC 3526 we have statement that 2 is a generator for 3072-bit MODP Group, but it's wrong because 2 ^ ((N - 1)/2) = 1 (mod N) where N is 2^3072 - 2^3008 - 1 + 2^64 * { [2^2942 pi] + 1690314 }. I think that correct value of generator for this group should be 5.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This should be submitted as errata.
See https://www.rfc-editor.org/errata.php
Submitting it will initiate a review process.
I'm closing this issue here as it is not a datatracker issue.
