### ISSUE TITLE
Join meetecho tool from meeting pages

### ISSUE THREAD

**Issue by aaronpk** [ietf-tools/datatracker#4738]
### Description

Would it be possible to get the link to join the in-room meeting tool from a WG's meeting page?

Currently it's faster for me to visit the WG page and navigate to meetings, rather than loading the ITF115 entire agenda and search for a particular group.

So when I'm looking at a page like https://datatracker.ietf.org/wg/oauth/meetings/ or even https://datatracker.ietf.org/meeting/115/session/oauth it would be great to have a link to join the meetecho tool.

This is particularly relevant when I'd like to join the meetecho tool from my computer while in a meeting room, since I don't have an easy way to scan the QR code on the screen into my computer, and there is no alternate link for the QR code visible on the screen to manually enter either.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
See also #1954, #2105, and #4722.
