### ISSUE TITLE
Add explanatory text when the IRSG ballot search finds no ballots

### ISSUE THREAD

**Issue by mirjak** [ietf-tools/datatracker#4749]
### Describe the issue

<img width="1412" alt="Screenshot 2022-11-11 at 12 14 34" src="https://user-images.githubusercontent.com/8420764/201329211-c679e749-177c-45c4-999a-e42edd0e33b3.png">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by mirjak** [comment]
okay, I guess I understand now that this means there is no document in IRSG review...? Would be useful to add a note saying "no document currently under review" and maybe also list most recent document or add another tap for that (or where do I find them?)

**Comment by rjsparks** [comment]
There is no place to look at all the closed IRSG (or IESG) ballots in the aggregate. You look at the ballots on individual documents.

**Comment by rjsparks** [comment]
Intended action:
> add a note saying "no document currently under review"
