### ISSUE TITLE
RFC 5477: wrong "Send notices to" value

### ISSUE THREAD

**Issue by bclaise** [ietf-tools/datatracker#4766]
### Describe the issue

Hi,

https://datatracker.ietf.org/doc/rfc5477/
Send notices to: @informatik.uni-erlangen.de

The above line is wrong.

Regards, Benoit

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
I just removed the malformed address
