### ISSUE TITLE
Security.txt: Timestamp format is not correct (anymore)

### ISSUE THREAD

**Issue by metters** [ietf-tools/datatracker#4780]
The [format of the example timestamp](https://datatracker.ietf.org/doc/html/draft-foudil-securitytxt-12#section-3.5.5) for the expires property of security.txt files is not correct anymore: `2021-12-31T18:37:07z`
The [official website](https://securitytxt.org/) states the format as `2021-12-31T18:37:07.000Z`. Also there is a Note there that warns about this change:
![Screenshot 2022-11-17 at 10 52 45](https://user-images.githubusercontent.com/9088722/202414330-feba91d5-1233-4689-8321-4c8e1ee1fd1b.png)

I checked the existing issues for "[timestamp](https://github.com/ietf-tools/datatracker/issues?q=is%3Aissue+is%3Aopen+timestamp)" and "[expires](https://github.com/ietf-tools/datatracker/issues?q=is%3Aissue+is%3Aopen+expires)", but I could not find anything about this change.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This isn't a bug with the datatracker software, but is rather a subject for an [errata report](https://www.rfc-editor.org/errata.php) against RFC 9116, which is what draft-foudil-securitytxt became.
I'm closing the issue here.

cc @rdanyliw
