### ISSUE TITLE
mediaman document list is not showing draft-ietf-mediaman-haptics

### ISSUE THREAD

**Issue by alvestrand** [ietf-tools/datatracker#4805]
### Describe the issue

The -haptics draft is not showing in the document list - despite the document management page showing that the patterns should detect 3 drafts and having tried to manually add it, it's not showing - only -toplevel and -suffixes show.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
FWIW, it shows up in my local dev instance, which is running the current tip of `main`. So maybe this is fixed already?
<img width="478" alt="Screenshot 2022-11-30 at 16 09 22" src="https://user-images.githubusercontent.com/200328/204804797-90d43522-3bc7-47d6-9424-622fd8a376c4.png">

**Comment by alvestrand** [comment]
The page with the bug says "[Version 9.1.0 (main - 9579f61)](https://github.com/ietf-tools/datatracker/releases/tag/9.1.0)"
![Selection_001](https://user-images.githubusercontent.com/480893/204808766-eeb16872-1d37-49de-b44d-d0379724fcd3.png)

**Comment by rjsparks** [comment]
The draft is not showing because it has been marked IESG state Dead in the production database. The History shows this happened likely as a side-effect of it being in AD is watching and then expiring. I'll contact the AD to have the IESG state adjusted.

**Comment by rjsparks** [comment]
I restored the AD is Watching state -  Murray can adjust it if needed when he's available next.
