### ISSUE TITLE
meeting/upcoming calendar shows cancelled sessions but doesn't label them cancelled

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#4815]
There's an argument for continuing to show cancelled sessions, but they should be clearly distinguished from sessions that actually intend to meet.

For a couple of days (until 6Dec), stir acts as an example.

**Comment by larseggert** [comment]
I think this is fixed? At least I tried it in my dev instance and there is a "cancelled" pill shown.

**Comment by rjsparks** [comment]
The issue is in the calendar view, not the table list.
This is fine (I cancelled an upcoming edm meeting in my test instance):
![image](https://user-images.githubusercontent.com/10996692/217601142-0bd58a0f-8fcc-4044-8dfc-34be089d9303.png)
This is not:
![image](https://user-images.githubusercontent.com/10996692/217601325-5c587a77-8c84-4780-a522-c13d4a4b0991.png)
