### ISSUE TITLE
Consistent use of terminology such as Internet-Draft and I-D

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/datatracker#4818]
### Describe the issue

Datatracker ought to be consistent with established style in using terms like “Internet-Draft” and “I-D”. This is pretty widely used but there are some places where it is not yet. A few examples:

a)  on the [Important Dates page](https://datatracker.ietf.org/meeting/important-dates/):

s/Internet Draft/Internet-Draft
s/for all drafts/for all I-Ds

b) In the Documents menu (screenshot attached):

s/Drafts/I-Ds

c) In the meeting proceedings page (e.g. https://datatracker.ietf.org/meeting/115/proceedings):

s/Drafts/I-Ds
(screenshot attached)

<img width="333" alt="image" src="https://user-images.githubusercontent.com/5347540/205115758-a27675f9-816e-4c09-ba95-6ebf0433ac47.png">

<img width="172" alt="image" src="https://user-images.githubusercontent.com/5347540/205114782-baa9d092-efd7-4f2a-97a9-f43132ee2cb6.png">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
@larseggert What's your reaction to removing the bare "Draft" word from the UI?

**Comment by larseggert** [comment]
Fine by me

**Comment by rjsparks** [comment]
Note that important dates is just an example - the issue is intended to cover the entire datatracker.
