### ISSUE TITLE
Can't remove email address.

### ISSUE THREAD

**Issue by karolzlot** [ietf-tools/datatracker#4827]
### Describe the issue

On https://datatracker.ietf.org/accounts/profile/  I can see:
```
Note: Email addresses cannot be deleted in this form, only deactivated.
```

I would like to completely remove one outdated email from your system.
Please let me know how can I do this.

Do I need to remove whole account? (is it even possible? how can I do it?)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
We intentionally do not support removing addresses, only deactivating them, particularly if they were ever involved in any interaction with drafts/email lists/etc - they are part of the public history of your contributions. If you have a special reason for removing an address send email to support@ietf.org explaining the situation. Please point to this issue in the message.
