### ISSUE TITLE
Improve validation for form that accepts pasted email feedback

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#4839]
### Describe the issue

When cut/pasting email feedback via the Chair Task "Enter email feedback" it *really* wants email headers.  I got an unknown server error.  When I hit BACK and then put a From and Subject line and a blank line as the first three lines of the text, it worked.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Yes, what's intended is that the _full raw message_ go in.

**Comment by richsalz** [comment]
I figured that out.  But maybe change the message to be "From: not found" or such.

**Comment by rjsparks** [comment]
Yes, the validation should let you know what happened rather than hand you a server crash.
