### ISSUE TITLE
Compare links for RFCs compare drafts

### ISSUE THREAD

**Issue by martinthomson** [ietf-tools/datatracker#4857]
### Describe the issue

On /doc/html/rfcXXXX the "Compare Versions" feature doesn't really produce what is expected for an RFC.  The comparison is between the last draft before publication and its immediate predecessor.

p.s., The new view on the datatracker for drafts and RFCs is excellent.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
I believe this is addressed by the changes that went into 9.4.0. Reopen if I'm wrong.
