### ISSUE TITLE
Logo on htmlization pages is not sized consistently

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#4865]
From @alicerusso

> Under 'RFC stream' at right, the IETF logo image is very large on
> https://datatracker.ietf.org/doc/html/rfc9130
> https://datatracker.ietf.org/doc/html/rfc9133
> 
> (seemingly intended to be smaller. as compared with the image on https://datatracker.ietf.org/doc/html/rfc9302 or https://datatracker.ietf.org/doc/html/rfc5234 for example)

**Comment by larseggert** [comment]
Note to self: Check if the HTML is malformed near the YANG validation.
