### ISSUE TITLE
Add "generate email" to action on nominees page

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#4893]
### Description

It can be useful to search through the nominees, pick a subset, and then generate an email list of those picked. For example, find all those who have submitted questionnaires and then click on those who have not been interviewed, generate an email list, so that you can cut/paste it into a mail message to remind them to sign up for an interview time.

Perhaps the list should have each entry end with a semicolon to make it easier to directly cut and paste it.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by richsalz** [comment]
And the block of addresses should be wrapped in `<pre>...</pre>` tags.

**Comment by richsalz** [comment]
I think a downloaded list, *without mailto:* is probably better.  mailto doesn't easily support a single mail to multiple people.  I often wanted to send "hey folks, if you're on the CC list you didn't complete your questionnaire"  That's the workflow.

**Comment by rjsparks** [comment]
Where have you seen trouble with mailto supporting multiple mail recipients? I've build those all the time. You can even tell it to put things in cc.

**Comment by richsalz** [comment]
"Never mind"  Brain f--t.
