### ISSUE TITLE
Format tweak to "extract mail lists"

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#4894]
### Description

Once #4893 is done, I am not so sure if this pull-down option in the Chair tasks should be removed.

If it is kept, then I think the lists that are generated should be wrapped in `<pre>...</pre>` tags, and each line should be terminated with a  semicolon for easier cut/paste.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
I'm still not sure cut-paste to get a list is the best thing to do. Wouldn't downloads be better?

**Comment by richsalz** [comment]
Yes, downloads would be better.  I was stuck in thinking how I had done things.

**Comment by richsalz** [comment]
Done as part of fixing #4893; closing this.
