### ISSUE TITLE
htmlized view of last revision before an RFC has broken version links

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#4898]
See https://datatracker.ietf.org/doc/html/draft-carpenter-eligibility-expand-10
and note that all of the version buttons under "Select version" point to
https://datatracker.ietf.org/doc/html/draft-carpenter-eligibility-expand
rather than something with an explicit version.

At the view of the rfc, or any version _other_ than -10, the links are versioned.

**Comment by larseggert** [comment]
This is fixed now.
