### ISSUE TITLE
IESG telechat agenda: Also add a ZIP file of the the same documents in pdf form (for kindle readers, etc.)

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#490]
`keyword_imported` `keyword_sprint` `type_enhancement`   |    by 

___

Also add a ZIP file of the the same documents in pdf form (for kindle readers, etc.)

___
_Issue migrated from trac:490 at 2022-03-04 01:35:45 +0000_

**Comment by rjsparks** [comment]
This ticket is extremely old and the pressure for the contents have changed. I'm closing this as being covered by #4081
