### ISSUE TITLE
(X)HTML format for RFC documents is not Well-Formed 

### ISSUE THREAD

**Issue by cmplstofB** [ietf-tools/datatracker#4900]
### Describe the issue

The HTML format for RFC documents is declared as XHTML 1.0.

```xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
[...]
```

but in 14th line for every RFCs, the `<meta>` element does not have the close tag.

```xhtml
      <meta name="citation_technical_report_number" content="rfc5147">
                                                           Here -----^
```

I think this code should be modified as below.

```diff
-      <meta name="citation_technical_report_number" content="rfc5147">
+      <meta name="citation_technical_report_number" content="rfc5147"/>
```

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This is a well-known argument in the HTML space. We will follow the HTML spec. I think you are wanting to argue with that rather than this implementation.

**Comment by cmplstofB** [comment]
You seem to be confusing HTML and XHTML.

Certainly, in HTML 4.01, where the grammar is defined as SFGML compatible, and in HTML5, where special lexical interpretation is defined by HTML Living Standards, the part I pointed out is acceptable. However, since the IETF publishes the documents as XHTML, the format that is not well-formed XML is clearly incorrect.

In other words, this issue is not a discussion about the HTML specification, but an error report in the XHTML document published by the IETF.

**Comment by rjsparks** [comment]
(This isn't really a datatracker issue, but we'll keep the discussion here for the moment.)

The RPC pointed out to me that this is part the html rendering of pre v3 RFCs. See anything past RFC8650 for what modern treatment looks like. There is a conversation about whether to change the pre-8650 html renderings underway.

**Comment by rjsparks** [comment]
As noted in the reference above, the htmlization rendering of pre v3 RFCs at the rfc-editor site will change to close the tag.
