### ISSUE TITLE
Unable to see old versions of documents in htmlized view

### ISSUE THREAD

**Issue by j-schoeff** [ietf-tools/datatracker#4936]
### Describe the issue

Its seems the htmlized page loads the url of old versions, but displays only the newest version, this is misleading and frustrating to deal with. I also find it strange that the compare versions dropdown shows older versions, but the version selector does not. Basically, you can only use htmlized for current docs and must use rfc-editor to see older versions?

However, not all docs have a html link with rfc-editor. For example, this SFTP draft does not (assuming because its not an RFC): https://datatracker.ietf.org/doc/draft-ietf-secsh-filexfer. This forces the plaintext versions which is sad.

Expectation: If i have a link to an older version, i want to read the older version. If i am viewing a newer version, i'd like the version selector to provide older version options.

Examples:

https://datatracker.ietf.org/doc/html/draft-ietf-smime-rfc2633bis-05 actually loads https://datatracker.ietf.org/doc/html/rfc3851

https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02 actually loads https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-13

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Both of these links reflect issues in the data from the original import from the IESG tracker to the datatracker (decades ago). Correcting them will require synthesizing event data that we don't currently have. These are specific instances of the general problem pointed to by #4933.

**Comment by rjsparks** [comment]
I'm going to close this issue as a duplicae of #4933.
