### ISSUE TITLE
Meaningless citation counts

### ISSUE THREAD

**Issue by becarpenter** [ietf-tools/datatracker#4938]
### Describe the issue

Please see https://datatracker.ietf.org/stats/document/author/citations/?type=rfc
What is the source of the citation counts? At the very least it should be documented. If it's supposed to be RFCs-citing-RFCs the numbers are wrong (especially for Scott Bradner, even though RFC2119 is a great success). For my own data, the correct value is ~654 and the value displayed is 2106. This apparently includes duplicate citations from drafts, so is a completely meaningless number. 
As a result the H-index values are presumably meaningless. (They are probably meaningless anyway, since even if correct for RFCs-citing-RFCs, they don't cover citations by non-RFC publications. Again, this needs to be documented.)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
It needs to be reimplemented - what's there is not accurate and is an attractive nuisance.

See https://github.com/ietf-tools/datatracker/issues/3712 (this ticket will become part of that set addressed during that reimplementation.

**Comment by rjsparks** [comment]
I'm going to close this one as duplicate
