### ISSUE TITLE
side bar datatracker package pretends to lead to versioned drafts but does not

### ISSUE THREAD

**Issue by paulwouters** [ietf-tools/datatracker#4944]
### Describe the issue

For example, both

https://datatracker.ietf.org/doc/html/draft-davies-int-historic-04

and

https://datatracker.ietf.org/doc/html/draft-davies-int-historic-05

have a link in the top right side bar claiming to be versioned, but instead both go to the same main document page (which is good, it should just not mislead people with the version in the link name )

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Is it the right thing to do to change the link to just say draft-davies-int-historic, or to change the href for the links to include the version (e.g. https://datatracker.ietf.org/doc/draft-davies-int-historic/04)?

**Comment by paulwouters** [comment]
I would say without version ? Since that is what the link will end up at. But perhaps in the grander scheme of thing, it shouldn't just be a link with the draftname, because it is going to the datatracker main page for the doc, not the doc txt/html itself ? Which is what I originally thought when this layout first appeared (and I couldn't find a link to the datatracker for the doc)

**Comment by rjsparks** [comment]
@lars - do you see paul's confusion with the interface (it's more than just whether the link is versioned...)

**Comment by larseggert** [comment]
@paulwouters would something like this be better?
<img width="286" alt="Screenshot 2023-01-11 at 15 05 11" src="https://user-images.githubusercontent.com/200328/211813614-13588842-65bd-454a-812c-21f30bd6cc79.png">

**Comment by paulwouters** [comment]
Yes that would be better in my opinion and solve the two problems at once. No wrong link AND a clear button to the datatracker.Sent using a virtual keyboard on a phoneOn Jan 11, 2023, at 08:05, Lars Eggert ***@***.***> wrote:﻿
@paulwouters would something like this be better?
