### ISSUE TITLE
Additional Resources field missing from datatracker listing for drafts

### ISSUE THREAD

**Issue by eckelcu** [ietf-tools/datatracker#4948]
### Describe the issue

Previously it was possible to view and edit the "Additional Resources" for a draft or RFC. This field is no longer being displayed when a draft is viewed in the datatracker. An example is https://datatracker.ietf.org/doc/draft-eckel-edm-find-code/. Both a GitHub repository for the draft and an example implementation are specified as Additional Resources, but this information is not displayed.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
I think this may have been broken at #4825.

If you have one handy, could you also point to a draft that hasn't expired?

cc: @larseggert

**Comment by eckelcu** [comment]
https://datatracker.ietf.org/doc/draft-ietf-opsawg-ipfix-srv6-srh/ is an example of a draft that has not expired and has Additional Resource that are not being displayed.

**Comment by eckelcu** [comment]
Thanks for addressing this so quickly. Additional Resources field is working as expected for me again.
