### ISSUE TITLE
Potential new `datetime` issues

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#4976]
### Describe the issue

See CI failures
* https://github.com/ietf-tools/datatracker/actions/runs/3899998769/jobs/6660186805
* https://github.com/ietf-tools/datatracker/actions/runs/3900011570/jobs/6660211516

There is also this one, which is different but possibly related:
* https://github.com/ietf-tools/datatracker/actions/runs/3900217767/jobs/6660629415

CC @jennifer-richards 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
I didn't encounter these during the recent release builds - are they transient or OBE?

**Comment by larseggert** [comment]
Men neither. Transient.

**Comment by jennifer-richards** [comment]
I think it's probably real, the test is using a UTC date to compare with the deadline computed in `DEADLINE_TZINFO` (still PST8PDT). I'd have thought there was enough fuzz in the comparison, but it's easier to fix this than think super hard about that. Will do that now.
