### ISSUE TITLE
Download questionnaire responses

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#4981]
### Description

The questionnaire responses, filed in the feedback section, are often sent to the confirming body. It would be convenient to have a "download to file" button. This would address 8bit chars in content, too.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by pselkirk** [comment]
@richsalz Could you elaborate on what you're looking for? It sounds like you just want to cut and paste the feedback into an email message.

**Comment by rjsparks** [comment]
I'll answer for Rich:

These questionnaires are long documents that people standing for a position fill out. When sent to confirming bodies, the body is often getting _several_ of these (all of the ADs that a nomcom selects go to the IAB for confirmation for example - see https://www.rfc-editor.org/rfc/rfc8713.html#name-candidate-review for more detail).

This is more data than should go through a cut-paste process - the confirming body would rather get these as attachments to one or more email messages, or via some non-email transfer path where "file" is still a better model than "paste buffer".

**Comment by richsalz** [comment]
Yes.  Even though last year I only offered to make the questionnaires available if anyone asked, and nobody asked.
