### ISSUE TITLE
Broken time record for https://datatracker.ietf.org/doc/draft-jaeggli-interim-observations/

### ISSUE THREAD

**Issue by mirjak** [ietf-tools/datatracker#5007]
### Describe the issue

This draft is expired since 2013 but the datatracker metadata say last updated on "2016-02-25 (Latest revision 2013-01-14)"...? In any case this draft in not indicated as expired in the datatracker. Seems like a bug...

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
The Last Updated date is not wrong.

See https://datatracker.ietf.org/doc/draft-jaeggli-interim-observations/history/

The last time the state on the document changed _WAS_ 2016-02-25 and that is what the updated field shows - when the metadata is updated, not when any new revision was issued.

The draft's normal expiration time passed while the document was in the independent stream. Documents there are protected from expiration. (More specifically, its the rfc-rev state - see the very old https://github.com/ietf-tools/datatracker/issues/1654).

I'll raise clearing the document's tags and expiring it with the secretariat.

**Comment by rjsparks** [comment]
Using the admin and the shell, I manually removed the rfc editor review tag and expired this particular draft.
These actions need to be scripted and generally applied to all stale docs affected #1654.
