### ISSUE TITLE
Proceedings ignores "notmeet" irtf sessions

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#5010]
### Describe the issue

PR #5005 inadvertently changed the handling of irtf sessions set as 'notmeet'. These are no longer shown on the proceedings. They are left off whether or not they have materials attached to them. Previously, the 'notmeet' flag was ignored for irtf sessions.

For IETF-115, this results in anrw and qirg not being listed on the proceedings.

Need to decide how to display these sessions (and whether they should be included in the first place).

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
@csperkins - preference?

**Comment by csperkins** [comment]
Research groups should appear in the proceedings listed as "did not meet" if they did not meet at a particular IETF. Research area groups (i.e., ANRW and IRTFOPEN, which I think are labelled differently in the datatracker) should not appear in the proceedings if they don't meet.
