### ISSUE TITLE
Problems with adding new e-mail address to the existing account

### ISSUE THREAD

**Issue by kszarkowicz** [ietf-tools/datatracker#5033]
### Describe the issue

After logging to datatracker with kszarkowicz@gmail.com, I am trying to add a new e-mail address (kszarkowicz@juniper.net) to the existing account kszarkowicz@gmail.com. However, I get following error message:

"Email address 'kszarkowicz@juniper.net' is already assigned to account 'None' (Krzysztof Szarkowicz)"

After logging out from datatracker, and trying to restore datatracker password of kszarkowicz@juniper.net, I get following message:

"Didn't find a matching account. If you don't have an account yet, you can create one."

So,  the account kszarkowicz@juniper.net doesn't exist in datatracker, but I am not able to add kszarkowicz@juniper.net e-mail address to the kszarkowicz@gmail.com datatracker account.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Try again please - adjustments have been made. If you still have issues, please send email to support@ietf.org with the details.
