### ISSUE TITLE
The "Mark as action taken" button not working - liaison 

### ISSUE THREAD

**Issue by jennybui1** [ietf-tools/datatracker#5042]
### Describe the issue

Hi, 

We received a ticket from Scott Mansfield that mentions that the "Mark as action taken" button on this liaison: https://datatracker.ietf.org/liaison/1798/ does not appear to do anything. I have also tried clicking on the button and it doesn't appear to work, also tried in Sandbox and nothing happened. 

Thanks,
Jenny 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennybui1** [comment]
Hi Tools Team,

Happy Friday! 

Scott Mansfield mentioned that nothing appeared to happen when he clicked on the “Mark as action taken”, but it does work me now when I click on it. 

Jenny

**Comment by rjsparks** [comment]
Hi Jenny - this was deployed last Tuesday. I'll reach out to Scott to see why he's still having trouble.
