### ISSUE TITLE
500 error from Mailman when attempting to unsubscribe

### ISSUE THREAD

**Issue by cindymorgan** [ietf-tools/datatracker#5056]
### Describe the issue

When users enter an email address into the "unsubscribe or edit options" field on a Mailman listinfo page (e.g. https://www.ietf.org/mailman/listinfo/moq) and the address isn't actually subscribed to the list, it returns a 500 internal server error. Is there a way to get this to be a more helpful error message that lets them know that the email address they are trying wasn't found?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This isn't a datatracker issue. We'll look to see if there's something we've done to the mailman install that causes this. But if it's a bug in the mailman2 code, we're not going to fork to fix that - rather it will be a bug that goes away when we move to mailman3.
