### ISSUE TITLE
Unable to get to historical internet-drafts from htmlized view of an RFC

### ISSUE THREAD

**Issue by jhaas-pfrc** [ietf-tools/datatracker#5062]
### Describe the issue

Pick your favorite RFC. (Mine's RFC 4271.)
From the datatracker view for the RFC, you can see the timeline for the prior issues of the draft prior to RFC.  Pick one.
Select the htmlized view.
Rather than get the prior views, you get the RFC 4271 text and a selector box for the last version of the draft, -26.
You're unable to get to prior revisions of the document.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
Same as #4933 I believe.

**Comment by rjsparks** [comment]
Yes. 4271 only has DocHistory for 05. Will close this as duplicate. (The above comment links this to 4933 already).
