### ISSUE TITLE
I-D PDFs have "Updates:", "Obsoletes:", and "Authors:" printed vertically in header

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/datatracker#5073]
### Describe the issue

The headers of multiple I-D PDFs have the labels "Obsoletes:", "Updates:", and "Authors:" printed one letter per line. Examples include the PDFs of documents on the [IESG Telechat agenda](https://datatracker.ietf.org/iesg/agenda/). In particular, https://datatracker.ietf.org/doc/pdf/draft-ietf-elegy-rfc8989bis-04:

```
Workgroup: ELEGY
Internet-Draft: draft-ietf-elegy-rfc8989bis-04
O          8989 (if approved)
        b
        s
        o
        l
        e
        t
        e
        s
        :
U      8713 (if approved)
     p
     d
     a
     t
     e
     s
     :
 Published: 25 January 2023
Intended Status: Best Current Practice
Expires: 29 July 2023
A     M. Duke
     uGoogle LLC
     t
     h
     o
     r
     s
     :
```

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
CC @martinthomson

**Comment by martinthomson** [comment]
I will provide some hints.  These labels use CSS "content" rules in a `::before` pseudo-element.  These are drawn into a block that has a negative margin.  The renderer clearly thinks that the subsequent characters need to be drawn on successive lines.

My guess is that these are an interaction between the above, the lack of an explicit width on the element (which might lead to it being sized as zero width) and the introduction of the `overflow-wrap: break-word` rule (@larseggert will know what this is for).  One of two options might be worth investigating:

* Add an explicit width for each of these elements.  Each would require its own special width.
* Disable the `overflow-wrap` rule for `dd::before`.
