### ISSUE TITLE
The layout of the graph within the draft in HTML/PDF version is not right

### ISSUE THREAD

**Issue by AijunWang** [ietf-tools/datatracker#5079]
### Describe the issue

In the newest version of HTM/PDF layout of the internet draft, the graph is wrapped around automatically, and let almost every graph can't be easily viewed by the reader.
Can you fix it, or add horizon scroll bar to improve the overview of the draft.

you can check the problem in the "Table of Contents" part of  https://datatracker.ietf.org/doc/html/draft-wang-tcpm-tcp-service-affinity-option, and Figure 1 in the introduction part of the same draft.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
I see the issue, but I can't reproduce it in my development instance - the PDF looks fine there. @rjsparks, any ideas?

**Comment by rjsparks** [comment]
Maybe the differences are in the fonts weasyprint is finding on ietfa vs the dev instances? Note that the header is wrapped badly in the pdfized text cached at the datatracker.

**Comment by rjsparks** [comment]
The datatracker generated pdfs are using Liberation-Mono - the dev instance generated pdfs are using DejaVu-Sans-Mono

**Comment by larseggert** [comment]
That is probably it. We should standardize on fonts asap.

**Comment by AijunWang** [comment]
Is it solved?

When I review https://datatracker.ietf.org/doc/html/draft-ietf-idr-vpn-prefix-orf-00, the problem still exists.

How can I review it in correct format?

 

Best Regards

 

Aijun Wang

China Telecom

**Comment by larseggert** [comment]
The fix hasn't been deployed yet.
