### ISSUE TITLE
width settin in .rfcmarkup pre causes unnecessary line wraps making the document difficult to read

### ISSUE THREAD

**Issue by Renlor** [ietf-tools/datatracker#5087]
### Describe the issue

The following style block causes rfcs to be unnecessarily line wrapped on Firefox, possibly other browsers, making the document difficult to read.

```css
rfcmarkup pre {
  width: 72ch;
  white-space: pre-wrap;
}
```
Removing the width  property or setting it to a higher value like `87ch` resolves the issue.

Here is one page with the issue: https://datatracker.ietf.org/doc/html/rfc5759

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
I wonder if this is related to #5073. Could you send a screenshot? I can't reproduce locally with FF.

**Comment by Renlor** [comment]
Hope it helps:
![Screenshot from 2023-02-06 21-04-45](https://user-images.githubusercontent.com/22872623/217145633-6a8bdddf-a422-4174-97e2-bb02b4d458a2.png)

**Comment by larseggert** [comment]
Do you override the site's font choices in your browser?

**Comment by Renlor** [comment]
No.  I am using whatever firefox has decided to use for the page based on what the page asks for and what is available on my system.  Maybe it is looking for fonts that aren't installed by default on my OS?  I am running PoP-OS (effectively Ubuntu 22.10).

If it's an issue with the layout not working with the particular font that happened to be chosen by the browser here, it seems like the layout should be font agnostic (at least as much as is reasonable) for usability reasons, milder forms of dyslexia being an example.

**Comment by Renlor** [comment]
![Screenshot from 2023-02-07 05-47-09](https://user-images.githubusercontent.com/22872623/217249326-deb28fe3-b33c-4d19-9ed6-4d94daaafea7.png)

**Comment by larseggert** [comment]
Yes it should be font-agnostic, but I'm at the moment just trying to find a way to reproduce it. (The UI font looked unusual, hence my question about custom fonts...)

**Comment by larseggert** [comment]
@Renlor is this still happening?

**Comment by rjsparks** [comment]
@Renior - nudge?

**Comment by rjsparks** [comment]
sure
