### ISSUE TITLE
the changed_state docevent should have WG name perhaps

### ISSUE THREAD

**Issue by moonshiner** [ietf-tools/datatracker#5090]
### Description

the docevent API captures the change of state when a WG does a CfA and/or Adopts or not.  But the WG is not captured clearly.

I understand not all changed_state events have WGs, and this would involve extending the schema.

So definitely and RFE and a low priority. 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Walk from docevent to doc to group.

**Comment by rjsparks** [comment]
@moonshiner - is the above sufficient to close this?

**Comment by moonshiner** [comment]
Works for me!
