### ISSUE TITLE
How do I kill a chartering effort?

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#5153]
### Describe the issue

See https://datatracker.ietf.org/doc/charter-ietf-term/

I set the charter document state to "Not currently under review" and the WG state to "Abandoned", but it is still showing up on https://datatracker.ietf.org/doc/ad/lars.eggert

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Cindy found an older closed related issue at #2889.

I suspect we need to filter this in the logic for the /doc/ad/ view.
