### ISSUE TITLE
Wording change on /secr/sreq

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#5163]
### Description

Requested by @flynnliz, please change, "You should not include the Area Directors; they will be added automatically," to something like, "You should not include your Area Director; the tool accounts for their conflicts separately," to avoid giving the impression that the AD's name will actually appear in the field.

People seem to add the AD anyway. Would be nice to prevent this because even the rephrasing may not discourage it enough.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by cabo** [comment]
(Don't accept data you don't want to process...)

**Comment by rjsparks** [comment]
See #3890
