### ISSUE TITLE
Typo in draft-ietf-openpgp-crypto-refresh

### ISSUE THREAD

**Issue by e-rossman** [ietf-tools/datatracker#5164]
### Describe the issue

Following Table 19: Public-key algorithm registry

The paragraph reads
Implementations MUST implement **EdDSA** (19) for signatures, ...
but should read
Implementations MUST implement **ECDSA** (19) for signatures, ...

EdDSA is 22, ECDSA is 19

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This isn't a bug in the datatracker software. It's more appropriately reported to the openpgp working group or the document authors. Those email addresses are on the document page at https://datatracker.ietf.org/doc/draft-ietf-openpgp-crypto-refresh/.

**Comment by rjsparks** [comment]
See https://gitlab.com/openpgp-wg/rfc4880bis/-/merge_requests/237
