### ISSUE TITLE
During submission, draft HTML is stale from an older upload attempt

### ISSUE THREAD

**Issue by chrysn** [ietf-tools/datatracker#5171]
### Describe the issue

I just submitted a draft manually, reviewed its HTML, found a bad wording, cancelled, produced a new XML file and uploaded it. When checking the HTML again, I found that it still contained the old wording, while the XML I could download was already the new one.

I haven't clicked "Post Submission" yet to facilitate debug information retrieval from the live instance:

* The submission is for  draft-amsuess-core-pd-body-error-position-01
* Submission URI is https://datatracker.ietf.org/submit/status/131618/
* The XML is at https://www.ietf.org/staging/draft-amsuess-core-pd-body-error-position-01.xml
* The HTML is at https://www.ietf.org/staging/draft-amsuess-core-pd-body-error-position-01.html
* The difference between the XML and the HTML can be spotted when grepping for "or, where possible," -- this is present in the XML, while the HTML still says "place, where possible"

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
Both your XML and HTML links contain "or, where possible" for me now. I think you were running into a stale cloudflare cache of the HTML. Can you check whether it looks correct for you now?

**Comment by chrysn** [comment]
Both links indeed converged on the new version.

A caching issue with a third party load balncing service that disregards
cache control is a plausible explanation would be consistent with the
observed behavior.

**Comment by rjsparks** [comment]
We need to rework how submission staging is done anyhow - the better solution would have you accessing the datatracker for a specific view, not the website. In the meantime we can adjust the website's caching rules for that URL tree.

**Comment by NGPixel** [comment]
URLs starting with `/staging/` now have its cache bypassed.
