### ISSUE TITLE
Remove confusing information from the status tag for published RFCs 

### ISSUE THREAD

**Issue by emanjon** [ietf-tools/datatracker#5177]
### Description

Hi,

When suggestion that 3GPP should use RFC 9310 a comment was that the status page states "Incomplete, due 2022-10-27"

https://datatracker.ietf.org/doc/rfc9310/

Looking at the DataTracker status page for RFC 9310 there are several things that can be confusing for people not familiar with the IETF process.

IANA OK - Actions Needed
Submitted to IESG for Publication
Incomplete, due 2022-10-27
Ready with Nits
Ready with Issues 

I think it would be good if this kind of historical information was moved to another tab for published RFCs. Otherwise it is very easy for people and other SDOs to believe that the document is still being worked on.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This will get addressed at the latest when we make RFCs first-class document objects (instead of being a pseudo-version of an Internet-Draft). But in the meantime, we can look at not displaying some of the not-relevant-to-the-RFC items when viewing an RFC.

**Comment by rjsparks** [comment]
This has been addressed on the feat/rfc branch - the draft process related things are not shown when viewing the RFC - but they are still available when looking at specific revisions of the draft.

I'm closing this now, but it you won't see the changes in production until feat/rfc is merged and released.
