### ISSUE TITLE
Change "report a bug" button in htmlized view

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#5191]
### Description

Per IESG discussion, this makes people think they should use it to file issues with doc content.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Wasn't this addressed in #5193 ?

**Comment by larseggert** [comment]
Yes.
