### ISSUE TITLE
order_number is not computed for sessions on group meetings view

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#5208]
### Describe the issue

Group meetings views (`/group/<acronym>/meetings/`) are hitting server errors trying to render meetecho links. This is happening because the template for the meetecho URL includes `session.order_number`. Need to add this attribute to the sessions.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Fixed in #5209
