### ISSUE TITLE
Andy19 

### ISSUE THREAD

**Issue by Apdlrcjafg19** [ietf-tools/datatracker#5213]
### Description

Página 9]

[RFC 62](https://www.rfc-editor.org/rfc/rfc62)                   IPC para compartir recursos 3 de agosto de 1970

                        SITIO K SITIO L

                        ______ ______
                       / \ / \
                      / \ / \
                     / \ / \
                    / \ / \
                   | | | |
                   | Proceso A | | Proceso B |
                   | | | |
                    \ / \ /
                     \/ RECIBIR--> puerto M/
                      \ / CUALQUIER \ /
                       \______/ \______/

   El proceso A, afortunadamente, sabe de la existencia del puerto M en el sitio L y
   envía un mensaje utilizando la operación SEND FROM ANY del puerto N al puerto
   M. El mensaje contiene dos números de puerto e instrucciones para el proceso
   B para ENVIAR mensajes para el proceso A al puerto P desde el puerto Q. El sitio del sitio K
   El número se adjunta a este mensaje junto con el puerto SEND N del mensaje.

                        SITIO K SITIO L

                        ______ ______
                       / \ / \
                      / \ / \
                     / \ / \
                    / \ / \
                   | | | |
                   | Proceso A | | Proceso B |
                   | | | |
                    \ puerto N / \ puerto M /
                     \ /--->ENVIAR DESDE --->\ /
                      \ / CUALQUIER \ /
                       \______/ \______/

                                   al puerto M, sitio L

                                   que contiene K, N, P y Q

   El proceso A ahora ejecuta un RECIBO en el puerto P desde el puerto Q. Proceso A
   especifica que el sitio de encuentro es el sitio L.

Walden [Página 10]

[RFC 62](https://www.rfc-editor.org/rfc/rfc62)                   IPC para compartir recursos 3 de agosto de 1970

                        SITIO K SITIO L

                        ______ ______
                       / \ / \
                      / \ / \
                     / \ Cita / \
                    / \ mesa \
                   | | | |
                   | Proceso A | ^ | Proceso B |
                   | | | | |
                    \ puerto P / | \ /
                     \ / | \ /
                      \ / <--RECIBIR __/ \ /
                       \______/ MENSAJE \______/

                                    al sitio L

                                    que contiene P, Q y K

   Se envía un mensaje RECIBIR desde el sitio K al sitio L y se ingresa en el
   mesa de encuentro en el sitio L. En algún otro momento, el proceso B ejecuta un
   ENVIAR al puerto P desde el puerto Q especificando el sitio L como el sitio de encuentro.

                        SITIO K SITIO L

                        ______ ______
                       / \ / \
                      / \ / \
                     / \ Cita / \
                    / \ mesa \
                   | | | |
                   | Proceso A | | Proceso B |
                   | | | |
                    \ puerto P / <--------- puerto Q /
                     \ / \ /
                      \ / ENVIAR \ /
                       \______/ \______/
                                        al sitio L

                                        que contiene P & Q

   Se hace una cita, se limpia la mesa de la cita y se
   tiene lugar la transmisión al puerto P en el sitio K. El número del sitio ENVIAR
   (y posiblemente el número de puerto SEND) se adjunta a los mensajes de
   la transmisión para la edificación del proceso de recepción.

Walden [Página 11]

[RFC 62](https://www.rfc-editor.org/rfc/rfc62)                   IPC para compartir recursos 3 de agosto de 1970

                        SITIO K SITIO L

                        ______ ______
                       / \ / \
                      / \ / \
                     / \ / \
                    / \ / \
                   | | | |
                   | Proceso A | | Proceso B |
                   | | | |
                    \ puerto P / \ puerto Q /
                     \ /<--transmisión<--\ /
                      \ / \ /
                       \______/ al puerto P, sitio K \______/

                                  que contiene datos y L

   El proceso B puede querer ejecutar simultáneamente un RECEIVE desde el puerto N en
   puerto m

   Tenga en cuenta que solo hay un mensaje de control importante en este sistema
   que se mueve entre sitios, el tipo de mensaje que se llama
   Host/Mensaje de protocolo Host en [2]. Este mensaje de control es el
   RECIBIR mensaje. Hay otros dos posibles controles entre sitios
   mensajes: un mensaje de error para el sitio de origen cuando un mensaje RECEIVE o
   ENVIAR ha expirado y el mensaje ENVIAR en el raro caso en que el
   El sitio de encuentro no es el sitio de ENVÍO. También debe haber un estándar
   formato para mensajes entre puertos. Por ejemplo, lo siguiente:

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This isn't the forum for discussing changes to the content of RFCs. See www.rfc-editor.org for reporting errata, or contact the IESG for assistance in finding the appropriate discussion venue.
