### ISSUE TITLE
Document Search: Add RFC-Editor's Queue status field

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#527]
`keyword_sprint` `type_enhancement`   |    by turners@ieca.com

___

It would be interesting if you could add an additional advanced search 
option for RFC editor queue status: EDIT, AUTH48, RFC-EDITOR, etc.

___
_Issue migrated from trac:527 at 2022-03-04 01:38:26 +0000_

**Comment by rjsparks** [comment]
closing this as stale. The idea is already fed into requirements for search in the upcoming rpc tool modernization work, and in having a global search function.
