### ISSUE TITLE
Upload fails

### ISSUE THREAD

**Issue by GregMirsky** [ietf-tools/datatracker#5292]
### Describe the issue

Upload fails with the following:
![image](https://user-images.githubusercontent.com/8866056/224193956-173c58dd-0842-4404-8a1a-4072f9a7f4fb.png)
Could it be a problem with my file? I cannot see any, it's a regular XML. Earlier versions of the draft that I successfully upload before fail with the same response.
Thank you for your help.

Regards,
Greg

PS. Ping me to get the XML file.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Hi Greg - I replied on tools discuss already at https://mailarchive.ietf.org/arch/msg/tools-discuss/5Fxt3ym_LZuKetazR0W7cb0nqZc

The essence was this:
There's an issue with libmagic in the production deployment. Here's a workaround:


If you change your XML start line from

`<?xml version="1.0" encoding="utf-8"?>`

to

`<?xml version='1.0' encoding='utf-8'?>`

the post will succeed.

**Comment by rjsparks** [comment]
The draft is posted

**Comment by GregMirsky** [comment]
Much appreciate your help, Robert.

Regards,
Greg
