### ISSUE TITLE
Plaintextify the HTML introduces spurious asterisk bullets for some lists

### ISSUE THREAD

**Issue by jgscudder** [ietf-tools/datatracker#5293]
### Describe the issue

I noticed that the "Plaintextify the HTML" rendering for at least one list in draft-ietf-idr-long-lived-gr-04 (Section 3.1) inserts spurious asterisk bullets. "HTMLize the plaintext" is fine, so is txt of course, and so is native HTML. PDF is broken in the same way as the Plaintextify rendering, I assume the one is used to produce the other.

(04 is where I noticed it, but when I look back at 01 which is the first version for which there is a native HTML rendering, unsurprisingly the artifact is there too.)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
CC @martinthomson

**Comment by martinthomson** [comment]
For reference: https://datatracker.ietf.org/doc/html/draft-ietf-idr-long-lived-gr-04#section-3.1-4

Already fixed upstream at https://github.com/martinthomson/rfc-txt-html/blob/2b0a8173ac8d262e72aa242db00dc211d8c05547/txt.css#L219-L221 (other related rules change as well).

**Comment by martinthomson** [comment]
BTW, that section of that draft has a very strange layout.  I don't know whether this is down to the draft itself or what xml2rfc does with it, but it looks like the line spacing is wide at the start of the section, but the last point "Long-lived Stale Time" has no spacing at all.  (Given the contortions here, I'm pretty chuffed that the styling--other than the bug mentioned--is perfectly consistent with the text output.)

**Comment by martinthomson** [comment]
@jgscudder you might be able to use a [definition list](https://www.ietf.org/archive/id/draft-irse-draft-irse-xml2rfcv3-implemented-03.html#name-dl) to alleviate some of the problems, though I suspect that the figure will continue to be a nuisance.  Using vspace might use make things worse.  Of course, RFCEd experts will likely be able to help.

**Comment by Variousqwrw** [comment]
Круто
