### ISSUE TITLE
/doc/html replaced drafts

### ISSUE THREAD

**Issue by martinthomson** [ietf-tools/datatracker#5344]
### Description

A replaced draft on /doc shows what it was replaced with.

A draft that replaces another shows what it replaced on /doc/html.  That is fine, though it only does so via the "Compare versions" feature.

A draft that has been replaced does not show what replaced it anywhere on /doc/html.

It seems like this might be a useful feature when looking at a draft, especially for drafts that have been adopted, where you might want to see the latest.

Story: I was trying to find my way from https://datatracker.ietf.org/doc/html/draft-xu-risav to the latest version.  I ended up going to GitHub (which the draft conveniently links) to find what replaced the draft (though the /doc link might have been faster).

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
The issue seems to be that `interesting_doc_relations` when called with a `DocHistory` doesn't find these relationships, but I need some clue from @rjsparks on why that could be.

**Comment by rjsparks** [comment]
I think there have been a set of choices for whether to look at the doc or the dochistory on the html page that is fighting making the view easy at this point. It might be a sprint activity to talk this through and straighten out.

**Comment by rjsparks** [comment]
OBE
