### ISSUE TITLE
Exported IETF 116 iCalendar agenda has incomplete events

### ISSUE THREAD

**Issue by ghedo** [ietf-tools/datatracker#5392]
### Describe the issue

Importing the full IETF 116 `agenda.ics` into Google Calendar seems to be failing for me.

Looking at my locally downloaded file, it appears that a number of events are incomplete (missing tags), notably all of the "Break" events around lunch time:
```
BEGIN:VEVENT
UID:ietf-116-15206-secretariat
SUMMARY:Break
BEGIN:VEVENT
UID:ietf-116-15262-ietf
SUMMARY:Story Telling Event sponsored by JPRS
LOCATION:G403
```
The `ietf-116-15206-secretariat` event is incomplete (missing `DTSTART`/`DTEND`/`DTSTAMP` and `END:VEVENT`). This seems to apply to all `SUMMARY:Break` events (but not the "Beverage Break" and "Beverage and Snack Break" ones).

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
Some conditional statements got corrupted in the `agenda.ics` template - straightening them out now.
