### ISSUE TITLE
Meeting agenda doesn't show floors on mobile

### ISSUE THREAD

**Issue by flynnliz** [ietf-tools/datatracker#5399]
### Describe the issue

Viewing the meeting agenda in a mobile browser, the floor data is missing (1F, 4F, etc). Compare this screenshot from Safari on mobile to the info available on the web: 

<img width="561" alt="Screen Shot 2023-03-25 at 9 18 16 AM" src="https://user-images.githubusercontent.com/29440652/227667129-c4e657ab-d282-4a36-8e82-4920e7b38734.png">
![File](https://user-images.githubusercontent.com/29440652/227667163-23b9b0f2-f52e-40b4-8d77-9d8a0c8c93c3.jpg)

It would be helpful to have the floor info on a mobile browser as well.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by flynnliz** [comment]
Whoops, here is the mobile screenshot: 

![File](https://user-images.githubusercontent.com/29440652/227667250-c7ff58fe-e439-4d85-8c09-c759686f9c15.jpg)

**Comment by rjsparks** [comment]
@NGPixel can comment more, but I think there's a space/layout issue adding the floor markers on the mobile view.
Did you notice that the room numbers above are links on the mobile view - if you press G304 above, you will get the map view, showing the floor

**Comment by NGPixel** [comment]
As @rjsparks mentioned, there's not enough space to display floor indicators on mobile. As soon as you scroll down to the sessions, space is very limited:

<img width="295" alt="image" src="https://user-images.githubusercontent.com/15522395/227758451-417912d6-e655-4b3f-860f-e50a9b0ce9b6.png">

Pressing on the room will bring you to the floor plan with the floor indicator next to each room.

**Comment by flynnliz** [comment]
(I was passing this along from someone who complained about this to me) - I think their point was that it would be helpful to know what floor a room is on without having to click all the way through into the floor plan. But if this is by design/not planned to change, that's fine.
