### ISSUE TITLE
Expired IAB or RG documents are considered as active

### ISSUE THREAD

**Issue by kivinen** [ietf-tools/datatracker#5404]
### Describe the issue

In the main search https://datatracker.ietf.org/doc/search?name=draft&sort=&activedrafts=on&by=group&group= if you select to show only active internet drafts, and use criteria like "draft" you get 195 active internet drafts, and 5 expired Internet-drafts.

The common thing for all those expired draft is that they are active iab or rg documents, but if the drafts are expired, I think they should not be shown here.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Masking these with expired isn't the right thing to do. We instead need to correct the invalid states of those documents. I'll aim the secretariat at them.

**Comment by rjsparks** [comment]
This is now down to 2 RG docs - nudging those along...

**Comment by rjsparks** [comment]
We're now down to only recently expired things showing, which is arguably less likely to violate the principle of least astonishment than showing them in an "Expired drafts" section when no expired drafts were asked for (remember, this same logic gets used to show the group document pages).

I'm going to close this issue, but will continue to watch for outliers.
