### ISSUE TITLE
Submission shouldn't accept pdf as an uploadable format anymore

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#5405]

**Comment by rjsparks** [comment]
@larseggert, @evyncke  - Please make sure the IESG is ok if we remove the ability for an author to provide their own pdf during I-D submission.

**Comment by evyncke** [comment]
I cannot imagine a reason why this would cause an issue, but I will ask tomorrow during the IESG meeting

**Comment by evyncke** [comment]
As written by email, nobody objected at the IESG meeting

**Comment by rjsparks** [comment]
Final steps complete with 10.3.0
