### ISSUE TITLE
pdfization is broken again

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#5426]
At, e.g., https://datatracker.ietf.org/doc/draft-ietf-stir-certificates-ocsp/ the [pdf] button pdfizes, and produces broken output:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/10996692/227752182-43302725-e3a1-43cc-9ce1-e6b747ea3531.png">

@larseggert Is this interacting with the new /doc/html htmlization?

**Comment by larseggert** [comment]
Possibly. Sigh. This is going to be difficult to debug without a browser with a proper web inspector.

CC @martinthomson just in case it rings a bell for him.

**Comment by martinthomson** [comment]
Looks like a regression of the fix in #5078, which might need to be applied again.

**Comment by martinthomson** [comment]
https://github.com/martinthomson/rfc-txt-html/commit/a593bf729103915f911ab18bd3ce9c5832541288 in case you need a repeat.

**Comment by rjsparks** [comment]
Yep - this one reverted it:
https://github.com/ietf-tools/datatracker/pull/5339/files
