### ISSUE TITLE
Slide approvals should be marked to history

### ISSUE THREAD

**Issue by kivinen** [ietf-tools/datatracker#5432]
### Description

When WG chair approves a -00 document there is entry added to history saying:

  2022-12-07	00 	Yoav Nir 	WG -00 approved

but when the slides for the meeting are approved by someone there is no such entry in the history:

https://datatracker.ietf.org/doc/slides-116-ipsecme-ikev2-link-maximum-atomic-packet-and-packet-too-big-notification-extension/history/

I.e., there is only entry added when the slides where uploaded, but no entry when and by whom they were approved.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kivinen2** [comment]
I test this now and it seems I do get both new slides and approvals in the history.

![image](https://github.com/user-attachments/assets/2135aca3-5cf0-4627-bda5-941418964c7f)

**Comment by kivinen2** [comment]
So I think this can be closed.
