### ISSUE TITLE
Let people know when their slides have been accepted

### ISSUE THREAD

**Issue by paulehoffman** [ietf-tools/datatracker#5440]
### Description

When someone submits slides in the Datatracker, and the WG chair accepts their submission, the slides go into the WG list but the submitter doesn't know that. It would be nice if the submission causes an email to the submitter.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This will involve a new mailtrigger, and the code to cause mail to be emitted towards the recipients (which should be the slide submitters and the group chairs) added just before https://github.com/ietf-tools/datatracker/blob/9a09bf1f7b2b6ab100482090012422263f85207a/ietf/meeting/views.py#L4558

**Comment by rjsparks** [comment]
Fixed by #6470
