### ISSUE TITLE
Wrong collate sequence in https://registration.ietf.org/116/participants/onsite/

### ISSUE THREAD

**Issue by evyncke** [ietf-tools/datatracker#5449]
### Describe the issue

In https://registration.ietf.org/116/participants/onsite/, the collate sequence when sorting rows is wrong, check for Mirja Kühlewind who is listed at the end of all K* participants.

At least in German, it should be listed as if written as Kuehlewind.

Or even 'worse' ;), my own first name. 'Éric' appears at the end of the list when sorting on the first name.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
The tools team does not manage the registration.ietf.org. It's an AMS product.
You can report registration site bugs to  `support@ietf.org`.

**Comment by evyncke** [comment]
Ticket rt5.ietf.org #16338 opened
