### ISSUE TITLE
Check HTML/PDFization of overly wide table

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#5453]
### Describe the issue

In https://datatracker.ietf.org/doc/html/draft-ietf-extra-sieve-action-registry-06#section-2.2

CC @martinthomson 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by martinthomson** [comment]
I wasn't able to constrain the size of the table in the short time I tried.  Maybe the authors should consider not using a table that contains this much data.

**Comment by cabo** [comment]
On 2023-03-31, at 13:06, Martin Thomson ***@***.***> wrote:
> 
> I wasn't able to constrain the size of the table in the short time I tried. Maybe the authors should consider not using a table that contains this much data.

The table is fine:

https://www.ietf.org/archive/id/draft-ietf-extra-sieve-action-registry-06.html#name-initial-sieve-action-regist

It’s only the plaintext emulation that fails.
Maybe we should not try to use a Procrustes bed here?

(That said, some tools that help converting between tables and definition lists should be done on the author tooling side.)

Grüße, Carsten

**Comment by martinthomson** [comment]
The table is not fine.  This is what it looks like with a style sheet that uses a reasonable line length:

![image](https://user-images.githubusercontent.com/67641/229043436-d98eeac2-fdea-484f-90ea-655081096e53.png)

Though I do agree regarding the definition conversion option.  That conversion is awkward and time consuming and a tool would certainly help.
