### ISSUE TITLE
pages link to the raw chatlog - should link to rendered version instead.

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#5456]
at
https://datatracker.ietf.org/group/keytrans/meetings/
the icon to the chat log points to the raw json at 
https://datatracker.ietf.org/meeting/116/materials/chatlog-116-keytrans-202303291300-00
it should instead point to the page that makes the log human readable at
https://datatracker.ietf.org/doc/chatlog-116-keytrans-202303291300/
_that_ page should offer a link to get to the raw json.

**Comment by cabo** [comment]
For me it points to https://datatracker.ietf.org/group/keytrans/meetings/session.chat_room_url
which is 404

**Comment by rjsparks** [comment]
@cabo - What page as that link, and where on the page do you see it?

**Comment by rjsparks** [comment]
Closing with can't_find.
Please re-open with a link to the page this occurs on if it's still occuring.
