### ISSUE TITLE
emodir (soon to be eodir) datatracker and agenda representations

### ISSUE THREAD

**Issue by kodonog** [ietf-tools/datatracker#5458]
### Description

There are several activities that show up on the datatracker Agenda for a meeting that are under the umbrella for EMODIR. These are all mixed into a single entry. This can cause confusion in the various datatracker pages for the meeting. It would be nice to have a way to separate these types of activities. 

One example is for the WG Chairs Forum --> Can the zulip channel linked from meetecho be #wgchairs instead of #emodir

For the materials page, in looking at the screenshot, the group is not shown as emodir, it is the quick connections session, the timeslots shown in Agenda are for the New Participants Overview and the WGChairs Forum. 

<img width="1173" alt="Screen Shot 2023-03-31 at 12 07 50 PM" src="https://user-images.githubusercontent.com/15526656/229012977-909bb2f4-be21-4c57-a236-c8e932b5aeb1.png">

This also causes confusion when we schedule wgchair forum virtual interims. Because the list of upcoming meetings, https://datatracker.ietf.org/meeting/upcoming the meeting shows as emodir instead of wgchairs

One possible approach would be to add an additional tag so that is showed up as eodir:wgchairs or eodir:newparticipants or just eodir (for an actual eodir meeting). 

All of this being said, maybe a few small special case changes would be all that is really needed. Have wgchairs be labeled wgchairs instead of eodir and link to the right zulip channel. 

Finally, I don't consider this a major issue as the current people involved understand the work arounds. I am happy to brainstorm possible fixes if you wish. 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
>One example is for the WG Chairs Forum --> Can the zulip channel linked from meetecho be #wgchairs instead of #emodir

See #5438

**Comment by rjsparks** [comment]
> For the materials page, in looking at the screenshot, the group is not shown as emodir, it is the quick connections session, the timeslots shown in Agenda are for the New Participants Overview and the WGChairs Forum.

If a Session has a name, the name is shown rather than the group.

**Comment by rjsparks** [comment]
> Because the list of upcoming meetings, https://datatracker.ietf.org/meeting/upcoming the meeting shows as emodir instead of wgchairs

The upcoming meetings page should show a session name if it exists.

**Comment by larseggert** [comment]
I *think* this can be closed now the other PRs are merged?
