### ISSUE TITLE
doc/html Contents empty

### ISSUE THREAD

**Issue by martinthomson** [ietf-tools/datatracker#5483]
### Describe the issue

Some recent internet-drafts are showing up with an empty table of contents in the side panel.  I'm also getting a JS error that might have something to do with that:

```
properties of undefined (reading 'match')
    at wr (nav.js:11:20)
    at Array.map (<anonymous>)
    at xr (nav.js:27:10)
    at HTMLDocument.<anonymous> (document_html.js:45:5)
```

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
This is because https://github.com/ietf-tools/rfc2html/pull/12 got merged. Will fix.
