### ISSUE TITLE
Incorrect time in the upcoming.ics calendar

### ISSUE THREAD

**Issue by dhruvdhody** [ietf-tools/datatracker#5527]
### Describe the issue

The time at https://datatracker.ietf.org/meeting/upcoming does not match the time imported in the calendar from https://datatracker.ietf.org/meeting/upcoming.ics

It assumed that it might be an issue from the data tracker migration and thus deleted the calendar and added it again on Google Calendar. I am still getting an incorrect time. 

![Screenshot 2023-04-24 at 12 02 14 PM](https://user-images.githubusercontent.com/8587468/233916996-c7b7d526-b73b-446e-868c-c9a9fcde6971.png)

You can compare it with the time at https://datatracker.ietf.org/meeting/upcoming 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
@mcr has made several observations about google calendar on tools-discuss. I think we have an interop problem specific to that system. Speculation is that it remembers older things it has seen even if you think you've removed them.

The ics file does have the right timestamps in it (you can verify this with curl). 

We are looking into using a different library to generate the ics files (right now we generate them with a django template). The result might irritate google calendar differently.

**Comment by mcr** [comment]
CELLAR, btw, looks wrong too.  It was at 1500 Eastern, which I think (based upon timeandate.com) would be 12:30am Bengaluru time, not 7:30am!

@rjsparks , I don't think that changing libraries is useful use of our limited resources.
I mean, you could look at the different output, and do some experiments against google calendar using static files.  I continue to suspect something about the ETag processing.  
Without a google calendar internal person, I'd say we are lost.   (I'd pay them for a service with an SLA, but they won't take my money unless I give them everything, including DNS)
Maybe there are some @google.com people in the calendaring MLs that we could unicast.

**Comment by rjsparks** [comment]
Changing libraries is actually needed. And I should have said "Use a maintained library instead of rolling our own ics".

The 7 hour difference you point to says to me that this is leftover, _at google_, of the period where the timestamps in the datatracker were wrong.

Again, you can use curl to verify that what's in the ics now is correct. (Please do so - if you get a different answer from curl than me, we have a different problem to pursue).

```
rjsparks@undex tmp % curl --no-progress-meter https://datatracker.ietf.org/meeting/upcoming.ics | grep -A5 cellar
UID:ietf-interim-2023-cellar-05-14974
SUMMARY:cellar - Codec Encoding for LossLess Archiving and Realtime transmission
LOCATION:Amsterdam,NL
STATUS:CONFIRMED
CLASS:PUBLIC
DTSTART;TZID=Europe/Amsterdam:20230523T210000
DTEND;TZID=Europe/Amsterdam:20230523T220000
--
UID:ietf-interim-2023-cellar-06-14975
SUMMARY:cellar - Codec Encoding for LossLess Archiving and Realtime transmission
LOCATION:Amsterdam,NL
STATUS:CONFIRMED
CLASS:PUBLIC
DTSTART;TZID=Europe/Amsterdam:20230627T210000
DTEND;TZID=Europe/Amsterdam:20230627T220000
--
UID:ietf-interim-2023-cellar-07-14976
SUMMARY:cellar - Codec Encoding for LossLess Archiving and Realtime transmission
LOCATION:Amsterdam,NL
STATUS:CONFIRMED
CLASS:PUBLIC
DTSTART;TZID=Europe/Amsterdam:20230822T210000
DTEND;TZID=Europe/Amsterdam:20230822T220000
--
UID:ietf-interim-2023-cellar-08-14977
SUMMARY:cellar - Codec Encoding for LossLess Archiving and Realtime transmission
LOCATION:Amsterdam,NL
STATUS:CONFIRMED
CLASS:PUBLIC
DTSTART;TZID=Europe/Amsterdam:20230926T210000
DTEND;TZID=Europe/Amsterdam:20230926T220000
--
UID:ietf-interim-2023-cellar-09-14978
SUMMARY:cellar - Codec Encoding for LossLess Archiving and Realtime transmission
LOCATION:Amsterdam,NL
STATUS:CONFIRMED
CLASS:PUBLIC
DTSTART;TZID=Europe/Amsterdam:20231024T210000
DTEND;TZID=Europe/Amsterdam:20231024T220000
--
UID:ietf-interim-2023-cellar-10-14979
SUMMARY:cellar - Codec Encoding for LossLess Archiving and Realtime transmission
LOCATION:Amsterdam,NL
STATUS:CONFIRMED
CLASS:PUBLIC
DTSTART;TZID=Europe/Amsterdam:20231205T210000
DTEND;TZID=Europe/Amsterdam:20231205T220000
```

**Comment by dhruvdhody** [comment]
Ah! For the time being I removed the subscription from Google Calendar and moved it to the iCloud calendar. The time there is correct!

**Comment by rjsparks** [comment]
I'm going to close this as not-a-datatracker-bug (though it could well be that we could produce _better_ ics, which we'll track at #5393 ).
