### ISSUE TITLE
automatic addition of secretaries to "must be present" when requesting to schedule a meeting.

### ISSUE THREAD

**Issue by ggx** [ietf-tools/datatracker#5533]
### Description

Hi,

I've just submitted a request to schedule a meeting for the upcoming 117 meeting and noticed that chairs and AD are now automatically added to the "participants who must be present" list. Thumbs up for this!

But... in my WG (LISP WG) we have also a secretary and I had to add him explicitly (see screenshot). Would be nice if also secretaries (for WG that have one) can be added automatically.

Luigi
<img width="652" alt="Screenshot 2023-04-25 at 14 25 51" src="https://user-images.githubusercontent.com/8026122/234275576-b254290c-91ad-42fc-babc-cd0803b25bf8.png">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ggx** [comment]
Hi Robert,

Thanks your email.

I do agree that the more constraints we add the harder is the scheduling problem.
As for the tooling itself, I still consider that an explicit option on the interface would be nice. An opt in or opt out so that WG with different needs can do different choices.
I can certainly bring this up during the WG chairs lunch in SF.
The survey is also a good idea, I can even take the action point….

Ciao

L.

**Comment by larseggert** [comment]
I propose to close this with no action.

**Comment by rjsparks** [comment]
I'll do so - if we get new information from, e.g., conversations in SF, we can reopen.
