### ISSUE TITLE
Resurrected doc not appearing on WG documents page

### ISSUE THREAD

**Issue by cindymorgan** [ietf-tools/datatracker#5542]
### Describe the issue

ROLL recently updated an expired I-D (https://datatracker.ietf.org/doc/draft-ietf-roll-nsa-extension/), but the now-active draft does not appear on the WG documents page (https://datatracker.ietf.org/wg/roll/documents/).

I suspect this might have something to do with the draft having been in the IESG state "AD is Watching" when it expired. Upon expiry, it was automatically moved to the IESG state "Dead." Resurrection did not move this back to "AD is watching."

(In the sandbox, I attempted to see if changing the IESG state back to "AD is watching" would fix the issue, but I got a 404 error at https://sandbox.ietf.org/doc/draft-ietf-roll-nsa-extension/edit/state/)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Closed through out-of-band communication.
