### ISSUE TITLE
Searching for "RFC ####" (with a space) fails to return results

### ISSUE THREAD

**Issue by alexisannerossi** [ietf-tools/datatracker#5567]
### Describe the issue

Search for "RFC 9280" fails:
https://datatracker.ietf.org/doc/search?csrfmiddlewaretoken=ppkZbIvYkXtK5k6DAZv25PzPIuDQ38iOKSTHWzvpnBxjLpulgfyfyui5cWGKcgvU&name=RFC+9280&sort=&rfcs=on&activedrafts=on&by=group&group=

Search for "RFC9280" succeeds:
https://datatracker.ietf.org/doc/search?csrfmiddlewaretoken=UQCPa1qMaPdqYlDdNmvTqCbWSl0R96IvfjbxVSqddthZEq1VtCy6ThUcmN3LieVB&name=RFC9280&sort=&rfcs=on&activedrafts=on&by=group&group=

It seems like we should be able to return the right RFC if there's a space, particularly since we display RFCs as having a space in most places where we refer to them on the site.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
See also #4328.

This will be addressed as part of making RFCs first class objects in the datatracker (#2917) which will be an early step in the RPC tools modernization effort.

**Comment by rjsparks** [comment]
Also, there continue to be conversations about replacing app-specific searches with a separate search application.

**Comment by rjsparks** [comment]
This is fixed on feat/rfc - this issue will be closed when we merge and deploy that feature branch

**Comment by rjsparks** [comment]
deployed with 12.0.0
