### ISSUE TITLE
Date of "Datatracker url" link

### ISSUE THREAD

**Issue by astirst024** [ietf-tools/datatracker#5603]
### Describe the issue

Needs a better date of being listed, will comunicate privetly if you want to know more.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by astirst024** [comment]
https://www.rfc-editor.org/errata.php#reportnew

**Comment by rjsparks** [comment]
If you need to send private clarification use tools-help@ietf.org.
Otherwise, there's nothing actionable in this issue. I'm closing it.
