### ISSUE TITLE
Broken link in shepherd writeup template

### ISSUE THREAD

**Issue by furry13** [ietf-tools/datatracker#5650]
### Describe the issue

Section 10 of the shepherd writeup template refers to the list of common issues/expert topics. However that link points to a non-existent page. The writeup template in the datatracker refers to  https://trac.ietf.org/trac/iesg/wiki/ExpertTopics  and https://datatracker.ietf.org/doc/shepherdwriteup-template/individual refers to https://wiki.ietf.org/group/iesg/ExpertTopics

Both pages do not exist. What does exist is "https://wiki.ietf.org/en/group/iesg/experttopics"

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Yes, this is an example of several pages that didn't maintain their CamelCase name as they were migrated. We are working on solving the general problem, but in the meantime, we'll rename pages like this (that are pointed to by documents like the shepherd writeup template or by RFCs).

**Comment by rjsparks** [comment]
The redirect should get you to where you want now. The change to the writeup template to avoid the redirect is in progress
