### ISSUE TITLE
Refactor to drop dependency on decorator package

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#5654]
### Description

We have a few decorators defined in `ietf/utils/decorator.py` that use the "decorator" package. This provides the `@decorator` decorator and a `decorate` method. The built-in Python `functools.wraps()` method can fulfill the needs here without the additional dependency. As far as I can tell we're not making use of any of the features provided by the "decorator" package.

The `@decorator` mechanism also seems to interfere with Django's `@method_decorator`, which led to refactoring the `requires_api_key` decorator already.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
Reopening - there is still a dependency in `debug.py` as @microamp mentioned in his PR comment

**Comment by microamp** [comment]
If I recall, this issue was resolved via two separate PRs as shown above - #7199 and #7219. Please let me know otherwise.
