### ISSUE TITLE
Documents that recently finished Last Call did not advance by the system

### ISSUE THREAD

**Issue by akvezza** [ietf-tools/datatracker#5664]
### Describe the issue

Discussed this issue with Robert via Slack earlier. There are a few documents that should have finished Last Call in the past few days that were not moved forward by the system as expected. 

draft-ietf-lsr-ip-flexalgo-11 - last call ended May 16 (manually moved to Waiting for Writeup on May 19 at the behest of the AD)
draft-ietf-ippm-stamp-srpm-11 - last call ended May 17
draft-ietf-sfc-multi-layer-oam-23 - last call ended May 17

And if this is still an issue on Monday, May 22:
draft-ietf-jsonpath-iregexp-06 - last call is due to end May 22

All other documents In Last Call have end dates after May 22.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Running expire_last_call manually (as wwwrun) expired the two you point out:
```
2023-05-19T12:29:05.969933-07:00 ietfa datatracker[44272]: Expired last call for <draft-ietf-ippm-stamp-srpm-11.txt> (id=102422)
2023-05-19T12:29:06.370046-07:00 ietfa datatracker[44272]: Expired last call for <draft-ietf-sfc-multi-layer-oam-23.txt> (id=87476)
```
Something must be preventing the normal cron invocation from succeeding.

**Comment by rjsparks** [comment]
Breakage located and corrected.
I'll work out manually correcting the rest of what should have happened to `draft-ietf-lsr-ip-flexalgo` with the secretariat.
