### ISSUE TITLE
Intewrnet-Draft submission misinterprets type of the file to upload

### ISSUE THREAD

**Issue by GregMirsky** [ietf-tools/datatracker#5678]
### Describe the issue

I experience a problem with the draft submission tool. Upon selecting XML file I've been working on, the tool responds with
Expected an XML file of type "application/xml" or "text/xml", found one of type "text/plain"
although file's properties are as follows:
![image](https://github.com/ietf-tools/datatracker/assets/8866056/0995f994-3e4a-4fa4-819d-53b643dbcd00)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Hi Greg - 
Remember #5292. The same fix is what you are looking for now I think.
Let me know if that change doesn't address your upload issue today.
This annoyance is expected to go away when we change the underlying IT infrastructure.
