### ISSUE TITLE
Menus don't work on a touch screen

### ISSUE THREAD

**Issue by martinthomson** [ietf-tools/datatracker#5702]
### Describe the issue

It's in the title.  Mouseover doesn't work on touch screens, so maybe the menus need to open when they are tapped (they open when clicked with a mouse, but that is probably a result of the mouse having to be over them to click the button).

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Please give a little more context - type of device, which browser, etc.?
(I tested using browserstack on one of their real ipads, using chrome, and unless they've hidden the bug with the glue they have between me and that device, the menus were working there on both main and django4.

**Comment by martinthomson** [comment]
I have a Windows device with a touch screen, using Firefox (but Edge fails too).  Maybe there is a hole in the code that detects tablets or phones but doesn't consider the possibility that touch is possible on other platforms.

**Comment by larseggert** [comment]
@martinthomson what event is sent when you touch?

**Comment by martinthomson** [comment]
I'm pretty sure that a touchscreen generates "click" events on touch.  There are also touch events, but you don't need to listen for those.

**Comment by larseggert** [comment]
Hm. That entire bit of code (dropdown menus) comes from bootstrap. The only bit we're adding in our code is opening/closing the dropdowns on `mouseenter`/`mouseleave`.

**Comment by larseggert** [comment]
@martinthomson I assume this is still an issue? Could we maybe sit down in SF and triage this on your device?

**Comment by martinthomson** [comment]
Happy to try to help out.

**Comment by larseggert** [comment]
@martinthomson want to come to the codesprint to debug this?
