### ISSUE TITLE
Improve web viewer by removing scrollbar on each RFC pages (overflow)

### ISSUE THREAD

**Issue by jmaselbas** [ietf-tools/datatracker#5719]
### Description

Reading RFCs with the html viewer at https://datatracker.ietf.org/doc/html/rfc2119 is not very comfortable because of spurious scrollbars for each individual pages, this brakes scrolling.

This can be "easily" fixed by removing the `overflow:auto` css property of `pre` elements:
```
 pre {
   margin-top: 0;
   margin-bottom: 1rem;
   font-size: .875em;
   display: block;
-  overflow: auto;
 }
```
which is defined in "_reboot.css" which I believe comes from `bootstrap/scss/reboot`
which is included by `document_html.scss` which in included by `document_html_referenced.scss`...

I don't know how to fix this properly, as I am not familiar with all of this web complexity.

...

This could also be fixed by:
```
 .rfcmarkup pre {
   width: 80ch;
   white-space: pre-wrap;
+  overflow: unset;
 }
```
in `document_html_referenced.scss`

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
#5709 should also fix this

**Comment by jmaselbas** [comment]
> #5709 should also fix this

Yes it also fixes this issue

**Comment by rjsparks** [comment]
#5709 is merged
