### ISSUE TITLE
"Purpose" table incorrect

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#5720]
### Describe the issue

The "purpose" table on the top of https://datatracker.ietf.org/meeting/requests seems to be incorrect. It currently lists 90 "regular" timeslot requests only, but when you look at the GEN-area requests, you see the hackathon requests with a purpose of "Coding" - shouldn't those be reported in that table?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Groups of type "team" are currently filtered out of the table - eodir, hackathon, and tools sessions don't show in the summary. 

We could change the label of the summary, add a note about teams being filtered out of the summary, add a second summary table for groups that are not teams, or make some other adjustment.

The original request for the table came from Liz to help understand the pressure for the agenda building process. What use case do you have in mind where having the team sessions in the summary would be useful?

**Comment by rjsparks** [comment]
btw: 
https://github.com/ietf-tools/datatracker/blob/e5dcc1667c0a75d48d7f4c8209f3c2c9d96dc74c/ietf/meeting/views.py#L104
https://github.com/ietf-tools/datatracker/blob/e5dcc1667c0a75d48d7f4c8209f3c2c9d96dc74c/ietf/meeting/views.py#L2243-L2248
https://github.com/ietf-tools/datatracker/blob/e5dcc1667c0a75d48d7f4c8209f3c2c9d96dc74c/ietf/meeting/views.py#L2351
