### ISSUE TITLE
Yarn dependencies incorrectly met?

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#5725]
### Describe the issue

Am doing `./run -r` to rebuild everything and I saw this:
```
Compiling native node packages...
➤ YN0000: ┌ Resolution step
➤ YN0060: │ root-workspace-0b6124@workspace:. provides luxon (pd9264) with version 3.3.0, which doesn't satisfy what @fullcalendar/luxon2 requests
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
```

Not sure if that's a bug or not.  Ping @NGPixel ?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by NGPixel** [comment]
You can ignore this warning. For a long time the fullcalendar plugin only listed luxon2 as a dependency while the rest of the project used luxon3, hence the warning. They finally released an update with an option for luxon3 last week.

I opened a PR (#5729) which will make this warning go away.
