### ISSUE TITLE
Downref registry page should provide brief explanation of what a downref is

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/datatracker#5759]
### Describe the issue

There was an earlier issue (#2788) that covered this, and it was closed as fixed (commit 13fee54). However, the text does not appear on the [Downref registry](https://datatracker.ietf.org/doc/downref/) page.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by becarpenter** [comment]
Note that the missing text mentioned in #2788 is slightly incomplete, since BCP97 consists of three RFCs: 3967, 4897 and 8067.

**Comment by larseggert** [comment]
Closing, since #5789 got merged.
