### ISSUE TITLE
Data tracker

### ISSUE THREAD

**Issue by Flaminggay** [ietf-tools/datatracker#5778]
### Description

Trying to figure out how to use data tracker.com

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Not a datatracker issue. Pay attention to draft development in a working group. Read the getting started messages at www.ietf.org.
