### ISSUE TITLE
/wg/1wg-charters-by-acronym.txt broken in middleware

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#5786]
Can we _please_ stop serving these big amalgamations?

**Comment by jennifer-richards** [comment]
Retrieving this URL just worked for me when logged in - the failure we had earlier was with AnonymousUser.

**Comment by jennifer-richards** [comment]
This was a side effect of [Django 3.2's change to the HttpResponse header handling](https://docs.djangoproject.com/en/3.2/releases/3.2/#requests-and-responses). A Django 2.2-format response to this endpoint had been cached prior to the deployment of datatracker 11.0.0. When a request came in, the cached value was retrieved and Django attempted to use its new code with the old object, causing the missing attribute error.
