### ISSUE TITLE
affiliation in the statistics

### ISSUE THREAD

**Issue by zhoutr** [ietf-tools/datatracker#5790]
### Describe the issue

In the statistic page:
https://datatracker.ietf.org/stats/document/author/affiliation/

Huawei and Huawei Technologies are obviously the same affiliation.
ZTE and ZTE Corporation are obviously the same affiliation.
Juniper and Juniper Networks are obviously the same affiliation.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
There is an incomplete attempt to map different names to the same organization in the code.
However, this entire section of the codebase is planned to be removed and replaced with a different implementation - see the list at https://github.com/ietf-tools/datatracker/issues/3712.
