### ISSUE TITLE
Document search doesn't always provide newest revision

### ISSUE THREAD

**Issue by cabo** [ietf-tools/datatracker#5799]
### Describe the issue

https://datatracker.ietf.org/doc/search/?search_submit=&author=Bormann&name=draft&activeDrafts=on&by=author&sortBy=date

has jsonpath-base-13, while

https://datatracker.ietf.org/doc/draft-ietf-jsonpath-base/

shows that we are at -14.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Thanks for spotting this - we have a new cache issue that we will address.

**Comment by rjsparks** [comment]
This is fixed in 11.1.0
