### ISSUE TITLE
Navigation menu doesn't include SATP WG

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#5854]
### Describe the issue

The SATP WG is missing under SEC.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
<img width="783" alt="Screenshot 2023-06-20 at 13 12 16" src="https://github.com/ietf-tools/datatracker/assets/200328/a48d77d7-00d6-496d-89a4-adb306fd3d94">

**Comment by rjsparks** [comment]
Because it's in ART.

**Comment by larseggert** [comment]
Doh
