### ISSUE TITLE
Draft submission fails due to a system error

### ISSUE THREAD

**Issue by mlichvar** [ietf-tools/datatracker#5867]
### Describe the issue

I'm trying to submit a draft, but it fails with `Meta-Data errors found!`, showing all metadata to be missing and the result is `Submission rejected: A system error occurred while processing the submission.`.

The draft passes idnits. It's available [here](https://raw.githubusercontent.com/mlichvar/draft-ntp-over-ptp/main/ntp-over-ptp.xml) if you want to try it. I was able to submit a draft last week with no issues.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by richsalz** [comment]
I am having the same problem  I forwarded the issue directly to the tools-discuss mailing list to bump the importance, since the cut-off is coming...

**Comment by mlichvar** [comment]
It works now. Thanks!

**Comment by richsalz** [comment]
works for me too; you can close this.
