### ISSUE TITLE
Sign in link issues

### ISSUE THREAD

**Issue by kesara** [ietf-tools/datatracker#5876]
### Describe the issue

The "Sign in" link in the top right-hand corner keeps appending content for the next query parameter.

To reproduce:
* Go to Datatracker as an unlogged user.
* Click on "Sign in" button on the top right-hand corner.
* Click the "Sign in" button in the top right-hand corner again.
* New URL is `https://datatracker.ietf.org/accounts/login/?next=/accounts/login/%3Fnext%3D/`
* If you click again, the URL will be `https://datatracker.ietf.org/accounts/login/?next=/accounts/login/%3Fnext%3D/accounts/login/%253Fnext%253D/`.

Because clicking on the "Sign in" button from the sign-in page changes the `next` query parameter to `/account/login/<stuff>`, the user will be presented with a login screen after successful login.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Might be nice to put the page to return to in the session rather than have it as a query parameter (we _know_ there's a session).
