### ISSUE TITLE
Remove "resources requested" options from session request form

### ISSUE THREAD

**Issue by flynnliz** [ietf-tools/datatracker#5897]
### Description

Both the items under "Resources Requested" (experimental room setup and flipcharts) in the session request form should be deleted. These are outdated and no longer available. 

Ideally should be done before session requests open for 118 please!

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Pretty sure this was done in the admin before 118 schedule requests were opened. Closing this as complete. @flynnliz - reopen if it doesn't look right please.
