### ISSUE TITLE
add  xml reference as button on document page

### ISSUE THREAD

**Issue by marcblanchet** [ietf-tools/datatracker#5908]
### Description

I always struggle to get the proper `<reference>` for a draft that I'm referencing in my own draft. I know it is available like in bib.ietf.org (and maybe other places), but I always go to the datatracker for that draft (to know its status, get the right version, ...). It would be very valuable and probably not that lot of work (given already implemented the bibtex button) to have in datatracker/doc/draft-... a new button in the "Formats" line to provide such bibxml info of that draft. 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by pselkirk** [comment]
I just issued a PR for a button. In the meantime, the bibxml is already there (just without a UI), and you can enter the URLs directly, e.g.
https://datatracker.ietf.org/doc/bibxml3/draft-blanchet-dtn-email-over-bp.xml
https://datatracker.ietf.org/doc/bibxml3/draft-blanchet-dtn-email-over-bp-02.xml

**Comment by BobRichnow** [comment]
Encapsulation of Email over Delay-Tolerant Networks(DTN) using the Bundle Protocol This document describes the encapsulation of emails using RFC2442 format in the payload of bundles of the Bundle Protocol for the use case of Delay-Tolerant Networks(DTN) such as in space communications.
