### ISSUE TITLE
Draft submission with empty strings in date element fails with generic "Meta-Data errors found!" message

### ISSUE THREAD

**Issue by bobhinden** [ietf-tools/datatracker#5913]
### Describe the issue

I tried submitting an xml draft, hard fail due to "Meta-Data error found".   Very odd since it passes the submission checks.

There is a closed issue that sounds similar, but apparently not fixed.

I can send the xml, but this doesn't allow that file type.

<img width="1009" alt="Image" src="https://github.com/ietf-tools/datatracker/assets/6423658/fb3e7616-ea04-46e8-a6d2-0d359888f7b7">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
This is similar in presentation to the recently closed issue but is a new bug. It appears to be related to your draft's contents - I see the failures in the logs and other drafts have been successfully uploaded in between attempts.

The back end is failing with the following traceback
```
Traceback (most recent call last):
  File "/workspace/ietf/submit/utils.py", line 1265, in process_and_validate_submission
    xml_metadata = process_submission_xml(submission.name, submission.rev)
  File "/workspace/ietf/submit/utils.py", line 1166, in process_submission_xml
    "document_date": xml_draft.get_creation_date(),
  File "/workspace/ietf/utils/xmldraft.py", line 154, in get_creation_date
    return datetime.date(year, month, day)
TypeError: an integer is required (got type str)
```

The parser is having a problem with the date element in your draft's front section. Can you post that (or zip the entire xml and attach, I believe github will allow you to attach it)?

Thank you for the report.

**Comment by bobhinden** [comment]
[draft-ietf-6man-hbh-processing-09.xml.zip](https://github.com/ietf-tools/datatracker/files/11951620/draft-ietf-6man-hbh-processing-09.xml.zip)

**Comment by bobhinden** [comment]
The date element in the draft hasn't changed for a long time.   The draft is -09.

**Comment by jennifer-richards** [comment]
Thanks- the problem is triggered because your `<date>` element has empty fields. If you fill in those values or remove the element entirely, I expect it will be accepted. You can probably also just use an empty `<date/>` element without the `year`, `month`, and `day`.

I believe the date field is invalid as it is. It's likely the parser looked the other way in the past and treated is as if it were absent.

We should coordinate with xml2rfc on how we handle this. Obviously we need to give better feedback here if we're not going to accept this format.

**Comment by jennifer-richards** [comment]
Also, the impression that submission checks passed is false, caused by #5696.

**Comment by jennifer-richards** [comment]
Just checked and xml2rfc accepts this, treating it as though the year/month/day were not present, so datatracker should do the same.

**Comment by bobhinden** [comment]
Thanks, removing the date field fixed the problem.
