### ISSUE TITLE
The email sent when an IRTF charter is approved needs adjustment.

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#5917]
Currently the email appears to come from the IESG and does not copy irtf-announce. It does copy ietf-announce. Should it continue to do so?

cc: @csperkins, @cindymorgan

**Comment by csperkins** [comment]
This should come from `irtf-chair@irtf.org` and be sent to `irtf-announce@irtf.org`, with a copy to `iab@iag.org, `irsg@irtf.org`, the RG, and the RG Chairs.

**Comment by csperkins** [comment]
Also, we should check the message body doesn't say "The IESG has approved…"

**Comment by pselkirk** [comment]
@csperkins You wanted the email cc'd to `iab@iag.org`, but that doesn't happen for WGs? Should it happen for RGs?

**Comment by pselkirk** [comment]
Questions that might expand the scope of this ticket:

There's a second email that gets sent when the charter is approved:```

**Comment by csperkins** [comment]
@pselkirk it should copy `iab@iab.org` because the IAB approves IRTF RF Charters (whereas it's the IESG that approves IETF WG charters)

**Comment by csperkins** [comment]
```
  From: IETF Secretariat <ietf-secretariat-reply@ietf.org>
  To: <iesg-secretary@ietf.org>
  Subject: Regarding RG <acronym>: Charter state changed to "Approved"
```
This should probably be `To: irtf-chair@irtf.org, irsg@irtf.org`.


>Should other email templates be adjusted for the IRTF?

Possibly, although I'm not sure what other templates exist.

**Comment by rjsparks** [comment]
The above message goes into the secretariat's ticketing system currently and they are the _only_ recipient. It would not be correct to change that message. If we also want a message sent to the irtf-chair and irsg it should be a separate email.

cc @cindymorgan

**Comment by rjsparks** [comment]
> Should other email templates be adjusted for the IRTF?
If you see something that seems obvious, ask about it. Otherwise, keep this to the scope in the issue title please.

**Comment by rjsparks** [comment]
The above said, #6460 addresses this issue and I'm going to merge that and close this issue. Any other messages or templates that we identify can be handled in their own issues.

Also, on reflection:
>The above message goes into the secretariat's ticketing system currently and they are the only recipient. It would not be correct to change that message. If we also want a message sent to the irtf-chair and irsg it should be a separate email.

We should not send a separate email in this case - the message being modified by #6460 is enough. The message pointed to is only to trigger a process at the secretariat to followup on potential manual setup for newly formed or rechartered groups.
