### ISSUE TITLE
Submission checks don't compare submitter/author email addresses case-insensitively

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#5929]
There is at least one participant that is not able to use the submission tool because Email records have CamelCase@Address.Tld and the submitted draft has camelcase@address.tld.

**Comment by pselkirk** [comment]
After extensive review, I've determined that author case sensitivity is not a problem with either the interactive submission tool or the API. The tool does a `Person` comparison, and the API does an explicitly case-insensitive string comparison.

**Comment by rjsparks** [comment]
(for the benefit of historians): The original issue was actually a MySQL->Postgresql migration error where we left two Email objects with addresses that varied only by case. That combined with making Email.address a CIText field led to difficult to diagnose behavior. We corrected that (verifying that there were no other instances) and the reported issue for the submitter was resolved.
