### ISSUE TITLE
doc url parser accepts revision for rfcs

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#5934]
/doc/rfc8989/99/ works by unintended consequence (redirecting to /doc/rfc8989.
/doc/rfc8989/99/bibtex works (producing bibtex for rfc8989.

Both should 404 instead.

**Comment by maybe-hello-world** [comment]
For info: `/idnits2-state` too, I suppose.

**Comment by maybe-hello-world** [comment]
Clarifications:

- `/idnits2-state` should stay unchanged
- `/doc/rfc8989/<rev>` should return 404 no matter what revision number is as revisions are for drafts
