### ISSUE TITLE
Agenda: cancelling one part of a multi-group meeting doesn't cancel all

### ISSUE THREAD

**Issue by paulehoffman** [ietf-tools/datatracker#5950]
### Describe the issue

ACE/LAKE were a combined WG meeting that was cancelled. As seen in the attached image, only one is really marked as cancelled.

<img width="1008" alt="image" src="https://github.com/ietf-tools/datatracker/assets/638939/f3c93e2e-5b57-464a-b5ce-a6429a7d00a4">

Related: ACE was originally schedule later in the week, then moved. It is still shown as "rescheduled".

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
You misinterpreted what is happening, and what is currently showing is confusing.Ace _is_ meeting jointly with Lake.
I'll work with the secretariat to change the configuration of the meeting to make this more obvious.

The issue here is that "Joint-with" is a bit of a hack still.

**Comment by paulehoffman** [comment]
Oooooh, I can see that now. LAKE/ACE is meeting, but ACE is not. (And ACE was moved.) 

Proposal for this circumstance: just don't mention ACE in the WG name field anywhere in the agenda, and rely on ACE people to do a search of the body to find it. That is not optimal, but I don't see a non-confusing way to list LAKE/ACE without duplication of the whole row.
