### ISSUE TITLE
/person/<name or email> endpoint should search case-insensitive

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#5972]
Right now `/person/robert sparks` 404s.

**Comment by Godseesall** [comment]
![Screenshot_20230717_162719_Chrome](https://github.com/ietf-tools/datatracker/assets/139814447/6516d2d2-63e5-4fe1-8ba6-b7eab620a626)

**Comment by Godseesall** [comment]
I find this on my phone i have someone that has ben following me and i have the meaner on me okease help me

**Comment by Godseesall** [comment]
![Screenshot_20230717_162712_Chrome](https://github.com/ietf-tools/datatracker/assets/139814447/4fbe7418-4118-43c3-8d5b-886b4d5f2f77)

**Comment by Godseesall** [comment]
![Screenshot_20230717_162719_Chrome](https://github.com/ietf-tools/datatracker/assets/139814447/0c8af1ce-0c16-40c9-a9ab-5d6afc49759b)

**Comment by rjsparks** [comment]
closed by #6007
