### ISSUE TITLE
Weekly email status of the directorate review requests

### ISSUE THREAD

**Issue by evyncke** [ietf-tools/datatracker#5976]
### Description

(if not yet done of course), but both INT and DNS directorates would like to have an automated weekly email sent to their respective lists copying the web page information, somehow like secdir remainders/status:

https://mailarchive.ietf.org/arch/msg/secdir/7iYP3AXNZj8WeQQ8XsjfOw2Nbx8/

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This is currently not automatic for secdir - instead, Tero has a button that sends it on demand, giving him an opportunity to edit the text that's automatically generated to be sent.

The relevant code is at:
https://github.com/ietf-tools/datatracker/blob/83a13a58baec8c986d4c80b0c4df5ddf70774104/ietf/group/utils.py#L268-L270
and
https://github.com/ietf-tools/datatracker/blob/83a13a58baec8c986d4c80b0c4df5ddf70774104/ietf/group/views.py#L1746-L1847

Note in particular
https://github.com/ietf-tools/datatracker/blob/83a13a58baec8c986d4c80b0c4df5ddf70774104/ietf/group/views.py#L1816-L1820 and consider whether there should be a team specific template for the generated message.

Extending sending this message on demand for other team secretaries would be a sprint-sized task.

Automating the sending would be a little larger than sprint sized.

**Comment by rjsparks** [comment]
Also note the rather secdir specific coding in the messages...

**Comment by evyncke** [comment]
Thanks, I will have a look at it today at the Code Sprint

**Comment by evyncke** [comment]
And after looking in the code and doing some experiments, this seem to work fine except for an non-initialized variable passed to the templates.

Let's close this issue and I will open another one to fix the remaining issue.
