### ISSUE TITLE
darkmode review status badge colors need better text contrast

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#5990]
![image](https://github.com/ietf-tools/datatracker/assets/10996692/fd6030c2-7fa4-4d1a-8cfe-ee7c31fbe5f8)

Is very hard to read for me (strong protonopia) - please make the text contrast more (black might be nice).

cc: @larseggert

**Comment by larseggert** [comment]
Feel free to assign me other tickets like this @rjsparks

**Comment by larseggert** [comment]
And please include a URL with the issue.

**Comment by rjsparks** [comment]
/accounts/review/ as me (or anyone who has done a bunch of reviews).

**Comment by larseggert** [comment]
Thanks, will fix at codesprint. Please just assign any other dark mode issues to me, so I don't miss them.

**Comment by larseggert** [comment]
This got fixed in #6001.
