### ISSUE TITLE
review badges in light mode send wrong signal

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#5991]
![image](https://github.com/ietf-tools/datatracker/assets/10996692/cd6ac3c5-ffa4-478a-8876-dc1c4c362c2c)

To a strong protonope is indistinguishable from the same button with a red background, and _my_ brain says it's red and there's something wrong.

A better set of accessible colors for anywhere we're using badges to say "ok" "notice" and "error" is needed.  We might also want to make the shape or border of the badge change to help people with even further away from typical vision.

I wonder if we're using the right bootstrap classes for these semantics, or are somehow otherwise missing things they intended - it's surprising the set gives me this much trouble.

cc: @larseggert

**Comment by cabo** [comment]
I don't think I have anything but normal color vision, but I notice the black on dark green is nearly unreadable to me.
Something is definitely broken here even for me.

**Comment by larseggert** [comment]
This got fixed in #6001.
