### ISSUE TITLE
Remove the IESG Note from the IESG writeups tab

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#6013]
The field for an RFC Editor note has not been used for a long time.
Lets remove it and adjust the places (like email sent) that used it.
cc: @larseggert @evyncke @wkumari

**Comment by larseggert** [comment]
As discussed with @rjsparks, this is about removing the *IESG Note*, **not** the *RFC Editor Note**.

That is kept in `doc.note`, which is also used for notes by other approving bodies (IRTF, IAB, etc.) - should that all go? (I'd think so.)

CC @csperkins @mirjak
