### ISSUE TITLE
Automate loading past public IAB agendas into the datatracker (was Internal server error when uploading an old interim agenda)

### ISSUE THREAD

**Issue by cindymorgan** [ietf-tools/datatracker#6081]
### Describe the issue

Hi! I just tried to upload an agenda for interim-2022-iab-35 (from December 2022) and got an internal server error when trying to upload the text file. Now the IAB meetings page shows an active agenda button for that meeting that points to https://datatracker.ietf.org/doc/agenda-interim-2022-iab-35-sessa/, but it looks like the file itself didn't make it to the Datatracker.

(This is not urgent; pre-2023 IAB agendas already live in the IAB wiki, and this was just an attempt to put an older one in the Datatracker.)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This is a directory permission issue - the import of older minutes didn't anticipate that older agendas would be added later.

**Comment by rjsparks** [comment]
Per discussion with Cindy, we'll automate loading the older public agendas.

**Comment by rjsparks** [comment]
And I deleted the broken agenda-interim-2022-iab-35-sessa using the admin - the automated load will provide a correct variant.

**Comment by cindymorgan** [comment]
A list of the missing agendas and the current URLs has been added to the "www.iab.org content (as of 2022-12-12) transition plan" spreadsheet

**Comment by rjsparks** [comment]
Completed in the 11.10.0 release
