### ISSUE TITLE
improper access control

### ISSUE THREAD

**Issue by Mirsaifali** [ietf-tools/datatracker#6109]
### Describe the issue

  Current Internet-Drafts

   This summary sheet provides a short synopsis of each Internet-Draft
available within the "internet-drafts" directory at the shadow
sites directory.  These Internet-Drafts are listed alphabetically by working
group acronym and start date. Generated 2023-08-09 17:05:42 UTC.

link : https://www.ietf.org/id/1id-abstracts.txt

link : https://www.ietf.org/id/ 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
These documents are intentionally publicly available through direct access to the file system as one mechanism of many.  We openly advertise the document directories you have identified below on this web page https://www.ietf.org/how/open-records/ and explain our approach here https://www.ietf.org/privacy-statement/ .
