### ISSUE TITLE
Pill colours affecting readability

### ISSUE THREAD

**Issue by fiestajetsam** [ietf-tools/datatracker#6116]
### Describe the issue

User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0

Pills without any specific colour (falling back to grey) blend in too well with the alternating colours of tables making the text difficult to read, for example:
<img width="194" alt="image" src="https://github.com/ietf-tools/datatracker/assets/66874126/e5fbd049-7d0b-4f54-9284-1c52ce51a43e">

Possibly related to #6112 ?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
Which page/URL is that on?

**Comment by larseggert** [comment]
Also, this is possibly already fixed on the feat/dark-mode branch.

**Comment by fiestajetsam** [comment]
@larseggert the above screenshot is on the "[My Reviews](https://datatracker.ietf.org/accounts/review/)" page.

**Comment by larseggert** [comment]
Thanks! feat/dark-mode should have the fix already.

**Comment by rjsparks** [comment]
Dark-mode was released today - @fiestajetsam, does it address your concern?

**Comment by rjsparks** [comment]
I'm closing this - my inspection says that it addresses the issue - if the fix turns out to be insufficient, please reopen.
