### ISSUE TITLE
BCP11 should be RFC9281?

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#6117]
### Describe the issue

https://datatracker.ietf.org/doc/bcp11/ goes to https://datatracker.ietf.org/doc/rfc2028/ and not https://datatracker.ietf.org/doc/rfc9281/ that replaces it.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This will be corrected when feat/rfc comes in.
