### ISSUE TITLE
Account error

### ISSUE THREAD

**Issue by VMatrix1900** [ietf-tools/datatracker#6118]
### Describe the issue

The following two profiles are exactly identical: [account of 10099.com.cn](https://datatracker.ietf.org/person/yangtianle@10099.com.cn) and [account of chinamobile.com](https://datatracker.ietf.org/person/yangtianle@chinamobile.com). But account of 10099.com.cn can not receive the registration or password reset email from datatracker. The [draft](https://datatracker.ietf.org/doc/draft-shi-cats-analysis-of-metric-distribution/) submmitted using 10099.com.cn(please see the [xml file](https://www.ietf.org/archive/id/draft-shi-cats-analysis-of-metric-distribution-01.xml) is shown chinamobile.com address in the datatracker page. It seems like the two account is not merged and one account is blocked/overwrited by another account.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This has been addressed.
