### ISSUE TITLE
RFC9245 does not show Susan Harris as an author in the metadata

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#6150]
### Describe the issue

https://datatracker.ietf.org/doc/rfc9245/ does not show Susan Harris as an author in the metadata?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This hit an edge case in the code that deals with ingesting RFCs as a new version of the document - fwiw, the author set of the approved _draft_ was only Lars. I'll manually fix the DocumentAuthor set for this RFC in the datatracker. The feat/rfc work will change how we ingest RFCs and the edge will go away.
