### ISSUE TITLE
Cannot assign document to someone who has rejected the review

### ISSUE THREAD

**Issue by kivinen** [ietf-tools/datatracker#6169]
### Describe the issue

I have situation where the David Mandelberg rejected the review because he thought it was assigned to him by mistake. I explained the situation and tried to assign it back to him. The datatracker does not allow me to assign it to him, as he has rejected it before. I tried to remove the request and recreate the request and tried to assign that to him, but that failed too. His name is simply not listed in the list of reviewers I can assign to him.

I know we did ask that we will never automatically assign document back to person who has rejected it once, but the secretary should still be able to assign document to that person.

I had similar issue when I wanted to assign document to area director (at his request), but I could not as he was marked as being unavailable. I think the datatracker should still allow such assignments, but should give warning explaining the situation.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
They are slightly different, but could be combined - the distinction is who the actor is (reviewer or secretary) in overriding the rejection.
