### ISSUE TITLE
Too grey

### ISSUE THREAD

**Issue by paulehoffman** [ietf-tools/datatracker#6179]
### Describe the issue

The new color scheme for the Datatracker header is dark, so there is not enough contrast between the new background and the text. Please lighten it greatly.

<img width="754" alt="image" src="https://github.com/ietf-tools/datatracker/assets/638939/957e8a14-d4c9-41e3-8069-9bde2412b518">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
This should be already fixed by #6166

**Comment by paulehoffman** [comment]
As of right now, it is not, and I get the same screen shot as above. The page I'm on reports "Version 11.8.0 (release - b3a057d)"

**Comment by rjsparks** [comment]
You can preview the next release at dt-main.dev.ietf.org.

**Comment by paulehoffman** [comment]
The pink is better, but why have any background at all? Any background color makes the text harder to read for someone. And, yes, I'm a bit bah-humbug-y about design changes...

**Comment by paulehoffman** [comment]
I appreciate the color change, but I am now reopening this because now the "Report a bug" text is unreadable:
<img width="413" alt="image" src="https://github.com/ietf-tools/datatracker/assets/638939/be7a70cf-199d-475b-94c0-396fa09ae209">
