### ISSUE TITLE
Migrate DocHistory objects for RFCs

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#6195]
### Describe the issue

`DocHistory` objects that pertain to the RFC rather than the I-D need to be migrated to hang off the new `type_id="rfc"` `Document`. The `name` and `rfc_number` fields should be updated to match.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
D'oh - the migration so far doesn't populate rfc_number.

**Comment by rjsparks** [comment]
fixed at #6328
