### ISSUE TITLE
Migrate tags from draft to RFC Documents

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#6196]
### Describe the issue

Tags applied to drafts should be moved to the corresponding RFC document. The existing migration probably needs to be extended to do this.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
On inspecting the existing tags, I think the _only_ tags that should move are those related to errata, and there's a migration that does that now. I think we can close this.
