### ISSUE TITLE
Fix Typo On Page 38 in Database Section

### ISSUE THREAD

**Issue by xshinigamiy** [ietf-tools/datatracker#6198]
### Description

I noticed there seems to be a typo on Page number 38. 
Line says "hash structures used to store tree sections must insure" -> here _insure_ should be written as _ensure_

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Please note the text on the new issue form for the datatracker:

> Please do not report issues with the content of Internet-Drafts or RFCs using this repository. Send email to the relevant group instead. Some Internet-Drafts have their own github repositories where issues can be reported. See the datatracker's page for the I-D for links and email addresses. Errata for published RFCs are submitted at https://www.rfc-editor.org/errata.php#reportnew

You appear to be attempting to report an issue with RFC1035. You could pursue your suggested change using the RFC editor's errata system.

I am closing this as "not a datatracker bug".
