### ISSUE TITLE
Cannot switch off dark mode

### ISSUE THREAD

**Issue by toth-istvan-zoltan** [ietf-tools/datatracker#6200]
### Describe the issue

My operating system setting is dark because I want the window headers etc. not to take attention from my work. My in-application setting is light because I want to focus on that content and for me dark text on light background works best.

When looking at an RFC I haven't been able to find any way to switch it from dark mode to light mode.

I consider this a bug as it really inconvenient, nigh impossible for me to read text this way.

Operating system : Mac OS X 12.6.8
Web browser: Safari 16.6

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
Could you clarify: Does the user preference setting not work for you?

**Comment by toth-istvan-zoltan** [comment]
I don't have a user. I've came to the site from Wikipedia, following a link to an RFC.

**Comment by toth-istvan-zoltan** [comment]
Yes, it is. Sorry if I was not clear. I tried the User/Preferences and I was able to switch it to light and it kept the setting when I went back to the /doc/html. It would be beneficial to have that in the viewer as many users probably drop there from external links.

Actually, I've checked the main page to see if it is there but haven't noticed the "Preferences" under "User". It is somewhat logical, but well hidden. :)

**Comment by toth-istvan-zoltan** [comment]
I mean, I tried it now, not before opening the issue. I checked the main page before I've opened the issue but haven't figured it out.

**Comment by larseggert** [comment]
Thanks for confirming - I'll see if I can add a dark mode toggle on the document view.

**Comment by toth-istvan-zoltan** [comment]
Thank you, that would be very helpful.
