### ISSUE TITLE
Hide some process metadata for published RFCs

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#6201]
### Description

For example, in a collapsible that is by default hidden.

Such as the things under "Stream", "IESG", "IANA" and the directorate reviews.

CC @cabo 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This is best handled in /feat/rfc rather than in main (since we're making RFCs a much more distinct thing there already).

**Comment by rjsparks** [comment]
Sorry for the extra state change noise - closing this as addressed (in branch feat/rfc), but you won't see the effect in production until feat/rfc is merged and deployed.
