### ISSUE TITLE
Role confusion (author, responsible AD)

### ISSUE THREAD

**Issue by cabo** [ietf-tools/datatracker#6230]
### Describe the issue

A couple of days ago, I requested publication of a document:

https://datatracker.ietf.org/doc/search?name=oscore-ed&sort=&rfcs=on&activedrafts=on

The responsible AD entered by datatracker is @fpalombini -- looks good on first glance.
But @fpalombini also is first author.
Should datatracker recognize this situation and do something different?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Not a datatracker code bug - it's an IESG decision - The IESG can (and probably will) choose to change the responsible AD, but the requested default is to stay with the AD responsible for the group until that AD has a chance to talk to the IESG about who should take responsibility. (It is often, but not always, the co-ad, and for some areas, there are more than one potential co-ad that might take the role).

**Comment by cabo** [comment]
Thank you for the explanation!
