### ISSUE TITLE
Some meeting participants listed twice on attendees list in proceedings

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#6265]
### Describe the issue

The attendees page in the proceedings page for 117 (and perhaps others) lists many, but not all, people twice. Scanning the list, it appears plausible that this is related to hackathon registration, but that's just a guess.

https://datatracker.ietf.org/meeting/117/proceedings/attendees/

Not exactly related, but in the same space as #5928

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
Investigating, the attendees list is pulled from a `DBTemplate` that is generated by the `finalize(meeting)` method. That retrieves the attendees list from the `settings.STATS_REGISTRATION_ATTENDEES_JSON_URL` and renders the list into the `DBTemplate`.

Fixing this will require regenerating or editing the template. Going forward we could add a de-duplicating step to `finalize(meeting)`, but I'd say the problem is duplicates coming from the registration system.

**Comment by rjsparks** [comment]
It should instead start using the MeetingRegistration/Attended tables rather than calling the registration system for data that we've already been given.

**Comment by rjsparks** [comment]
cc: @rpcross

**Comment by rjsparks** [comment]
We should look at re-using and specializing how the nomcom eligibility code determines "attended". On this page, we probably want to leave a mark if the attendance counts towards nomcom eligibility or not.

**Comment by rpcross** [comment]
**Scope Question**
The attendees view currently has two display paths, for meeting.proceedings_format_version == 1 (96 and older), redirect to apache served static files. Else use dbtemplate generated from Reg API. Are we addressing the second path, 97 and above, with this change, or attempting more? (MeetingRegistration records go back to meeting 72)
https://github.com/ietf-tools/datatracker/blob/main/ietf/meeting/views.py#L3847

**MeetingRegistration (MR) Query by Meeting**
72-106: registered attendees who checked in to the meeting. MR, reg_type=None, checkedin=True
107: First virtual meeting. MR, reg_type=None, attended=True
108-112: MR, reg_type=remote, attended=True 
113+: MR either remote+attended or onsite+checkedin

If we massage the data to populate reg_type (< 107=onsite, 107=remote) the last detailed query (from 113+) should suffice for all meetings.

**Comment by rjsparks** [comment]
I suggest doing this in two steps - fix the immediate problem for the current and most recent meetings first - then address the older ones.
