### ISSUE TITLE
Review action holder manipulation on draft-revision submission.

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#6266]
From @cabo at https://mailarchive.ietf.org/arch/msg/tools-discuss/kRL2lI4KASkF040nPkpdP6I_Gu8:

> https://datatracker.ietf.org/doc/draft-ietf-lake-edhoc/ is in state Publication Requested::AD Followup
> 
> You would expect that this makes the AD action holder?
> 
> No.  When a new version was posted, the state changed, and the action holder was removed:
> 
> "Removed all action holders (IESG state changed)”
> 
> So the AD needs to do the followup now but isn’t an action holder?
> 
> (I had the same problem earlier with one of my drafts, so this is not a fluke.)

**Comment by jennifer-richards** [comment]
The action holder updates are controlled by [`update_action_holders()`](https://github.com/ietf-tools/datatracker/blob/bae204862d1fa589a45fe39a8aa19b7c40bbb7d1/ietf/doc/utils.py#L463-L511). When the state changes, it clears the action holders when the new state is in `DocumentActionHolder.CLEAR_ACTION_HOLDERS_STATES`, which is currently
```python
    CLEAR_ACTION_HOLDERS_STATES = ['approved', 'ann', 'rfcqueue', 'pub', 'dead']  # draft-iesg state slugs
```

For this draft, the holders were cleared because it entered the `"approved"` state.

**Comment by cabo** [comment]
It now is approved, but surely wasn't on July 07 when I made this observation.

https://datatracker.ietf.org/doc/draft-ietf-lake-edhoc/history/

2023-07-07 | 20 | (System) | Removed all action holders (IESG state changed)
-- | -- | -- | --
2023-07-07 | 20 | (System) | Sub state has been changed to AD Followup from Revised I-D Needed
2023-07-07 | 20 | Göran Selander | New version available: draft-ietf-lake-edhoc-20.txt

2023-07-07
20	(System)	Removed all action holders (IESG state changed)
2023-07-07
20	(System)	Sub state has been changed to AD Followup from Revised I-D Needed
2023-07-07
20	Göran Selander	New version available: [draft-ietf-lake-edhoc-20.txt](https://datatracker.ietf.org/doc/draft-ietf-lake-edhoc/20/)

**Comment by jennifer-richards** [comment]
Ah, had not noticed the date on your email and had not looked back far enough through the history to see the previous clearing of action holders.

The issue is that the code only adds the AD as an action holder if the state changes. The "sub state" is handled separately - removing the "need-id" causes the authors to be dropped but there's no corresponding rule to add the AD for this transition.

**Comment by B6188556** [comment]
> From @cabo at https://mailarchive.ietf.org/arch/msg/tools-discuss/kRL2lI4KASkF040nPkpdP6I_Gu8:
> 
> > https://datatracker.ietf.org/doc/draft-ietf-lake-edhoc/ is in state Publication Requested::AD Followup
> > You would expect that this makes the AD action holder?
> > No.  When a new version was posted, the state changed, and the action holder was removed:
> > "Removed all action holders (IESG state changed)”
> > So the AD needs to do the followup now but isn’t an action holder?
> > (I had the same problem earlier with one of my drafts, so this is not a fluke.)

I'm the credit union owner!

**Comment by B6188556** [comment]
> From @cabo at https://mailarchive.ietf.org/arch/msg/tools-discuss/kRL2lI4KASkF040nPkpdP6I_Gu8:
> 
> > https://datatracker.ietf.org/doc/draft-ietf-lake-edhoc/ is in state Publication Requested::AD Followup
> > You would expect that this makes the AD action holder?
> > No.  When a new version was posted, the state changed, and the action holder was removed:
> > "Removed all action holders (IESG state changed)”
> > So the AD needs to do the followup now but isn’t an action holder?
> > (I had the same problem earlier with one of my drafts, so this is not a fluke.)

I'm the credit union owner!

**Comment by B6188556** [comment]
> From @cabo at https://mailarchive.ietf.org/arch/msg/tools-discuss/kRL2lI4KASkF040nPkpdP6I_Gu8:
> 
> > https://datatracker.ietf.org/doc/draft-ietf-lake-edhoc/ is in state Publication Requested::AD Followup
> > You would expect that this makes the AD action holder?
> > No.  When a new version was posted, the state changed, and the action holder was removed:
> > "Removed all action holders (IESG state changed)”
> > So the AD needs to do the followup now but isn’t an action holder?
> > (I had the same problem earlier with one of my drafts, so this is not a fluke.)

I'm the credit union owner! [What's 5geb    CLEAR_ACTION_HOLDERS_STATES = ['approved', 'ann', 'rfcqueue', 'pub', 'dead']  # draft-iesg state slugs](url)
