### ISSUE TITLE
xml parsing heuristics crash if a reference has anchor "STD", "FYI", "RFC", or "BCP"

### ISSUE THREAD

**Issue by martinthomson** [ietf-tools/datatracker#6267]
### Describe the issue

I'm trying to submit a draft.  On my first attempt, I realized that I tagged the wrong commit and missed some important changes from a co-author.  So when I received the email, I cancelled the submission.

I have since tried twice (with the right commit).  Both have gotten to the point where I receive an email and both have failed when I requested that the draft be published.

For my second retry attempt, the failed submission was apparently still in progress, so that failed.  I then cancelled the first retry and tried a third time.  That has also failed.  I will leave things in that state for now.

https://datatracker.ietf.org/submit/status/136389/ (original, cancelled)
https://datatracker.ietf.org/submit/status/136390/ (retry 1, failed, also cancelled)
https://datatracker.ietf.org/submit/status/136403/ (retry 3, failed)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
I think the cancellation is a red herring - the issue I see is that the draft has a reference like `<reference anchor="STD">`. The code that parses references assumes that an anchor starting with "STD..." will have a decimal number after it (like "STD123") and naively tries to convert the value to an integer. It (mis-)handles RFC, BCP, and FYI anchor prefixes in the same way.

Until we get that fixed, changing the anchor either to look like `STD123` or not to be `STD` should allow the draft to be confirmed.

**Comment by martinthomson** [comment]
Thanks for finding that.  I will fix that and re-post.
