### ISSUE TITLE
Install fonts from xml2rfc-fonts repository

### ISSUE THREAD

**Issue by kesara** [ietf-tools/datatracker#6294]
### Description

In order to generate internet draft PDFs with correct fonts, use fonts from [xml2rfc-fonts](https://github.com/ietf-tools/xml2rfc-fonts) font repository.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
Might want to add https://fonts.google.com/noto/specimen/Noto+Emoji to xml2rfc-fonts, due to #6050.

**Comment by kesara** [comment]
> Might want to add https://fonts.google.com/noto/specimen/Noto+Emoji to xml2rfc-fonts, due to #6050.

It is a separate project, I created https://github.com/ietf-tools/xml2rfc-fonts/issues/1 to add emoji fonts from Noto Emoji Project.
