### ISSUE TITLE
Allow editing of interim meeting subject lines / Edits to RSWG interm meeting announcement subject

### ISSUE THREAD

**Issue by cindymorgan** [ietf-tools/datatracker#6310]
### Describe the issue

The subject line for interim meeting announcements is not editable by the Secretariat.

For RSWG (admittedly, not a regular group), the subject line is:

  RFC Series Working Group (rswg) EDWG Virtual Meeting: 2023-09-28

That would probably make more sense as something like:

  RFC Series Working Group (RSWG) Virtual Meeting: 2023-09-28

(From https://datatracker.ietf.org/meeting/interim/announce/interim-2023-rswg-01)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
And while we're there, we can special case the Subject construction for RSWG
