### ISSUE TITLE
Remove the "AD is Watching" draft-iesg state.

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#6316]
### Describe the issue

Putting a doc into "AD is watching" state makes the AD the action holder. That should IMO not happen, because watching does not imply any action being needed by the AD.

Example: https://datatracker.ietf.org/doc/draft-halpern-gendispatch-antitrust/

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
I am becoming more convinced that AD is watching is not an IESG state and that what it is being used to achieve should be provided a different way.

**Comment by larseggert** [comment]
It's IMO redundant now since we have the ability to tag I-Ds.

**Comment by jennifer-richards** [comment]
Is this worth fixing or should we do away with the state?

If it's to be fixed, preventing the AD from becoming an action holder is easy but the straightforward change will clear out the action holders. It would not be difficult to have it leave the action holders alone but it'd be a new code path.

**Comment by rjsparks** [comment]
Lets ask the IESG if we can do away with the state and make no other changes.
cc: @evyncke , @wkumari

**Comment by rjsparks** [comment]
@evyncke, @wkumari; nudge

**Comment by evyncke** [comment]
For me, let's simple remove this state, it is rarely used and AD can easily tag I-D to appear in the watch list.

**Comment by rjsparks** [comment]
We will do away with the state - editing the issue title to reflect that.
