### ISSUE TITLE
Documents help

### ISSUE THREAD

**Issue by Jayboyokok** [ietf-tools/datatracker#6319]
### Describe the issue

I have messed up RFC documents trying to update my network, so that all messages will come through actually. I believe my area home location was blocked and trying to get more information. No one will FU to my inquiries. I want forms back to default and help understanding why my home location address is blocked 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This is indistinguishable from spam. If there is a real issue behind this contact support@ietf.org
