### ISSUE TITLE
Improve "responsible AD" option on Datatracker

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#634]
`keyword_sprint` `type_enhancement`   |    by shane@time-travellers.org

___

There's a separator in the "responsible AD" list when you are using the 'advanced search' on the Datatracker. It's -------- or the equivalent.

First problem, is that it can be selected like any other option. It should be tagged 'disabled'. That won't work in IE, at least not old versions of IE, but it shouldn't hurt anything.

Second problem, it is ugly. Google shows a number of hacks to try to get around this, by stretching fonts or pixels to convert them into a line.

Finally, it is non-obvious to me why it's there, although surely there is some logic to it. I'm not sure how to fix this, although perhaps this could be done by disabled labels, like this:

```
+--------------------+
| Important AD       | <- disabled, maybe bold and/or italic
|   Joe Schmoe       | <- enabled, indented a bit
|   Francis Farmer   |
|   Anon E. Mouse    |
| Bottom Feeders     | <- disabled, maybe bold and/or italic
|   Ipso Facto       | <- enabled, indented a bit
|   Quid Pro Quo     |
|      .             |
|      .             |
```

Probably the final approach is the best, although someone would have to figure out why there is the separator in the first place to properly label the two sections. :)

___
_Issue migrated from trac:634 at 2022-03-04 01:47:35 +0000_

**Comment by rjsparks** [comment]
Closing as OBE (maybe in a horrible way) by the bs5 facelift - the set of ADs in that dropdown are still ordered, but the separator has simply been removed.
