### ISSUE TITLE
Scheduling interim meetings in series doesn't work

### ISSUE THREAD

**Issue by apelov** [ietf-tools/datatracker#6344]
### Describe the issue

When requesting a series of virtual interim meetings, only the first session is scheduled, all others are ignored.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
Thank you for the report. I believe this is a duplicate of #5595 - please reopen if I'm mistaken.
