### ISSUE TITLE
Duplicate HTML ID in`templates/group/all_photos.html`

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#6355]
### Describe the issue

See https://github.com/ietf-tools/datatracker/actions/runs/6263672611/job/17008584937?pr=6345

My guess is that there is an internationalized last name with a `last_initial` that gets Romanized to "c", and also some other name with a `last_initial` of "c".

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Since the runs will be removed after a few days, the important part Lars is pointing to is
```
 /tmp/html-validate-2i77axa2/52452af37bec4d14/ietf/templates/group/all_photos.html:
          <h2 class="mt-4" id="c">C</h2>
          ^^^^^^^^^^^^^^^^^^^^^^^^
          info: The first occurrence of ID 'c' was here.


/tmp/html-validate-2i77axa2/52452af37bec4d14/ietf/templates/group/all_photos.html:
</div>
            
        </div>
    
        <h2 class="mt-4" id="c">Č</h2>
                             ^
                             no-dup-id: Duplicate ID "c" on line 642:30
```
