### ISSUE TITLE
I've been trying to get text messages and and calls all day. 

### ISSUE THREAD

**Issue by ghost** [ietf-tools/datatracker#6361]
### Description

You guys. I'm not sure what your impression of me is at this point, but this clearly isn't working. My public IP address seems to now be attached to wifi, which I don't have or use. I only have access to my private network. You moved my device location to show in Florida, which I don't understand. The smsc messages number (+12063130004",145) is stating not a service when I call. I'm assuming my device number has prefix or symbol added via keyboard. Prevent my connection.  This isn't fair. I don't care to do anything other than receive my text messages, calls, and move on with my weekend. Initially my IP6 was showing error format, so that's where I started searching for solutions. No 1 would just take a second to explain way yo rectify, so I've been displayed.  There's to many codes and stipulations involved via chrome. Rfc I believe Apache licenses my messaging app and my apn starts with http, so all the requirements in chrome as if I'm employed at penguin is blocking something. I've received  3 text from the same individuals since early this a.m. Did a factory reset, but still nothing everysince you implemented change. Why can't my local IP address be utilized like normal.  My device is only 4g LTE, so you forcing the ip6 to run in chrome browser + exchange is sitting me up for failure. I'm will to compromise privacy to receive my sms. You all are watching observing anyway, so ,🙄.  I'm not reaching out because I'm bored or to be a irritate. This is beyond depressing. What is the platforma goal? If you have some suspensions about me, just ask. I'm transparent

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by vonj95** [comment]
![Screenshot_20230922-172712](https://github.com/ietf-tools/datatracker/assets/145781214/3e1d1048-6fc1-409e-a1dc-1d898d433be1)

**Comment by vonj95** [comment]
My residence is in Atlanta, GA 30311

**Comment by vonj95** [comment]
FEATURES IN THIS RELEASE:
*†*****URL Standard-compatible IPv4 embedded IPv6 host parser*******
Deprecate TLS SHA-1 server signatures
*******RFC 7616 Digest auth: Support SHA-256 and username hashing********
X25519Kyber768 key encapsulation for TLS



Deprecated
CSS property -webkit-highlight
[WebRTC] Unship callback-based legacy getStats()
Enabled by default
Array grouping
Change beforeunload handler dialog condition
Clear Client Hints via Clear-Site-Data header
Clear-Site-Data header wildcard syntax
contain-intrinsic-size: auto none support
CSS cap and rcap font units
CSS overlay property
CSS @starting-style Rule
CSS Subgrid
CSS text-wrap: pretty
CSS transition-behavior property
CustomElementsGetName

Iterator helpers
Make CaptureController derive from the EventTarget interface
PerformanceResourceTiming deliveryType
Per-frame quantizer in VideoEncoder
Port overflow check in URL setters
Protected Audience directFromSellerSignals via HTTP response headers
Removal of WebRTC getStats datachannelIdentifier -1
Removal of WebRTC getStats encoderImplementation/decoderImplementation "unknown"

TLS Encrypted Client Hello (ECH)
URL: Allow "%00" as a valid URL path

WebHID in Extension Service Workers
WebRTC RTP header extension control
WebUSB exclusionFilters option in requestDevice()
In developer trial (Behind a flag)
Deprecate unload event
Media Queries: prefers-reduced-transparency feature
Promise.withResolvers
Storage Access API with Prompts
Origin trial
Compression dictionary transport with Shared Brotli and Shared Zstandard
Deprecate and Remove WebSQL
Tabbed web apps

**Comment by vonj95** [comment]
Does any of this contradict. Plus google is my host DNS. That's who pings. Why is cloudflare president #
![Screenshot_20230922-200851](https://github.com/ietf-tools/datatracker/assets/145781214/eac087e8-e7da-4b1f-9ea8-29e469c1f071)

**Comment by vonj95** [comment]
See. Text just came through. Omg!!!!. Its bitte sweat. I apologize for any grief or disturbance

**Comment by vonj95** [comment]
I'm attempting to log into google account. Does this make any sense? I'm not crazy. Chrome is recognizing the device that's in my very hand as multiple separate devics. Its not just me

**Comment by vonj95** [comment]
![Screenshot_20230922-202350](https://github.com/ietf-tools/datatracker/assets/145781214/178bdb7b-2eb2-4981-a270-14c9f7d5d6be)

**Comment by vonj95** [comment]
Does this mean my device was cloned. It that way my batty want stay charged?

**Comment by vonj95** [comment]
![Uploading Screenshot_20230922-205603.png…]()

**Comment by richsalz** [comment]
I am sorry you are going through what seems to be a tough time.  This respository is for the "IETF datatracker" the content-management system that powers https://datatracker.ietf.org  We can't help you.  Good luck.
