### ISSUE TITLE
XML uploads not working

### ISSUE THREAD

**Issue by waldemara** [ietf-tools/datatracker#6373]
### Describe the issue

Upload of XML formatted drafts are rejected because of incorrect mime type. I tried many browsers, chrome, firefox, edge, linux, windows, you name it. The result is the same, draft is rejected because of mime type evidently detected as text/plain.  I think the draft submission tool should not rely on mime types. It checks the document in great detail anyway. 

The tool should not reject perfectly good drafts based on (incorrectly reported)  mime types.  As far as I'm concerned, this is a bug.

I know, the tool proposes to upload text files if xml does not work. I am forced to use this workaround. This is not ideal.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This will change when we are able to change our underlying infrastructure (see the recent RFPs if you are curious).
In the meantime, in many cases, there is a thing that is irritating libmagic that can be avoided. Look in your xml to see if you have 

`<?xml version="1.0" encoding="utf-8"?>`

and try changing it to

`<?xml version='1.0' encoding='utf-8'?>`

(Note changing double-quotes to single-quotes).

Yes, this is _not_ a solution to the problem, only a workaround (and a better workaround than submitting text).

**Comment by waldemara** [comment]
Yes, it worked. Thank you.
I understand, this will be fixed. I'm fine with this answer.
Maybe a note about the quotes on the draft submission page?? 
Anyway, we can close this issue.
