### ISSUE TITLE
Can you please help me

### ISSUE THREAD

**Issue by ghost** [ietf-tools/datatracker#6415]
### Describe the issue

I've been trying to restore original ietf document that allows to device to operate smoothly. I've chosen so many and think it's effecting my network. I have no idea what I'm doing. Can someone please take a look. I barely get text messages to my device. I live in Atlanta, GA, but seems my location is showing elsewhere. How do I restore to default draft

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Jayboyok43** [comment]
![Screenshot_20230930-221842](https://github.com/ietf-tools/datatracker/assets/146604630/fbd5c0ee-9ec3-42d5-85df-f0a50120222e)

**Comment by Jayboyok43** [comment]
![Screenshot_20230930-221723](https://github.com/ietf-tools/datatracker/assets/146604630/5244d9ac-afaf-45fc-b870-409c16f8d149)

**Comment by Jayboyok43** [comment]
![Uploading Screenshot_20230930-215356.png…]()

**Comment by Jayboyok43** [comment]
![Screenshot_20230930-220358](https://github.com/ietf-tools/datatracker/assets/146604630/aca54b30-b10b-4ac4-a1b5-1eb9e25c9bec)

**Comment by Jayboyok43** [comment]
Please help. None of my social apps run
