### ISSUE TITLE
Agenda tool not readable in Dark mode

### ISSUE THREAD

**Issue by dhruvdhody** [ietf-tools/datatracker#6427]
### Describe the issue

Use the 117 link as a reference https://datatracker.ietf.org/meeting/117/agenda/lflynn@amsl.com/preprelim1/edit when the preference is set for the dark mode - 

![Screenshot 2023-10-04 at 10 10 18 AM](https://github.com/ietf-tools/datatracker/assets/8587468/e03f017b-c32a-47a9-bb27-376c5abeb784)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
This was fixed by #6428.
