### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by mario-loffredo** [ietf-tools/datatracker#6453]
### Describe the issue

Can't sign in. Started password reset but didn't receive the email.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Your best option is to follow this advice that was on the page you used to submit this issue:

>If you are having trouble logging into the datatracker, please do not open an issue here. Instead, please send email to [support@ietf.org](mailto:support@ietf.org) providing your name and username.

Please move your request there (we'll need the username you are trying to login with to be able to diagnose).

I'm closing the issue here.
