### ISSUE TITLE
I'm not finding archived internet-drafts that I've written

### ISSUE THREAD

**Issue by flyinhome** [ietf-tools/datatracker#6461]
### Describe the issue

I searched for expired internet drafts with my name as author, and got no hits.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
More detail please.

Are you using the main search page? Did you use advanced search to tell it to include expired I-Ds in the search?

https://datatracker.ietf.org/doc/search?olddrafts=on&by=author&author=Keith+Moore returns non-empty. Are there drafts missing from what it returns?

**Comment by rjsparks** [comment]
I'm closing this as OBE. If there's still something wrong, reopen it and provide more detail please.
