### ISSUE TITLE
Conflict review request not changing state for ISE

### ISSUE THREAD

**Issue by elear** [ietf-tools/datatracker#6474]
### Describe the issue

When the ISE clicks the button to request an RFC 5742 conflict review, the document state should change to "In IESG Review".  This isn't happening, and it is a regression.  I had to set the status manually for the last two documents I sent over, draft-pkcs12-gost and draft-makarenko-gost2012-dnssec.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
The state should not change. And you shouldn't change it to "In IESG Review", because that is entered when the AD who did the conflict review puts it up for ballot.

**Comment by pselkirk** [comment]
I'm not saying you're wrong about it being a regression, but I don't see it in the code. Be that as it may, I recently made a similar change for the IRTF in #3469 - see his [requirements](https://github.com/ietf-tools/datatracker/issues/3469#issuecomment-1682542188). I could easily extend that to the ISE. The one wrinkle is what the state should be upon review completion - ISE doesn't have an equivalent to the "Waiting for IRTF Chair" state.

**Comment by elear** [comment]
I don't have a state similar to "Waiting for ISE", but otherwise what you did for #3469 looks good.  Yes please.
