### ISSUE TITLE
A system error occurred while processing the submission?

### ISSUE THREAD

**Issue by ju7ien** [ietf-tools/datatracker#6519]
### Describe the issue

Automatically cancelled submission while uploading an I-D: https://datatracker.ietf.org/submit/status/137822/

The XML file I've used was converted from v2 to v3 using the xml2rfc option. The file may have something wrong, but the "system error" doesn't provide any clue on what to change to make it work...

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
See also #5696 (would mark this duplicate and close it, but we'll help with the draft content first if we can)

**Comment by jennifer-richards** [comment]
The actual failure was
```
Error: Expected <rfc> version="3", but found "4"
```
That indicates that the `version` attribute in the `<rfc>` tag was set incorrectly. Try setting it to `version="3"` and see if that works.

**Comment by jennifer-richards** [comment]
(that version is the RFC XML version, not the version of the I-D)
