### ISSUE TITLE
States in Conflict Review listing of AD Dashboard are not in the right order

### ISSUE THREAD

**Issue by rdanyliw** [ietf-tools/datatracker#6528]
### Describe the issue

In the "Conflict Review State Counts" table of the AD Dashboard (https://datatracker.ietf.org/doc/ad), the counts of conflict per state are listed.  The columns, each representing a state, should be in the progression by which the states are used.  A conflict starts with "Needs Shepherd" --> "AD Review" --> "IESG Evaluation", etc.  To that end, "Needs Shepherd" should come before "AD Review" (i.e., swap the order of these two columns).

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
code should be leveraging this:
```
>>> State.objects.filter(type="conflrev").order_by("order").values_list("slug","order")
<QuerySet [('needshep', 1), ('adrev', 2), ('iesgeval', 3), ('defer', 4), ('appr-reqnopub-pr', 5), ('appr-noprob-pr', 6), ('appr-reqnopub-pend', 7), ('appr-noprob-pend', 8), ('appr-reqnopub-sent', 9), ('appr-noprob-sent', 10), ('withdraw', 11), ('dead', 12)]>
```
