### ISSUE TITLE
Allow entering text directly instead of uploading a file for the agenda

### ISSUE THREAD

**Issue by aaronpk** [ietf-tools/datatracker#6532]
### Description

It would save a step to have a text field for editing an agenda inline instead of having to first create a file on my computer and upload it.

<img width="1077" alt="image" src="https://github.com/ietf-tools/datatracker/assets/113001/6e9032bb-fa26-42b7-80fc-25786b34127e">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
We have a similar field for entering reviews - we can provide one here - but be wary - it is only really usable for cut-paste - we _don't_ have keystrokes being stored serverside (or even in a cookie) while editing, so a closed browser tab will lose any typing work.

**Comment by aaronpk** [comment]
That's perfectly fine, thanks! This will also help make quick edits to the agenda a lot easier!
