### ISSUE TITLE
Disclaimer banner for unadopted I-Ds

### ISSUE THREAD

**Issue by rdanyliw** [ietf-tools/datatracker#6539]
### Description

(The design and text of this enhancement has the consensus of the IESG, and concurrence of the IETF, IAB, IRTF and ISE stream managers)

Create a banner in the datatracker with the following text when the draft is active and the "RFC Stream" field = "None":

==[ banner text ]==
Currently, this document is an Internet-Draft (I-D) not an RFC. Anyone may submit an I-D, no prior permission or membership is required. This individual I-D is not endorsed by the IETF and has no formal standing in the [IETF standards process](RFC2026).
==[ banner text ]==

Notionally the display of the banner is sketched at https://docs.google.com/presentation/d/1bg9V2GFbHbWQ1LrJ3w6EuAxiKjgm6pmRuUfCTwftDWM/edit#slide=id.g23f74cb6a64_0_22.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
The logic on when to show this banner is more complicated than stream==None or not.

The IETF stream, in particular, has several "pre adoption" stream states, and a document in those states is in the stream.

See https://datatracker.ietf.org/help/state/draft-stream-ietf

At what point does this label get applied? I suspect the label should still show for "Candidate for adoption" and "Call for adoption issued".  Should it show for "Adopted for information only"? Should it show for "Adopted by a WG" state that's different from "WG Document"?

cc: @larseggert
