### ISSUE TITLE
Improvements for interims doing unintuitive things to sessions at full ietf meetings

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#6542]
![image](https://github.com/ietf-tools/datatracker/assets/10996692/03c9fb91-cc90-4b9f-9515-17fb1f6fd182)

What's the 02:00 supposed to convey?

cc: @larseggert

**Comment by larseggert** [comment]
Which view is this?

**Comment by rjsparks** [comment]
https://datatracker.ietf.org/group/tools/meetings/
