### ISSUE TITLE
Query string for picking sessions from schedule doesn't seem to work

### ISSUE THREAD

**Issue by squarooticus** [ietf-tools/datatracker#6544]
### Describe the issue

The method we use internally for auto-generating schedules from a list of working group names is not producing the expected results. For instance:

https://datatracker.ietf.org/meeting/118/agenda?show=mops,6man,tsvwg,cfrg,mboned,nwcrg,iccrg,ccwg,quic,moq,ietf-sessc

shows me an agenda that is missing several of the sessions. I see only mops, ccwg, 6man, mboned, and cfrg, while I know quic, moq, tsvwg, and the Plenary are also happening. I also tried this in a private window (i.e., with no cookies or local state) and confirmed the same behavior.

This worked fine up through IETF 117.

![Screenshot_20231025_212426](https://github.com/ietf-tools/datatracker/assets/3170247/03e198e4-3743-4496-95b6-55f378650894)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
I am able to reproduce what you describe. It looks like individual sessions are being enabled/disabled strangely.

As a quick workaround, does clicking "Discard" in the "Session selection" box on the right-hand side show what you expect?

**Comment by squarooticus** [comment]
No. not completely. It restores some of the sessions, but not all.

**Comment by jennifer-richards** [comment]
This is what I see - do you see the same? I don't see any missing sessions compared to the unfiltered agenda (noting that nwcrg and iccrg appear in your example URL but do not have any sessions on the agenda).

<img width="702" alt="image" src="https://github.com/ietf-tools/datatracker/assets/19472766/b2aefb4b-e081-4f2c-adc2-4aa96ba68489">

**Comment by squarooticus** [comment]
When I hit "discard" from the link https://datatracker.ietf.org/meeting/118/agenda?show=mops,6man,tsvwg,cfrg,mboned,nwcrg,iccrg,ccwg,quic,moq,ietf-sessc, I now see the entire meeting agenda.
![Screenshot_20231026_112936](https://github.com/ietf-tools/datatracker/assets/3170247/d42d9fb6-e605-4bf1-8eed-fa115f44e747)

**Comment by jennifer-richards** [comment]
Ah, yes, I do too. I was being bamboozled by side effects of other testing. Thank you for the follow up.

**Comment by jennifer-richards** [comment]
@NGPixel helped me notice that you're using `?show=` in your querystring. That selects individual sessions. To select groups, you want to use `?filter=`, so https://datatracker.ietf.org/meeting/118/agenda?filters=mops,6man,tsvwg,cfrg,mboned,nwcrg,iccrg,ccwg,quic,moq,ietf-plenary is probably the URL you want.

(note also that `ietf-sessc` is changed to `ietf-plenary` in the string)

If you build a set of filters in the agenda UI, you can click the "Share" button above the "Filter Areas + Groups" widget and it will show you a URL corresponding to what you've selected. That might be useful in teaching your generator how to generate the URLs if it's ambiguous.

**Comment by squarooticus** [comment]
Great, that works. I'll update our generator. Thanks!

Kyle
