### ISSUE TITLE
draft-ietf-rtgwg-vrrp-rfc5798bis-11 should inherit IPR declarations from RFC 5798. 

### ISSUE THREAD

**Issue by aceelindem** [ietf-tools/datatracker#6557]
### Describe the issue

A document that obsoletes another document should inherit the IPR declarations. 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
cc: @evyncke @wkumari : question for the IESG ☝️

**Comment by larseggert** [comment]
I don't think this should be automatically done. Whether IPR applies on the new document depends only on its contents.

**Comment by aceelindem** [comment]
Well, in most cases of BIS documents the IPR applies. We can’t depend on the original IPR owner to issue new statements.

**Comment by larseggert** [comment]
We need to rely on them. We can't simply make up disclosures for them, it creates a legal risk for us.

**Comment by rjsparks** [comment]
@aceelindem  : Going to close this as wont-fix. If you end up convincing the IESG differently, reopen it.

**Comment by jgscudder** [comment]
> I don't think this should be automatically done. Whether IPR applies on the new document depends only on its contents.

Yes, but. Going from a 00 to a 01, we inherit IPR... but the contents could have changed in some material way. Sometimes the contents change _a lot_ between draft versions. Yet, we assume they didn't. I agree that merely having the tag "obsoletes" is not enough to create the presumption that the IPR on the obsoleted document would apply -- I'm sure I can find examples where that wouldn't be the case at all. But in the case of a bis (which is what this issue refers to), I think the relationship is more like that between version N and version N+1 of a draft, i.e. ISTM it would be equally reasonable to presume prior IPR also applies.

Whether it's practical for the tooling to draw that distinction or not is another question. I suppose matching on "[0-9]+bis" is probably a pretty reliable heuristic, but it does then come back to Lars's point that it might create some kind of jeopardy if we started doing automatic disclosures based on a heuristic. Maybe what this ends up being, is an argument that we should have some structured way to identify a document as a bis and capture its ancestry. (To make matters worse, I can think of at least one example of a bis that has multiple RFC ancestors, that it proposes to combine.) If we had that data then I would feel more confident making the case that we should do as Acee suggests.

**Comment by evyncke** [comment]
Even for a -bis document, the "call for IPR" is still done. Perhaps should the IESG issue yet another guideline to request the shepherd to contact not only the -bis authors but also the original ones ?

One case where a non-automated procedure is probably more accurate.

**Comment by aceelindem** [comment]
> On Nov 3, 2023, at 03:06, Eric Vyncke ***@***.***> wrote:
> 
> 
> Even for a -bis document, the "call for IPR" is still done. Perhaps should the IESG issue yet another guideline to request the shepherd to contact not only the -bis authors but also the original ones ?
> 
This is a very bad idea - the fact that the original authors are not included is many times because they have dropped off the grid.
