### ISSUE TITLE
Dick Hardt was not with Microsoft while writing RFC 8725

### ISSUE THREAD

**Issue by cabo** [ietf-tools/datatracker#6575]
### Describe the issue

https://datatracker.ietf.org/doc/html/rfc8725

The top header shows D. Hardt being with Microsoft.

https://www.rfc-editor.org/rfc/rfc8725.txt
or
https://www.rfc-editor.org/rfc/rfc8725.html

make clear he wasn't at the time.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
CC @martinthomson

**Comment by martinthomson** [comment]
I see what is going on.  I can fix this with a minimum height rule.

**Comment by martinthomson** [comment]
I've added a fix for this that should help.

**Comment by larseggert** [comment]
Got a pointer? I'll import to DT then.

**Comment by rjsparks** [comment]
https://github.com/martinthomson/rfc-txt-html/commit/32f8003712fc27519111d8fa5eb79f23d1619bed
