### ISSUE TITLE
Document history not showing previous draft names on feat/rfc branch

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#6579]
### Describe the issue

Drafts that, e.g., started as individual drafts, were then adopted by a wg, then published as an RFC should show this in the history graph on the doc info page. They do this on the main branch but not the feat/rfc branch.

Example is rfc9370

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Fixed by #6646
