### ISSUE TITLE
Nomcom references (in announcement page) is outdated

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#6581]
### Describe the issue

The file `templates/nomcom/announcements.html` only lists 8713; it should also list 9389.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
addressed by #6583
