### ISSUE TITLE
Double entries for RFCs in group documents list on feat/rfc

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#6582]
### Describe the issue

RFC documents are listed twice in the last section of the group documents page. They appear once for the RFC and once for the draft that became that RFC. These should be merged into a single entry.

@kivinen 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This appears only to be in the "Related Internet-Drafts" section. Production shows RFCs in this section - it is mislabeled.

**Comment by jennifer-richards** [comment]
Closing as fixed on the feat/rfc branch
