### ISSUE TITLE
Change search engine button on doc page

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#6590]
### Description

We should add more than just google to the "search for this doc" page.
I think Bing and DuckDuckGo.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by richsalz** [comment]
Chatting with @rjsparks he suggest the right thing to do is remove any mention of external search engines. That's a good point, and I will close my current PR #6591

**Comment by rjsparks** [comment]
@richsalz -  c74cf61 doesn't appear to be part of any PR?

**Comment by richsalz** [comment]
Sure, it's right here in my repo.... oh, wait.  What's this `push` command I hear about? :)
#6686

**Comment by rjsparks** [comment]
closing this in favor of #6630
