### ISSUE TITLE
https://datatracker.ietf.org/meeting/118/agenda#now does not work

### ISSUE THREAD

**Issue by kivinen** [ietf-tools/datatracker#6622]
### Description

As the "now" link seems to point to https://datatracker.ietf.org/meeting/118/agenda#now url, I hoped that if I used that link directly it would load the agenda, and jump to "now", but that does not seem to work. I think it used to work with old agenda, but now as the agenda is not loaded directly but are loaded from javascript there is no "#now" spot on the page when it initially loads, so the javascript which does the loading, should check the url and jump to the #hash location after loading the data.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
Related, a "now" button on the narrow mobile rendering of the agenda page would be appreciated.

**Comment by kivinen** [comment]
Lars Eggert writes:
> Related, a "now" button on the narrow mobile rendering of the agenda page
> would be appreciated.

There is separate issue #6621 about that. This was my try to get
around of that problem by trying if that url would work...
-- 
***@***.***

**Comment by rjsparks** [comment]
I think this is addressed with #6654, so I'm closing it. Please reopen if I've misunderstood.
