### ISSUE TITLE
Two types of IAB (interim) meetings

### ISSUE THREAD

**Issue by mirjak** [ietf-tools/datatracker#6638]
### Description

The IAB has business calls and technical discussions. In order to find the later faster, it would be nice we could schedule two different kind of "interims" or highlight this difference somehow. Btw. also calling the business calls "interims" might be confusing anyway.

Or maybe it would be easier we we could simply add some additional information to an "interim" meeting? E.g. for the 118 meeting there is an additional column that says "Liaison Coordinators Office Hours" here: https://datatracker.ietf.org/group/iab/meetings/

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by mirjak** [comment]
@rjsparks is this sometime we could address maybe with a small change to the interim request form? It would be really make my life easier if I could find technical discussions easily and if we could get to an interim solution quickly that would be really helpful. Happy to chat more about what I need and potentially solutions!

**Comment by cindymorgan** [comment]
Yes, we have a way to note whether it's a business meeting or a technical discussion via the admin, so this can be closed.
