### ISSUE TITLE
AD milestones page crashes if any milestones have no due date

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#6641]
### Describe the issue

The milestones view at `/iesg/milestones/` throws a server error if there are `GroupMilestone` instances with null `due` fields in the display list. The error is
```
TypeError at /iesg/milestones/

'<' not supported between instances of 'NoneType' and 'NoneType'

Request Method: 	GET
Request URL: 	https://datatracker.ietf.org/iesg/milestones/
Django Version: 	4.2.6
Exception Type: 	TypeError
Exception Value: 	

'<' not supported between instances of 'NoneType' and 'NoneType'

Exception Location: 	/a/www/ietf-datatracker/11.14.0/ietf/iesg/views.py, line 529, in milestones_needing_review
```

The specific problem is that the sorting code for milestones assumes `due` is a valid sorting key. Filling in that field for the two milestones currently without it avoids this bug. The obvious fix is to apply the standard ordering on milestones (`order`, `due`, `id`) for the model rather than only `due`.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
cc: @rdanyliw
