### ISSUE TITLE
dt-rfc search box fail

### ISSUE THREAD

**Issue by becarpenter** [ietf-tools/datatracker#6673]
### Describe the issue

The search box in the top bar at https://dt-rfc.dev.ietf.org/ doesn't seem to work - e.g. if I enter 'rfc8990' it finds nothing.
The longer search bar just below works fine.
(I was not logged in.)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
duplicate of #6665

**Comment by rjsparks** [comment]
To be clear - this has been addressed as part of #6665 - the fix is deployed at dt-rfc
