### ISSUE TITLE
[dt-rfc] Non existing draft or RFC raises attribute error

### ISSUE THREAD

**Issue by kesara** [ietf-tools/datatracker#6675]
### Describe the issue

In dt-rfc branch, the API call `/api/rfcdiff-latest-json/` for a non-existing draft/RFC generates an attribute error.

Example:
* https://dt-rfc.dev.ietf.org/api/rfcdiff-latest-json/rfc9999
* https://dt-rfc.dev.ietf.org/api/rfcdiff-latest-json/draft-ftie-foo-bar-00

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
addressed by #6681
