### ISSUE TITLE
[dt-rfc] https://dt-rfc.dev.ietf.org/stream/ise/ throws an error

### ISSUE THREAD

**Issue by dhruvdhody** [ietf-tools/datatracker#6676]
### Describe the issue

<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">AssertionError at /stream/ise/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; word-break: break-word; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Arrived at code in fill_in_document_table_attributes() which was marked unreachable on 2023-11-15.</pre>
Request Method: | GET
-- | --
http://dt-rfc.dev.ietf.org/stream/ise/
4.2.7
AssertionError
Arrived at code in fill_in_document_table_attributes() which was marked unreachable on 2023-11-15.
/workspace/ietf/utils/log.py, line 153, in unreachable
ietf.group.views.stream_documents
/usr/local/bin/python
3.9.18
['/workspace',  '/workspace',  '/workspace/ietf',  '/usr/local/lib/python39.zip',  '/usr/local/lib/python3.9',  '/usr/local/lib/python3.9/lib-dynload',  '/usr/local/lib/python3.9/site-packages',  '/workspace']
Mon, 20 Nov 2023 20:47:12 -0800

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by dhruvdhody** [comment]
also at 
https://dt-rfc.dev.ietf.org/stream/iab/
https://dt-rfc.dev.ietf.org/stream/irtf/

**Comment by rjsparks** [comment]
The fix for this (#6677) has been merged and is deployed at dt-rfc.
