### ISSUE TITLE
cancelled virtual interims

### ISSUE THREAD

**Issue by cindymorgan** [ietf-tools/datatracker#6708]
### Description

Subject: 	cancelled virtual interims
From: 	"Michael Richardson" <mcr+ietf@sandelman.ca>

When a meeting is cancelled, like -17 in https://datatracker.ietf.org/wg/cbor/meetings/
could the date of the meeting (that was cancelled) be part of the "cancelled"
button?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
We could show the date after the cancelled pill with a strikethrough perhaps.
