### ISSUE TITLE
draft-yuchaozhang-i2bgp-02.xml is UTF16-LE

### ISSUE THREAD

**Issue by cabo** [ietf-tools/datatracker#6726]
### Describe the issue

draft-yuchaozhang-i2bgp-02.xml is UTF16-LE
(and declares itself to be UTF-8).
How did that ever get into the database?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
This was submitted in June 2023 - at the time, the submission process looked at the content type from libmagic to confirm that it smelled like XML, but did not look at the character encoding. The xml2rfc tool accepts the file without error despite the lie in the xml tag, so this slipped through.

In October, we dropped the libmagic test and added an explicit validation of the character encoding. Attempting to upload this draft's xml results in an error, so no new cases should be possible:

<img width="273" alt="screencap with error message 'Invalid utf-8 byte(s) starting at byte 1: [0xff]'" src="https://github.com/ietf-tools/datatracker/assets/19472766/c3fbde4a-388e-4367-b70e-c32f7f57acb0">

**Comment by jennifer-richards** [comment]
I think we're going to leave this draft alone rather than try to fix it, so closing the ticket. Thank you for the report!

**Comment by cabo** [comment]
Thank you for the diagnosis!
Will we convert the draft to UTF-8?

**Comment by jennifer-richards** [comment]
We were not planning to convert it

**Comment by rjsparks** [comment]
The best thing to do would to be asking the authors for a revised document. We shouldn't be changing what has been submitted.

**Comment by cabo** [comment]
OK, this means that any tool that operates on XML in the database will need to handle this one as an exceptional case.
Fair enough.
