### ISSUE TITLE
pearg Email Archive Link broken

### ISSUE THREAD

**Issue by dvorak42** [ietf-tools/datatracker#6740]
### Describe the issue

It looks like the pearg email archive link points to https://irtf.org/mail-archive/web/pearg/, which 404s, it looks like the correct link should be https://mailarchive.ietf.org/arch/browse/pearg/.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Yes, this is a consequence of recent changes to irtf.org and there will be a bulk update of RG to adjust the Archive and Subscribe To links.

**Comment by rjsparks** [comment]
This (and the other active RG) have been addressed through secretariat action.
