### ISSUE TITLE
AssertionError "rev is None" in fuzzy_find_documents() after feat/rfc deployment

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#6769]
### Describe the issue

After deploying v12.0.0, a call to `document_pdfized()` led to a failed assertion in `fuzzy_find_documents()`

The offending parameters were `{'name': 'rfc4231', 'rev': '02'}`

Traceback in a screenshot here because I don't have a better way to copy/paste at the moment
<img width="902" alt="image" src="https://github.com/ietf-tools/datatracker/assets/19472766/68a50cd4-9578-4399-8ef4-3ca5e4ce357c">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
also seeing:
`{'name': 'rfcdraft-ietf-httpbis-cookie-alone', 'rev': '01'}`

**Comment by rjsparks** [comment]
I think the log.assertion was a mistake - this code deals with strings provided directly in urls which may be nonsense, and it should just not find anything matching the nonsense.
