### ISSUE TITLE
TypeError at /stats/document/yearly/affiliation/

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#6772]
### Describe the issue

After v12.0.0 deployment, got a 500 error: TypeError at /stats/document/yearly/affiliation/

The specific error is: `'NoneType' object is not iterable`

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Fixing `/stats/` is not the best use of time since it should be removed, but this should be correctable with a minor change. It's breaking on drafts that became old rfcs since we moved all the docevents away from the draft and should be also looking at the rfcs I think.
