### ISSUE TITLE
create an llc-comms group

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/datatracker#6783]
### Description

A goal for the IETF LLC Comms monthly meetings is to use the general IETF Datatracker/Meetecho interim meeting processes/infrastructure, and in particular to have info about monthly meetings published as part of the [upcoming meetings](https://datatracker.ietf.org/meeting/upcoming).

This should be modeled on the current [llc-staff](https://datatracker.ietf.org/group/llc-staff/about/) group. Some items for initial set up:

Name: IETF LLC comms 
Members: Greg Wood, Jay Daley
WikiJS admins: Greg Wood, Jay Daley
About:  The IETF LLC comms group aims to provide greater transparency for, get input on, and answer any questions about IETF LLC marketing communications work in support of the ongoing operations of the IETF, including meetings and non-meeting activities and raising money on behalf of the IETF. Discussion is intended to cover items at a tactical-level, and to be complementary (rather than duplicative) of work surfaced and discussed as part of the Education and Outreach Directorate (eodir). Meetings are open to any interested IETF participant.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This is done - it will take a little time for the group to show in the menus (the menu cache will need to expire).
