### ISSUE TITLE
Duplicate rows on the referencedBy page

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#6808]
### Describe the issue

At https://dt-main.dev.ietf.org/doc/rfc2784/referencedby/ there are currently three identical rows for the reference from RFC 9378. There should be only one.

<img width="817" alt="screenshot showing three rows labeled 'RFC 9378'" src="https://github.com/ietf-tools/datatracker/assets/19472766/2710e2e6-e3d8-4b0c-b145-188d17549910">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
I don't see this on `main`?

**Comment by jennifer-richards** [comment]
How recent is your db snapshot? I think this is similar to 6802 and will probably show or not depending on how events were migrated (or not) and whether the `rfc-editor-index-update` script has run.
