### ISSUE TITLE
RFC column empty

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#6814]
### Describe the issue

The RFC column on https://datatracker.ietf.org/doc/ad/#rfc is empty.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
The graphs rewrite the element incorrectly if the input values are all zero. Consider tracking a separate issue to fix that unintended effect?

If you logout (and see the table with no graphs) the column is full of zeros (which I'll work to correct for this issue).

**Comment by rjsparks** [comment]
The issue with the column values is that the published_rfc event moved to the RFC document - it will never appear on a draft document. 

https://github.com/ietf-tools/datatracker/blob/50aa3995ee2f166ba90bf2fc00fef438d3243946/ietf/doc/views_search.py#L470-L474
