### ISSUE TITLE
the "Mailing list discussion" link for rfcs is incorrect

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#6823]
The generated link into the mailarchive uses `&q=` where it should use `/q=`. The query should also look for both references to the rfc name and the name of the draft the rfc came from.

**Comment by elear** [comment]
Just a comment of no particular significance.  I realize it's your namespace, but is that meant to be a query, but yet doesn't quite look like one?  Would it make sense to add &q= into the mailarchive?

**Comment by jennifer-richards** [comment]
I think it's currently generating `.../?email_list=<acro>?q=<docname>` but should be`.../?email_list=<acro>&q=<docname>`

**Comment by rjsparks** [comment]
This is a data cleaning / code robustness issue:
https://github.com/ietf-tools/datatracker/blob/50aa3995ee2f166ba90bf2fc00fef438d3243946/ietf/templates/doc/document_info.html#L434
and
```
>>> Group.objects.filter(list_archive__endswith="/").count()
383
>>> Group.objects.exclude(list_archive="").exclude(list_archive__endswith="/").count()
334
```

**Comment by rjsparks** [comment]
And I typo-ed in the original post, stimulating an unnecessary conversation - apologies.

**Comment by rjsparks** [comment]
Yet redirects at mailarchive are handling those differences already. Attempting to rediscover the document that motivated this issue.

**Comment by rjsparks** [comment]
Relocated - the issue is at /doc/rfc5280/ which links to `https://mailarchive.ietf.org/arch/search/?email_list=pkix?q=rfc5280` because
```
>>> Group.objects.get(acronym='pkix').list_archive
'https://mailarchive.ietf.org/arch/search/?email_list=pkix'
```

Further:
```
>>> Group.objects.filter(list_archive__contains="?email_list").count()
165
```

We should transform those to use the shorter version of `/arch/browse/<acronym>`
