### ISSUE TITLE
"Email authors" button provides invalid email for https://datatracker.ietf.org/doc/html/rfc4035

### ISSUE THREAD

**Issue by qdm12** [ietf-tools/datatracker#6856]
### Describe the issue

The "Email authors" gives the email address "rfc4035@ietf.org" which is not found. The automated email response is:

> Address not found
> Your message wasn't delivered to rfc4035@ietf.org because the address couldn't be found, or is unable to receive mail.
> The response from the remote server was:
> 550 5.1.1 <rfc4035@ietf.org>: Recipient address rejected: User unknown in virtual alias table 

Would it be possible to fix the email address in order to communicate with the authors? Thank you!

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
See also #6214

**Comment by rjsparks** [comment]
Paul - short term fix that won't close this issue, but will at least return us to the datatracker's previous less-bad-than links that cannot work behavior.

At the place where this link is emitted, look to see if the rfc came_from_draft and if so, use the draft alias, but _only_ if the generate-draft-aliases script would have emitted the alias. If the rfc didn't come from a draft or the draft wouldn't have a working alias, emit nothing.

We will come back to this later and make rfcnnnn@ aliases, but I want to wait until the new mail processing system is in place first (we will be maintaining the aliases very differently when that happens).
