### ISSUE TITLE
Draft Name Search Box Yields No Results - Only Top Search Bar Works

### ISSUE THREAD

**Issue by starrant-rpc** [ietf-tools/datatracker#6883]
### Describe the issue

If you search for a draft string in the middle part of the page "Document Search", no matter how many "Additional search criteria" you enable, no results are yielded. However, you can still use the top right search to find drafts.

<img width="902" alt="Screen Shot 2024-01-04 at 10 37 15 AM" src="https://github.com/ietf-tools/xml2rfc/assets/132307348/00e306b0-f3a7-4939-80ac-d8f91c57360f">
<img width="1064" alt="Screen Shot 2024-01-04 at 10 37 36 AM" src="https://github.com/ietf-tools/xml2rfc/assets/132307348/17d2f285-ae4d-4a25-a56a-44d2a641db61">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Hi Sarah - I moved this issue to the datatracker's repository.

Maybe this is fixed by today's release?

When I search for `draft-irtf-cfrg-ristretto255-decaf448` on the main page without changing any of the search criteria it returns RFC9496.

Note that the form in the middle part of the page is not reactive - it won't search as you type the way the upper right corner will. You have to hit the search button. (This will change in an upcoming release).

**Comment by rjsparks** [comment]
Guessing a little bit, but I wonder if what you're finding is that it's not obvious that leaving the RFC box checked is what you should do when you're looking for an internet draft that became an RFC (note that when you click on the link in returned in the top right search box, it takes you to the RFC page, from which you can navigate to versions of the draft that became the RFC).

If I'm right, I wonder if changing
![image](https://github.com/ietf-tools/datatracker/assets/10996692/06f5c49a-5302-4c9f-9834-5370fe3efb51)
to something like
![image](https://github.com/ietf-tools/datatracker/assets/10996692/31ecd53c-ffb8-48cb-8a87-331044ff1932)
would have made the form more intuitive?

**Comment by Hashfixplease** [comment]
How does these draft effect my web messages? I keep seeing error code 404. I'm not receiving any messages via Google voice.  Are you blocking? I'm so very disappointed

**Comment by starrant-rpc** [comment]
Hi Robert - today, the issue appears to be fixed, as I searched other draft strings, which resulted in accurate/true results. Looks good to me!

If the checkbox "RFC" was already searching for I-Ds that have become RFCs, then I don't think it needs the parenthetical. I always assumed it could find I-Ds published as RFCs.
