### ISSUE TITLE
Missing button text for PostScript

### ISSUE THREAD

**Issue by kesara** [ietf-tools/datatracker#6900]
### Describe the issue

Icon and button text are missing for the PostScript file downloads.
Examples:
* https://datatracker.ietf.org/doc/draft-ietf-tsvwg-quickstart/07/
* https://datatracker.ietf.org/doc/draft-ietf-rmt-bb-webrc/04/

Screenshot:
<img width="1183" alt="Screenshot 2024-01-09 at 17 38 22" src="https://github.com/ietf-tools/datatracker/assets/1027692/bb74989e-dac5-473f-bf29-623ca2d1d878">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
I thought we had removed Postscript a long time ago?

**Comment by rjsparks** [comment]
We removed the ability for people to upload new postscript, but we are still showing postscript people had provided in years past I thought.

**Comment by larseggert** [comment]
Ah. I think I misunderstood this and ripped these buttons out a long time ago. I wonder if we can just stop showing PS that we have now?

**Comment by rjsparks** [comment]
I believe there are some documents where the PS mattered (the txt referred to the PS for a diagram). But nobody's complained - we could stop showing the link until someone asks and provide it on demand.

**Comment by rjsparks** [comment]
But that is a policy decision that has not been made, and is probably an IESG level decision, no?

**Comment by larseggert** [comment]
Yes.

**Comment by rjsparks** [comment]
@larseggert - followup?

**Comment by larseggert** [comment]
The IESG discussed this but I am blanking on the outcome. CC @evyncke

**Comment by evyncke** [comment]
Found back the discussion on the private https://iesg.privatewikis.ietf.org/notes/2024-01-11

The bottom line is literally `Sure, kill it.` (talking about the buttons) 

I.e., there is a need to remove the textless button though.

**Comment by evyncke** [comment]
Should be fixed in #7200
