### ISSUE TITLE
Password reset not working 

### ISSUE THREAD

**Issue by philbedard** [ietf-tools/datatracker#6904]
### Describe the issue

Attempting to reset my account password.  Password reset email is never received.  

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Hi @phildbard - the new issue form contains this text that you missed:

> If you are having trouble logging into the datatracker, please do not open an issue here. Instead, please send email to [support@ietf.org](mailto:support@ietf.org) providing your name and username.

I'm going to close this issue - if you've not already done so, please send that email (so you don't have to put your username into this public github issue). and we will help correct the issue.
