### ISSUE TITLE
Authors field missing in RFC 9521

### ISSUE THREAD

**Issue by xiaomin2016** [ietf-tools/datatracker#6949]
### Describe the issue

While reviewing https://datatracker.ietf.org/doc/rfc9521/, I found that Authors field missing, none of the authors displayed.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
It appears to me that we're not setting authors at all when importing RFCs, which must not have been adequately exercised by our pre-deployment testing.

**Comment by jennifer-richards** [comment]
RFCs with either 0 authors or whose author count disagrees with the draft are:
```
    doc.name: 'rfc9382' <-- datatracker has 2 authors, rfc-editor.org has 1
    doc.name: 'rfc9401' <-- datatracker has 0 authors (april 1 rfc)
    doc.name: 'rfc9402' <-- datatracker has 0 authors (april 1 rfc)
    doc.name: 'rfc9405' <-- datatracker has 0 authors (april 1 rfc)
    doc.name: 'rfc9458'
    doc.name: 'rfc9467'
    doc.name: 'rfc9475'
    doc.name: 'rfc9490'
    doc.name: 'rfc9496'
    doc.name: 'rfc9497'
    doc.name: 'rfc9501'
    doc.name: 'rfc9517'
    doc.name: 'rfc9518'
    doc.name: 'rfc9520'
    doc.name: 'rfc9521'
    doc.name: 'rfc9552'
```
Those

**Comment by jennifer-richards** [comment]
I think 9458 and later were all affected by the datatracker v12 bug - these should be easily fixable using the mgmt command in #6957, as should 9382. The April 1 RFCs do not have a draft and will need to be fixed up through the admin interface.

**Comment by rjsparks** [comment]
@xiaomin2016 - we still have to run the management command to do the fixup before the author list will be restored for this rfc

**Comment by rjsparks** [comment]
(this is now done)

**Comment by xiaomin2016** [comment]
@rjsparks It works now. Thank you very much.
