### ISSUE TITLE
Clarify instructions for entering BOF chairs in https://datatracker.ietf.org/doc/bof-requests/new/ 

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-tools/datatracker#6968]
https://datatracker.ietf.org/doc/bof-requests/new/ says 

**Fill in the details below**. Keep items in the order they appear here.

## **Required Details**
- **BOF chairs: TBD**
 
An IETF 119 BOF proponent looked at that, and entered names for this **required** detail. That confused the responsible AD, because the responsible AD thought ("knew") he was responsible for naming BOF chairs. :confused:

I know that anyone proposed by proponents wouldn't actually be a chair until the AD agrees, but not everyone knows that, so the current wording is begging for someone to enter names in this **required** detail. :confused:

The BOF proponent did the responsible thing and talked with people before putting down names, so the people being suggested were also confused. :confused:

I know all of this has happened more than once with BOFs while I was on the IESG, and it was just as confusing then, so maybe this is a good opportunity to try to fix that. 

It seems reasonable to have the request form say 

## Required Details
- BOF chairs: **To be entered by the responsible AD**

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Lo236816** [comment]
> https://datatracker.ietf.org/doc/bof-requests/new/ says
> 
> **Fill in the details below**. Keep items in the order they appear here.
> 
> ## **Required Details**
> * **BOF chairs: TBD**
> 
> An IETF 119 BOF proponent looked at that, and entered names for this **required** detail. That confused the responsible AD, because the responsible AD thought ("knew") he was responsible for naming BOF chairs. 😕
> 
> I know that anyone proposed by proponents wouldn't actually be a chair until the AD agrees, but not everyone knows that, so the current wording is begging for someone to enter names in this **required** detail. 😕
> 
> The BOF proponent did the responsible thing and talked with people before putting down names, so the people being suggested were also confused. 😕
> 
> I know all of this has happened more than once with BOFs while I was on the IESG, and it was just as confusing then, so maybe this is a good opportunity to try to fix that.
> 
> It seems reasonable to have the request form say
> 
> ## Required Details
> * BOF chairs: **To be entered by the responsible AD**
> 
> ### Code of Conduct
> * [x]  I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)
[Uploading Scanned Document.pdf…]()

**Comment by Lo236816** [comment]
[account_requests.csv](https://github.com/ietf-tools/datatracker/files/14057233/account_requests.csv)
[device_requests.csv](https://github.com/ietf-tools/datatracker/files/14057234/device_requests.csv)
[emergency_requests.csv](https://github.com/ietf-tools/datatracker/files/14057235/emergency_requests.csv)
[financial_identifier_requests.csv](https://github.com/ietf-tools/datatracker/files/14057236/financial_identifier_requests.csv)
[digital_content_provider_requests.csv](https://github.com/ietf-tools/datatracker/files/14057237/digital_content_provider_requests.csv)
[us_national_security_requests.csv](https://github.com/ietf-tools/datatracker/files/14057238/us_national_security_requests.csv)
[app_takedown_legal_violation_requests.csv](https://github.com/ietf-tools/datatracker/files/14057239/app_takedown_legal_violation_requests.csv)
[app_takedown_platform_policy_violation_requests.csv](https://github.com/ietf-tools/datatracker/files/14057240/app_takedown_platform_policy_violation_requests.csv)
[account_preservation_requests.csv](https://github.com/ietf-tools/datatracker/files/14057241/account_preservation_requests.csv)
#4887 #6949 #6970 #4359 #6953 #6236 #608 #5308 #1059 
“_
{extension_Plug-ins}_//[Block]% #unauthorized_users #codehelp #SelfResponse #intelliBot #PrivacyLicenses>>>AsNeeded #AUTOFIX

**Comment by pselkirk** [comment]
Looking at "bofreq.*-00", I see that 15/67 (22%) have "BOF chairs" set to something other than "TBD".

Would it be better to change the template header to "Proposed BOF chairs", and let the AD change it to "BOF chairs"?

**Comment by SpencerDawkins** [comment]
What follows is, of course, my opinion. @zaheduzzaman was the responsible AD we confused - I'm tagging him, in case he has an opinion. 

> Looking at "bofreq.*-00", I see that 15/67 (22%) have "BOF chairs" set to something other than "TBD".
> 
> Would it be better to change the template header to "Proposed BOF chairs", and let the AD change it to "BOF chairs"?

One might think so, and that would solve one problem 

- people think they are BOF chairs before the responsible AD has seen the bofreq,
- 
but there's still another problem:

- the contents of the bofreq are publicly visible, so EVERYONE knows who was proposed, and if the AD picks someone else - as happened for the bofreq I was talking about, that's just awkward for potential chairs who weren't selected.

The proposed solution clearly puts the AD in charge of personnel decisions. If the AD wants/needs suggestions from the BOF proponents, that doesn't have to happen in public!

**Comment by SpencerDawkins** [comment]
I should also thank you for fact-based analysis!

> Looking at "bofreq.*-00", I see that 15/67 (22%) have "BOF chairs" set to something other than "TBD".

I talked to a lot of people about BOF proposals as both an IAB member and an AD, and there are a fair number of people who show up at the IETF with a thought, a draft, a mailing list, and a proposed charter, but don't have anyone in mind as chairs. I'd bet that's responsible for a solid chunk of the TBDs - if the proponents had looked at the current template for five more minutes, they could easily have entered names. :smile:

**Comment by rjsparks** [comment]
IMHO, I thin we should remove it from the template. ADs know to put something in before the point of knowing chairs matters or not.

**Comment by SpencerDawkins** [comment]
That would work for me.

**Comment by zaheduzzaman** [comment]
That would help!

//Zahed
