### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by aznclouds** [ietf-tools/datatracker#6976]
### Describe the issue

Bug not allowing me to access my settings 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Closing this as likely off-topic given other issues opened around the same time. If you have a real issue accessing/configuring your datatracker account, contact tools-help@ietf.org.
