### ISSUE TITLE
mail archive search URL (sometimes?) wrong

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#6993]
### Describe the issue

While doing a SECDIR review, the URL for "search the mail archives" is this:
```
No results found ('No results: https://mailarchive.ietf.org/arch/export/mbox/?qdr=c&start_date=2023-08-02&email_list=secdir&q=subject%3A%28draft-ietf-lamps-rfc8398bis%29&as=1 -> No results found') (searched for ["draft-ietf-lamps-rfc8398bis"](https://mailarchive.ietf.org/arch/search/?qdr=c&start_date=2023-08-02&email_list=secdir&q=subject%3A%28draft-ietf-lamps-rfc8398bis%29&as=1), corresponding [export](https://mailarchive.ietf.org/arch/export/mbox/?qdr=c&start_date=2023-08-02&email_list=secdir&q=subject%3A%28draft-ietf-lamps-rfc8398bis%29&as=1)). You have to fill in link and content yourself.
```

It shouldn't be *secdir* it should be the WG where the document is, in this case SPASM.

It also wasn't clear to me that what I would get would be a TGZ file of mbox archives.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Rich - what did you do to get that URL?

The string `mbox` does not appear in `view-source:https://datatracker.ietf.org/doc/draft-ietf-lamps-rfc8398bis/`

(and that lamps draft is the only URL I see in the link you provided, so I'm having trouble connecting this to SPASM?)

**Comment by richsalz** [comment]
I clicked on this link: ```https://datatracker.ietf.org/doc/draft-ietf-lamps-rfc8398bis/reviewrequest/15278/complete/``` and then I clicked on "search mail archives and got the message posted above.

**Comment by rjsparks** [comment]
So the workflow is that you've sent a review to the list already, and now you're wanting to tell the datatracker to go find the review you sent and the form is not populating the field based on the search response? (I'm trying to duplicate and have not yet gotten to something that results in an mbox download).

**Comment by richsalz** [comment]
> But, one note - it is intentional that the link is into the review team's archive and not the group's archive.

Aha.  Light dawns on Marblehead, as they say.  Perhaps the message could be tweaked.  Change
```
Search mail archive subjects for:
```
To
```
Search directorate mail archive subjects for:
```

**Comment by rjsparks** [comment]
The part of this issue that talks about the un-intuitive link displayed when the search fails has been moved to the mailarchive for the creation of a purposed API for the datatracker to use.

The remaining part of this issue is to accept the small text change Rich proposes.

**Comment by pselkirk** [comment]
@richsalz Would it be clearer to say `Search secdir@ietf.org mail archive subjects for:`?

**Comment by richsalz** [comment]
@pselkirk sure that's fine.
