### ISSUE TITLE
Failure when creating joint session meeting schedule request

### ISSUE THREAD

**Issue by kiranmak** [ietf-tools/datatracker#6996]
### Describe the issue

Hi,
I am trying to edit SNAC WG request and make it a joint session with DNSSD. But I receive an internal error. I do not know if I am breaking any boundary checks or providing any incorrect information.
URL: https://datatracker.ietf.org/secr/sreq/119/snac/edit/
Request:  Select DNSSD from WD drop down for joint-session. See actual error text below copy-pasted.
=======
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there was an error in a script used to generate the requested page. In case this was an overload problem or other temporary error, you may want to try again in a little while.

A failure report with details about what happened has been sent to the server administrators. It would be helpful if you would create an issue providing additional information at [GitHub](https://github.com/ietf-tools/datatracker/issues/new/choose), too.
========

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
Sorry for the difficulties. I've passed this along to the secretariat - they should be reaching out to you to coordinate your request.

This bug was reported as #4080 and is planned to be fixed / obviated by the refactoring described in #6146, so I'm going to close this ticket.

Thank you for the report!
