### ISSUE TITLE
Rework the search button in the action button row for a document page to not link to external search engines

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#7009]
Change
![image](https://github.com/ietf-tools/datatracker/assets/10996692/cfad9990-6504-4748-a3f0-f1d564113871)
to a simple button that searches the mailarchive only.

**Comment by rjsparks** [comment]
In the process, I believe this will become dead code:

https://github.com/ietf-tools/datatracker/blob/4c7be64e961fe97834f7170c01d6730d07c4adcb/ietf/doc/views_doc.py#L480

If I'm correct, please clean it away.

**Comment by Sarrac3873** [comment]
> Change
> ![image](https://github.com/ietf-tools/datatracker/assets/10996692/cfad9990-6504-4748-a3f0-f1d564113871)
> to a simple button that searches the mailarchive only.
