### ISSUE TITLE
Link to PDF is missing (workshop material)

### ISSUE THREAD

**Issue by mirjak** [ietf-tools/datatracker#7017]
### Describe the issue

This page doesn't have the link to the PDF: https://datatracker.ietf.org/doc/slides-biasws-imap-internet-monitoring-action-project-internet-censorship-report/

(Note the -00 version shows the link correctly)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
duplicate of #7018?

**Comment by rjsparks** [comment]
Please see the discussion in #7018 about root cause.

**Comment by rjsparks** [comment]
Fixed with 12.5.0
