### ISSUE TITLE
People listed as NomCom candidates should be linked to their personal profiles

### ISSUE THREAD

**Issue by paulehoffman** [ietf-tools/datatracker#7032]
### Description

Similar to #7031, when reviewing people for NomCom, it would be useful to be able to see their personal profiles easily.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Be aware of the discussion at #6068

**Comment by rjsparks** [comment]
Added contrib easy as turning the list of names into links to profile pages will be simple.

**Comment by richsalz** [comment]
If you're talking about the "Enter feedback" tab, which then provides a list of names on the right-hand side, I am confused.  The names are links as shown by this screenshot.
![Screenshot 2024-03-16 at 11 08 16 AM](https://github.com/ietf-tools/datatracker/assets/7332500/8600a480-ccb9-4939-b6d2-fb94a14fca99)

If you click on someone's name, you get the "enter feedback" page.  And if you hover over their name is says "view their datatracker profile"  With a possibly-confusing envelope icon next to it:

![Screenshot 2024-03-16 at 11 10 48 AM](https://github.com/ietf-tools/datatracker/assets/7332500/9143f743-0d1b-4449-97c6-be5eb7ac9d2c)

So what should be done here?

**Comment by rjsparks** [comment]
the envelope should be a link to send them email.

**Comment by richsalz** [comment]
Yeah, but it's a separate link from the "point to datatracker profile" which is why I called it possibly-confusing.
I think it should be `with_email=False` since you can get their email address from the public profile.

**Comment by rjsparks** [comment]
@paulehoffman reopen if you were looking at a different spot for links
