### ISSUE TITLE
Make it easier to find "Non-Working Group Email List Guidelines"

### ISSUE THREAD

**Issue by paulehoffman** [ietf-tools/datatracker#7059]
### Description

The page at https://www.ietf.org/how/lists/nonwglist-guidelines/ is quite useful. It would have been nice if I had found it before bugging my AD for a new list. :-( I looked at https://datatracker.ietf.org/list/nonwg and https://chairs.ietf.org/, but didn't see it. I'm doing a separate edit for the latter, but maybe the former page is under Tools control.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by cabo** [comment]
Is that really the name:

"Non-Working Group email lists"

I think some of the groups will be surprised that they are considered non-working.

**Comment by rjsparks** [comment]
That view is a morass - it has been decoupled from Mailman2, and will be re-implemented on top of Mailman3 later. In the meantime, adjusting its title and providing the link Paul suggests should be easy.
