### ISSUE TITLE
Cannot login after changing the primary email

### ISSUE THREAD

**Issue by BorisH2018** [ietf-tools/datatracker#7060]
### Describe the issue

Hi,
I changed my primary email to bhassanov@yahoo.com in my profile and cannot login after that to datatracker.
Please help to troubleshoot.

SY,
Boris

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Hello Boris - I'm closing this issue and moving working on it to a support mail list.

For others with similar problems in the future, as the new issue form notes:
>If you are having trouble logging into the datatracker, please do not open an issue here. Instead, please send email to [support@ietf.org](mailto:support@ietf.org) providing your name and username.
