### ISSUE TITLE
.ics files have a zillion RDATE lines in them

### ISSUE THREAD

**Issue by paulehoffman** [ietf-tools/datatracker#7113]
### Describe the issue

Something appears to be stuffing nonsense "RDATE" lines into the .ics files that are being generated by the Datatracker for meetings. For example, https://datatracker.ietf.org/meeting/interim-2024-rswg-02/sessions/rswg.ics has 178 RDATE lines.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
This is part of the `America/Chicago` timezone definition - I think it's specifying when daylight savings begins / ends. It's also out of date, judging by the last RDATE being in 2006. 
```
BEGIN:VCALENDAR
PRODID:-//IETF Tools//NONSGML ietf-agenda-ical 1.03//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:America/Chicago
X-LIC-LOCATION:America/Chicago
BEGIN:DAYLIGHT
TZOFFSETFROM:-0600
TZOFFSETTO:-0500
TZNAME:CDT
DTSTART:20070311T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0500
TZOFFSETTO:-0600
TZNAME:CST
DTSTART:20071104T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-055036
TZOFFSETTO:-0600
TZNAME:CST
DTSTART:18831118T120924
RDATE:18831118T120924
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0600
TZOFFSETTO:-0500
TZNAME:CDT
DTSTART:19180331T020000
RDATE:19180331T020000
RDATE:19190330T020000
RDATE:19200613T020000
RDATE:19210327T020000
RDATE:19220430T020000
RDATE:19230429T020000
RDATE:19240427T020000
RDATE:19250426T020000
RDATE:19260425T020000
RDATE:19270424T020000
RDATE:19280429T020000
RDATE:19290428T020000
RDATE:19300427T020000
RDATE:19310426T020000
```

**Comment by jennifer-richards** [comment]
#5683 covers the need to update the timezone info.

#5398 covers needing to overhaul our handling of the deceptively intricate iCalendar format.

**Comment by jennifer-richards** [comment]
I've added a mention of the RDATE issue to #5393 and am going to close this as a request for that larger issue. Please comment there (or reopen this if you think it needs separate handling).
