### ISSUE TITLE
yanglint errors when submitted a YANG model draft

### ISSUE THREAD

**Issue by Yingzhen-ietf** [ietf-tools/datatracker#7122]
### Describe the issue

I got the following errors when submitting a draft with YANG data model. I tried a couple of different drafts and got the same errors.

yanglint SO 1.9.2: yanglint --verbose -p {tmplib} -p {rfclib} -p {draftlib} -p {ianalib} -p {cataloglib} {model} -i:
err : Encountered invalid character sequence "\
rt
     ".
err : Module "iana-bfd-types" parsing failed.
err : Importing "iana-bfd-types" module into "ietf-bfd-types" failed.
err : Module "ietf-bfd-types" parsing failed.
err : Importing "ietf-bfd-types" module into "ietf-isis" failed.
err : Module "ietf-isis" parsing failed.
err : Importing "ietf-isis" module into "ietf-isis-remaining-lifetime" failed.
err : Module "ietf-isis-remaining-lifetime" parsing failed.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
@Yingzhen-ietf - changes were made at yangcatalog that should clear this up. It might be tomorrow before these changes propogate to the datatracker though.

**Comment by Yingzhen-ietf** [comment]
Hi Robert,

Thanks for the update and fixing the issue. I'll try uploading drafts
tomorrow.

Thanks,
Yingzhen

**Comment by rjsparks** [comment]
Closing this as OBE
