### ISSUE TITLE
IOTdir review page does not accept .txt file attachments.

### ISSUE THREAD

**Issue by charliep51** [ietf-tools/datatracker#7123]
### Describe the issue

IOTdir review page does not accept .txt file attachments.  I had to copy and paste the contents into the page.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
what error did you receive?

I suspect you're triggering a bug in the current server's underlying libmagic. The error message would confirm that.

**Comment by rjsparks** [comment]
@charliep51 - I'm going to close this for lack of feedback. If you encounter the issue again, reopen it (or open a new one), and include the error you received.
