### ISSUE TITLE
https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4

### ISSUE THREAD

**Issue by rawmet1989** [ietf-tools/datatracker#7140]
### Describe the issue

Same
![IMG_1616](https://github.com/ietf-tools/datatracker/assets/63019701/4e0115a8-6c14-467a-8b00-1bacbf441e6d)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
closing this as non-actionable. If there's a real bug here, describe it.
