### ISSUE TITLE
Can't display number of RFCs per country

### ISSUE THREAD

**Issue by jdbest92** [ietf-tools/datatracker#7145]
### Describe the issue

I'm trying to display the number of RFC authors per country:
https://datatracker.ietf.org/stats/document/yearly/country/?type=rfc
But the result is blank.
Tested on Linux Debian 11 with Firefox 123.0 and Chrome 122.0.6261.94 
![Capture d’écran_2024-03-06_11-18-13](https://github.com/ietf-tools/datatracker/assets/151540302/185e4c43-19bd-47d5-b186-9f3f27b8336e)

(see screenshot1)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
See #3712. The stats module is known to be broken in many places and will be removed and later reimplemented.

**Comment by rjsparks** [comment]
Closing this as won't fix - it's linked to #3712, so it'll be captured in the re-implementation.
