### ISSUE TITLE
Meetecho links timing out

### ISSUE THREAD

**Issue by vmbennett** [ietf-tools/datatracker#7148]
### Describe the issue

I am getting a  ERR_CONNECTION_TIMED_OUT error when trying to reach http://recs.conf.meetecho.com/Playout/watch.jsp?recording=IETF98_TSVAREA&chapter=chapter_1 using Chrome (Version 121.0.6167.139 (Official Build) (arm64)).

I get this error for all linked meetecho recordings from meeting 98 (https://ietf98.conf.meetecho.com/index.php/Recordings#IDR), at least.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by alexamirante** [comment]
I think you got there from the proceedings page, right? There was a bad redirect in place that should now be fixed.
