### ISSUE TITLE
Chair should be able to propose slides

### ISSUE THREAD

**Issue by cabo** [ietf-tools/datatracker#7178]
### Description

Chairs may want to recuse themselves on a document that they are co-author on.
Being able to just post slides on my documents makes me feel like an elephant stepping on my co-chairs' feet.
So I should be able to go through the same slide submission that every other author has to go through, if I chose so.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
You _could_ just send the slides to your co-chair and ask them to upload them (or coordinate with them ahead of time so they have given you pre-approval). (No, this is not the same as saying that any participant could just send the slides to the chair for upload).

We can look at this, but I think it stands a greater chance of introducing confusion for most chairs than relieving social pressure. Having both an Upload Slides and a Propose Slides button is going to lead to the wrong button getting pushed.

What this _shouldn't_ turn into is something where you as a chair wouldn't get to approve your own uploaded slides.

**Comment by cabo** [comment]
On 2024-03-12, at 21:29, Robert Sparks ***@***.***> wrote:
> 
> 
> You could just send the slides to your co-chair and ask them to upload them (or coordinate with them ahead of time so they have given you pre-approval). (No, this is not the same as saying that any participant could just send the slides to the chair for upload).

Yes, but now I would create work for my co-chairs.

> We can look at this, but I think it stands a greater chance of introducing confusion for most chairs than relieving social pressure. Having both an Upload Slides and a Propose Slides button is going to lead to the wrong button getting pushed.

(An inverse button, moving a slide deck from “uploaded” back to “proposed”, might do what I think would be useful, might be useful in other cases, and would cause less confusion.)

> What this shouldn't turn into is something where you as a chair wouldn't get to approve your own uploaded slides.

Definitely not.

Grüße, Carsten

**Comment by rjsparks** [comment]
>Yes, but now I would create work for my co-chairs.
The shape of the work is slightly different, but the size of the work is the same.

Unless you're just wanting a rubber-stamp, the chairs are going to have to pull the slides down, review them, and then hit approve. Not seeing a big difference there than the path that is review, then upload. (Ok - edge cases where something with the upload goes wrong, but that's not a typical thing _chairs_ run into with the slide decks they've prepared.
