### ISSUE TITLE
could the "technology and network" page have a direct link to meetecho please

### ISSUE THREAD

**Issue by geeohgeegeeoh** [ietf-tools/datatracker#7212]
### Description

meetecho will install as a web app on Android (and I assume Apple) if you are in the URL on chrome. This is useful because it means the app can be clicked on directly to sign in (bluesheet formalism) to a session. But, there is no direct URL to meetecho on the page about networks and technology: instead it has links to the documentation. There should be one link.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
The UI you are describing is essentially providing a shortcut from the app launcher to open a browser with a given URI. The meetecho links are specific to a given session. There is no link to a generic meetecho page that could be installed that would let you select sessions.
