### ISSUE TITLE
About page for WIT does not show area directors

### ISSUE THREAD

**Issue by JonathanLennox** [ietf-tools/datatracker#7216]
### Describe the issue

The page at URL https://datatracker.ietf.org/group/wit/about/ -- unlike the "About" page for other WGs -- does not show the WIT area directors.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
The IESG created the Area early and assigned WGs to it, but not ADs. This was to help with the inter-group conflict resolution when building the schedule for 119.

It will get ADs at Plenary, and then they will show on this page. This is on the secretariat's hotlist of things to do at plenary.

cc: @cindymorgan
