### ISSUE TITLE
Icons have gone wonky

### ISSUE THREAD

**Issue by rdviii** [ietf-tools/datatracker#7225]
### Describe the issue

In Chrome 122.0.6261.128 on a Mac, when I reload the agenda, the icons for WG agenda, materials, etc. turn into...something else.
<img width="1014" alt="Screenshot 2024-03-18 at 15 05 51" src="https://github.com/ietf-tools/datatracker/assets/2833100/c2d45269-93b2-447d-ad41-e1f7fbb0b185">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Which browser and version please.
(I'm not seeing the behavior in my browsers yet, but can confirm a similar thing with Chrome on another view - see #7223

**Comment by rdviii** [comment]
Chrome 122.0.6261.128 on a Mac running Ventura 13.5.1 (22G90).

**Comment by rdviii** [comment]
For better or worse, has now gone away. Close as anomalous?

**Comment by rjsparks** [comment]
Will leave it open for awhile in case others run into it (and while we work out whether 7223 was also transient).

**Comment by rpcross** [comment]
I just experienced this problem. 
- pulled up agenda page and got wonky icons like above
- refresh did not help
- went to about Chrome to check version, 122.? 
- chrome had downloaded an update, instructed me to relaunch to install
- on relaunch icons are correct. now Version 123.0.6312.59 (Official Build) (arm64)

**Comment by rjsparks** [comment]
Closing this as OBE
