### ISSUE TITLE
Yangvalidor says the modules are missing

### ISSUE THREAD

**Issue by dhruvdhody** [ietf-tools/datatracker#7226]
### Describe the issue

err : Module "iana-bfd-types" parsing failed.
err : Importing "iana-bfd-types" module into "ietf-bfd-types" failed.
err : Module "ietf-bfd-types" parsing failed.
err : Importing "ietf-bfd-types" module into "ietf-ospf" failed.
err : Module "ietf-ospf" parsing failed.
err : Importing "ietf-ospf" module into "ietf-pcep" failed.
err : Module "ietf-pcep" parsing failed.

for draft-ietf-pce-pcep-yang-23

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by dhruvdhody** [comment]
This error are showing up for previously comping modules such as https://datatracker.ietf.org/doc/draft-ietf-lsr-ospfv3-extended-lsa-yang/

**Comment by rjsparks** [comment]
@xorrkaz - is this at yc.o or at the datatracker's copies of what's there?

**Comment by dhruvdhody** [comment]
I ran this at the yangvalidator and I am getting the errors there as well....

**Comment by xorrkaz** [comment]
This is the problem I reported to Mahesh.  Essentially, yc.o has loaded his draft iana-bfd-types module, and this module is bad.  It's breaking compilation.  He said they'd be releasing a -15 to address this problem.  I've reviewed that draft, and this problem is solved.  So I'm hoping that will be fixed soon.

**Comment by xorrkaz** [comment]
FYI, this is caused by https://datatracker.ietf.org/doc/draft-ietf-bfd-optimizing-authentication/, and I'm waiting for Mahesh (or one of the authors) to push -15 with a fix.

**Comment by xorrkaz** [comment]
I spoke with Mahesh face to face today, and he said he would publish -15 soon to address this.

**Comment by xorrkaz** [comment]
He has published the new draft with the fixed module.  @dhruvdhody can you confirm if compilation succeeds now?

**Comment by dhruvdhody** [comment]
Yes it does! Thanks everyone involved!
