### ISSUE TITLE
Sometimes the emojis are not decoded correctly on the Agenda page.

### ISSUE THREAD

**Issue by koezgen** [ietf-tools/datatracker#7231]
### Describe the issue

![image](https://github.com/ietf-tools/datatracker/assets/95245093/d9c519c8-3fb7-43b9-9bb3-37ad3ecdaaab)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
duplicate of #7225
