### ISSUE TITLE
could meetecho get threads? an explicit @reply mechanism?

### ISSUE THREAD

**Issue by geeohgeegeeoh** [ietf-tools/datatracker#7232]
### Description

people are adopting other IM norms to @person namecheck things, and presumably will continue. I am wondering if there is an explicit meetecho mechanism in planning to manage the semantic intent behind "reply"

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Meetecho's chat is Zulip (meetecho's client acts as a zulip client), and the modality of communication available is informed by what zulip offers. Meetecho is already exposing Zulip's `topic` concept. Zulip's own UI has a "quote and reply" feature that we could look at using.

**Comment by rjsparks** [comment]
(That said, this isn't a datatracker issue - i'll move it to the right place in a bit).

**Comment by geeohgeegeeoh** [comment]
thanks. appreciate the guidance and help to relocate the "improvement"
where it should be

**Comment by rjsparks** [comment]
According to MeetEcho, the chat part of the client supports all the markup documented here: https://zulip.com/help/format-your-message-using-markdown, which includes mentions.

Replys can be done with markup, but there's not UI built to copy the text from a previous message into a quote for you.

Closing this datatracker issue. The better place for it at the moment is a email list discussion on tools-discuss@ietf.org if we need to take it further.
