### ISSUE TITLE
Button to go straight to “now”

### ISSUE THREAD

**Issue by ckuhtz** [ietf-tools/datatracker#7245]
### Description

I probably pulled this page up on mobile dozens and dozens of times during 119. And then proceeded to scroll down to the helpfully highlighted section. Would it be possible to add a prominently placed button at the top of the mobile page to go to “now”, preferably even something that I can link to with a link on the phones Home Screen? If this doesn’t make sense or is unclear, please ask :-)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Hi Christian - This exists, but is hard to demonstrate outside the meeting time. At this point on the app:
![image](https://github.com/ietf-tools/datatracker/assets/10996692/0f8d264b-d21b-4acc-b9da-cc785f999256)
the menu showed `Now` when now was within the meeting times.

A URL that signaled "jump to now" is an interesting idea. I don't _think_ that already exists, and we will explore it.
