### ISSUE TITLE
Order of document states in an AD's dashboard

### ISSUE THREAD

**Issue by rdanyliw** [ietf-tools/datatracker#7276]
### Describe the issue

Consider an AD's dashboard (e.g., [Roman's](https://datatracker.ietf.org/doc/ad/roman.danyliw)).  In the "Documents for <AD's name>" section, it groups all of the documents by particular state and sequences them by their natural progression.  

Currently, the sequence is:

1. IESG Evaluation Internet-Drafts
2. Waiting for AD Go-Ahead Internet-Drafts
3. Approved-announcement to be sent Internet-Draft

However, "Waiting for AD Go-Ahead" occurs before "IESG Evaluation".  These states should be swapped in sequencing so that it displays as:

1. Waiting for AD Go-Ahead Internet-Drafts
2. IESG Evaluation Internet-Drafts
3. Approved-announcement to be sent Internet-Draft

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
@rdanyliw is this different from #6829?
