### ISSUE TITLE
Attempts to clear a status change ballots crash

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#7335]
```
AttributeError at /doc/status-change-mpls-rfc7506-to-historic/edit/clearballot/statchg/

'NoneType' object has no attribute 'slug'

Exception Location: | .../12.10.0/ietf/doc/views_ballot.py, line 405, in clear_ballot

```

cc: @cindymorgan

**Comment by wyatterp365** [comment]
> ```
> AttributeError at /doc/status-change-mpls-rfc7506-to-historic/edit/clearballot/statchg/
> 
> 'NoneType' object has no attribute 'slug'
> 
> Exception Location: | .../12.10.0/ietf/doc/views_ballot.py, line 405, in clear_ballot
> ```
> 
> cc: @cindymorgan

AttributeError at /doc/status-change-mpls-rfc7506-to-historic/edit/clearballot/statchg/

'NoneType' object has no attribute 'slug'

Exception Location: | .../12.10.0/ietf/doc/views_ballot.py, line 405, in clear_ballot
