### ISSUE TITLE
update intro text on https://datatracker.ietf.org/list/nonwg

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/datatracker#7340]
### Description

the structure of www.ietf.org has changed and embedded URLs are friendlier for screen readers so the text at top of the nonwg list page should now be (ideally):

`Guidelines for these lists, including how to request a new one to be created, can be found on the [Non-Working Group Email List Guidelines](https://www.ietf.org/participate/lists/nonwglist-guidelines/) webpage.`

Or, at a minimum the explicit URL should be updated to:

`https://www.ietf.org/participate/lists/nonwglist-guidelines/`

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Easy to make this change, but consider changing the title of the www.ietf.org page first?

See [Carsten's comment](https://github.com/ietf-tools/datatracker/issues/7059#issuecomment-1944400401) about considering groups to be "non-working".

**Comment by ghwood** [comment]
OK. I've changed the formulation on the page to improve clarity. The "non-Working Group" formulation follows CMOS examples (e.g. `the post–World War II years`).

**Comment by cabo** [comment]
CMOS would be "non–working-group".  Of course, this needs a dash, which we still haven't embraced in RFCs. But we can do it here...
