### ISSUE TITLE
This submission has been cancelled due to a system error during processing. Modification is no longer possible.

### ISSUE THREAD

**Issue by antonyantony** [ietf-tools/datatracker#7343]
### Describe the issue

I am trying to upload an XML file and see this error.

Submission status: Cancelled
    
This submission has been cancelled due to a system error during processing. Modification is no longer possible.
    
      
        <h2 class="mt-5">Submission checks</h2>
        <p class="alert alert-warning my-3">
            
                No submission checks were applied to your Internet-Draft.
            
        </p>

        <h2 class="mt-5">Meta-data from the submission</h2>
        
            <div class="alert alert-warning my-3">
                <b>Note:</b> The meta-data shown for a cancelled draft may be incorrect or incomplete.
            </div>
        
    
    
Document | draft-antony-ipsecme-iekv2-beet-mode
-- | --
00
Individual Submission
None
2024-04-21
 
0 authors
 
None
0 bytes
None recognized
None

</div>Submission status: Cancelled

This submission has been cancelled due to a system error during processing. Modification is no longer possible.
Submission checks

No submission checks were applied to your Internet-Draft.
Meta-data from the submission
Note: The meta-data shown for a cancelled draft may be incorrect or incomplete.
Document 	draft-antony-ipsecme-iekv2-beet-mode
Revision 	00
Group 	Individual Submission
Document date 	None
Submission date 	2024-04-21
Title 	
Author count 	0 authors
Abstract 	
Page count 	None
File size 	0 bytes
Formal languages used 	None recognized
Submission additional resources 	None
History
Date 	By 	Event
2024-04-21 		Submission rejected: A system error occurred while processing the submission.
2024-04-21 	[Antony Antony]	Uploaded submission

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
Hi - you're running into the error described here: https://github.com/ietf-tools/datatracker/issues/5696#issuecomment-1631006009

To fix, you need to set `version="3"` or `version="2"` in the `<rfc>` element in the XML you're submitting, as appropriate for the syntax you're using. Note that this `version` is not related to the revision of your draft.

**Comment by antonyantony** [comment]
thanks. I fixed it with your tip. My local  xml2rfc validation didn't give any indication version was set to 0.

**Comment by jennifer-richards** [comment]
Yes, we are aware of that issue and you're unfortunately not the first person to stumble over it. It's on our list to give better feedback when errors are encountered at submission. Thank you for your patience and for making the report.
