### ISSUE TITLE
The RFC history tab rarely shows useful information as all real history is in the "draft" part - merge into one

### ISSUE THREAD

**Issue by paulwouters** [ietf-tools/datatracker#7363]
### Description

Usually the RFC history data does not contain much useful info, and most of the data I look for is in the draft history.
Why not merge the two into one list with a clear item divider that says "Published as RFC xxx".

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Paul - we considered this carefully during the design of the RFC pages, and while I'm happy to begin a new conversation, my initial reaction is "no".

The history of the RFC is the history of the RFC.

The history of the draft is the history of the draft.

Conflating them (streaming them onto each other's pages) was attempted, and the edge cases (RFCs that never had drafts for instance), and the opportunities for incorrectly signaling responsibility stuck out.

Your perspective is currently heavily influenced by having to do an ADs job. For _most_ consumers of RFCs, the interesting part of the history of the RFC is not in the history of the draft.

**Comment by paulwouters** [comment]
That's fair. I'll learn to live with it :P
