### ISSUE TITLE
Active WG document does not show up in WG datatracker

### ISSUE THREAD

**Issue by loghyr** [ietf-tools/datatracker#7383]
### Describe the issue

Look at https://datatracker.ietf.org/wg/nfsv4/documents/, https://datatracker.ietf.org/doc/html/draft-ietf-nfsv4-delstid-04 does not show up as a NFSv4 WG document.

The history of the draft was that it went through WG last call and was sent for AD Evaluation. It was then sent back to the WG pending changes per the AD review. That as draft-ietf-nfsv4-delstid-03.

The changes were made as draft-ietf-nfsv4-delstid-04. It was submitted and the document can not be sent back to the AD as it is not being tracked. 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This draft entered IESG: Dead when it expired. I've asked the secretariat to inspect and adjust it.
```
2024-02-27
	03 	(System) 	Document has expired
2024-02-27
	03 	(System) 	Removed all action holders (IESG state changed)
2024-02-27
	03 	(System) 	IESG state changed to Dead from I-D Exists
```

**Comment by cindymorgan** [comment]
The state has been changed back to "AD is watching." It now shows up on https://datatracker.ietf.org/wg/nfsv4/documents/, and you should be able to resubmit it to the IESG for publication.

**Comment by loghyr** [comment]
Thanks Cindy!
