### ISSUE TITLE
Cannot scroll metadata sidebar

### ISSUE THREAD

**Issue by becarpenter** [ietf-tools/datatracker#7390]
### Describe the issue

In pages like https://datatracker.ietf.org/doc/html/draft-carpenter-6man-zone-ui-04, it's nice that the metadata sidebar can be switched on or off, but when it's present, it can longer be scrolled up or down and most of it is inaccessible without zooming way out.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by cabo** [comment]
Interesting.  WFM (tried current Safari and Chromium).
What was your Browser?

**Comment by becarpenter** [comment]
Firefox 117 on Windows 10. Same problem with Chrome and Edge on Windows. I can't test on Linux as I'm on travel.

On an Android phone things are different, as the metadata sidebar isn't presented as a sidebar, and things work as intended.

**Comment by jennifer-richards** [comment]
Firefox 125 on macOS allows the metadata to be scrolled using a scroll wheel or trackpad gesture when the cursor is over the sidebar, but there's no associated scroll bar widget for the sidebar.

**Comment by becarpenter** [comment]
I don't have a mouse with me this week, but you're right, a very non-intuitive trackpad gesture does work (hold down one finger and scroll with another finger). It seems to me that this is new, but without a time machine I can't be sure.

**Comment by becarpenter** [comment]
I meant to add that when I got home from travel, I realised that I've been scrolling that sidebar with the mouse wheel (without ever thinking about it), so this is nothing new. But with just the trackpad, it's a _very_ non-intuitive two-finger operation.

Isn't it possible to add a vertical scroll bar within the sidebar?

**Comment by rjsparks** [comment]
I think @larseggert had tried and ran into issues, but we'll revisit.

**Comment by larseggert** [comment]
The main issue is that the main view scrollbar and the sidebar scrollbar overlap. There may be a solution through adding padding, but that obviously wastes a bit of horizontal space.

**Comment by becarpenter** [comment]
Can you make the sidebar float? 
There's an ancient stackoverflow conversation about something similar: https://stackoverflow.com/questions/19967352

**Comment by becarpenter** [comment]
Thanks! I just noticed that this has been fixed with an additional scrollbar.
