### ISSUE TITLE
password reset request

### ISSUE THREAD

**Issue by sameph** [ietf-tools/datatracker#7447]
### Describe the issue

i couldn't receive password reset request, since i have forgot my username.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
@sameph, Your username is your email address. Any active email address known to the datatracker should work. Send an email to `tools-help@ietf.org` or `support@ietf.org` to support you further.
