### ISSUE TITLE
Canceled interim meeting shows wrong date on group meetings page

### ISSUE THREAD

**Issue by cindymorgan** [ietf-tools/datatracker#7455]
### Describe the issue

The IAB had a meeting scheduled for 2024-05-22 that was canceled on 2024-05-21. On the IAB's meeting page in the Datatracker, it shows the canceled meeting's date as 2024-05-21 instead of 2024-05-22.

Also, would it be possible to have the "Cancelled" notification for a meeting also show up on the cancelled meeting's agenda page (e.g. https://datatracker.ietf.org/doc/agenda-interim-2024-iab-17-iab-01/)?

Thanks,
Cindy

<img width="1040" alt="Screen Shot 2024-05-22 at 12 30 22 PM" src="https://github.com/ietf-tools/datatracker/assets/22178783/be346fb8-d901-4ce3-be1c-53fda99eb590">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Still an issue:
![image](https://github.com/user-attachments/assets/2b7c10a6-b6cb-43ae-af3c-ae3dd799451d)
