### ISSUE TITLE
Please delete ballot for draft-ietf-dnsop-zoneversion

### ISSUE THREAD

**Issue by cindymorgan** [ietf-tools/datatracker#7480]
### Describe the issue

From: 	"Warren Kumari" <warren@kumari.net>
Subject: 	Whoops, wrong button on draft-ietf-dnsop-zoneversion…
To: 	"IESG_Secretary" <iesg-secretary@ietf.org>, "The IESG" <iesg@ietf.org>
Date: 	Tue, 28 May 2024 10:15:34 -0700

Hi there,

I generally complete my ballot writeup while doing my AD review (i.e before IETF LC) --that way it's all fresh in my mind, etc.
This time I accidentally hit "Save and issue ballot" instead of "Save", and so there is an IESG Eval even though the document hasn't had a LC yet. 

Secretariat: Can you please unissue[0] the ballot?
IESG: Can you please ignore the ballot for now? IETF LC still needs to happen…

Thanks!
W
[0]: Hey, I think it should be a real word… perhaps recall?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by wkumari** [comment]
If this is hard to fix it's not the end of the world -- I've asked other ADs to not ballot yet, and, well, not balloting is easy :-)

It would be nice though if the warned you that you are about to issue a ballot for a document which has not yet had an IETF LC -- I *think* that it used to do this, because I'm fairly sure I've seen the warning previously...

**Comment by rjsparks** [comment]
Manually removed that ballot and added a note to the document history.

**Comment by rjsparks** [comment]
The warning is currently issued by this:

https://github.com/ietf-tools/datatracker/blob/607a5c84b2ba7965c8186437145d11754ff8ebd4/ietf/doc/views_ballot.py#L689

but this particular draft was in this state at the time (prev_state is the state the document was in when the view was entered):
```
>>> d
<Document: draft-ietf-dnsop-zoneversion>
>>> d.get_state('draft-iesg')
<State: AD is watching>
```

**Comment by rjsparks** [comment]
The use of the `watching` `draft-iesg` state has been inconsistent between ADs, and has changed over time (most uses of it went away when the ability to return to `iesg-state` `idexists` was added to the datatracker.

We could add `watching` to the above conditional, but it may have unintended consequences given other uses of that state.

@wkumari - what is your preference?

**Comment by wkumari** [comment]
I had actually forgotten that this document was in "AD Watching" state — I
personally use this state when I've sent the document back to the WG for
some additional fixes. This often means that there has been a significant
delay, and the history is messy, and so (to me ) it seems extra useful to
have the warning - but I get that everyone uses this state differently…

My preference would be that the warning is shown — it's just a warning and
ADs can choose to ignore it if they choose. The "failure" of showing a
warning seems less bad than issuing a ballot before the IETF LC has
completed…

W

**Comment by rjsparks** [comment]
Moved the code change request into its own issue.
