### ISSUE TITLE
Handling authors with no email

### ISSUE THREAD

**Issue by d3e3e3** [ietf-tools/datatracker#7505]
### Describe the issue

There is a somewhat unusual problem in the MANET WG trying to put through drafts with one or two deceased authors. We want to keep them on the front page and have AD backing in that. It seems best to not list old, non-working, emails for them so if the draft is pushed through the submission process without an email for an author, it seems as if none@none.org is synthesized for them. Problems with this: (1) if this happens for two authors, things get quite confused and typically only one get listed on the front page; (2) none.org seems to be a real parked domain name with a web server and email server at the IP address it resolves to. Not sure what the best answer is. MANET is going to try using the full author name @none.org to avoid collisions. But maybe the system should automatically use full0=-author-name@none.invalid since invalid is supposed to never exist as a top level domain name.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Hi Donald - please mail support@ietf.org for help - there are proceedures to follow in this case.
But at a high level:

The draft itself doesn't have to provide an email for the deceased author.

'The submission form _does_ have to identify the author.

Making up a non-working non-existing email address is not the correct thing to do.

Again. please reach out to the secretariat at support@ietf.org.

Quoting from the end of #6114:

> 
> Right now you could submit a draft that had no email address for an author in the draft itself and ask the secretariat to post it manually, and they can post the draft, but they have to add an email address for that author in the metadata adjustment page. To restate - the draft does not require having an email for each author. The metadata adjustment page requires email to attach each author to a Person.
> 
> The error message presented to both the submitter (you) and the secretariat is horribly misleading and we will fix that.
I _thought_ we had done so already - I will revisit to make sure.
> 
> I will work with the secretariat to make sure anyone handling manual post requests knows what to do in the meantime (and a future release will spell this out). I apologize that this was not as straightforward for you and the secretariat as it should have been.
> 
> And as noted, we will be working toward better suppressing email sent to addresses that the datatracker has been told not to use.

**Comment by d3e3e3** [comment]
Hi Robert,

Thanks for the reply. This problem is mostly being worked on by my
co-chairs on MANET WG and I will forward your response to them.

Thanks,
Donald
===============================
 Donald E. Eastlake 3rd   +1-508-333-2270 (cell)
 2386 Panoramic Circle, Apopka, FL 32703 USA
 ***@***.***

**Comment by rjsparks** [comment]
Closing this as a datatracker issue
