### ISSUE TITLE
background of my DISCUSSED item didn't turn red

### ISSUE THREAD

**Issue by paulwouters** [ietf-tools/datatracker#7566]
### Describe the issue

![dtbug](https://github.com/ietf-tools/datatracker/assets/83961974/8c6e19ee-b3ee-46b7-b22c-5b525f0686d4)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
can't reproduce - I see (from yestedays database):
![image](https://github.com/ietf-tools/datatracker/assets/10996692/98410992-3a95-4cab-8e12-ce918219c39a)
Could you have been looking at a previously loaded tab above? Did anything change if you reloaded the tab?
Are you experiencing the issue _now_?

**Comment by paulwouters** [comment]
at the time, i shift-reloaded the tab and nothing changed.

now it shows up as red properly, so i guess close it and i will see if i can reproduce it in two weeks

**Comment by rjsparks** [comment]
If it does recur - capture the network trace from your browser and send it directly to me please?

**Comment by rjsparks** [comment]
closing - reopen if you are able to recreate.
