### ISSUE TITLE
virtual interim numbering

### ISSUE THREAD

**Issue by cindymorgan** [ietf-tools/datatracker#7588]
### Description

Subject: 	virtual interim numbering
From: 	"Michael Richardson" <mcr+ietf@sandelman.ca>
To: 	support@ietf.org
Date: 	Sun, 23 Jun 2024 17:03:46 -0400

For those WGs that have approximately monthly virtual interim meetings, the
numbering of the meetings as YYYY-WG-XX can be confusing as XX!=Month number.
But, it sure sometimes looks like that, especially if one makes a series of
meetings for the year.

I want to suggest that XX be changed in some way.
More digits, letters, roman numerals, ... I don't care.
Just not two digits.

--
Michael Richardson <mcr+IETF@sandelman.ca> . o O ( IPv6 IøT consulting )
Sandelman Software Works Inc, Ottawa and Worldwide
signature.asc

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by mcr** [comment]
@mcr asked for this.

**Comment by rjsparks** [comment]
Hi Michael -

Such a change would require either splitting the schema for the filenames at a point in time (which brings surprising future technical debt) or renaming (and redirecting accesses to) the ~3600 of these we already have.

**Comment by mcr** [comment]
Are you saying that the name: "interim-2024-cellar-07" is always generated from other data and never stored?
interim-2024-cellar-AA would still be better.

**Comment by rjsparks** [comment]
>Are you saying that the name: "interim-2024-cellar-07" is always generated from other data and never stored?

No. Not sure how you are reading that from what I said.

Those are meeting names. They are the names stored in the Meeting objects. They are also currently the name of a directory in which the meeting materials are stored. They show up in URLs that have been on the Internet for years.

I hear your concern that someone may misinterpret them as months. A new greenfield solution might name them a different way such as you propose. But we've been using them this way for many years already, and have a large legacy base of them to deal with. That's the point of my comment above - changing the way the names are made now would not come at a small cost.

**Comment by mcr** [comment]
Robert Sparks ***@***.***> wrote:
    >> Are you saying that the name: "interim-2024-cellar-07" is always generated from other data and never stored?

    > No. Not sure how you are reading that from what I said.

If the name is generated once, I would think it was generated in one place,
and then placed into a column of a table, and then used.  So this is where
I'm confused as to why making a change "now" would create the technical debt
that you mention.

    > I hear your concern that someone may misinterpret them as months. A new
    > greenfield solution might name them a different way such as you
    > propose. But we've been using them this way for many years already, and
    > have a large legacy base of them to deal with. That's the point of my
    > comment above - changing the way the names are made now would not come
    > at a small cost.

let's close this issue

**Comment by rjsparks** [comment]
Ok - we can close this, but lets talk about it at 120 if you're there?
