### ISSUE TITLE
/api/directauth/ always responds with 200 OK to a POST

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#7632]
### Describe the issue

I'm on the fence as to whether this is a bug or an enhancement request, but [as discussed in this imap auth failure ticket](https://github.com/ietf-tools/authp/issues/7#issuecomment-2205563912), the `/api/directauth/` API call returns a 200 OK status for any POST request. This makes debugging a bit more difficult.

For an "invalid post" it should return a 400 and for an "invalid authtoken" it should return a 403. A 200 is appropriate for the other cases.

Before doing this, we need to confirm with users of the endpoint that they'll tolerate the change.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
> Before doing this, we need to confirm with users of the endpoint that they'll tolerate the change.

As noted in [this comment](https://github.com/ietf-tools/authp/issues/7#issuecomment-2211561348), it looks like authp is the only user of the endpoint and it should treat a 4xx reply correctly. It should therefore be ok to change the response status code to something more helpful

**Comment by rjsparks** [comment]
I disagree - we may need to have a real-time discussion, but to try to explain:

A 403 should signal "You aren't allowed to use this endpoint" - i.e. the caller provided an invalid token for getting the endpoint to do more work than look for the token.

It was intentional that "this password isn't good" is passed in the json. It's not an HTTP error.

How would changing that design actually help?

**Comment by jennifer-richards** [comment]
You're right, I was thinking in terms of the app_api_tokens that come in an HTTP header rather than in the payload.

This would help in that you can easily see from the log stream that something is misconfigured, but I think that needs to be fixed in the authp logging where the JSON is interpreted.

Closing.
