### ISSUE TITLE
Announcement Tool: form should start completely blank

### ISSUE THREAD

**Issue by rpcross** [ietf-tools/datatracker#7679]
### Description

All fields of the message, including To: and From: should start blank so user has to set them explicitly

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Please provide more context? The pre-population was explicitly requested before - is this a request for a particular class of users of the announce tool or _any_ user of the announce tool?

**Comment by rpcross** [comment]
There have been occurrences of users not changing the default fields and accidentally sending messages with wrong values. While the "To" field options are explicitly ordered and "IETF Announcement List" seems reasonable, the "From" options are sorted alphabetically and I would argue "IAB Chair" is not a good default.

**Comment by rjsparks** [comment]
So this seems specific to the secretariat use, where there's no obvious role based on their login to set the From.
