### ISSUE TITLE
Area names are not correct for renamed areas in proceedings

### ISSUE THREAD

**Issue by gloinul** [ietf-tools/datatracker#7706]
### Describe the issue

I was looking back at older proceedings and looked at IETF 107. The areas listed here includes WIT, and do not list Transport (TSV). There appear the datatracker fails maintain/present correctly what area WGs belonged to at the particular point in time and meeting. This leads to strange presentation like for 107 where MASQUE WG was TSV, but WebTrans was ART at that time. And ART do exist as category due to other WGs. This appears to be common across all proceedings pages that are generated based on datatracker database. 

Example: https://datatracker.ietf.org/meeting/107/proceedings

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This is most likely bug in the proceedings templates where it's not using group_parent_at_the_time (or getting to parrent correctly from group_at_the_time) where it should be.
