### ISSUE TITLE
Dark mode changes are only partially applied to agenda

### ISSUE THREAD

**Issue by sbingler** [ietf-tools/datatracker#7739]
### Describe the issue

When dark mode is enabled or disabled while viewing the agenda only some of the rows have the change applied. See image.

Refreshing the page will cause the new mode to be correctly displayed.

![Screenshot 2024-07-24 2 47 41 AM](https://github.com/user-attachments/assets/5dfdbdc9-208d-4490-b32d-270fc7674267)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
I think #7851 addresses this

**Comment by jennifer-richards** [comment]
> I think #7851 addresses this

Unfortunately not, changing between light/dark mode with the agenda open still leaves artifacts like in the screenshot. With #7851, the reload again fixes the styling, but the change isn't picked up automatically.

This is with firefox on a mac.

**Comment by rjsparks** [comment]
@holloway  - it would be good to revisit this before 121 - It may be mac specific. 
Changing things in this dialog:
