### ISSUE TITLE
people profile search

### ISSUE THREAD

**Issue by marcblanchet** [ietf-tools/datatracker#7749]
### Description

sometimes, you just want to know more about someone you don't know. While not complete, I found that the data tracker profiles (https://datatracker.ietf.org/person/) are really useful, at least to see the contribution of that person as well as documents, roles, .... I haven't found a way to do just a basic search of a name that would go to those profiles. I could see an item in the pull down of "Other" or else.  If that exists already, please inform me and maybe consider a better way to see it. 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by richsalz** [comment]
Probably a dup of #7031 but see #6008 for some concerns.

**Comment by marcblanchet** [comment]
yes dup of #7031. closing.
