### ISSUE TITLE
Cannot access the agenda page, either forbidden or keep on loading and dispany nothing

### ISSUE THREAD

**Issue by haiguang-wang** [ietf-tools/datatracker#7755]
### Describe the issue

I access the agenda page via company proxy and blocked by the cloudflare server. This problem appeared since IETF 199 and continue to IETF 120

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Please email tools-help@ietf.org with the Ray-ID that's at the bottom of the forbidden page. If you get a forbidden page that doesn't have a Ray-ID, it's likely coming from the company proxy, not Cloudflare.
