### ISSUE TITLE
IRTF groups does not show on meeting agenda

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#777]
`resolution_fixed` `type_defect`   |    by lars@eggert.org

___

https://datatracker.ietf.org/meeting/83/agenda.html does not show any IRTF research groups.

Except for CFRG, which is shown incorrectly as a SEC area working group on Friday afternoon.

___
_Issue migrated from trac:777 at 2022-03-04 01:59:22 +0000_

**Comment by larseggert** [comment]
This should be closed.
