### ISSUE TITLE
It took about 8minutes to delete 1000 acls, when executing "no acls"

### ISSUE THREAD

**Issue by guixf86** [ietf-tools/datatracker#7781]
### Describe the issue

For YANG Data Model for ACLs, https://datatracker.ietf.org/doc/rfc8519/

Based the ietf YANG data, we used standalone Yang Engine confd(8.0.13) to do some test.
Configured 1000 acls firstly, then it took 8minutes to delete 1000acls by the command "no acls".
After deleted the "when" statement in container ipv4 and ipv6, it only take 1s to delete 1000acls by the command "no acls".

Test results as below:
1. Before deleted "when" statement, "no acls" took about 8miuntes(12:24:48 - 12:16:44 = 8min4s)
seroiuts01313# config
Tue Jul  23 12:16:44.148 UTC+02:00
Entering configuration mode terminal
seroiuts01313(config)# no acls
Tue Jul  23 12:16:44.157 UTC+02:00
seroiuts01313(config)# commit
Tue Jul  23 12:24:48.662 UTC+02:00   
Commit complete.
seroiuts01313(config)# end
Tue Jul  23 12:25:46.309 UTC+02:00
seroiuts01313#

2.After deleted "when" statement, "no acls" took about 1s(07:38:59 - 07:38:58 = 1s)
seroiuts01313# config
Fri Aug  2  07:38:58.528 UTC+02:00
Entering configuration mode terminal
seroiuts01313(config)# no acls
Fri Aug  2  07:38:58.541 UTC+02:00
seroiuts01313(config)# commit
Fri Aug  2  07:38:59.145 UTC+02:00
Commit complete.
seroiuts01313(config)# end
Fri Aug  2  07:39:01.839 UTC+02:00
seroiuts01313#

Configuration of one acl like this:
acls acl v4-acl1
 type ipv4-acl-type
 aces ace rule1
  matches ipv4 protocol  6
  matches ipv4 destination-ipv4-network 100.1.0.0/16
  matches ipv4 source-ipv4-network 100.1.0.0/16
  matches tcp source-port operator eq
  matches tcp source-port port 1798
  actions forwarding accept
  acls attachment-points interface int1
 egress acl-sets acl-set v4-acl1

From the results, "when" statement of container ipv4 and ipv6 will take long time, while deleting acl configurations.
choice l3 {
  container ipv4 {
	when "derived-from-or-self(/acls/acl/type, "
	   + "'acl:ipv4-acl-type')";
	if-feature "match-on-ipv4";
	uses pf:acl-ip-header-fields;
	uses pf:acl-ipv4-header-fields;
	description
	  "Rule set that matches IPv4 headers.";
  }

  container ipv6 {
	when "derived-from-or-self(/acls/acl/type, "
	   + "'acl:ipv6-acl-type')";
	if-feature "match-on-ipv6";
	uses pf:acl-ip-header-fields;
	uses pf:acl-ipv6-header-fields;
	description
	  "Rule set that matches IPv6 headers.";
  }
  description
	"Choice of either IPv4 or IPv6 headers";
}

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
@guixf86, datatracker source repository is not the place to discuss the content of Internet-Drafts or RFCs.
You should look at the [netmod](https://datatracker.ietf.org/wg/netmod/about/) working group and its' [mailing list](https://mailman3.ietf.org/mailman3/lists/netmod@ietf.org/).
