### ISSUE TITLE
Review summaries for "On the right track" and "Serious Issues" don't have "badges" and so don't render properly.

### ISSUE THREAD

**Issue by wkumari** [ietf-tools/datatracker#7808]
### Describe the issue

When looking at the [Telechat agenda](https://datatracker.ietf.org/iesg/agenda/) or an document detail page (e.g: [draft-ietf-lisp-name-encoding - "LISP Distinguished Name Encoding"](https://datatracker.ietf.org/doc/draft-ietf-lisp-name-encoding/)](https://datatracker.ietf.org/doc/draft-ietf-lisp-name-encoding/)) the "badges" next to some of the reviews are missing. 

This includes (at least "On the right track" and "Serious Issues"). 

Screenshot attached. 
<img width="1211" alt="Screenshot 2024-08-08 at 10 25 39 AM" src="https://github.com/user-attachments/assets/ae8bea5c-f43d-4836-9b53-60947061b1af">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Fixed by #7809
