### ISSUE TITLE
My datatracker profile

### ISSUE THREAD

**Issue by bobhinden** [ietf-tools/datatracker#7827]
### Describe the issue

I was looking at my profile to see if it needed to be updated and have two questions:

How do I update it?  I didn't see a link or instructions.

According to the RFC editor search, I am the author of 48 RFCs, but the profile page says 43.   Why the discrepancy?

Thanks
Bob

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
I assume you were looking at the public profile page at `/person/Bob Hinden`. You can affect what that shows by making changes at the account info page at `/person/profile'. 

If there are items shown at the first that aren't editable at the second (such as Bio), send email to support@ietf.org to ask for changes.

For the discrepancy between the rfc editor search and the listing on the profile page for RFCs. Older RFCs, in particular, when imported into the datatracker, did not get accurate DocumentAuthor information. See, for instance, the "Authors" row for https://datatracker.ietf.org/doc/rfc823/. I'll enter a ticket on your behalf at support@ to have the secretariat manually correct the missing ones.

**Comment by bobhinden** [comment]
Robert,

Thank, I was able to edit my bio.

Thanks for asking the secretariat to fix the RFC count!

Bob
