### ISSUE TITLE
Postscript document button is broken

### ISSUE THREAD

**Issue by sh-cho** [ietf-tools/datatracker#7879]
### Describe the issue

<img width="535" alt="image" src="https://github.com/user-attachments/assets/3d30f97b-c42a-45f7-9750-1e3c10ad6e6c">

ex) https://datatracker.ietf.org/doc/rfc2616/

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
Looks like PostScript button was only removed for drafts. [^1] [^2]

[^1]: https://github.com/ietf-tools/datatracker/pull/7200
[^2]: https://github.com/ietf-tools/datatracker/issues/6900

**Comment by sh-cho** [comment]
Oh, thanks for the history!
Can I make a patch for this one?

**Comment by kesara** [comment]
Yes, you are welcome to contribute this project.

This [guide](https://github.com/ietf-tools/datatracker?tab=readme-ov-file#getting-started) might help you get started.
