### ISSUE TITLE
Allow blanket disclosures in section V of the specific disclosure form

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#7909]
For Section V, add a checkbox, unselected by default, titled "Blanket IPR Disclosure" with the following text: 

In satisfaction of its disclosure obligations, Patent Holder commits to license all of IPR (as defined in RFC 8179) that would have required disclosure under RFC 8179 on a royalty-free (and otherwise reasonable and non-discriminatory) basis. Patent Holder confirms that all other terms and conditions are described in this IPR disclosure. 

When this box is selected, do not make the remaining fields in section V mandatory.

Update the display of IPR disclosures to reflect this selection.

This will probably require a new boolean field on the specific ipr disclosure model.

**Comment by jennifer-richards** [comment]
Should this be in part A of section V alongside the other details (Patent number, inventor, title, etc) or does it need a new section?

For future reference in case it changes, that has title "A. For granted patents or published pending patent applications, please provide the following information:". There's also "B. Does your disclosure relate to an unpublished pending patent application?" with a single checkbox for "has patent pending"

**Comment by rjsparks** [comment]
It belongs in part A. But part B is obviated. If someone wants to check the box (or enter some explicit patent into the rest of A if the blanket disclosure option is chosen), we should let them.

**Comment by rjsparks** [comment]
Also:

If the blanket disclosure declaration checkbox is selected in V., we should require the submitter to select (b) in Section VI. 

`b) Royalty-Free, Reasonable and Non-Discriminatory License to All Implementers`
