### ISSUE TITLE
wrong link in RFC3711

### ISSUE THREAD

**Issue by carnicer** [ietf-tools/datatracker#7926]
### Describe the issue

The link to the RTP RFC in the SRTP RFC seems to be wrong. It should be RFC3550 instead of RFC3350 (2x '3's instead of 2x '5's).

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by carnicer** [comment]
That's the RFC with the issue: https://datatracker.ietf.org/doc/html/rfc3711

**Comment by kesara** [comment]
@carnicer You should report this as an errata to [RFC editor](https://www.rfc-editor.org/).

You can click on the **Report errata** button on datatracker or visit https://www.rfc-editor.org/errata.php#reportnew

There are few already exist for that RFC 3711: https://www.rfc-editor.org/errata_search.php?rfc=3711&rec_status=15&presentation=table
