### ISSUE TITLE
Developer build warns of obsolete attribute for vscode

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#7930]
WARN[0000] /Users/rjsparks/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1726167207867.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion

**Comment by jennifer-richards** [comment]
https://github.com/ietf-tools/datatracker/pull/7931 fixed?
