### ISSUE TITLE
Add a "diff" button

### ISSUE THREAD

**Issue by pjaitken** [ietf-tools/datatracker#7977]
### Description

When viewing a document at https://datatracker.ietf.org/doc/blah, it would be very useful to have a "diff" button linking to the appropriate https://author-tools.ietf.org/iddiff page, ie https://author-tools.ietf.org/iddiff?url1=blah

Thanks.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This is on the history tab for the document:
![image](https://github.com/user-attachments/assets/3b27840e-0606-4aab-9058-9bf387f32f1a)
