### ISSUE TITLE
Pending Interim Meeting Requests don't inform the approval

### ISSUE THREAD

**Issue by martinduke** [ietf-tools/datatracker#7981]
### Description

When a working group chair requests an in-person interim meeting, it goes into "pending" state. There is no automated notification to the approving AD. Since most datatracker approval flows automatically inform the approver, it is easy for the AD to miss.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Hi Martin - 

Were the Oct 3 moq meetings in person? If so, there was a message to the ADs here:
https://mailarchive.ietf.org/arch/msg/moq/sfZfp0duHLwaAlfmUJjOiERCKOk/

If that wasn't an in-person meeting, could you give me the meeting number (interim-<acronym>-2024-??) of some request that didn't get a notification so I can chase it down?

If you didn't mean email notification, could you add more detail?

**Comment by richsalz** [comment]
Just answering because I know: yes, the MOQ interim this week is in-person in Cambridge MA :)

**Comment by rjsparks** [comment]
@martinduke Closing this as invalid given that notifications were sent. If there's some other change you would like to see, let us know.
