### ISSUE TITLE
draft-ietf-6man-pio-pflag-11 File Error

### ISSUE THREAD

**Issue by Rayrob** [ietf-tools/datatracker#8006]
### Describe the issue

Version 11 of the draft was uploaded this morning (08:30 UTC) but cannot be accessed.
Error message: "Error; cannot read 'draft-ietf-6man-pio-pflag-11.txt'"

HTML version also inaccessible and the compare tool fails for  similar reason.

<img width="872" alt="image" src="https://github.com/user-attachments/assets/aa68d1ec-59a4-41cb-8c0c-dc6a179bc987">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by furry13** [comment]
Thank you for reporting this, I came to file exactly this issue...
Providing we (the authors) are waiting for the IESG approval for the draft publication, the timing is very unfortunate...

**Comment by furry13** [comment]
BTW at least two other drafts have been submitted after  draft-ietf-6man-pio-pflag-11  (one individual doc and one WG doc):
https://datatracker.ietf.org/doc/recent

Both are OK, so it seems to be smth wrong with draft-ietf-6man-pio-pflag-11 (though https://author-tools.ietf.org/ renders that document into HTML just fine)

**Comment by jennifer-richards** [comment]
Thanks for the report. This is fixed and the underlying issue tracked in #8016.

**Comment by jennifer-richards** [comment]
Just so it's clear, there was no problem with the submitted files. They rendered correctly but were not moved into place. Sorry for the inconvenience.
