### ISSUE TITLE
Links to draft submitted via API return 404 error

### ISSUE THREAD

**Issue by cindymorgan** [ietf-tools/datatracker#8010]
### Describe the issue

To: 	support@ietf.org
Date: 	Fri, 4 Oct 2024 09:55:05 +1000
Subject: 	Fwd: New Version Notification for draft-mediaman-6838bis-00.txt
From: 	"Mark Nottingham" <mnot@mnot.net>

Hi,

This document appeared to submit successfully (using MT's repo, so via the API), but all of the links are 404 - thoughts?

Cheers,

    Begin forwarded message:

    From: internet-drafts@ietf.org
    Subject: New Version Notification for draft-mediaman-6838bis-00.txt
    Date: 4 October 2024 at 9:48:37 am AEST
    To: "Mark Nottingham" <mnot@mnot.net>, "Pete Resnick" <resnick@episteme.net>

    A new version of Internet-Draft draft-mediaman-6838bis-00.txt has been
    successfully submitted by Mark Nottingham and posted to the
    IETF repository.

    Name:     draft-mediaman-6838bis
    Revision: 00
    Title:    Media Type Specifications and Registration Procedures
    Date:     2024-10-03
    Group:    Individual Submission
    Pages:    31
    URL:      https://www.ietf.org/archive/id/draft-mediaman-6838bis-00.txt
    Status:   https://datatracker.ietf.org/doc/draft-mediaman-6838bis/
    HTML:     https://www.ietf.org/archive/id/draft-mediaman-6838bis-00.html
    HTMLized: https://datatracker.ietf.org/doc/html/draft-mediaman-6838bis

    Abstract:

      This document defines procedures for the specification and
      registration of media types for use in HTTP, MIME, and other Internet
      protocols.

    The IETF Secretariat

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by cindymorgan** [comment]
cc @mnot

**Comment by sdaoden** [comment]
(did not see that before)
Likely the same as https://github.com/ietf-tools/datatracker/issues/8015

**Comment by jennifer-richards** [comment]
FYI, there's an issue affecting the moving of files into place when a submission is posted. We haven't identified the cause yet, but it results in the txt and html files not moving into place. I'm cleaning up the ones I see now and expect them to be in place in the next half hour or so.

Will take some time to identify and fix the underlying issue, though, so more may crop up.

**Comment by jennifer-richards** [comment]
I believe this issue and #8015 are both now corrected. I'll create a new ticket for tracking the root cause issue.

Please reopen if there's something I've missed on this one.

**Comment by mnot** [comment]
Thx!
