### ISSUE TITLE
draft-irtf-cfrg-vdaf-12 published but the txt, html and htmlized formats are missing

### ISSUE THREAD

**Issue by cjpatton** [ietf-tools/datatracker#8012]
### Describe the issue

Today we published https://datatracker.ietf.org/doc/draft-irtf-cfrg-vdaf/12/ from https://github.com/cfrg/draft-irtf-cfrg-vdaf. The XML was published, but the human readable formats seemed to not have been generated.

The txt preview is also missing:
![image](https://github.com/user-attachments/assets/069fc8a6-f639-4461-87db-6743da0acb4f)

Note that the previous drafts have the txt, html, and htmlized formats generated.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by sdaoden** [comment]
(did not see that before)
Likely the same as https://github.com/ietf-tools/datatracker/issues/8015

**Comment by jennifer-richards** [comment]
@sdaoden is correct. This draft is fixed and the underlying issue is being tracked in #8016. Thanks for the report.
