### ISSUE TITLE
Datatracker entry for draft-crocker-dnsop-dnssec-algorithm-lifecycle seems wrong

### ISSUE THREAD

**Issue by paulehoffman** [ietf-tools/datatracker#8013]
### Describe the issue

https://datatracker.ietf.org/doc/draft-crocker-dnsop-dnssec-algorithm-lifecycle/ says "Error; cannot read 'draft-crocker-dnsop-dnssec-algorithm-lifecycle-01.txt'". It looks like there is no text version for that draft. I suspect the XML is not compiling for some reason.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by cabo** [comment]
On 4. Oct 2024, at 22:18, Paul Hoffman ***@***.***> wrote:
> 
>  I suspect the XML is not compiling for some reason.

The XML does compile for me (tested to .txt and to real .pdf).

Grüße, Carsten

**Comment by sdaoden** [comment]
(did not see that before)
Likely the same as https://github.com/ietf-tools/datatracker/issues/8015

**Comment by jennifer-richards** [comment]
Can confirm, this is the same as #8010 and #8015. It should be resolved now, but these may recur until #8016 is fixed.

Thank you for the report.
