### ISSUE TITLE
datatracker format conversion seems broken

### ISSUE THREAD

**Issue by sdaoden** [ietf-tools/datatracker#8015]
### Describe the issue

The page
https://datatracker.ietf.org/doc/draft-nurpmeso-dkim-hash-adaptivity/
does not show the draft, but only says
<pre>
Error; cannot read 'draft-nurpmeso-dkim-hash-adaptivity-00.txt'
</pre>.
I can download the XML file though, and it is the uploaded version.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by sdaoden** [comment]
btw my other submission just works fine: https://datatracker.ietf.org/doc/draft-nurpmeso-smtp-tls-srv/
They are both small, maybe an expert can make some sense out of that.

**Comment by jennifer-richards** [comment]
Please see comment [here](https://github.com/ietf-tools/datatracker/issues/8010#issuecomment-2394766563).

I'm pretty sure this is the same issue, so I'm closing it to concentrate the attention. Thank you for reporting.
