### ISSUE TITLE
draft-ietf-6man-pio-pflag-12 HTML/TXT are not copied

### ISSUE THREAD

**Issue by furry13** [ietf-tools/datatracker#8025]
### Describe the issue

I've just posted -12 of https://datatracker.ietf.org/doc/draft-ietf-6man-pio-pflag/ but neither .txt nor .html are available..

It looks like another case of https://github.com/ietf-tools/datatracker/issues/8016

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by furry13** [comment]
Oh it's available now, so I guess I should have waited longer..sorry for the false alarm..

**Comment by jennifer-richards** [comment]
Yes - we're still diagnosing and working on a fix. In the meantime, I'm watching the incoming drafts and fixing them up by hand so there will be a bit of a lag but they will show up. This one has been fixed.
