### ISSUE TITLE
3.6.8.  Integer Description starts with ”vCard “

### ISSUE THREAD

**Issue by youwch** [ietf-tools/datatracker#8054]
### Describe the issue

3.6.8.  Integer Description starts with ”vCard “, but should be "iCalendar"

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Closing this as non-actionable. If you were commenting on the contents of an Internet-Draft or RFC contact the relevant group (listed on the main datatracker page for that document).
