### ISSUE TITLE
Submission: What does "replace" mean?

### ISSUE THREAD

**Issue by cabo** [ietf-tools/datatracker#8059]
### Describe the issue

A not-so-frequent submitter just submitted a -07 for a draft.

He was confused by the field

*Any Internet-Drafts that this document replaces (approval required for replacing an Internet-Draft you are not the author of)*

Of course, his new draft replaces -06, but there was no way to enter that.

The legend needs to explain that this is about replacing I-D *series*, not the single I-Ds that make up a series (which are automatically "replaced" by the next one in the series).

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
we've gone back and forth on providing form guidance here over time. Do you have exact wording to suggest?

**Comment by jaimejim** [comment]
Something like:

“This section is typically intended for an IETF draft transitions from an individual submission to a Working Group (WG) document. It should not be used for subsequent versions of the same WG document. Note: Approval is required to replace an Internet-Draft if you are not the original author.”

**Comment by DerrioSC** [comment]
> ### Describe the issue
> A not-so-frequent submitter just submitted a -07 for a draft.
> 
> He was confused by the field
> 
> _Any Internet-Drafts that this document replaces (approval required for replacing an Internet-Draft you are not the author of)_
> 
> Of course, his new draft replaces -06, but there was no way to enter that.
> 
> The legend needs to explain that this is about replacing I-D _series_, not the single I-Ds that make up a series (which are automatically "replaced" by the next one in the series).
> 
> ### Code of Conduct
> * [x]  I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ghwood** [comment]
It is possible to be clear about what's going on with just a bit more text.

```
An  I-D submission will be automatically attached to the previous version of the I-D with the same name, or assigned "-00" version if no previous version exists.

If this submission is intended to replace an I-D with a different name (e.g. when an individual I-D is adopted as a Working Group document), please enter that name here. (Approval required to replace an I-D for which you are not an author.)
```

Help text for input field:

```
Type name to search for I-D to replace
```
