### ISSUE TITLE
Authors per country per RFC is blank

### ISSUE THREAD

**Issue by alvestrand** [ietf-tools/datatracker#8096]
### Describe the issue

This URL:
https://datatracker.ietf.org/stats/document/yearly/country/?type=rfc

shows me a blank image.
The corresponding page for I-Ds seems to work, but is not the one I want.

### Code of Conduct

- [x] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
See #7742 and #3712
