### ISSUE TITLE
https://datatracker.ietf.org/doc/rfc1101/email/

### ISSUE THREAD

**Issue by zashab** [ietf-tools/datatracker#8187]
### Description

https://datatracker.ietf.org/doc/rfc1101/email/

### Code of Conduct

- [x] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Closing as unactionable. If you see something that needs to change, add a new comment.
