### ISSUE TITLE
HTTP Live Streaming article references to examples with gay and adult content.

### ISSUE THREAD

**Issue by dibalavs** [ietf-tools/datatracker#8216]
### Describe the issue

Link to original Article:
https://datatracker.ietf.org/doc/html/rfc8216

Issue in chapter:
[11.2](https://datatracker.ietf.org/doc/html/rfc8216#section-11.2).  Informative References

This link:
```
[M3U]      Nullsoft, Inc., "The M3U Playlist format, originally
              invented for the Winamp media player",
              <[https://en.wikipedia.org/w/](https://en.wikipedia.org/w/index.php?title=M3U7amp;oldid=786631666)
              [index.php?title=M3U7amp;oldid=786631666](https://en.wikipedia.org/w/index.php?title=M3U7amp;oldid=786631666)>.
```
goes to article version on wikipedia with examples with gay and adult content.
(see examples in  chapter Extended M3U)

### Code of Conduct

- [x] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by dibalavs** [comment]
`7amp;` should be replaced to original `&` symbol

**Comment by kesara** [comment]
This is not a datatracker issue. Any erratas on RFCs should be reported to rfc-editor[^1].
Note, there's an errata already about that reference[^2].

[^1]: https://www.rfc-editor.org/errata.php
[^2]: https://www.rfc-editor.org/errata/eid6430
