### ISSUE TITLE
datatracker document lookup broken?

### ISSUE THREAD

**Issue by he32** [ietf-tools/datatracker#8259]
### Describe the issue

When trying to look up a document via https://datatracker.ietf.org/, no matter what I search for I get a sour error message which says

   Forbidden (403)

   CSRF verification failed. Request aborted.

I suspect I am not alone in seeing this?

### Code of Conduct

- [x] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
[As discussed at the November Tools Team call](https://notes.ietf.org/tools-team-20241119#Change-to-datatracker-search-behavior), we have changed the search to require CSRF verification. It appears this is a bug related to that. While we work on a permanent fix, an immediate workaround is to log in to a datatracker account. This should allow your search to succeed.

Thank you for your report and sorry for the inconvenience.

**Comment by jennifer-richards** [comment]
Initial fix did not resolve this

**Comment by jennifer-richards** [comment]
Appears to have been fixed. Please reopen or file a new ticket if you continue to have problems.
