### ISSUE TITLE
Bad HTTP redirects for tools

### ISSUE THREAD

**Issue by paulehoffman** [ietf-tools/datatracker#8298]
### Describe the issue

I'm not sure if this is a "Datatracker" bug per se, but:

`https://tools.ietf.org/tools/rfcdiff/rfcdiff-1.46.tgz` redirects to `https://author-tools.ietf.org/iddiff/rfcdiff-1.46.tgz`. However, the latter redirects to `https://_/iddiff`, which is clearly wrong.

### Code of Conduct

- [x] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
Historically, `https://tools.ietf.org/tools/rfcdiff/` was the home for the tool (not the rfcdiff webservice)[^1].

I have added redirect rules to redirect anything from `https://tools.ietf.org/tools/rfcdiff/` to https://github.com/ietf-tools/rfcdiff.

[^1]: http://web.archive.org/web/20200215173551/https://tools.ietf.org/tools/rfcdiff/

**Comment by cabo** [comment]
Did you include the string after the directory?
(See location below.)

```
$ curl -LI https://tools.ietf.org/tools/rfcdiff/rfcdiff-1.46.tgz
HTTP/2 301 
date: Thu, 05 Dec 2024 02:51:03 GMT
content-type: text/html
content-length: 167
location: https://github.com/ietf-tools/rfcdiff
cache-control: max-age=3600
expires: Thu, 05 Dec 2024 03:51:03 GMT
x-robots-tag: noindex, nofollow
server: cloudflare
cf-ray: 8ed0bb74ffbc58de-TXL
alt-svc: h3=":443"; ma=86400

HTTP/2 200 
server: GitHub.com
date: Thu, 05 Dec 2024 02:51:04 GMT
content-type: text/html; charset=utf-8
```

**Comment by paulehoffman** [comment]
To say it differently than @cabo, what one gets now with `https://tools.ietf.org/tools/rfcdiff/rfcdiff-1.46.tgz` is very clearly not a .tgz file.

**Comment by kesara** [comment]
That's intentional because we don't serve the tarball anymore.

**Comment by kesara** [comment]
@paulehoffman, where do you find that reference to `rfcdiff-1.46.tgz`?

**Comment by kesara** [comment]
I'm going to transfer this issue to https://github.com/ietf-tools/rfcdiff
