### ISSUE TITLE
Seamless Domain Transitions Using Shared TLS Certificates

### ISSUE THREAD

**Issue by fra-iesus** [ietf-tools/datatracker#8339]
### Description

Dear all,

I would like to propose a feature that allows seamless transitions between domains sharing the same TLS certificate. Currently, web browsers treat different domains as entirely separate contexts, even if they are validated and included in the same TLS certificate (e.g., via SAN – Subject Alternative Name).

**Problem:**
When transitioning between two domains (e.g., example.com and example.de) in the same application, users experience delays caused by new TLS handshakes and full page reloads.
Data (e.g., cookies, session context) must be re-established, leading to a suboptimal user experience.
Despite having the same TLS certificate, the connection cannot be reused across domains.

**Proposed Solution:**
Modify the TLS protocol to allow connection reuse between domains validated by the same certificate.
Establish a mechanism to securely transfer session context (e.g., cookies or storage) between such domains.

**Benefits:**
Improved user experience, especially for applications operating across multiple domains (e.g., regional or language-specific websites).
Simplified architecture for multi-domain applications.
Preserved security, as shared TLS certificates already validate ownership of all included domains.

**Key Considerations:**
Collaboration with the HTTP Working Group would likely be required to address browser and application-level implementations (e.g., cross-origin data sharing).
This enhancement would improve the efficiency of TLS usage and multi-domain web applications without compromising security. I would be happy to provide more details or collaborate further on this proposal.

Best regards,
Lex

### Code of Conduct

- [x] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by richsalz** [comment]
This repo is for the system that manages IETF documents.  You might take your proposal to the HTTPBIS working group, https://datatracker.ietf.org/wg/httpbis/about/
