### ISSUE TITLE
More notification emails from the WG Tracker

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#866]
`keyword_sprint` `type_defect`   |    by warren@kumari.net

___

I would like to request a feature for the data tracker -- when a (chair | secretary) updates the status of the document allow them to also enter a date. Once that date arrives, send email reminding them that something needs to happen.

The use case for this is, eg. WGLC -- I would like to be able to start a WGLC and update the data tracker to reflect this. I would also like to set a 2 week interval for this, and after 2 weeks the data tracker will start sending me email reminding me that the LC has closed and I now need to do something…

___
_Issue migrated from trac:866 at 2022-03-04 02:34:59 +0000_

**Comment by rjsparks** [comment]
The state of this got brutally out of sync with reality during the various repository moves. Closing this issue again.
