### ISSUE TITLE
Discusses page has documents with only ex-AD DISCUSSes

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#872]
`keyword_hard` `keyword_resnick` `keyword_sprint` `type_defect`   |    by presnick@qualcomm.com

___

https://datatracker.ietf.org/iesg/discusses/ lists documents where the only DISCUSS holder are retired ADs. It should not have those documents listed.

___
_Issue migrated from trac:872 at 2022-03-04 02:35:28 +0000_

**Comment by rjsparks** [comment]
I'm going to close this as wontfix after a decade of lack of change. The current representation of the page makes it easy to see which things are in this state, and it's not irritating to the community enough to prioritize the change.
If we ever revisit it (or rework the way the search for the page is built) - it _might_ be possible to post-process the resulting list in the view by looking for a blocking position by at least one standing AD. BUT, I've had feedback over the interim that some IESG members have found the current behavior useful to note abandoned discusses.
