### ISSUE TITLE
Color coded ballot positions

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#886]
`keyword_easy` `keyword_sprint` `type_enhancement`   |    by presnick@qualcomm.com

___

Two of us this week made the same silly mistake: We balloted "Abstain" when we meant "Recuse". We each went back and fixed it, but that still leaves a silly History record. Is there some way to put little color boxes next to each position or otherwise colorize them (green for Yes or No Objection , red for Discuss, yellow for Abstain, and gray for Recuse)? That would have made things obvious.

___
_Issue migrated from trac:886 at 2022-03-04 02:36:49 +0000_

**Comment by rjsparks** [comment]
@larseggert Is this something that would still be worthwhile?

**Comment by larseggert** [comment]
I don't think so. Nobody worries about the history entries :-)

**Comment by rjsparks** [comment]
closing as wontfix
