### ISSUE TITLE
Publish RFC entry only lasts 24 hours

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#936]
`type_defect`   |    by ietf@augustcellars.com

___

Personal Atom Feed

In the feed the entry for publishing of RFCs only lasts for 24 hours (assuming that there is no check that it has been sent on some feed) which means that it is easy to miss the event if one does not check the feed frequently enough.

___
_Issue migrated from trac:936 at 2022-03-04 02:41:24 +0000_

**Comment by rjsparks** [comment]
Closing this as wontfix/can't-reproduce.
The related logic is at https://github.com/ietf-tools/datatracker/blob/9a7ef90e52ed13dad549afd238072aca5cfa8ba0/ietf/doc/feeds.py#L125. The default feed goes back 8 days, and the DocEvent did exist:
```
>>> DocEvent.objects.filter(type='published_rfc',doc__docalias__name='rfc8798')
<QuerySet [<DocEvent: draft-ietf-core-senml-more-units published rfc by (System) at 2020-06-25 11:19:27>]>
```
