### ISSUE TITLE
Timezone support for Important Dates

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#960]
`keyword_sprint` `type_enhancement`   |    by housley@vigilsec.com

___

Today, important dates is a static webpage.  It would be great if people could show the cut-off times in their local timezone.  As part of this, people will need to be able to specify their local timezone in a profile.  This is probably a straightforward addition to the information that is already stored for community draft tracking.

___
_Issue migrated from trac:960 at 2022-03-04 02:43:25 +0000_

**Comment by rjsparks** [comment]
I think this is OBE,

**Comment by rjsparks** [comment]
closing as OBE
